# import libraries

In [1]:
import pandas as pd
from ax.service.ax_client import AxClient, ObjectiveProperties
import matplotlib.pyplot as plt
from ax.modelbridge.registry import Models
from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy   
import time


import sys
sys.path.append('../')
import helper_functions as hf

/var/folders/9p/f66yhymx35939zzlg51g0rrc0000gn/T/ipykernel_43164/3307975217.py:5: DeprecationWarning: Please import from 'ax.generation_strategy.generation_strategy' instead of 'ax.modelbridge.generation_strategy'. The latter is deprecated and will be removed in a future release.
  from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy

# generate recommendations

In [2]:
n = hf.get_iteration_number()

for i in range(3):
    print("Very Important: Please Confirm the Iteration Number is Iteration " + str(n))

print()

list_of_drugs = (['IBP']  + ['LOV']  + ['DCF']  + ['GLV']) * 2

for i in range(3):
    print("Very Important: Please Confirm the Drugs are: ", list_of_drugs)

Very Important: Please Confirm the Iteration Number is Iteration 3
Very Important: Please Confirm the Iteration Number is Iteration 3
Very Important: Please Confirm the Iteration Number is Iteration 3

Very Important: Please Confirm the Drugs are:  ['IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV']
Very Important: Please Confirm the Drugs are:  ['IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV']
Very Important: Please Confirm the Drugs are:  ['IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV']

In [3]:
time_start = time.time()


df_design, ax_client = hf.run_optimizer(current_iteration=n, drug_list= list_of_drugs,  bopt = 1)

time_end = time.time()
time_duration = round((time_end - time_start)/60,2)

print("Time taken for optimization: " + str(time_duration) + " mins")
print("Time taken for optimization: " + str(time_duration * 60) + " seconds")

**************************************************************************************************** 1  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Ibuprofen IBP  | Iteration:  3

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[INFO 07-29 12:12:18] ax.service.ax_client: Generated new trial 48 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 22, 'surf_2_conc': 15, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's6'} using model BoTorch.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

**************************************************************************************************** 2  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Lovastatin LOV  | Iteration:  3

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[INFO 07-29 12:12:21] ax.service.ax_client: Generated new trial 49 with parameters {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 15, 'surf_2_conc': 16, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's6'} using model BoTorch.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

**************************************************************************************************** 3  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Diclofenac DCF  | Iteration:  3

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[INFO 07-29 12:12:23] ax.service.ax_client: Generated new trial 50 with parameters {'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 22, 'surf_2_conc': 16, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's6'} using model BoTorch.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

**************************************************************************************************** 4  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Griseofulvin GLV  | Iteration:  3

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[INFO 07-29 12:12:27] ax.service.ax_client: Generated new trial 51 with parameters {'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 26, 'surf_2_conc': 15, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's6'} using model BoTorch.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

**************************************************************************************************** 5  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Ibuprofen IBP  | Iteration:  3

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[INFO 07-29 12:12:29] ax.service.ax_client: Generated new trial 52 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 23, 'surf_2_conc': 15, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's6'} using model BoTorch.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

**************************************************************************************************** 6  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Lovastatin LOV  | Iteration:  3

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[INFO 07-29 12:12:32] ax.service.ax_client: Generated new trial 53 with parameters {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 28, 'surf_2_conc': 15, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's6'} using model BoTorch.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

**************************************************************************************************** 7  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Diclofenac DCF  | Iteration:  3

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[INFO 07-29 12:12:35] ax.service.ax_client: Generated new trial 54 with parameters {'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 29, 'surf_2_conc': 16, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's6'} using model BoTorch.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

**************************************************************************************************** 8  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Griseofulvin GLV  | Iteration:  3

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[INFO 07-29 12:12:38] ax.service.ax_client: Generated new trial 55 with parameters {'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 26, 'surf_2_conc': 14, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's6'} using model BoTorch.

Time taken for optimization: 0.37 mins
Time taken for optimization: 22.2 seconds

# process results

In [4]:
ax_client = hf.load_design_optimizer(n)
ax_client.get_trials_data_frame()

/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

,trial_index,arm_name,trial_status,generation_node,obj_surf_conc,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,drug_conc,surf_1,surf_2
0,0,0_0,COMPLETED,GenerationStep_0,35.0,0.2063,0.3073,0.0373,29,6,25.0,s7,s6
1,1,1_0,COMPLETED,GenerationStep_0,50.0,0.4045,0.4196,0.0728,6,44,25.0,s4,s4
2,2,2_0,COMPLETED,GenerationStep_0,100.0,0.2962,0.4364,0.0493,4,27,25.0,s2,s6
3,3,3_0,COMPLETED,GenerationStep_0,92.0,0.3528,0.2810,0.0711,91,1,25.0,s1,s2
4,4,4_0,COMPLETED,GenerationStep_0,46.0,0.2063,0.3073,0.0373,32,14,25.0,s3,s4
5,5,5_0,COMPLETED,GenerationStep_0,94.0,0.4045,0.4196,0.0728,18,76,25.0,s8,s1
6,6,6_0,COMPLETED,GenerationStep_0,62.0,0.2962,0.4364,0.0493,59,3,25.0,s8,s2
7,7,7_0,COMPLETED,GenerationStep_0,100.0,0.3528,0.2810,0.0711,2,66,25.0,s3,s6
8,8,8_0,COMPLETED,GenerationStep_0,79.0,0.2063,0.3073,0.0373,48,31,25.0,s4,s6
9,9,9_0,COMPLETED,GenerationStep_0,30.0,0.4045,0.4196,0.0728,12,18,25.0,s4,s8
10,10,10_0,COMPLETED,GenerationStep_0,100.0,0.2962,0.4364,0.0493,22,10,25.0,s6,s1
11,11,11_0,COMPLETED,GenerationStep_0,100.0,0.3528,0.2810,0.0711,55,24,25.0,s2,s4
12,12,12_0,COMPLETED,GenerationStep_0,73.0,0.2063,0.3073,0.0373,12,61,25.0,s1,s8
13,13,13_0,COMPLETED,GenerationStep_0,100.0,0.4045,0.4196,0.0728,38,48,25.0,s1,s1
14,14,14_0,COMPLETED,GenerationStep_0,100.0,0.2962,0.4364,0.0493,1,75,25.0,s2,s7
15,15,15_0,COMPLETED,GenerationStep_0,100.0,0.3528,0.2810,0.0711,57,12,25.0,s1,s3
16,16,16_0,COMPLETED,GenerationStep_0,84.0,0.2063,0.3073,0.0373,49,35,25.0,s8,s5
17,17,17_0,COMPLETED,GenerationStep_0,100.0,0.4045,0.4196,0.0728,15,22,25.0,s2,s5
18,18,18_0,COMPLETED,GenerationStep_0,100.0,0.2962,0.4364,0.0493,24,5,25.0,s2,s2
19,19,19_0,COMPLETED,GenerationStep_0,100.0,0.3528,0.2810,0.0711,10,54,25.0,s3,s7
20,20,20_0,COMPLETED,GenerationStep_0,100.0,0.2063,0.3073,0.0373,54,17,25.0,s1,s5
21,21,21_0,COMPLETED,GenerationStep_0,100.0,0.4045,0.4196,0.0728,40,43,25.0,s6,s4
22,22,22_0,COMPLETED,GenerationStep_0,100.0,0.2962,0.4364,0.0493,30,2,25.0,s3,s8
23,23,23_0,COMPLETED,GenerationStep_0,100.0,0.3528,0.2810,0.0711,63,25,25.0,s1,s5
24,24,24_0,COMPLETED,GenerationStep_0,49.0,0.2063,0.3073,0.0373,9,40,25.0,s7,s4
25,25,25_0,COMPLETED,GenerationStep_0,100.0,0.4045,0.4196,0.0728,41,50,25.0,s6,s3
26,26,26_0,COMPLETED,GenerationStep_0,100.0,0.2962,0.4364,0.0493,5,32,25.0,s6,s3
27,27,27_0,COMPLETED,GenerationStep_0,97.0,0.3528,0.2810,0.0711,89,8,25.0,s8,s1
28,28,28_0,COMPLETED,GenerationStep_0,54.0,0.2063,0.3073,0.0373,34,20,25.0,s2,s7
29,29,29_0,COMPLETED,GenerationStep_0,100.0,0.4045,0.4196,0.0728,16,83,25.0,s7,s2
30,30,30_0,COMPLETED,GenerationStep_0,87.0,0.2962,0.4364,0.0493,72,15,25.0,s8,s2
31,31,31_0,COMPLETED,GenerationStep_0,67.0,0.3528,0.2810,0.0711,14,53,25.0,s6,s1
32,32,32_0,COMPLETED,GenerationStep_1,100.0,0.2063,0.3073,0.0373,8,10,25.0,s4,s4
33,33,33_0,COMPLETED,GenerationStep_1,100.0,0.4045,0.4196,0.0728,5,9,25.0,s4,s4
34,34,34_0,COMPLETED,GenerationStep_1,100.0,0.2962,0.4364,0.0493,6,11,25.0,s4,s4
35,35,35_0,COMPLETED,GenerationStep_1,100.0,0.3528,0.2810,0.0711,6,8,25.0,s4,s4
36,36,36_0,COMPLETED,GenerationStep_1,100.0,0.2063,0.3073,0.0373,7,8,25.0,s4,s4
37,37,37_0,COMPLETED,GenerationStep_1,100.0,0.4045,0.4196,0.0728,6,10,25.0,s4,s4
38,38,38_0,COMPLETED,GenerationStep_1,100.0,0.2962,0.4364,0.0493,6,9,25.0,s4,s4
39,39,39_0,COMPLETED,GenerationStep_1,100.0,0.3528,0.2810,0.0711,6,10,25.0,s4,s4
40,40,40_0,COMPLETED,GenerationStep_1,100.0,0.2063,0.3073,0.0373,13,18,25.0,s4,s8
41,41,41_0,COMPLETED,GenerationStep_1,100.0,0.4045,0.4196,0.0728,9,18,25.0,s4,s8
42,42,42_0,COMPLETED,GenerationStep_1,100.0,0.2962,0.4364,0.0493,9,18,25.0,s4,s8
43,43,43_0,COMPLETED,GenerationStep_1,100.0,0.3528,0.2810,0.0711,25,18,25.0,s4,s8
44,44,44_0,COMPLETED,GenerationStep_1,100.0,0.2063,0.3073,0.0373,11,18,25.0,s4,s8
45,45,45_0,COMPLETED,GenerationStep_1,100.0,0.4045,0.4196,0.0728,18,18,25.0,s4,s8
46,46,46_0,COMPLETED,GenerationStep_1,32.0,0.2962,0.4364,0.0493,14,18,25.0,s4,s8
47,47,47_0,COMPLETED,GenerationStep_1,54.0,0.3528,0.2810,0.0711,36,18,25.0,s4,s8
48,48,48_0,RUNNING,GenerationStep_1,NaN,0.2063,0.3073,0.0373,22,15,25.0,s7,s6
49,49,49_0,RUNNING,GenerationStep_1,NaN,0.4045,0.4196,0.0728,15,16,25.0,s7,s6
50,50,50_0,RUNNING,GenerationStep_1,NaN,0.2962,0.4364,0.0493,22,16,25.0,s7,s6
51,51,51_0,RUNNING,GenerationStep_1,NaN,0.3528,0.2810,0.0711,26,15,25.0,s7,s6
52,52,52_0,RUNNING,GenerationStep_1,NaN,0.2063,0.3073,0.0373,23,15,25.0,s7,s6
53,53,53_0,RUNNING,GenerationStep_1,NaN,0.4045,0.4196,0.0728,28,15,25.0,s7,s6
54,54,54_0,RUNNING,GenerationStep_1,NaN,0.2962,0.4364,0.0493,29,16,25.0,s7,s6
55,55,55_0,RUNNING,GenerationStep_1,NaN,0.3528,0.2810,0.0711,26,14,25.0,s7,s6

In [5]:
df_design, df_vol = hf.design_to_vol (n)
df_design

,trial_index,drug_name,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,drug_conc,surf_1,surf_2,surf_conc,obj_surf_conc
0,48,IBP,0.2063,0.3073,0.0373,22,15,25.0,s7,s6,37,NaN
1,49,LOV,0.4045,0.4196,0.0728,15,16,25.0,s7,s6,31,NaN
2,50,DCF,0.2962,0.4364,0.0493,22,16,25.0,s7,s6,38,NaN
3,51,GLV,0.3528,0.2810,0.0711,26,15,25.0,s7,s6,41,NaN
4,52,IBP,0.2063,0.3073,0.0373,23,15,25.0,s7,s6,38,NaN
5,53,LOV,0.4045,0.4196,0.0728,28,15,25.0,s7,s6,43,NaN
6,54,DCF,0.2962,0.4364,0.0493,29,16,25.0,s7,s6,45,NaN
7,55,GLV,0.3528,0.2810,0.0711,26,14,25.0,s7,s6,40,NaN

In [6]:
df_vol

,trial_index,drug_name,drug,s1,s2,s3,s4,s5,s6,s7,s8,dmso,water,IBP,LOV,DCF,GLV
0,48,IBP,180.0,0.0,0.0,0.0,0.0,0.0,180.0,264.0,0.0,0.0,756.0,180.0,0.0,0.0,0.0
1,49,LOV,180.0,0.0,0.0,0.0,0.0,0.0,192.0,180.0,0.0,0.0,828.0,0.0,180.0,0.0,0.0
2,50,DCF,180.0,0.0,0.0,0.0,0.0,0.0,192.0,264.0,0.0,0.0,744.0,0.0,0.0,180.0,0.0
3,51,GLV,180.0,0.0,0.0,0.0,0.0,0.0,180.0,312.0,0.0,0.0,708.0,0.0,0.0,0.0,180.0
4,52,IBP,180.0,0.0,0.0,0.0,0.0,0.0,180.0,276.0,0.0,0.0,744.0,180.0,0.0,0.0,0.0
5,53,LOV,180.0,0.0,0.0,0.0,0.0,0.0,180.0,336.0,0.0,0.0,684.0,0.0,180.0,0.0,0.0
6,54,DCF,180.0,0.0,0.0,0.0,0.0,0.0,192.0,348.0,0.0,0.0,660.0,0.0,0.0,180.0,0.0
7,55,GLV,180.0,0.0,0.0,0.0,0.0,0.0,168.0,312.0,0.0,0.0,720.0,0.0,0.0,0.0,180.0

In [7]:
df_vol[['s1', 's2', 's3', 's4', 's5', 's6', 's7', 's8']].sum()

s1       0.0
s2       0.0
s3       0.0
s4       0.0
s5       0.0
s6    1464.0
s7    2292.0
s8       0.0
dtype: float64

In [8]:
plate_well = input("Enter the plate well starting well (e.g., F1): ")
deepplate_well = input("Enter the deep plate well starting well (e.g., F1): ")


print("Please confirm the following information:")
print("Wellplate will start at: " + plate_well)
print("Deep plate will start at: " + deepplate_well)

print()
print("*******************************************************")
print("Continue if correct, or rerun this cell if incorrect.")
print("*******************************************************")

Please confirm the following information:
Wellplate will start at: E1
Deep plate will start at: B5

*******************************************************
Continue if correct, or rerun this cell if incorrect.
*******************************************************

In [9]:
hf.generate_protocol(df_vol=df_vol, iteration=n, plate_well=plate_well, deepplate_well=deepplate_well)

✅ Successfully wrote to: protocol/otflex_3.py

In [10]:
df_absorbance = hf.process_absorbance(iteration=n, threshold=0.06)
df_absorbance

   trial_index  success
0            0        1
1            1        0
2            2        1
3            3        0
4            4        1
5            5        0
6            6        1
7            7        0

In [11]:
results = hf.build_results(n, df_absorbance)
results

,trial_index,drug_name,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,drug_conc,surf_1,surf_2,surf_conc,obj_surf_conc,success
0,48,IBP,0.2063,0.3073,0.0373,22,15,25.0,s7,s6,37,37,1
1,49,LOV,0.4045,0.4196,0.0728,15,16,25.0,s7,s6,31,100,0
2,50,DCF,0.2962,0.4364,0.0493,22,16,25.0,s7,s6,38,38,1
3,51,GLV,0.3528,0.2810,0.0711,26,15,25.0,s7,s6,41,100,0
4,52,IBP,0.2063,0.3073,0.0373,23,15,25.0,s7,s6,38,38,1
5,53,LOV,0.4045,0.4196,0.0728,28,15,25.0,s7,s6,43,100,0
6,54,DCF,0.2962,0.4364,0.0493,29,16,25.0,s7,s6,45,45,1
7,55,GLV,0.3528,0.2810,0.0711,26,14,25.0,s7,s6,40,100,0

# load the results to the optimizer

In [12]:
ax_client = hf.load_data_to_optimizer(iteration = n, results = results)
ax_client

[INFO 07-29 13:53:19] ax.service.ax_client: Completed trial 48 with data: {'obj_surf_conc': (37.0, None)}.
[INFO 07-29 13:53:19] ax.service.ax_client: Completed trial 49 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-29 13:53:19] ax.service.ax_client: Completed trial 50 with data: {'obj_surf_conc': (38.0, None)}.
[INFO 07-29 13:53:19] ax.service.ax_client: Completed trial 51 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-29 13:53:19] ax.service.ax_client: Completed trial 52 with data: {'obj_surf_conc': (38.0, None)}.
[INFO 07-29 13:53:19] ax.service.ax_client: Completed trial 53 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-29 13:53:19] ax.service.ax_client: Completed trial 54 with data: {'obj_surf_conc': (45.0, None)}.
[INFO 07-29 13:53:19] ax.service.ax_client: Completed trial 55 with data: {'obj_surf_conc': (100.0, None)}.

AxClient(experiment=Experiment(drug_surfactant))