# import libraries

In [1]:
import pandas as pd
from ax.service.ax_client import AxClient, ObjectiveProperties
import matplotlib.pyplot as plt
from ax.modelbridge.registry import Models
from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy   
import time


import sys
sys.path.append('../')
import helper_functions as hf

/var/folders/9p/f66yhymx35939zzlg51g0rrc0000gn/T/ipykernel_63661/3307975217.py:5: DeprecationWarning: Please import from 'ax.generation_strategy.generation_strategy' instead of 'ax.modelbridge.generation_strategy'. The latter is deprecated and will be removed in a future release.
  from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy

# generate recommendations

In [2]:
n = hf.get_iteration_number()

for i in range(3):
    print("Very Important: Please Confirm the Iteration Number is Iteration " + str(n))

print()

list_of_drugs = (['IBP']  + ['LOV']  + ['DCF']  + ['GLV']) * 2

for i in range(3):
    print("Very Important: Please Confirm the Drugs are: ", list_of_drugs)

Very Important: Please Confirm the Iteration Number is Iteration 9
Very Important: Please Confirm the Iteration Number is Iteration 9
Very Important: Please Confirm the Iteration Number is Iteration 9

Very Important: Please Confirm the Drugs are:  ['IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV']
Very Important: Please Confirm the Drugs are:  ['IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV']
Very Important: Please Confirm the Drugs are:  ['IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV']

In [3]:
time_start = time.time()


df_design, ax_client, data_so_far, best_concs = hf.run_optimizer(current_iteration=n, drug_list= list_of_drugs,  bopt = 1)

time_end = time.time()
time_duration = round((time_end - time_start)/60,2)

print("Time taken for optimization: " + str(time_duration) + " mins")
print("Time taken for optimization: " + str(time_duration * 60) + " seconds")

******************************************************************************** 1/8 ********************************************************************************

Update constraints (drug=IBP)：surf_1_conc+surf_2_conc <= 22.0，>=1

[INFO 07-31 11:17:53] ax.service.ax_client: Generated new trial 96 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 14, 'surf_2_conc': 8, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's6'} using model BoTorch.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

******************************************************************************** 2/8 ********************************************************************************

Update constraints (drug=LOV)：surf_1_conc+surf_2_conc <= 29.0，>=1

[INFO 07-31 11:17:56] ax.service.ax_client: Generated new trial 97 with parameters {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 13, 'surf_2_conc': 16, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's8'} using model BoTorch.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

******************************************************************************** 3/8 ********************************************************************************

Update constraints (drug=DCF)：surf_1_conc+surf_2_conc <= 30.0，>=1

[INFO 07-31 11:17:58] ax.service.ax_client: Generated new trial 98 with parameters {'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 30, 'surf_2_conc': 0, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's4'} using model BoTorch.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

******************************************************************************** 4/8 ********************************************************************************

Update constraints (drug=GLV)：surf_1_conc+surf_2_conc <= 50.0，>=1

[INFO 07-31 11:18:00] ax.service.ax_client: Generated new trial 99 with parameters {'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 13, 'surf_2_conc': 37, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's8'} using model BoTorch.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

******************************************************************************** 5/8 ********************************************************************************

Update constraints (drug=IBP)：surf_1_conc+surf_2_conc <= 22.0，>=1

[INFO 07-31 11:18:03] ax.service.ax_client: Generated new trial 100 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 14, 'surf_2_conc': 7, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's6'} using model BoTorch.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

******************************************************************************** 6/8 ********************************************************************************

Update constraints (drug=LOV)：surf_1_conc+surf_2_conc <= 29.0，>=1

[INFO 07-31 11:18:06] ax.service.ax_client: Generated new trial 101 with parameters {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 13, 'surf_2_conc': 16, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's8'} using model BoTorch.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

******************************************************************************** 7/8 ********************************************************************************

Update constraints (drug=DCF)：surf_1_conc+surf_2_conc <= 30.0，>=1

[INFO 07-31 11:18:09] ax.service.ax_client: Generated new trial 102 with parameters {'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 14, 'surf_2_conc': 16, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's8'} using model BoTorch.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

******************************************************************************** 8/8 ********************************************************************************

Update constraints (drug=GLV)：surf_1_conc+surf_2_conc <= 50.0，>=1

[INFO 07-31 11:18:12] ax.service.ax_client: Generated new trial 103 with parameters {'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 13, 'surf_2_conc': 30, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's8'} using model BoTorch.

Time taken for optimization: 0.36 mins
Time taken for optimization: 21.599999999999998 seconds

# process results

In [4]:
ax_client = hf.load_design_optimizer(n)
ax_client.get_trials_data_frame()

/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

,trial_index,arm_name,trial_status,generation_node,obj_surf_conc,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,drug_conc,surf_1,surf_2
0,0,0_0,COMPLETED,GenerationStep_0,35.0,0.2063,0.3073,0.0373,29,6,25.0,s7,s6
1,1,1_0,COMPLETED,GenerationStep_0,50.0,0.4045,0.4196,0.0728,6,44,25.0,s4,s4
2,2,2_0,COMPLETED,GenerationStep_0,100.0,0.2962,0.4364,0.0493,4,27,25.0,s2,s6
3,3,3_0,COMPLETED,GenerationStep_0,92.0,0.3528,0.2810,0.0711,91,1,25.0,s1,s2
4,4,4_0,COMPLETED,GenerationStep_0,46.0,0.2063,0.3073,0.0373,32,14,25.0,s3,s4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99,99,99_0,RUNNING,GenerationStep_1,NaN,0.3528,0.2810,0.0711,13,37,25.0,s4,s8
100,100,100_0,RUNNING,GenerationStep_1,NaN,0.2063,0.3073,0.0373,14,7,25.0,s7,s6
101,101,97_0,RUNNING,GenerationStep_1,NaN,0.4045,0.4196,0.0728,13,16,25.0,s4,s8
102,102,102_0,RUNNING,GenerationStep_1,NaN,0.2962,0.4364,0.0493,14,16,25.0,s4,s8
103,103,103_0,RUNNING,GenerationStep_1,NaN,0.3528,0.2810,0.0711,13,30,25.0,s4,s8

In [5]:
df_design, df_vol = hf.design_to_vol (n)
df_design['constraint'] = df_design['drug_name'].map(best_concs).fillna(0.0)
df_design

,trial_index,drug_name,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,drug_conc,surf_1,surf_2,surf_conc,obj_surf_conc,constraint
0,96,IBP,0.2063,0.3073,0.0373,14,8,25.0,s7,s6,22,NaN,23.0
1,97,LOV,0.4045,0.4196,0.0728,13,16,25.0,s4,s8,29,NaN,30.0
2,98,DCF,0.2962,0.4364,0.0493,30,0,25.0,s7,s4,30,NaN,31.0
3,99,GLV,0.3528,0.2810,0.0711,13,37,25.0,s4,s8,50,NaN,51.0
4,100,IBP,0.2063,0.3073,0.0373,14,7,25.0,s7,s6,21,NaN,23.0
5,101,LOV,0.4045,0.4196,0.0728,13,16,25.0,s4,s8,29,NaN,30.0
6,102,DCF,0.2962,0.4364,0.0493,14,16,25.0,s4,s8,30,NaN,31.0
7,103,GLV,0.3528,0.2810,0.0711,13,30,25.0,s4,s8,43,NaN,51.0

In [6]:
df_vol

,trial_index,drug_name,drug,s1,s2,s3,s4,s5,s6,s7,s8,dmso,water,IBP,LOV,DCF,GLV
0,96,IBP,180.0,0.0,0.0,0.0,0.0,0.0,96.0,168.0,0.0,0.0,936.0,180.0,0.0,0.0,0.0
1,97,LOV,180.0,0.0,0.0,0.0,156.0,0.0,0.0,0.0,192.0,0.0,852.0,0.0,180.0,0.0,0.0
2,98,DCF,180.0,0.0,0.0,0.0,0.0,0.0,0.0,360.0,0.0,0.0,840.0,0.0,0.0,180.0,0.0
3,99,GLV,180.0,0.0,0.0,0.0,156.0,0.0,0.0,0.0,444.0,0.0,600.0,0.0,0.0,0.0,180.0
4,100,IBP,180.0,0.0,0.0,0.0,0.0,0.0,84.0,168.0,0.0,0.0,948.0,180.0,0.0,0.0,0.0
5,101,LOV,180.0,0.0,0.0,0.0,156.0,0.0,0.0,0.0,192.0,0.0,852.0,0.0,180.0,0.0,0.0
6,102,DCF,180.0,0.0,0.0,0.0,168.0,0.0,0.0,0.0,192.0,0.0,840.0,0.0,0.0,180.0,0.0
7,103,GLV,180.0,0.0,0.0,0.0,156.0,0.0,0.0,0.0,360.0,0.0,684.0,0.0,0.0,0.0,180.0

In [7]:
print("Please ensure to refill the water vial to 20 mL")
print("Please ensure to refill the water vial to 20 mL")
print("Please ensure to refill the water vial to 20 mL")


df_vol[['s1', 's2', 's3', 's4', 's5', 's6', 's7', 's8', 'water']].sum()

Please ensure to refill the water vial to 20 mL
Please ensure to refill the water vial to 20 mL
Please ensure to refill the water vial to 20 mL

s1          0.0
s2          0.0
s3          0.0
s4        792.0
s5          0.0
s6        180.0
s7        696.0
s8       1380.0
water    6552.0
dtype: float64

In [8]:
plate_well = input("Enter the plate well starting well (e.g., F1): ")
deepplate_well = input("Enter the deep plate well starting well (e.g., F1): ")


print("Please confirm the following information:")
print("Wellplate will start at: " + plate_well)
print("Deep plate will start at: " + deepplate_well)

print()
print("*******************************************************")
print("Continue if correct, or rerun this cell if incorrect.")
print("*******************************************************")

Please confirm the following information:
Wellplate will start at: C1
Deep plate will start at: C9

*******************************************************
Continue if correct, or rerun this cell if incorrect.
*******************************************************

In [9]:
hf.generate_protocol(df_vol=df_vol, iteration=n, plate_well=plate_well, deepplate_well=deepplate_well)

✅ Successfully wrote to: protocol/otflex_9.py

In [10]:
df_absorbance = hf.process_absorbance(iteration=n, threshold=0.06)
df_absorbance

   trial_index  success
0            0        1
1            1        0
2            2        0
3            3        0
4            4        1
5            5        0
6            6        0
7            7        1

In [11]:
results = hf.build_results(n, df_absorbance)
results

,trial_index,drug_name,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,drug_conc,surf_1,surf_2,surf_conc,obj_surf_conc,success
0,96,IBP,0.2063,0.3073,0.0373,14,8,25.0,s7,s6,22,22,1
1,97,LOV,0.4045,0.4196,0.0728,13,16,25.0,s4,s8,29,100,0
2,98,DCF,0.2962,0.4364,0.0493,30,0,25.0,s7,s4,30,100,0
3,99,GLV,0.3528,0.2810,0.0711,13,37,25.0,s4,s8,50,100,0
4,100,IBP,0.2063,0.3073,0.0373,14,7,25.0,s7,s6,21,21,1
5,101,LOV,0.4045,0.4196,0.0728,13,16,25.0,s4,s8,29,100,0
6,102,DCF,0.2962,0.4364,0.0493,14,16,25.0,s4,s8,30,100,0
7,103,GLV,0.3528,0.2810,0.0711,13,30,25.0,s4,s8,43,43,1

# load the results to the optimizer

In [12]:
ax_client = hf.load_data_to_optimizer(iteration = n, results = results)
ax_client

[INFO 07-31 15:05:31] ax.service.ax_client: Completed trial 96 with data: {'obj_surf_conc': (22.0, None)}.
[INFO 07-31 15:05:31] ax.service.ax_client: Completed trial 97 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 15:05:31] ax.service.ax_client: Completed trial 98 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 15:05:31] ax.service.ax_client: Completed trial 99 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 15:05:31] ax.service.ax_client: Completed trial 100 with data: {'obj_surf_conc': (21.0, None)}.
[INFO 07-31 15:05:31] ax.service.ax_client: Completed trial 101 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 15:05:31] ax.service.ax_client: Completed trial 102 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 15:05:31] ax.service.ax_client: Completed trial 103 with data: {'obj_surf_conc': (43.0, None)}.

AxClient(experiment=Experiment(drug_surfactant))