# import libraries

In [1]:
import pandas as pd
from ax.service.ax_client import AxClient, ObjectiveProperties
import matplotlib.pyplot as plt
from ax.modelbridge.registry import Models
from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy   
import time


import sys
sys.path.append('../')
import helper_functions as hf

/var/folders/hk/7jjnrbrj53n1t8_bmkhf0_k00000gn/T/ipykernel_28000/3307975217.py:5: DeprecationWarning: Please import from 'ax.generation_strategy.generation_strategy' instead of 'ax.modelbridge.generation_strategy'. The latter is deprecated and will be removed in a future release.
  from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy

# generate recommendations

In [2]:
n = hf.get_iteration_number()

for i in range(3):
    print("Very Important: Please Confirm the Iteration Number is Iteration " + str(n))

print()

list_of_drugs = (['IBP']  + ['LOV']  + ['DCF']  + ['GLV']) * 1

for i in range(3):
    print("Very Important: Please Confirm the Drugs are: ", list_of_drugs)

Very Important: Please Confirm the Iteration Number is Iteration 1
Very Important: Please Confirm the Iteration Number is Iteration 1
Very Important: Please Confirm the Iteration Number is Iteration 1

Very Important: Please Confirm the Drugs are:  ['IBP', 'LOV', 'DCF', 'GLV']
Very Important: Please Confirm the Drugs are:  ['IBP', 'LOV', 'DCF', 'GLV']
Very Important: Please Confirm the Drugs are:  ['IBP', 'LOV', 'DCF', 'GLV']

In [3]:
data_so_far, constrainst = hf.fetch_previous_design(current_iteration=n, drug_list=list_of_drugs, drug='IBP')

'IBP' is at index 0

In [4]:
data_so_far

,trial_index,arm_name,trial_status,generation_node,obj_surf_conc,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,drug_conc,surf_1,surf_2,drug_name,drug_full
0,0,0_0,COMPLETED,GenerationStep_0,35.0,0.2063,0.3073,0.0373,29,6,25.0,s7,s6,IBP,Ibuprofen
1,1,1_0,COMPLETED,GenerationStep_0,50.0,0.4045,0.4196,0.0728,6,44,25.0,s4,s4,LOV,Lovastatin
2,2,2_0,COMPLETED,GenerationStep_0,100.0,0.2962,0.4364,0.0493,4,27,25.0,s2,s6,DCF,Diclofenac
3,3,3_0,COMPLETED,GenerationStep_0,92.0,0.3528,0.2810,0.0711,91,1,25.0,s1,s2,GLV,Griseofulvin
4,4,4_0,COMPLETED,GenerationStep_0,46.0,0.2063,0.3073,0.0373,32,14,25.0,s3,s4,IBP,Ibuprofen
5,5,5_0,COMPLETED,GenerationStep_0,94.0,0.4045,0.4196,0.0728,18,76,25.0,s8,s1,LOV,Lovastatin
6,6,6_0,COMPLETED,GenerationStep_0,62.0,0.2962,0.4364,0.0493,59,3,25.0,s8,s2,DCF,Diclofenac
7,7,7_0,COMPLETED,GenerationStep_0,100.0,0.3528,0.2810,0.0711,2,66,25.0,s3,s6,GLV,Griseofulvin
8,8,8_0,COMPLETED,GenerationStep_0,79.0,0.2063,0.3073,0.0373,48,31,25.0,s4,s6,IBP,Ibuprofen
9,9,9_0,COMPLETED,GenerationStep_0,30.0,0.4045,0.4196,0.0728,12,18,25.0,s4,s8,LOV,Lovastatin
10,10,10_0,COMPLETED,GenerationStep_0,100.0,0.2962,0.4364,0.0493,22,10,25.0,s6,s1,DCF,Diclofenac
11,11,11_0,COMPLETED,GenerationStep_0,100.0,0.3528,0.2810,0.0711,55,24,25.0,s2,s4,GLV,Griseofulvin
12,12,12_0,COMPLETED,GenerationStep_0,73.0,0.2063,0.3073,0.0373,12,61,25.0,s1,s8,IBP,Ibuprofen
13,13,13_0,COMPLETED,GenerationStep_0,100.0,0.4045,0.4196,0.0728,38,48,25.0,s1,s1,LOV,Lovastatin
14,14,14_0,COMPLETED,GenerationStep_0,100.0,0.2962,0.4364,0.0493,1,75,25.0,s2,s7,DCF,Diclofenac
15,15,15_0,COMPLETED,GenerationStep_0,100.0,0.3528,0.2810,0.0711,57,12,25.0,s1,s3,GLV,Griseofulvin
16,16,16_0,COMPLETED,GenerationStep_0,84.0,0.2063,0.3073,0.0373,49,35,25.0,s8,s5,IBP,Ibuprofen
17,17,17_0,COMPLETED,GenerationStep_0,100.0,0.4045,0.4196,0.0728,15,22,25.0,s2,s5,LOV,Lovastatin
18,18,18_0,COMPLETED,GenerationStep_0,100.0,0.2962,0.4364,0.0493,24,5,25.0,s2,s2,DCF,Diclofenac
19,19,19_0,COMPLETED,GenerationStep_0,100.0,0.3528,0.2810,0.0711,10,54,25.0,s3,s7,GLV,Griseofulvin
20,20,20_0,COMPLETED,GenerationStep_0,100.0,0.2063,0.3073,0.0373,54,17,25.0,s1,s5,IBP,Ibuprofen
21,21,21_0,COMPLETED,GenerationStep_0,100.0,0.4045,0.4196,0.0728,40,43,25.0,s6,s4,LOV,Lovastatin
22,22,22_0,COMPLETED,GenerationStep_0,100.0,0.2962,0.4364,0.0493,30,2,25.0,s3,s8,DCF,Diclofenac
23,23,23_0,COMPLETED,GenerationStep_0,100.0,0.3528,0.2810,0.0711,63,25,25.0,s1,s5,GLV,Griseofulvin
24,24,24_0,COMPLETED,GenerationStep_0,49.0,0.2063,0.3073,0.0373,9,40,25.0,s7,s4,IBP,Ibuprofen
25,25,25_0,COMPLETED,GenerationStep_0,100.0,0.4045,0.4196,0.0728,41,50,25.0,s6,s3,LOV,Lovastatin
26,26,26_0,COMPLETED,GenerationStep_0,100.0,0.2962,0.4364,0.0493,5,32,25.0,s6,s3,DCF,Diclofenac
27,27,27_0,COMPLETED,GenerationStep_0,97.0,0.3528,0.2810,0.0711,89,8,25.0,s8,s1,GLV,Griseofulvin
28,28,28_0,COMPLETED,GenerationStep_0,54.0,0.2063,0.3073,0.0373,34,20,25.0,s2,s7,IBP,Ibuprofen
29,29,29_0,COMPLETED,GenerationStep_0,100.0,0.4045,0.4196,0.0728,16,83,25.0,s7,s2,LOV,Lovastatin
30,30,30_0,COMPLETED,GenerationStep_0,87.0,0.2962,0.4364,0.0493,72,15,25.0,s8,s2,DCF,Diclofenac
31,31,31_0,COMPLETED,GenerationStep_0,67.0,0.3528,0.2810,0.0711,14,53,25.0,s6,s1,GLV,Griseofulvin

In [18]:
ax_client_dict = {}

for drug in list_of_drugs:
    print("Very Important: Please Confirm the Drug is: ", drug)
    ax_client_drug_init = hf.optimizer_init(drug, constrainst)

    experiment = ax_client_drug_init.experiment
    orig_constraints = experiment.search_space._parameter_constraints

    experiment.search_space._parameter_constraints = []

    ax_client_drug_warm = hf.load_warm_start(ax_client_drug_init, data_so_far, objective_col="obj_surf_conc")

    experiment.search_space._parameter_constraints = orig_constraints

    ax_client_dict[drug] = ax_client_drug_warm

    print("Very Important: Please Confirm the Drug is: ", drug, " and the constraints are: ", ax_client_dict[drug].experiment.search_space._parameter_constraints)

[INFO 07-31 06:18:30] ax.service.utils.instantiation: Inferred value type of ParameterType.STRING for parameter surf_1. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/service/utils/instantiation.py:258: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "surf_1". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return ChoiceParameter(
[INFO 07-31 06:18:30] ax.service.utils.instantiation: Inferred value type of ParameterType.STRING for parameter surf_2. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/service/utils/instantiation.py:258: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "surf_2". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return ChoiceParameter(
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 0 with data: {'obj_surf_conc': (35.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 1 with data: {'obj_surf_conc': (50.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 2 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 3 with data: {'obj_surf_conc': (92.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 4 with data: {'obj_surf_conc': (46.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 5 with data: {'obj_surf_conc': (94.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 6 with data: {'obj_surf_conc': (62.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 7 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 8 with data: {'obj_surf_conc': (79.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 9 with data: {'obj_surf_conc': (30.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 10 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 11 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 12 with data: {'obj_surf_conc': (73.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 13 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 14 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 15 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 16 with data: {'obj_surf_conc': (84.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 17 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 18 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 19 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 20 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 21 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 22 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 23 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 24 with data: {'obj_surf_conc': (49.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 25 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 26 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 27 with data: {'obj_surf_conc': (97.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 28 with data: {'obj_surf_conc': (54.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 29 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 30 with data: {'obj_surf_conc': (87.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 31 with data: {'obj_surf_conc': (67.0, None)}.
[INFO 07-31 06:18:30] ax.service.utils.instantiation: Inferred value type of ParameterType.STRING for parameter surf_1. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/service/utils/instantiation.py:258: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "surf_1". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return ChoiceParameter(
[INFO 07-31 06:18:30] ax.service.utils.instantiation: Inferred value type of ParameterType.STRING for parameter surf_2. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/service/utils/instantiation.py:258: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "surf_2". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return ChoiceParameter(
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 0 with data: {'obj_surf_conc': (35.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 1 with data: {'obj_surf_conc': (50.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 2 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 3 with data: {'obj_surf_conc': (92.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 4 with data: {'obj_surf_conc': (46.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 5 with data: {'obj_surf_conc': (94.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 6 with data: {'obj_surf_conc': (62.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 7 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 8 with data: {'obj_surf_conc': (79.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 9 with data: {'obj_surf_conc': (30.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 10 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 11 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 12 with data: {'obj_surf_conc': (73.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 13 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 14 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 15 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 16 with data: {'obj_surf_conc': (84.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 17 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 18 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 19 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 20 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 21 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 22 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 23 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 24 with data: {'obj_surf_conc': (49.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 25 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 26 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 27 with data: {'obj_surf_conc': (97.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 28 with data: {'obj_surf_conc': (54.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 29 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 30 with data: {'obj_surf_conc': (87.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 31 with data: {'obj_surf_conc': (67.0, None)}.
[INFO 07-31 06:18:30] ax.service.utils.instantiation: Inferred value type of ParameterType.STRING for parameter surf_1. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/service/utils/instantiation.py:258: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "surf_1". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return ChoiceParameter(
[INFO 07-31 06:18:30] ax.service.utils.instantiation: Inferred value type of ParameterType.STRING for parameter surf_2. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/service/utils/instantiation.py:258: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "surf_2". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return ChoiceParameter(
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 0 with data: {'obj_surf_conc': (35.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 1 with data: {'obj_surf_conc': (50.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 2 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 3 with data: {'obj_surf_conc': (92.0, None)}.

Very Important: Please Confirm the Drug is:  IBP
Very Important: Please Confirm the Drug is:  IBP  and the constraints are:  [ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 34.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)]
Very Important: Please Confirm the Drug is:  LOV
Very Important: Please Confirm the Drug is:  LOV  and the constraints are:  [ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 29.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)]
Very Important: Please Confirm the Drug is:  DCF

[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 4 with data: {'obj_surf_conc': (46.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 5 with data: {'obj_surf_conc': (94.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 6 with data: {'obj_surf_conc': (62.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 7 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 8 with data: {'obj_surf_conc': (79.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 9 with data: {'obj_surf_conc': (30.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 10 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 11 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 12 with data: {'obj_surf_conc': (73.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 13 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 14 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 15 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 16 with data: {'obj_surf_conc': (84.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 17 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 18 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 19 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 20 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 21 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 22 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 23 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 24 with data: {'obj_surf_conc': (49.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 25 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 26 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 27 with data: {'obj_surf_conc': (97.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 28 with data: {'obj_surf_conc': (54.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 29 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 30 with data: {'obj_surf_conc': (87.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 31 with data: {'obj_surf_conc': (67.0, None)}.
[INFO 07-31 06:18:30] ax.service.utils.instantiation: Inferred value type of ParameterType.STRING for parameter surf_1. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/service/utils/instantiation.py:258: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "surf_1". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return ChoiceParameter(
[INFO 07-31 06:18:30] ax.service.utils.instantiation: Inferred value type of ParameterType.STRING for parameter surf_2. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/service/utils/instantiation.py:258: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "surf_2". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return ChoiceParameter(
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 0 with data: {'obj_surf_conc': (35.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 1 with data: {'obj_surf_conc': (50.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 2 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 3 with data: {'obj_surf_conc': (92.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 4 with data: {'obj_surf_conc': (46.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 5 with data: {'obj_surf_conc': (94.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 6 with data: {'obj_surf_conc': (62.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 7 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 8 with data: {'obj_surf_conc': (79.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 9 with data: {'obj_surf_conc': (30.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 10 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 11 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 12 with data: {'obj_surf_conc': (73.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 13 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 14 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 15 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 16 with data: {'obj_surf_conc': (84.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 17 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 18 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 19 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 20 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 21 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 22 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 23 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 24 with data: {'obj_surf_conc': (49.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 25 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 26 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 27 with data: {'obj_surf_conc': (97.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 28 with data: {'obj_surf_conc': (54.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 29 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 30 with data: {'obj_surf_conc': (87.0, None)}.
[INFO 07-31 06:18:30] ax.service.ax_client: Completed trial 31 with data: {'obj_surf_conc': (67.0, None)}.

Very Important: Please Confirm the Drug is:  DCF  and the constraints are:  [ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 61.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)]
Very Important: Please Confirm the Drug is:  GLV
Very Important: Please Confirm the Drug is:  GLV  and the constraints are:  [ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 66.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)]

In [16]:
experiment = ax_client_drug_init.experiment
orig_constraints = experiment.search_space.parameter_constraints
orig_constraints

[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 66.0),
 ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)]

In [12]:
experiment.search_space._parameter_constraints = ['s1_conc >0']

In [13]:
ax_client_drug_init.experiment.search_space._parameter_constraints

['s1_conc >0']

In [3]:
time_start = time.time()


df_design, ax_client = hf.run_optimizer(current_iteration=n, drug_list= list_of_drugs,  bopt = 1)

time_end = time.time()
time_duration = round((time_end - time_start)/60,2)

print("Time taken for optimization: " + str(time_duration) + " mins")
print("Time taken for optimization: " + str(time_duration * 60) + " seconds")

**************************************************************************************************** 1  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Ibuprofen IBP  | Iteration:  1

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[INFO 07-29 09:24:42] ax.service.ax_client: Generated new trial 32 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 8, 'surf_2_conc': 10, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's4'} using model BoTorch.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

**************************************************************************************************** 2  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Lovastatin LOV  | Iteration:  1

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[INFO 07-29 09:24:45] ax.service.ax_client: Generated new trial 33 with parameters {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 5, 'surf_2_conc': 9, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's4'} using model BoTorch.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

**************************************************************************************************** 3  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Diclofenac DCF  | Iteration:  1

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[INFO 07-29 09:24:48] ax.service.ax_client: Generated new trial 34 with parameters {'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 6, 'surf_2_conc': 11, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's4'} using model BoTorch.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

**************************************************************************************************** 4  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Griseofulvin GLV  | Iteration:  1

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[INFO 07-29 09:24:51] ax.service.ax_client: Generated new trial 35 with parameters {'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 6, 'surf_2_conc': 8, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's4'} using model BoTorch.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

**************************************************************************************************** 5  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Ibuprofen IBP  | Iteration:  1

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[INFO 07-29 09:24:54] ax.service.ax_client: Generated new trial 36 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 7, 'surf_2_conc': 8, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's4'} using model BoTorch.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

**************************************************************************************************** 6  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Lovastatin LOV  | Iteration:  1

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[INFO 07-29 09:24:57] ax.service.ax_client: Generated new trial 37 with parameters {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 6, 'surf_2_conc': 10, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's4'} using model BoTorch.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

**************************************************************************************************** 7  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Diclofenac DCF  | Iteration:  1

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[INFO 07-29 09:25:00] ax.service.ax_client: Generated new trial 38 with parameters {'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 6, 'surf_2_conc': 9, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's4'} using model BoTorch.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

**************************************************************************************************** 8  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Griseofulvin GLV  | Iteration:  1

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[INFO 07-29 09:25:03] ax.service.ax_client: Generated new trial 39 with parameters {'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 6, 'surf_2_conc': 10, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's4'} using model BoTorch.

Time taken for optimization: 0.42 mins
Time taken for optimization: 25.2 seconds

# process results

In [4]:
ax_client = hf.load_design_optimizer(n)
ax_client.experiment.trials

{0: Trial(experiment_name='drug_surfactant', index=0, status=TrialStatus.COMPLETED, arm=Arm(name='0_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 29, 'surf_2_conc': 6, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's6'})),
 1: Trial(experiment_name='drug_surfactant', index=1, status=TrialStatus.COMPLETED, arm=Arm(name='1_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 6, 'surf_2_conc': 44, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's4'})),
 2: Trial(experiment_name='drug_surfactant', index=2, status=TrialStatus.COMPLETED, arm=Arm(name='2_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 4, 'surf_2_conc': 27, 'drug_conc': 25.0, 'surf_1': 's2', 'surf_2': 's6'})),
 3: Trial(experiment_name='drug_surfactant', index=3, status=TrialStatus.COMPLETED, arm=Arm(name='3_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 91, 'surf_2_conc': 1, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's2'})),
 4: Trial(experiment_name='drug_surfactant', index=4, status=TrialStatus.COMPLETED, arm=Arm(name='4_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 32, 'surf_2_conc': 14, 'drug_conc': 25.0, 'surf_1': 's3', 'surf_2': 's4'})),
 5: Trial(experiment_name='drug_surfactant', index=5, status=TrialStatus.COMPLETED, arm=Arm(name='5_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 18, 'surf_2_conc': 76, 'drug_conc': 25.0, 'surf_1': 's8', 'surf_2': 's1'})),
 6: Trial(experiment_name='drug_surfactant', index=6, status=TrialStatus.COMPLETED, arm=Arm(name='6_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 59, 'surf_2_conc': 3, 'drug_conc': 25.0, 'surf_1': 's8', 'surf_2': 's2'})),
 7: Trial(experiment_name='drug_surfactant', index=7, status=TrialStatus.COMPLETED, arm=Arm(name='7_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 2, 'surf_2_conc': 66, 'drug_conc': 25.0, 'surf_1': 's3', 'surf_2': 's6'})),
 8: Trial(experiment_name='drug_surfactant', index=8, status=TrialStatus.COMPLETED, arm=Arm(name='8_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 48, 'surf_2_conc': 31, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's6'})),
 9: Trial(experiment_name='drug_surfactant', index=9, status=TrialStatus.COMPLETED, arm=Arm(name='9_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 12, 'surf_2_conc': 18, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's8'})),
 10: Trial(experiment_name='drug_surfactant', index=10, status=TrialStatus.COMPLETED, arm=Arm(name='10_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 22, 'surf_2_conc': 10, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's1'})),
 11: Trial(experiment_name='drug_surfactant', index=11, status=TrialStatus.COMPLETED, arm=Arm(name='11_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 55, 'surf_2_conc': 24, 'drug_conc': 25.0, 'surf_1': 's2', 'surf_2': 's4'})),
 12: Trial(experiment_name='drug_surfactant', index=12, status=TrialStatus.COMPLETED, arm=Arm(name='12_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 12, 'surf_2_conc': 61, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's8'})),
 13: Trial(experiment_name='drug_surfactant', index=13, status=TrialStatus.COMPLETED, arm=Arm(name='13_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 38, 'surf_2_conc': 48, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's1'})),
 14: Trial(experiment_name='drug_surfactant', index=14, status=TrialStatus.COMPLETED, arm=Arm(name='14_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 1, 'surf_2_conc': 75, 'drug_conc': 25.0, 'surf_1': 's2', 'surf_2': 's7'})),
 15: Trial(experiment_name='drug_surfactant', index=15, status=TrialStatus.COMPLETED, arm=Arm(name='15_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 57, 'surf_2_conc': 12, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's3'})),
 16: Trial(experiment_name='drug_surfactant', index=16, status=TrialStatus.COMPLETED, arm=Arm(name='16_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 49, 'surf_2_conc': 35, 'drug_conc': 25.0, 'surf_1': 's8', 'surf_2': 's5'})),
 17: Trial(experiment_name='drug_surfactant', index=17, status=TrialStatus.COMPLETED, arm=Arm(name='17_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 15, 'surf_2_conc': 22, 'drug_conc': 25.0, 'surf_1': 's2', 'surf_2': 's5'})),
 18: Trial(experiment_name='drug_surfactant', index=18, status=TrialStatus.COMPLETED, arm=Arm(name='18_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 24, 'surf_2_conc': 5, 'drug_conc': 25.0, 'surf_1': 's2', 'surf_2': 's2'})),
 19: Trial(experiment_name='drug_surfactant', index=19, status=TrialStatus.COMPLETED, arm=Arm(name='19_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 10, 'surf_2_conc': 54, 'drug_conc': 25.0, 'surf_1': 's3', 'surf_2': 's7'})),
 20: Trial(experiment_name='drug_surfactant', index=20, status=TrialStatus.COMPLETED, arm=Arm(name='20_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 54, 'surf_2_conc': 17, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's5'})),
 21: Trial(experiment_name='drug_surfactant', index=21, status=TrialStatus.COMPLETED, arm=Arm(name='21_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 40, 'surf_2_conc': 43, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's4'})),
 22: Trial(experiment_name='drug_surfactant', index=22, status=TrialStatus.COMPLETED, arm=Arm(name='22_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 30, 'surf_2_conc': 2, 'drug_conc': 25.0, 'surf_1': 's3', 'surf_2': 's8'})),
 23: Trial(experiment_name='drug_surfactant', index=23, status=TrialStatus.COMPLETED, arm=Arm(name='23_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 63, 'surf_2_conc': 25, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's5'})),
 24: Trial(experiment_name='drug_surfactant', index=24, status=TrialStatus.COMPLETED, arm=Arm(name='24_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 9, 'surf_2_conc': 40, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's4'})),
 25: Trial(experiment_name='drug_surfactant', index=25, status=TrialStatus.COMPLETED, arm=Arm(name='25_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 41, 'surf_2_conc': 50, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's3'})),
 26: Trial(experiment_name='drug_surfactant', index=26, status=TrialStatus.COMPLETED, arm=Arm(name='26_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 5, 'surf_2_conc': 32, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's3'})),
 27: Trial(experiment_name='drug_surfactant', index=27, status=TrialStatus.COMPLETED, arm=Arm(name='27_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 89, 'surf_2_conc': 8, 'drug_conc': 25.0, 'surf_1': 's8', 'surf_2': 's1'})),
 28: Trial(experiment_name='drug_surfactant', index=28, status=TrialStatus.COMPLETED, arm=Arm(name='28_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 34, 'surf_2_conc': 20, 'drug_conc': 25.0, 'surf_1': 's2', 'surf_2': 's7'})),
 29: Trial(experiment_name='drug_surfactant', index=29, status=TrialStatus.COMPLETED, arm=Arm(name='29_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 16, 'surf_2_conc': 83, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's2'})),
 30: Trial(experiment_name='drug_surfactant', index=30, status=TrialStatus.COMPLETED, arm=Arm(name='30_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 72, 'surf_2_conc': 15, 'drug_conc': 25.0, 'surf_1': 's8', 'surf_2': 's2'})),
 31: Trial(experiment_name='drug_surfactant', index=31, status=TrialStatus.COMPLETED, arm=Arm(name='31_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 14, 'surf_2_conc': 53, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's1'})),
 32: Trial(experiment_name='drug_surfactant', index=32, status=TrialStatus.RUNNING, arm=Arm(name='32_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 8, 'surf_2_conc': 10, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's4'})),
 33: Trial(experiment_name='drug_surfactant', index=33, status=TrialStatus.RUNNING, arm=Arm(name='33_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 5, 'surf_2_conc': 9, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's4'})),
 34: Trial(experiment_name='drug_surfactant', index=34, status=TrialStatus.RUNNING, arm=Arm(name='34_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 6, 'surf_2_conc': 11, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's4'})),
 35: Trial(experiment_name='drug_surfactant', index=35, status=TrialStatus.RUNNING, arm=Arm(name='35_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 6, 'surf_2_conc': 8, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's4'})),
 36: Trial(experiment_name='drug_surfactant', index=36, status=TrialStatus.RUNNING, arm=Arm(name='36_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 7, 'surf_2_conc': 8, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's4'})),
 37: Trial(experiment_name='drug_surfactant', index=37, status=TrialStatus.RUNNING, arm=Arm(name='37_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 6, 'surf_2_conc': 10, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's4'})),
 38: Trial(experiment_name='drug_surfactant', index=38, status=TrialStatus.RUNNING, arm=Arm(name='38_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 6, 'surf_2_conc': 9, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's4'})),
 39: Trial(experiment_name='drug_surfactant', index=39, status=TrialStatus.RUNNING, arm=Arm(name='39_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 6, 'surf_2_conc': 10, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's4'}))}

In [5]:
df_design, df_vol = hf.design_to_vol (n)
df_design

,trial_index,drug_name,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,drug_conc,surf_1,surf_2,surf_conc,obj_surf_conc
0,32,IBP,0.2063,0.3073,0.0373,8,10,25.0,s4,s4,18,NaN
1,33,LOV,0.4045,0.4196,0.0728,5,9,25.0,s4,s4,14,NaN
2,34,DCF,0.2962,0.4364,0.0493,6,11,25.0,s4,s4,17,NaN
3,35,GLV,0.3528,0.2810,0.0711,6,8,25.0,s4,s4,14,NaN
4,36,IBP,0.2063,0.3073,0.0373,7,8,25.0,s4,s4,15,NaN
5,37,LOV,0.4045,0.4196,0.0728,6,10,25.0,s4,s4,16,NaN
6,38,DCF,0.2962,0.4364,0.0493,6,9,25.0,s4,s4,15,NaN
7,39,GLV,0.3528,0.2810,0.0711,6,10,25.0,s4,s4,16,NaN

In [6]:
df_vol

,trial_index,drug_name,drug,s1,s2,s3,s4,s5,s6,s7,s8,dmso,water,IBP,LOV,DCF,GLV
0,32,IBP,180.0,0.0,0.0,0.0,216.0,0.0,0.0,0.0,0.0,0.0,984.0,180.0,0.0,0.0,0.0
1,33,LOV,180.0,0.0,0.0,0.0,168.0,0.0,0.0,0.0,0.0,0.0,1032.0,0.0,180.0,0.0,0.0
2,34,DCF,180.0,0.0,0.0,0.0,204.0,0.0,0.0,0.0,0.0,0.0,996.0,0.0,0.0,180.0,0.0
3,35,GLV,180.0,0.0,0.0,0.0,168.0,0.0,0.0,0.0,0.0,0.0,1032.0,0.0,0.0,0.0,180.0
4,36,IBP,180.0,0.0,0.0,0.0,180.0,0.0,0.0,0.0,0.0,0.0,1020.0,180.0,0.0,0.0,0.0
5,37,LOV,180.0,0.0,0.0,0.0,192.0,0.0,0.0,0.0,0.0,0.0,1008.0,0.0,180.0,0.0,0.0
6,38,DCF,180.0,0.0,0.0,0.0,180.0,0.0,0.0,0.0,0.0,0.0,1020.0,0.0,0.0,180.0,0.0
7,39,GLV,180.0,0.0,0.0,0.0,192.0,0.0,0.0,0.0,0.0,0.0,1008.0,0.0,0.0,0.0,180.0

In [9]:
df_vol[['s1', 's2', 's3', 's4', 's5', 's6', 's7', 's8']].sum()

s1       0.0
s2       0.0
s3       0.0
s4    1500.0
s5       0.0
s6       0.0
s7       0.0
s8       0.0
dtype: float64

In [7]:
plate_well = input("Enter the plate well starting well (e.g., F1): ")
deepplate_well = input("Enter the deep plate well starting well (e.g., F1): ")


print("Please confirm the following information:")
print("Wellplate will start at: " + plate_well)
print("Deep plate will start at: " + deepplate_well)

print()
print("*******************************************************")
print("Continue if correct, or rerun this cell if incorrect.")
print("*******************************************************")

Please confirm the following information:
Wellplate will start at: A1
Deep plate will start at: F5

*******************************************************
Continue if correct, or rerun this cell if incorrect.
*******************************************************

In [8]:
hf.generate_protocol(df_vol=df_vol, iteration=n, plate_well=plate_well, deepplate_well=deepplate_well)

✅ Successfully wrote to: protocol/otflex_1.py

In [11]:
df_absorbance = hf.process_absorbance(iteration=n, threshold=0.06)
df_absorbance

   trial_index  success
0            0        0
1            1        0
2            2        0
3            3        0
4            4        0
5            5        0
6            6        0
7            7        0

In [12]:
results = hf.build_results(n, df_absorbance)
results

,trial_index,drug_name,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,drug_conc,surf_1,surf_2,surf_conc,obj_surf_conc,success
0,32,IBP,0.2063,0.3073,0.0373,8,10,25.0,s4,s4,18,100,0
1,33,LOV,0.4045,0.4196,0.0728,5,9,25.0,s4,s4,14,100,0
2,34,DCF,0.2962,0.4364,0.0493,6,11,25.0,s4,s4,17,100,0
3,35,GLV,0.3528,0.2810,0.0711,6,8,25.0,s4,s4,14,100,0
4,36,IBP,0.2063,0.3073,0.0373,7,8,25.0,s4,s4,15,100,0
5,37,LOV,0.4045,0.4196,0.0728,6,10,25.0,s4,s4,16,100,0
6,38,DCF,0.2962,0.4364,0.0493,6,9,25.0,s4,s4,15,100,0
7,39,GLV,0.3528,0.2810,0.0711,6,10,25.0,s4,s4,16,100,0

# load the results to the optimizer

In [13]:
ax_client = hf.load_data_to_optimizer(iteration = n, results = results)
ax_client

[INFO 07-29 10:21:29] ax.service.ax_client: Completed trial 32 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-29 10:21:29] ax.service.ax_client: Completed trial 33 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-29 10:21:29] ax.service.ax_client: Completed trial 34 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-29 10:21:29] ax.service.ax_client: Completed trial 35 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-29 10:21:29] ax.service.ax_client: Completed trial 36 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-29 10:21:29] ax.service.ax_client: Completed trial 37 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-29 10:21:29] ax.service.ax_client: Completed trial 38 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-29 10:21:29] ax.service.ax_client: Completed trial 39 with data: {'obj_surf_conc': (100.0, None)}.

AxClient(experiment=Experiment(drug_surfactant))