# import libraries

In [6]:
import pandas as pd
from ax.service.ax_client import AxClient, ObjectiveProperties
import matplotlib.pyplot as plt
from ax.modelbridge.registry import Models
from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy   
import time


import sys
sys.path.append('../')
import helper_functions as hf

# generate recommendations

In [7]:
n = hf.get_iteration_number()

for i in range(3):
    print("Very Important: Please Confirm the Iteration Number is Iteration " + str(n))

print()

list_of_drugs = (['IBP']  + ['LOV']  + ['DCF']  + ['GLV']) * 1

for i in range(3):
    print("Very Important: Please Confirm the Drugs are: ", list_of_drugs)

Very Important: Please Confirm the Iteration Number is Iteration 17
Very Important: Please Confirm the Iteration Number is Iteration 17
Very Important: Please Confirm the Iteration Number is Iteration 17

Very Important: Please Confirm the Drugs are:  ['IBP', 'LOV', 'DCF', 'GLV']
Very Important: Please Confirm the Drugs are:  ['IBP', 'LOV', 'DCF', 'GLV']
Very Important: Please Confirm the Drugs are:  ['IBP', 'LOV', 'DCF', 'GLV']

In [8]:
time_start = time.time()


df_design, ax_client, data_so_far, best_concs = hf.run_optimizer(current_iteration=n, drug_list= list_of_drugs, bopt = 1)

time_end = time.time()
time_duration = round((time_end - time_start)/60,2)

print("Time taken for optimization: " + str(time_duration) + " mins")
print("Time taken for optimization: " + str(time_duration * 60) + " seconds")

******************************************************************************** 1/4 ********************************************************************************

Update constraints (drug=IBP)：surf_1_conc+surf_2_conc <= 7.0，>=1

[INFO 08-06 13:24:28] ax.service.ax_client: Generated new trial 156 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 7, 'surf_2_conc': 0, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's6'} using model BoTorch.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

******************************************************************************** 2/4 ********************************************************************************

Update constraints (drug=LOV)：surf_1_conc+surf_2_conc <= 9.0，>=1

[INFO 08-06 13:24:32] ax.service.ax_client: Generated new trial 157 with parameters {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 9, 'surf_2_conc': 0, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's4'} using model BoTorch.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

******************************************************************************** 3/4 ********************************************************************************

Update constraints (drug=DCF)：surf_1_conc+surf_2_conc <= 28.0，>=1

[INFO 08-06 13:24:37] ax.service.ax_client: Generated new trial 158 with parameters {'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 14, 'surf_2_conc': 14, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's8'} using model BoTorch.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

******************************************************************************** 4/4 ********************************************************************************

Update constraints (drug=GLV)：surf_1_conc+surf_2_conc <= 57.0，>=1

[INFO 08-06 13:24:42] ax.service.ax_client: Generated new trial 159 with parameters {'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 9, 'surf_2_conc': 48, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's1'} using model BoTorch.

Time taken for optimization: 0.29 mins
Time taken for optimization: 17.4 seconds

# process results

In [9]:
ax_client = hf.load_design_optimizer(n)
ax_client.get_trials_data_frame()

/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

,trial_index,arm_name,trial_status,generation_node,obj_surf_conc,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,drug_conc,surf_1,surf_2
0,0,0_0,COMPLETED,GenerationStep_0,35.0,0.2063,0.3073,0.0373,29,6,25.0,s7,s6
1,1,1_0,COMPLETED,GenerationStep_0,50.0,0.4045,0.4196,0.0728,6,44,25.0,s4,s4
2,2,2_0,COMPLETED,GenerationStep_0,100.0,0.2962,0.4364,0.0493,4,27,25.0,s2,s6
3,3,3_0,COMPLETED,GenerationStep_0,92.0,0.3528,0.2810,0.0711,91,1,25.0,s1,s2
4,4,4_0,COMPLETED,GenerationStep_0,46.0,0.2063,0.3073,0.0373,32,14,25.0,s3,s4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,155,155_0,COMPLETED,GenerationStep_1,59.0,0.3528,0.2810,0.0711,10,49,25.0,s6,s1
156,156,152_0,RUNNING,GenerationStep_1,NaN,0.2063,0.3073,0.0373,7,0,25.0,s7,s6
157,157,157_0,RUNNING,GenerationStep_1,NaN,0.4045,0.4196,0.0728,9,0,25.0,s4,s4
158,158,158_0,RUNNING,GenerationStep_1,NaN,0.2962,0.4364,0.0493,14,14,25.0,s4,s8
159,159,159_0,RUNNING,GenerationStep_1,NaN,0.3528,0.2810,0.0711,9,48,25.0,s6,s1

In [10]:
df_design, df_vol = hf.design_to_vol (n)
df_design['constraint'] = df_design['drug_name'].map(best_concs).fillna(0.0)
df_design

,trial_index,drug_name,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,drug_conc,surf_1,surf_2,surf_conc,obj_surf_conc,constraint
0,156,IBP,0.2063,0.3073,0.0373,7,0,25.0,s7,s6,7,NaN,9.0
1,157,LOV,0.4045,0.4196,0.0728,9,0,25.0,s4,s4,9,NaN,11.0
2,158,DCF,0.2962,0.4364,0.0493,14,14,25.0,s4,s8,28,NaN,30.0
3,159,GLV,0.3528,0.2810,0.0711,9,48,25.0,s6,s1,57,NaN,59.0

In [11]:
df_vol

,trial_index,drug_name,drug,s1,s2,s3,s4,s5,s6,s7,s8,dmso,water,IBP,LOV,DCF,GLV
0,156,IBP,180.0,0.0,0.0,0.0,0.0,0.0,0.0,84.0,0.0,0.0,1116.0,180.0,0.0,0.0,0.0
1,157,LOV,180.0,0.0,0.0,0.0,108.0,0.0,0.0,0.0,0.0,0.0,1092.0,0.0,180.0,0.0,0.0
2,158,DCF,180.0,0.0,0.0,0.0,168.0,0.0,0.0,0.0,168.0,0.0,864.0,0.0,0.0,180.0,0.0
3,159,GLV,180.0,576.0,0.0,0.0,0.0,0.0,108.0,0.0,0.0,0.0,516.0,0.0,0.0,0.0,180.0

In [12]:
print("Please ensure to refill the water vial to 20 mL")
print("Please ensure to refill the water vial to 20 mL")
print("Please ensure to refill the water vial to 20 mL")


df_vol[['s1', 's2', 's3', 's4', 's5', 's6', 's7', 's8', 'water']].sum()

Please ensure to refill the water vial to 20 mL
Please ensure to refill the water vial to 20 mL
Please ensure to refill the water vial to 20 mL

s1        576.0
s2          0.0
s3          0.0
s4        276.0
s5          0.0
s6        108.0
s7         84.0
s8        168.0
water    3588.0
dtype: float64

In [13]:
plate_well = input("Enter the plate well starting well (e.g., F1): ")
deepplate_well = input("Enter the deep plate well starting well (e.g., F1): ")


print("Please confirm the following information:")
print("Wellplate will start at: " + plate_well)
print("Deep plate will start at: " + deepplate_well)

print()
print("*******************************************************")
print("Continue if correct, or rerun this cell if incorrect.")
print("*******************************************************")

Please confirm the following information:
Wellplate will start at: B1
Deep plate will start at: E9

*******************************************************
Continue if correct, or rerun this cell if incorrect.
*******************************************************

In [14]:
hf.generate_protocol(df_vol=df_vol, iteration=n, plate_well=plate_well, deepplate_well=deepplate_well)

✅ Successfully wrote to: protocol/otflex_17.py

In [15]:
df_absorbance = hf.process_absorbance(iteration=n, threshold=0.06)
df_absorbance

   trial_index  success
0            0        0
1            1        0
2            2        0
3            3        1

In [16]:
results = hf.build_results(n, df_absorbance)
results

,trial_index,drug_name,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,drug_conc,surf_1,surf_2,surf_conc,obj_surf_conc,success
0,156,IBP,0.2063,0.3073,0.0373,7,0,25.0,s7,s6,7,100,0
1,157,LOV,0.4045,0.4196,0.0728,9,0,25.0,s4,s4,9,100,0
2,158,DCF,0.2962,0.4364,0.0493,14,14,25.0,s4,s8,28,100,0
3,159,GLV,0.3528,0.2810,0.0711,9,48,25.0,s6,s1,57,57,1

# load the results to the optimizer

In [17]:
ax_client = hf.load_data_to_optimizer(iteration = n, results = results)
ax_client

[INFO 08-06 14:46:03] ax.service.ax_client: Completed trial 156 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 08-06 14:46:03] ax.service.ax_client: Completed trial 157 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 08-06 14:46:03] ax.service.ax_client: Completed trial 158 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 08-06 14:46:03] ax.service.ax_client: Completed trial 159 with data: {'obj_surf_conc': (57.0, None)}.

AxClient(experiment=Experiment(drug_surfactant))