# import libraries

In [1]:
import pandas as pd
from ax.service.ax_client import AxClient, ObjectiveProperties
import matplotlib.pyplot as plt
from ax.modelbridge.registry import Models
from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy   
import time


import sys
sys.path.append('../')
import helper_functions as hf

/var/folders/9p/f66yhymx35939zzlg51g0rrc0000gn/T/ipykernel_47561/3307975217.py:5: DeprecationWarning: Please import from 'ax.generation_strategy.generation_strategy' instead of 'ax.modelbridge.generation_strategy'. The latter is deprecated and will be removed in a future release.
  from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy

# generate recommendations

In [2]:
n = hf.get_iteration_number()

for i in range(3):
    print("Very Important: Please Confirm the Iteration Number is Iteration " + str(n))

print()

list_of_drugs = (['IBP']  + ['LOV']  + ['DCF']  + ['GLV']) * 1

for i in range(3):
    print("Very Important: Please Confirm the Drugs are: ", list_of_drugs)

Very Important: Please Confirm the Iteration Number is Iteration 16
Very Important: Please Confirm the Iteration Number is Iteration 16
Very Important: Please Confirm the Iteration Number is Iteration 16

Very Important: Please Confirm the Drugs are:  ['IBP', 'LOV', 'DCF', 'GLV']
Very Important: Please Confirm the Drugs are:  ['IBP', 'LOV', 'DCF', 'GLV']
Very Important: Please Confirm the Drugs are:  ['IBP', 'LOV', 'DCF', 'GLV']

In [3]:
time_start = time.time()


df_design, ax_client = hf.run_optimizer(current_iteration=n, drug_list= list_of_drugs,  bopt = 2)

time_end = time.time()
time_duration = round((time_end - time_start)/60,2)

print("Time taken for optimization: " + str(time_duration) + " mins")
print("Time taken for optimization: " + str(time_duration * 60) + " seconds")

**************************************************************************************************** 1  out of  4 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Drug name:  Ibuprofen IBP  | Iteration:  16

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[INFO 07-22 12:16:39] ax.service.ax_client: Generated new trial 92 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 13, 'surf_2_conc': 7, 'surf_3_conc': 13, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's6', 'surf_3': 's8'} using model SAASBO.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

**************************************************************************************************** 2  out of  4 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Drug name:  Lovastatin LOV  | Iteration:  16

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[INFO 07-22 12:16:42] ax.service.ax_client: Generated new trial 93 with parameters {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 8, 'surf_2_conc': 0, 'surf_3_conc': 26, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's2', 'surf_3': 's7'} using model SAASBO.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

**************************************************************************************************** 3  out of  4 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Drug name:  Diclofenac DCF  | Iteration:  16

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[INFO 07-22 12:16:44] ax.service.ax_client: Generated new trial 94 with parameters {'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 17, 'surf_2_conc': 29, 'surf_3_conc': 26, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's5'} using model SAASBO.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

**************************************************************************************************** 4  out of  4 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Drug name:  Griseofulvin GLV  | Iteration:  16

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[INFO 07-22 12:16:47] ax.service.ax_client: Generated new trial 95 with parameters {'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 2, 'surf_2_conc': 35, 'surf_3_conc': 26, 'drug_conc': 25.0, 'surf_1': 's5', 'surf_2': 's6', 'surf_3': 's5'} using model SAASBO.

Time taken for optimization: 0.66 mins
Time taken for optimization: 39.6 seconds

# process results

In [4]:
ax_client = hf.load_design_optimizer(n)
ax_client.get_trials_data_frame()

/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

,trial_index,arm_name,trial_status,generation_node,obj_surf_conc,Drug_MW,Drug_LogP,Drug_TPSA,surf_1,surf_1_conc,surf_2,surf_2_conc,surf_3,surf_3_conc,drug_conc
0,0,0_0,COMPLETED,None,100.0,0.2063,0.3073,0.0373,s8,12,s6,39,s7,20,25.0
1,1,1_0,COMPLETED,None,95.0,0.2063,0.3073,0.0373,s3,51,s2,4,s6,40,25.0
2,2,2_0,COMPLETED,None,100.0,0.4045,0.4196,0.0728,s5,1,s7,56,s3,0,25.0
3,3,3_0,COMPLETED,None,100.0,0.4045,0.4196,0.0728,s3,28,s3,6,s8,14,25.0
4,4,4_0,COMPLETED,None,100.0,0.2962,0.4364,0.0493,s1,27,s4,63,s5,3,25.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,91,91_0,COMPLETED,GenerationStep_2,42.0,0.3528,0.2810,0.0711,s6,14,s5,2,s5,26,25.0
92,92,92_0,RUNNING,GenerationStep_2,NaN,0.2063,0.3073,0.0373,s1,13,s6,7,s8,13,25.0
93,93,93_0,RUNNING,GenerationStep_2,NaN,0.4045,0.4196,0.0728,s6,8,s2,0,s7,26,25.0
94,94,94_0,RUNNING,GenerationStep_2,NaN,0.2962,0.4364,0.0493,s6,17,s5,29,s5,26,25.0
95,95,95_0,RUNNING,GenerationStep_2,NaN,0.3528,0.2810,0.0711,s5,2,s6,35,s5,26,25.0

In [5]:
df_design, df_vol = hf.design_to_vol (n)
df_design

,trial_index,drug_name,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,surf_3_conc,drug_conc,surf_1,surf_2,surf_3,surf_conc,obj_surf_conc
0,92,IBP,0.2063,0.3073,0.0373,13,7,13,25.0,s1,s6,s8,33,NaN
1,93,LOV,0.4045,0.4196,0.0728,8,0,26,25.0,s6,s2,s7,34,NaN
2,94,DCF,0.2962,0.4364,0.0493,17,29,26,25.0,s6,s5,s5,72,NaN
3,95,GLV,0.3528,0.2810,0.0711,2,35,26,25.0,s5,s6,s5,63,NaN

In [6]:
df_vol

,trial_index,drug_name,drug,s1,s2,s3,s4,s5,s6,s7,s8,dmso,water,IBP,LOV,DCF,GLV
0,92,IBP,180.0,156.0,0.0,0.0,0.0,0.0,84.0,0.0,156.0,0.0,804.0,180.0,0.0,0.0,0.0
1,93,LOV,180.0,0.0,0.0,0.0,0.0,0.0,96.0,312.0,0.0,0.0,792.0,0.0,180.0,0.0,0.0
2,94,DCF,180.0,0.0,0.0,0.0,0.0,660.0,204.0,0.0,0.0,0.0,336.0,0.0,0.0,180.0,0.0
3,95,GLV,180.0,0.0,0.0,0.0,0.0,336.0,420.0,0.0,0.0,0.0,444.0,0.0,0.0,0.0,180.0

In [7]:
df_vol[['s1', 's2', 's3', 's4', 's5', 's6', 's7', 's8']].sum()

s1    156.0
s2      0.0
s3      0.0
s4      0.0
s5    996.0
s6    804.0
s7    312.0
s8    156.0
dtype: float64

In [9]:
plate_well = input("Enter the plate well starting well (e.g., F1): ")
deepplate_well = input("Enter the deep plate well starting well (e.g., F1): ")


print("Please confirm the following information:")
print("Wellplate will start at: " + plate_well)
print("Deep plate will start at: " + deepplate_well)

print()
print("*******************************************************")
print("Continue if correct, or rerun this cell if incorrect.")
print("*******************************************************")

Please confirm the following information:
Wellplate will start at: F1
Deep plate will start at: C9

*******************************************************
Continue if correct, or rerun this cell if incorrect.
*******************************************************

In [10]:
hf.generate_protocol(df_vol=df_vol, iteration=n, plate_well=plate_well, deepplate_well=deepplate_well)

✅ Successfully wrote to: protocol/otflex_16.py

In [11]:
df_absorbance = hf.process_absorbance(iteration=n, threshold=0.06)
df_absorbance

   trial_index  success
0            0        0
1            1        0
2            2        0
3            3        1

In [12]:
results = hf.build_results(n, df_absorbance)
results

,trial_index,drug_name,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,surf_3_conc,drug_conc,surf_1,surf_2,surf_3,surf_conc,obj_surf_conc,success
0,92,IBP,0.2063,0.3073,0.0373,13,7,13,25.0,s1,s6,s8,33,100,0
1,93,LOV,0.4045,0.4196,0.0728,8,0,26,25.0,s6,s2,s7,34,100,0
2,94,DCF,0.2962,0.4364,0.0493,17,29,26,25.0,s6,s5,s5,72,100,0
3,95,GLV,0.3528,0.2810,0.0711,2,35,26,25.0,s5,s6,s5,63,63,1

# load the results to the optimizer

In [13]:
ax_client = hf.load_data_to_optimizer(iteration = n, results = results)
ax_client

[INFO 07-22 13:58:58] ax.service.ax_client: Completed trial 92 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-22 13:58:58] ax.service.ax_client: Completed trial 93 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-22 13:58:58] ax.service.ax_client: Completed trial 94 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-22 13:58:58] ax.service.ax_client: Completed trial 95 with data: {'obj_surf_conc': (63.0, None)}.

AxClient(experiment=Experiment(drug_surfactant))