# import libraries

In [1]:
import pandas as pd
from ax.service.ax_client import AxClient, ObjectiveProperties
import matplotlib.pyplot as plt
from ax.modelbridge.registry import Models
from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy   
import time


import sys
sys.path.append('../')
import helper_functions as hf

/var/folders/9p/f66yhymx35939zzlg51g0rrc0000gn/T/ipykernel_26027/3307975217.py:5: DeprecationWarning: Please import from 'ax.generation_strategy.generation_strategy' instead of 'ax.modelbridge.generation_strategy'. The latter is deprecated and will be removed in a future release.
  from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy

# generate recommendations

In [2]:
n = hf.get_iteration_number()

for i in range(3):
    print("Very Important: Please Confirm the Iteration Number is Iteration " + str(n))

print()

list_of_drugs = ['IBP'] * 2 + ['LOV'] * 2 + ['DCF'] * 2 + ['GLV'] * 2

for i in range(3):
    print("Very Important: Please Confirm the Drugs are: ", list_of_drugs)

Very Important: Please Confirm the Iteration Number is Iteration 2
Very Important: Please Confirm the Iteration Number is Iteration 2
Very Important: Please Confirm the Iteration Number is Iteration 2

Very Important: Please Confirm the Drugs are:  ['IBP', 'IBP', 'LOV', 'LOV', 'DCF', 'DCF', 'GLV', 'GLV']
Very Important: Please Confirm the Drugs are:  ['IBP', 'IBP', 'LOV', 'LOV', 'DCF', 'DCF', 'GLV', 'GLV']
Very Important: Please Confirm the Drugs are:  ['IBP', 'IBP', 'LOV', 'LOV', 'DCF', 'DCF', 'GLV', 'GLV']

In [3]:
time_start = time.time()


df_design, ax_client = hf.run_optimizer(current_iteration=n, drug_list= list_of_drugs,  bopt = 1)

time_end = time.time()
time_duration = round((time_end - time_start)/60,2)

print("Time taken for optimization: " + str(time_duration) + " mins")
print("Time taken for optimization: " + str(time_duration * 60) + " seconds")

[WARNING 07-11 13:17:40] ax.modelbridge.transforms.standardize_y: Outcome surfactant_input is constant, within tolerance.

**************************************************************************************************** 1  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Ibuprofen IBP  | Iteration:  2

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/botorch/models/utils/assorted.py:273: InputDataWarning: Data (outcome observations) is not standardized (std = tensor([1., 1., 0.], dtype=torch.float64), mean = tensor([-2.7756e-17,  2.7756e-17,  0.0000e+00], dtype=torch.float64)).Please consider scaling the input to zero mean and unit variance.
  check_standardization(Y=train_Y, raise_on_fail=raise_on_fail)
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:486: RuntimeWarning: divide by zero encountered in scalar divide
  inv_model_std_quality = max_std if max_std > 1 / min_std else min_std
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:489: RuntimeWarning: divide by zero encountered in scalar divide
  return 1 / inv_model_std_quality
[INFO 07-11 13:17:44] ax.service.ax_client: Generated new trial 16 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 0, 's2': 100, 's3': 100, 's4': 0, 's5': 0, 's6': 0, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100} using model BO_MIXED.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
[WARNING 07-11 13:17:44] ax.modelbridge.transforms.standardize_y: Outcome surfactant_input is constant, within tolerance.

**************************************************************************************************** 2  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Ibuprofen IBP  | Iteration:  2

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:486: RuntimeWarning: divide by zero encountered in scalar divide
  inv_model_std_quality = max_std if max_std > 1 / min_std else min_std
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:489: RuntimeWarning: divide by zero encountered in scalar divide
  return 1 / inv_model_std_quality
[INFO 07-11 13:17:45] ax.service.ax_client: Generated new trial 17 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 0, 's2': 100, 's3': 0, 's4': 0, 's5': 0, 's6': 100, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100} using model BO_MIXED.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
[WARNING 07-11 13:17:45] ax.modelbridge.transforms.standardize_y: Outcome surfactant_input is constant, within tolerance.

**************************************************************************************************** 3  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Lovastatin LOV  | Iteration:  2

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:486: RuntimeWarning: divide by zero encountered in scalar divide
  inv_model_std_quality = max_std if max_std > 1 / min_std else min_std
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:489: RuntimeWarning: divide by zero encountered in scalar divide
  return 1 / inv_model_std_quality
[INFO 07-11 13:17:47] ax.service.ax_client: Generated new trial 18 with parameters {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 's1': 0, 's2': 100, 's3': 100, 's4': 0, 's5': 0, 's6': 0, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100} using model BO_MIXED.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
[WARNING 07-11 13:17:47] ax.modelbridge.transforms.standardize_y: Outcome surfactant_input is constant, within tolerance.

**************************************************************************************************** 4  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Lovastatin LOV  | Iteration:  2

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:486: RuntimeWarning: divide by zero encountered in scalar divide
  inv_model_std_quality = max_std if max_std > 1 / min_std else min_std
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:489: RuntimeWarning: divide by zero encountered in scalar divide
  return 1 / inv_model_std_quality
[INFO 07-11 13:17:48] ax.service.ax_client: Generated new trial 19 with parameters {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 's1': 0, 's2': 100, 's3': 0, 's4': 3, 's5': 0, 's6': 100, 's7': 100, 's8': 0, 'surfactant_conc': 100, 'drug_conc': 100} using model BO_MIXED.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
[WARNING 07-11 13:17:48] ax.modelbridge.transforms.standardize_y: Outcome surfactant_input is constant, within tolerance.

**************************************************************************************************** 5  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Diclofenac DCF  | Iteration:  2

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:486: RuntimeWarning: divide by zero encountered in scalar divide
  inv_model_std_quality = max_std if max_std > 1 / min_std else min_std
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:489: RuntimeWarning: divide by zero encountered in scalar divide
  return 1 / inv_model_std_quality
[INFO 07-11 13:17:50] ax.service.ax_client: Generated new trial 20 with parameters {'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 's1': 0, 's2': 100, 's3': 100, 's4': 0, 's5': 0, 's6': 0, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100} using model BO_MIXED.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
[WARNING 07-11 13:17:50] ax.modelbridge.transforms.standardize_y: Outcome surfactant_input is constant, within tolerance.

**************************************************************************************************** 6  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Diclofenac DCF  | Iteration:  2

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:486: RuntimeWarning: divide by zero encountered in scalar divide
  inv_model_std_quality = max_std if max_std > 1 / min_std else min_std
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:489: RuntimeWarning: divide by zero encountered in scalar divide
  return 1 / inv_model_std_quality
[INFO 07-11 13:17:51] ax.service.ax_client: Generated new trial 21 with parameters {'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 's1': 0, 's2': 100, 's3': 0, 's4': 3, 's5': 0, 's6': 100, 's7': 100, 's8': 0, 'surfactant_conc': 100, 'drug_conc': 100} using model BO_MIXED.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
[WARNING 07-11 13:17:51] ax.modelbridge.transforms.standardize_y: Outcome surfactant_input is constant, within tolerance.

**************************************************************************************************** 7  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Griseofulvin GLV  | Iteration:  2

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:486: RuntimeWarning: divide by zero encountered in scalar divide
  inv_model_std_quality = max_std if max_std > 1 / min_std else min_std
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:489: RuntimeWarning: divide by zero encountered in scalar divide
  return 1 / inv_model_std_quality
[INFO 07-11 13:17:53] ax.service.ax_client: Generated new trial 22 with parameters {'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 's1': 0, 's2': 100, 's3': 100, 's4': 0, 's5': 0, 's6': 0, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100} using model BO_MIXED.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
[WARNING 07-11 13:17:53] ax.modelbridge.transforms.standardize_y: Outcome surfactant_input is constant, within tolerance.

**************************************************************************************************** 8  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Griseofulvin GLV  | Iteration:  2

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:486: RuntimeWarning: divide by zero encountered in scalar divide
  inv_model_std_quality = max_std if max_std > 1 / min_std else min_std
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:489: RuntimeWarning: divide by zero encountered in scalar divide
  return 1 / inv_model_std_quality
[INFO 07-11 13:17:55] ax.service.ax_client: Generated new trial 23 with parameters {'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 's1': 0, 's2': 100, 's3': 0, 's4': 13, 's5': 0, 's6': 100, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100} using model BO_MIXED.

Time taken for optimization: 0.25 mins
Time taken for optimization: 15.0 seconds

# process results

In [4]:
ax_client = hf.load_design_optimizer(n)
ax_client.experiment.trials

{0: Trial(experiment_name='drug_surfactant', index=0, status=TrialStatus.COMPLETED, arm=Arm(name='0_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 48, 's2': 60, 's3': 49, 's4': 31, 's5': 96, 's6': 8, 's7': 9, 's8': 35, 'surfactant_conc': 86, 'drug_conc': 100})),
 1: Trial(experiment_name='drug_surfactant', index=1, status=TrialStatus.COMPLETED, arm=Arm(name='1_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 74, 's2': 0, 's3': 88, 's4': 66, 's5': 22, 's6': 52, 's7': 58, 's8': 79, 'surfactant_conc': 35, 'drug_conc': 100})),
 2: Trial(experiment_name='drug_surfactant', index=2, status=TrialStatus.COMPLETED, arm=Arm(name='2_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 's1': 78, 's2': 88, 's3': 1, 's4': 3, 's5': 32, 's6': 94, 's7': 44, 's8': 58, 'surfactant_conc': 1, 'drug_conc': 100})),
 3: Trial(experiment_name='drug_surfactant', index=3, status=TrialStatus.COMPLETED, arm=Arm(name='3_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 's1': 0, 's2': 46, 's3': 61, 's4': 94, 's5': 63, 's6': 49, 's7': 98, 's8': 0, 'surfactant_conc': 52, 'drug_conc': 100})),
 4: Trial(experiment_name='drug_surfactant', index=4, status=TrialStatus.COMPLETED, arm=Arm(name='4_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 's1': 16, 's2': 82, 's3': 85, 's4': 84, 's5': 71, 's6': 23, 's7': 35, 's8': 65, 'surfactant_conc': 21, 'drug_conc': 100})),
 5: Trial(experiment_name='drug_surfactant', index=5, status=TrialStatus.COMPLETED, arm=Arm(name='5_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 's1': 93, 's2': 27, 's3': 27, 's4': 17, 's5': 47, 's6': 67, 's7': 83, 's8': 22, 'surfactant_conc': 71, 'drug_conc': 100})),
 6: Trial(experiment_name='drug_surfactant', index=6, status=TrialStatus.COMPLETED, arm=Arm(name='6_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 's1': 59, 's2': 65, 's3': 62, 's4': 55, 's5': 7, 's6': 76, 's7': 19, 's8': 43, 'surfactant_conc': 94, 'drug_conc': 100})),
 7: Trial(experiment_name='drug_surfactant', index=7, status=TrialStatus.COMPLETED, arm=Arm(name='7_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 's1': 31, 's2': 19, 's3': 25, 's4': 46, 's5': 87, 's6': 32, 's7': 74, 's8': 99, 'surfactant_conc': 44, 'drug_conc': 100})),
 8: Trial(experiment_name='drug_surfactant', index=8, status=TrialStatus.COMPLETED, arm=Arm(name='8_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 0, 's2': 100, 's3': 100, 's4': 0, 's5': 100, 's6': 100, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 9: Trial(experiment_name='drug_surfactant', index=9, status=TrialStatus.COMPLETED, arm=Arm(name='9_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 0, 's2': 100, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 10: Trial(experiment_name='drug_surfactant', index=10, status=TrialStatus.COMPLETED, arm=Arm(name='10_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 's1': 100, 's2': 0, 's3': 0, 's4': 100, 's5': 0, 's6': 0, 's7': 0, 's8': 0, 'surfactant_conc': 1, 'drug_conc': 100})),
 11: Trial(experiment_name='drug_surfactant', index=11, status=TrialStatus.COMPLETED, arm=Arm(name='11_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 's1': 0, 's2': 0, 's3': 100, 's4': 0, 's5': 100, 's6': 100, 's7': 0, 's8': 0, 'surfactant_conc': 1, 'drug_conc': 100})),
 12: Trial(experiment_name='drug_surfactant', index=12, status=TrialStatus.COMPLETED, arm=Arm(name='12_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 's1': 100, 's2': 100, 's3': 0, 's4': 100, 's5': 0, 's6': 0, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 13: Trial(experiment_name='drug_surfactant', index=13, status=TrialStatus.COMPLETED, arm=Arm(name='13_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 's1': 0, 's2': 0, 's3': 100, 's4': 0, 's5': 100, 's6': 100, 's7': 0, 's8': 0, 'surfactant_conc': 1, 'drug_conc': 100})),
 14: Trial(experiment_name='drug_surfactant', index=14, status=TrialStatus.COMPLETED, arm=Arm(name='14_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 's1': 100, 's2': 100, 's3': 0, 's4': 100, 's5': 0, 's6': 0, 's7': 100, 's8': 0, 'surfactant_conc': 1, 'drug_conc': 100})),
 15: Trial(experiment_name='drug_surfactant', index=15, status=TrialStatus.COMPLETED, arm=Arm(name='15_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 's1': 0, 's2': 0, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 4, 's8': 0, 'surfactant_conc': 1, 'drug_conc': 100})),
 16: Trial(experiment_name='drug_surfactant', index=16, status=TrialStatus.RUNNING, arm=Arm(name='16_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 0, 's2': 100, 's3': 100, 's4': 0, 's5': 0, 's6': 0, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 17: Trial(experiment_name='drug_surfactant', index=17, status=TrialStatus.RUNNING, arm=Arm(name='17_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 0, 's2': 100, 's3': 0, 's4': 0, 's5': 0, 's6': 100, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 18: Trial(experiment_name='drug_surfactant', index=18, status=TrialStatus.RUNNING, arm=Arm(name='18_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 's1': 0, 's2': 100, 's3': 100, 's4': 0, 's5': 0, 's6': 0, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 19: Trial(experiment_name='drug_surfactant', index=19, status=TrialStatus.RUNNING, arm=Arm(name='19_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 's1': 0, 's2': 100, 's3': 0, 's4': 3, 's5': 0, 's6': 100, 's7': 100, 's8': 0, 'surfactant_conc': 100, 'drug_conc': 100})),
 20: Trial(experiment_name='drug_surfactant', index=20, status=TrialStatus.RUNNING, arm=Arm(name='20_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 's1': 0, 's2': 100, 's3': 100, 's4': 0, 's5': 0, 's6': 0, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 21: Trial(experiment_name='drug_surfactant', index=21, status=TrialStatus.RUNNING, arm=Arm(name='21_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 's1': 0, 's2': 100, 's3': 0, 's4': 3, 's5': 0, 's6': 100, 's7': 100, 's8': 0, 'surfactant_conc': 100, 'drug_conc': 100})),
 22: Trial(experiment_name='drug_surfactant', index=22, status=TrialStatus.RUNNING, arm=Arm(name='22_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 's1': 0, 's2': 100, 's3': 100, 's4': 0, 's5': 0, 's6': 0, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 23: Trial(experiment_name='drug_surfactant', index=23, status=TrialStatus.RUNNING, arm=Arm(name='23_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 's1': 0, 's2': 100, 's3': 0, 's4': 13, 's5': 0, 's6': 100, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100}))}

In [5]:
df_conc, df_vol = hf.design_to_conc_to_vol (n)

In [6]:
plate_well = input("Enter the plate well starting well (e.g., F1): ")
deepplate_well = input("Enter the deep plate well starting well (e.g., F1): ")


print("Please confirm the following information:")
print("Wellplate will start at: " + plate_well)
print("Deep plate will start at: " + deepplate_well)

print()
print("*******************************************************")
print("Continue if correct, or rerun this cell if incorrect.")
print("*******************************************************")

Please confirm the following information:
Wellplate will start at: A1
Deep plate will start at: B5

*******************************************************
Continue if correct, or rerun this cell if incorrect.
*******************************************************

In [7]:
hf.generate_protocol(df_vol=df_vol, iteration=n, plate_well=plate_well, deepplate_well=deepplate_well)

✅ Successfully wrote to: protocol/otflex_2.py

In [10]:
df_absorbance = hf.process_absorbance(iteration=n, threshold=0.06)
df_absorbance

   trial_index  success
0            0        1
1            1        1
2            2        1
3            3        1
4            4        1
5            5        1
6            6        0
7            7        0

In [11]:
results = hf.build_results(n, df_conc, df_absorbance)
results

,trial_index,drug_name,s1,s2,s3,s4,s5,s6,s7,s8,surfactant_input,drug_conc,success,complexity
0,16,IBP,0,100,100,0,0,0,100,100,50.0,25.0,1,4
1,17,IBP,0,100,0,0,0,100,100,100,50.0,25.0,1,4
2,18,LOV,0,100,100,0,0,0,100,100,50.0,25.0,1,4
3,19,LOV,0,100,0,3,0,100,100,0,50.0,25.0,1,4
4,20,DCF,0,100,100,0,0,0,100,100,50.0,25.0,1,4
5,21,DCF,0,100,0,3,0,100,100,0,50.0,25.0,1,4
6,22,GLV,0,100,100,0,0,0,100,100,50.0,25.0,0,4
7,23,GLV,0,100,0,13,0,100,100,100,50.0,25.0,0,5

In [12]:
norm_results = hf.normalize_data(results, 'normalize')

In [13]:
norm_results

,trial_index,drug_name,s1,s2,s3,s4,s5,s6,s7,s8,surfactant_input,drug_conc,success,complexity
0,16,IBP,0,100,100,0,0,0,100,100,1.0,1.0,1.0,0.500
1,17,IBP,0,100,0,0,0,100,100,100,1.0,1.0,1.0,0.500
2,18,LOV,0,100,100,0,0,0,100,100,1.0,1.0,1.0,0.500
3,19,LOV,0,100,0,3,0,100,100,0,1.0,1.0,1.0,0.500
4,20,DCF,0,100,100,0,0,0,100,100,1.0,1.0,1.0,0.500
5,21,DCF,0,100,0,3,0,100,100,0,1.0,1.0,1.0,0.500
6,22,GLV,0,100,100,0,0,0,100,100,1.0,1.0,0.0,0.500
7,23,GLV,0,100,0,13,0,100,100,100,1.0,1.0,0.0,0.625

# load the results to the optimizer

In [14]:
ax_client = hf.load_data_to_optimizer(iteration = n, norm_results = norm_results)
ax_client

[INFO 07-11 15:50:40] ax.service.ax_client: Completed trial 16 with data: {'success': (1.0, None), 'surfactant_input': (1.0, None), 'complexity': (0.5, None)}.
[INFO 07-11 15:50:40] ax.service.ax_client: Completed trial 17 with data: {'success': (1.0, None), 'surfactant_input': (1.0, None), 'complexity': (0.5, None)}.
[INFO 07-11 15:50:40] ax.service.ax_client: Completed trial 18 with data: {'success': (1.0, None), 'surfactant_input': (1.0, None), 'complexity': (0.5, None)}.
[INFO 07-11 15:50:40] ax.service.ax_client: Completed trial 19 with data: {'success': (1.0, None), 'surfactant_input': (1.0, None), 'complexity': (0.5, None)}.
[INFO 07-11 15:50:40] ax.service.ax_client: Completed trial 20 with data: {'success': (1.0, None), 'surfactant_input': (1.0, None), 'complexity': (0.5, None)}.
[INFO 07-11 15:50:40] ax.service.ax_client: Completed trial 21 with data: {'success': (1.0, None), 'surfactant_input': (1.0, None), 'complexity': (0.5, None)}.
[INFO 07-11 15:50:40] ax.service.ax_client: Completed trial 22 with data: {'success': (0.0, None), 'surfactant_input': (1.0, None), 'complexity': (1.0, None)}.
[INFO 07-11 15:50:40] ax.service.ax_client: Completed trial 23 with data: {'success': (0.0, None), 'surfactant_input': (1.0, None), 'complexity': (1.0, None)}.

Trial 16: success=1 → using surfactant_input=1.0, complexity=0.5
Trial 17: success=1 → using surfactant_input=1.0, complexity=0.5
Trial 18: success=1 → using surfactant_input=1.0, complexity=0.5
Trial 19: success=1 → using surfactant_input=1.0, complexity=0.5
Trial 20: success=1 → using surfactant_input=1.0, complexity=0.5
Trial 21: success=1 → using surfactant_input=1.0, complexity=0.5
Trial 22: success=0 → overriding surfactant_input & complexity to 1
Trial 23: success=0 → overriding surfactant_input & complexity to 1

AxClient(experiment=Experiment(drug_surfactant))