# import libraries

In [1]:
import pandas as pd
from ax.service.ax_client import AxClient, ObjectiveProperties
import matplotlib.pyplot as plt
from ax.modelbridge.registry import Models
from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy   
import time


import sys
sys.path.append('../')
import helper_functions as hf

/var/folders/9p/f66yhymx35939zzlg51g0rrc0000gn/T/ipykernel_54606/3307975217.py:5: DeprecationWarning: Please import from 'ax.generation_strategy.generation_strategy' instead of 'ax.modelbridge.generation_strategy'. The latter is deprecated and will be removed in a future release.
  from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy

# generate recommendations

In [2]:
n = hf.get_iteration_number()

for i in range(3):
    print("Very Important: Please Confirm the Iteration Number is Iteration " + str(n))

print()

list_of_drugs = (['IBP'])*4#  + ['LOV']  + ['DCF']  + ['GLV']) * 2

for i in range(3):
    print("Very Important: Please Confirm the Drugs are: ", list_of_drugs)

Very Important: Please Confirm the Iteration Number is Iteration 5
Very Important: Please Confirm the Iteration Number is Iteration 5
Very Important: Please Confirm the Iteration Number is Iteration 5

Very Important: Please Confirm the Drugs are:  ['IBP', 'IBP', 'IBP', 'IBP']
Very Important: Please Confirm the Drugs are:  ['IBP', 'IBP', 'IBP', 'IBP']
Very Important: Please Confirm the Drugs are:  ['IBP', 'IBP', 'IBP', 'IBP']

In [3]:
time_start = time.time()


df_design = hf.run_optimizer(current_iteration=n, drug_list= list_of_drugs,  bopt = 1)

time_end = time.time()
time_duration = round((time_end - time_start)/60,2)

print("Time taken for optimization: " + str(time_duration) + " mins")
print("Time taken for optimization: " + str(time_duration * 60) + " seconds")

******************************************************************************** 1/4 ********************************************************************************

Update constraints (drug=IBP)：surf_1_conc+surf_2_conc <= 11，>=1

[INFO 12-08 15:44:46] ax.service.ax_client: Generated new trial 24 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 0, 'surf_2_conc': 11, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's6'} using model BoTorch.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

******************************************************************************** 2/4 ********************************************************************************

Update constraints (drug=IBP)：surf_1_conc+surf_2_conc <= 11，>=1

[INFO 12-08 15:44:50] ax.service.ax_client: Generated new trial 25 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 0, 'surf_2_conc': 11, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's6'} using model BoTorch.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

******************************************************************************** 3/4 ********************************************************************************

Update constraints (drug=IBP)：surf_1_conc+surf_2_conc <= 11，>=1

[INFO 12-08 15:44:53] ax.service.ax_client: Generated new trial 26 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 0, 'surf_2_conc': 11, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's6'} using model BoTorch.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

******************************************************************************** 4/4 ********************************************************************************

Update constraints (drug=IBP)：surf_1_conc+surf_2_conc <= 11，>=1

[INFO 12-08 15:44:56] ax.service.ax_client: Generated new trial 27 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 0, 'surf_2_conc': 11, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's6'} using model BoTorch.

Time taken for optimization: 0.22 mins
Time taken for optimization: 13.2 seconds

# process results

In [4]:
ax_client = hf.load_design_optimizer(n)
ax_client.get_trials_data_frame()

/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

,trial_index,arm_name,trial_status,generation_node,obj_surf_conc,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,drug_conc,surf_1,surf_2
0,0,0_0,COMPLETED,GenerationStep_0,35.0,0.2063,0.3073,0.0373,29,6,25.0,s7,s6
1,1,1_0,COMPLETED,GenerationStep_0,50.0,0.2063,0.3073,0.0373,6,44,25.0,s4,s4
2,2,2_0,COMPLETED,GenerationStep_0,31.0,0.2063,0.3073,0.0373,4,27,25.0,s2,s6
3,3,3_0,COMPLETED,GenerationStep_0,92.0,0.2063,0.3073,0.0373,91,1,25.0,s1,s2
4,4,4_0,COMPLETED,GenerationStep_0,46.0,0.2063,0.3073,0.0373,32,14,25.0,s3,s4
5,5,5_0,COMPLETED,GenerationStep_0,94.0,0.2063,0.3073,0.0373,18,76,25.0,s8,s1
6,6,6_0,COMPLETED,GenerationStep_0,62.0,0.2063,0.3073,0.0373,59,3,25.0,s8,s2
7,7,7_0,COMPLETED,GenerationStep_0,68.0,0.2063,0.3073,0.0373,2,66,25.0,s3,s6
8,8,8_0,COMPLETED,GenerationStep_1,21.0,0.2063,0.3073,0.0373,7,14,25.0,s2,s6
9,9,9_0,COMPLETED,GenerationStep_1,23.0,0.2063,0.3073,0.0373,8,15,25.0,s2,s6
10,10,10_0,COMPLETED,GenerationStep_1,22.0,0.2063,0.3073,0.0373,6,16,25.0,s2,s6
11,11,11_0,COMPLETED,GenerationStep_1,23.0,0.2063,0.3073,0.0373,9,14,25.0,s2,s6
12,12,12_0,COMPLETED,GenerationStep_1,100.0,0.2063,0.3073,0.0373,0,1,25.0,s2,s6
13,13,12_0,COMPLETED,GenerationStep_1,100.0,0.2063,0.3073,0.0373,0,1,25.0,s2,s6
14,14,14_0,COMPLETED,GenerationStep_1,100.0,0.2063,0.3073,0.0373,1,0,25.0,s2,s6
15,15,12_0,COMPLETED,GenerationStep_1,100.0,0.2063,0.3073,0.0373,0,1,25.0,s2,s6
16,16,16_0,COMPLETED,GenerationStep_1,15.0,0.2063,0.3073,0.0373,0,15,25.0,s2,s6
17,17,16_0,COMPLETED,GenerationStep_1,15.0,0.2063,0.3073,0.0373,0,15,25.0,s2,s6
18,18,16_0,COMPLETED,GenerationStep_1,15.0,0.2063,0.3073,0.0373,0,15,25.0,s2,s6
19,19,16_0,COMPLETED,GenerationStep_1,15.0,0.2063,0.3073,0.0373,0,15,25.0,s2,s6
20,20,20_0,COMPLETED,GenerationStep_1,13.0,0.2063,0.3073,0.0373,0,13,25.0,s2,s6
21,21,20_0,COMPLETED,GenerationStep_1,13.0,0.2063,0.3073,0.0373,0,13,25.0,s2,s6
22,22,20_0,COMPLETED,GenerationStep_1,100.0,0.2063,0.3073,0.0373,0,13,25.0,s2,s6
23,23,20_0,COMPLETED,GenerationStep_1,13.0,0.2063,0.3073,0.0373,0,13,25.0,s2,s6
24,24,24_0,RUNNING,GenerationStep_1,NaN,0.2063,0.3073,0.0373,0,11,25.0,s7,s6
25,25,24_0,RUNNING,GenerationStep_1,NaN,0.2063,0.3073,0.0373,0,11,25.0,s7,s6
26,26,24_0,RUNNING,GenerationStep_1,NaN,0.2063,0.3073,0.0373,0,11,25.0,s7,s6
27,27,24_0,RUNNING,GenerationStep_1,NaN,0.2063,0.3073,0.0373,0,11,25.0,s7,s6

In [5]:
df_design, df_vol = hf.design_to_vol (n)
df_design

,trial_index,drug_name,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,drug_conc,surf_1,surf_2,surf_conc,obj_surf_conc
0,24,IBP,0.2063,0.3073,0.0373,0,11,25.0,s7,s6,11,NaN
1,25,IBP,0.2063,0.3073,0.0373,0,11,25.0,s7,s6,11,NaN
2,26,IBP,0.2063,0.3073,0.0373,0,11,25.0,s7,s6,11,NaN
3,27,IBP,0.2063,0.3073,0.0373,0,11,25.0,s7,s6,11,NaN

In [6]:
df_vol

,trial_index,drug_name,drug,s1,s2,s3,s4,s5,s6,s7,s8,dmso,water,IBP
0,24,IBP,180.0,0.0,0.0,0.0,0.0,0.0,132.0,0.0,0.0,0.0,1068.0,180.0
1,25,IBP,180.0,0.0,0.0,0.0,0.0,0.0,132.0,0.0,0.0,0.0,1068.0,180.0
2,26,IBP,180.0,0.0,0.0,0.0,0.0,0.0,132.0,0.0,0.0,0.0,1068.0,180.0
3,27,IBP,180.0,0.0,0.0,0.0,0.0,0.0,132.0,0.0,0.0,0.0,1068.0,180.0

In [7]:
df_vol[['s1', 's2', 's3', 's4', 's5', 's6', 's7', 's8']].sum()

s1      0.0
s2      0.0
s3      0.0
s4      0.0
s5      0.0
s6    528.0
s7      0.0
s8      0.0
dtype: float64

In [8]:
plate_well = input("Enter the plate well starting well (e.g., F1): ")
deepplate_well = input("Enter the deep plate well starting well (e.g., F1): ")


print("Please confirm the following information:")
print("Wellplate will start at: " + plate_well)
print("Deep plate will start at: " + deepplate_well)

print()
print("*******************************************************")
print("Continue if correct, or rerun this cell if incorrect.")
print("*******************************************************")

Please confirm the following information:
Wellplate will start at: G1
Deep plate will start at: G1

*******************************************************
Continue if correct, or rerun this cell if incorrect.
*******************************************************

In [9]:
hf.generate_protocol(df_vol=df_vol, iteration=n, plate_well=plate_well, deepplate_well=deepplate_well)

✅ Successfully wrote to: protocol/otflex_5.py

In [10]:
df_absorbance = hf.process_absorbance(iteration=n, threshold=0.06)
df_absorbance

   trial_index  success
0            0        1
1            1        1
2            2        0
3            3        1

In [11]:
results = hf.build_results(n, df_absorbance)
results

,trial_index,drug_name,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,drug_conc,surf_1,surf_2,surf_conc,obj_surf_conc,success
0,24,IBP,0.2063,0.3073,0.0373,0,11,25.0,s7,s6,11,11,1
1,25,IBP,0.2063,0.3073,0.0373,0,11,25.0,s7,s6,11,11,1
2,26,IBP,0.2063,0.3073,0.0373,0,11,25.0,s7,s6,11,100,0
3,27,IBP,0.2063,0.3073,0.0373,0,11,25.0,s7,s6,11,11,1

# load the results to the optimizer

In [12]:
ax_client = hf.load_data_to_optimizer(iteration = n, results = results)
ax_client

[INFO 12-08 16:22:47] ax.service.ax_client: Completed trial 24 with data: {'obj_surf_conc': (11.0, None)}.
[INFO 12-08 16:22:47] ax.service.ax_client: Completed trial 25 with data: {'obj_surf_conc': (11.0, None)}.
[INFO 12-08 16:22:47] ax.service.ax_client: Completed trial 26 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 12-08 16:22:47] ax.service.ax_client: Completed trial 27 with data: {'obj_surf_conc': (11.0, None)}.

AxClient(experiment=Experiment(drug_surfactant))