# import libraries

In [1]:
import pandas as pd
from ax.service.ax_client import AxClient, ObjectiveProperties
import matplotlib.pyplot as pltF
from ax.modelbridge.registry import Models
from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy   
import time

import sys
sys.path.append('../')
import helper_functions as hf

/var/folders/9p/f66yhymx35939zzlg51g0rrc0000gn/T/ipykernel_82729/1227705463.py:5: DeprecationWarning: Please import from 'ax.generation_strategy.generation_strategy' instead of 'ax.modelbridge.generation_strategy'. The latter is deprecated and will be removed in a future release.
  from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy

# initialize the optimizer

In [2]:
ax_client_init_file_name = 'optimizer/optimizer_00.json'
ax_client = hf.optimizer_init()
ax_client

[INFO 12-09 15:12:38] ax.service.utils.instantiation: Inferred value type of ParameterType.STRING for parameter surf_1. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/service/utils/instantiation.py:258: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "surf_1". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return ChoiceParameter(
[INFO 12-09 15:12:38] ax.service.utils.instantiation: Inferred value type of ParameterType.STRING for parameter surf_2. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/service/utils/instantiation.py:258: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "surf_2". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return ChoiceParameter(

AxClient(experiment=Experiment(drug_surfactant))

In [3]:
ax_client.save_to_json_file(ax_client_init_file_name)

# generate recommendations

In [8]:
n = hf.get_iteration_number()

for i in range(3):
    print("Very Important: Please Confirm the Iteration Number is Iteration " + str(n))

print()

list_of_drugs = (['IBP'])*12 #+ ['LOV']  + ['DCF']  + ['GLV'] ) * 

for i in range(3):
    print("Very Important: Please Confirm the Drugs are: ", list_of_drugs)

Very Important: Please Confirm the Iteration Number is Iteration 0
Very Important: Please Confirm the Iteration Number is Iteration 0
Very Important: Please Confirm the Iteration Number is Iteration 0

Very Important: Please Confirm the Drugs are:  ['IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP']
Very Important: Please Confirm the Drugs are:  ['IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP']
Very Important: Please Confirm the Drugs are:  ['IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP']

In [9]:
time_start = time.time()



df_design, ax_client,_,_ = hf.run_optimizer(current_iteration=n, drug_list= list_of_drugs, bopt=0)

time_end = time.time()
time_duration = round((time_end - time_start)/60,2)

print("Time taken for optimization: " + str(time_duration) + " mins")
print("Time taken for optimization: " + str(time_duration * 60) + " seconds")

[WARNING 12-09 15:13:29] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.7027725810185075, 'surf_1_OH_PARAM__1': 0.3893421981483698, 'surf_1_OH_PARAM__2': 0.5738334404304624, 'surf_1_OH_PARAM__3': 0.7244136435911059, 'surf_1_OH_PARAM__4': 0.3094446621835232, 'surf_1_OH_PARAM__5': 0.6977694006636739, 'surf_1_OH_PARAM__6': 0.9842043370008469, 'surf_1_OH_PARAM__7': 0.6977998036891222, 'surf_1_conc': 3.4374992094892827, 'surf_2_OH_PARAM__0': 0.1852993257343769, 'surf_2_OH_PARAM__1': 0.15290994476526976, 'surf_2_OH_PARAM__2': 0.128479091450572, 'surf_2_OH_PARAM__3': 0.0012486493214964867, 'surf_2_OH_PARAM__4': 0.25389708671718836, 'surf_2_OH_PARAM__5': 0.7091244384646416, 'surf_2_OH_PARAM__6': 0.07303992100059986, 'surf_2_OH_PARAM__7': 0.6562753710895777, 'surf_2_conc': 1.164580073451642, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 9.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 12-09 15:13:29] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.0, 'surf_1_OH_PARAM__1': 0.0, 'surf_1_OH_PARAM__2': 0.0, 'surf_1_OH_PARAM__3': 0.0, 'surf_1_OH_PARAM__4': 0.0, 'surf_1_OH_PARAM__5': 0.0, 'surf_1_OH_PARAM__6': 1.0, 'surf_1_OH_PARAM__7': 0.0, 'surf_1_conc': 3.0, 'surf_2_OH_PARAM__0': 0.0, 'surf_2_OH_PARAM__1': 0.0, 'surf_2_OH_PARAM__2': 0.0, 'surf_2_OH_PARAM__3': 0.0, 'surf_2_OH_PARAM__4': 0.0, 'surf_2_OH_PARAM__5': 1.0, 'surf_2_OH_PARAM__6': 0.0, 'surf_2_OH_PARAM__7': 0.0, 'surf_2_conc': 1.0, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 9.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 12-09 15:13:29] ax.service.ax_client: Generated new trial 0 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 3, 'surf_2_conc': 1, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's6'} using model Sobol.
[WARNING 12-09 15:13:29] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.0037634940817952156, 'surf_1_OH_PARAM__1': 0.8141217147931457, 'surf_1_OH_PARAM__2': 0.7406759671866894, 'surf_1_OH_PARAM__3': 0.9561039302498102, 'surf_1_OH_PARAM__4': 0.6756732063367963, 'surf_1_OH_PARAM__5': 0.21041523758322, 'surf_1_OH_PARAM__6': 0.3966235024854541, 'surf_1_OH_PARAM__7': 0.8127681268379092, 'surf_1_conc': 1.185890777499918, 'surf_2_OH_PARAM__0': 0.012163537554442883, 'surf_2_OH_PARAM__1': 0.3733033752068877, 'surf_2_OH_PARAM__2': 0.5632305471226573, 'surf_2_OH_PARAM__3': 0.7179085658863187, 'surf_2_OH_PARAM__4': 0.4923010217025876, 'surf_2_OH_PARAM__5': 0.23102684877812862, 'surf_2_OH_PARAM__6': 0.3515354748815298, 'surf_2_OH_PARAM__7': 0.42559066507965326, 'surf_2_conc': 4.920256209553033, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 9.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 12-09 15:13:29] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.0, 'surf_1_OH_PARAM__1': 0.0, 'surf_1_OH_PARAM__2': 0.0, 'surf_1_OH_PARAM__3': 1.0, 'surf_1_OH_PARAM__4': 0.0, 'surf_1_OH_PARAM__5': 0.0, 'surf_1_OH_PARAM__6': 0.0, 'surf_1_OH_PARAM__7': 0.0, 'surf_1_conc': 1.0, 'surf_2_OH_PARAM__0': 0.0, 'surf_2_OH_PARAM__1': 0.0, 'surf_2_OH_PARAM__2': 0.0, 'surf_2_OH_PARAM__3': 1.0, 'surf_2_OH_PARAM__4': 0.0, 'surf_2_OH_PARAM__5': 0.0, 'surf_2_OH_PARAM__6': 0.0, 'surf_2_OH_PARAM__7': 0.0, 'surf_2_conc': 5.0, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 9.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])

******************************************************************************** 1/12 ********************************************************************************


******************************************************************************** 2/12 ********************************************************************************

[INFO 12-09 15:13:29] ax.service.ax_client: Generated new trial 1 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 1, 'surf_2_conc': 5, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's4'} using model Sobol.
[WARNING 12-09 15:13:29] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.3404636224731803, 'surf_1_OH_PARAM__1': 0.9537274660542607, 'surf_1_OH_PARAM__2': 0.8137485692277551, 'surf_1_OH_PARAM__3': 0.013394019566476345, 'surf_1_OH_PARAM__4': 0.34946224465966225, 'surf_1_OH_PARAM__5': 0.2596472976729274, 'surf_1_OH_PARAM__6': 0.46504735853523016, 'surf_1_OH_PARAM__7': 0.7799381567165256, 'surf_1_conc': 0.9393282849225403, 'surf_2_OH_PARAM__0': 0.5236278707161546, 'surf_2_OH_PARAM__1': 0.04333105310797691, 'surf_2_OH_PARAM__2': 0.946794874034822, 'surf_2_OH_PARAM__3': 0.4187682056799531, 'surf_2_OH_PARAM__4': 0.07875171024352312, 'surf_2_OH_PARAM__5': 0.9976675165817142, 'surf_2_OH_PARAM__6': 0.275210446678102, 'surf_2_OH_PARAM__7': 0.750421991571784, 'surf_2_conc': 3.205272210669015, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 9.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 12-09 15:13:29] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.0, 'surf_1_OH_PARAM__1': 1.0, 'surf_1_OH_PARAM__2': 0.0, 'surf_1_OH_PARAM__3': 0.0, 'surf_1_OH_PARAM__4': 0.0, 'surf_1_OH_PARAM__5': 0.0, 'surf_1_OH_PARAM__6': 0.0, 'surf_1_OH_PARAM__7': 0.0, 'surf_1_conc': 1.0, 'surf_2_OH_PARAM__0': 0.0, 'surf_2_OH_PARAM__1': 0.0, 'surf_2_OH_PARAM__2': 0.0, 'surf_2_OH_PARAM__3': 0.0, 'surf_2_OH_PARAM__4': 0.0, 'surf_2_OH_PARAM__5': 1.0, 'surf_2_OH_PARAM__6': 0.0, 'surf_2_OH_PARAM__7': 0.0, 'surf_2_conc': 3.0, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 9.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 12-09 15:13:29] ax.service.ax_client: Generated new trial 2 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 1, 'surf_2_conc': 3, 'drug_conc': 25.0, 'surf_1': 's2', 'surf_2': 's6'} using model Sobol.
[WARNING 12-09 15:13:29] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.8914620978757739, 'surf_1_OH_PARAM__1': 0.280865803360939, 'surf_1_OH_PARAM__2': 0.9967592135071754, 'surf_1_OH_PARAM__3': 0.3080728258937597, 'surf_1_OH_PARAM__4': 0.7293922426179051, 'surf_1_OH_PARAM__5': 0.7696071183308959, 'surf_1_OH_PARAM__6': 0.9118743576109409, 'surf_1_OH_PARAM__7': 0.6449064332991838, 'surf_1_conc': 3.684023536543884, 'surf_2_OH_PARAM__0': 0.6659942548722029, 'surf_2_OH_PARAM__1': 0.4516969919204712, 'surf_2_OH_PARAM__2': 0.26041840948164463, 'surf_2_OH_PARAM__3': 0.862021173350513, 'surf_2_OH_PARAM__4': 0.16725186351686716, 'surf_2_OH_PARAM__5': 0.4444979326799512, 'surf_2_OH_PARAM__6': 0.05164653342217207, 'surf_2_OH_PARAM__7': 0.019188699312508106, 'surf_2_conc': 1.9616448418936134, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 9.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 12-09 15:13:29] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.0, 'surf_1_OH_PARAM__1': 0.0, 'surf_1_OH_PARAM__2': 1.0, 'surf_1_OH_PARAM__3': 0.0, 'surf_1_OH_PARAM__4': 0.0, 'surf_1_OH_PARAM__5': 0.0, 'surf_1_OH_PARAM__6': 0.0, 'surf_1_OH_PARAM__7': 0.0, 'surf_1_conc': 4.0, 'surf_2_OH_PARAM__0': 0.0, 'surf_2_OH_PARAM__1': 0.0, 'surf_2_OH_PARAM__2': 0.0, 'surf_2_OH_PARAM__3': 1.0, 'surf_2_OH_PARAM__4': 0.0, 'surf_2_OH_PARAM__5': 0.0, 'surf_2_OH_PARAM__6': 0.0, 'surf_2_OH_PARAM__7': 0.0, 'surf_2_conc': 2.0, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 9.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 12-09 15:13:29] ax.service.ax_client: Generated new trial 3 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 4, 'surf_2_conc': 2, 'drug_conc': 25.0, 'surf_1': 's3', 'surf_2': 's4'} using model Sobol.

******************************************************************************** 3/12 ********************************************************************************


******************************************************************************** 4/12 ********************************************************************************


******************************************************************************** 5/12 ********************************************************************************

[WARNING 12-09 15:13:29] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.4341551195830107, 'surf_1_OH_PARAM__1': 0.8013951778411865, 'surf_1_OH_PARAM__2': 0.1917425012215972, 'surf_1_OH_PARAM__3': 0.607687178067863, 'surf_1_OH_PARAM__4': 0.5676763271912932, 'surf_1_OH_PARAM__5': 0.795466797426343, 'surf_1_OH_PARAM__6': 0.9557190500199795, 'surf_1_OH_PARAM__7': 0.9993892572820187, 'surf_1_conc': 6.362614826806878, 'surf_2_OH_PARAM__0': 0.8799140024930239, 'surf_2_OH_PARAM__1': 0.9711983148008585, 'surf_2_OH_PARAM__2': 0.60481789521873, 'surf_2_OH_PARAM__3': 0.14747854508459568, 'surf_2_OH_PARAM__4': 0.4559036837890744, 'surf_2_OH_PARAM__5': 0.10055346880108118, 'surf_2_OH_PARAM__6': 0.9689407683908939, 'surf_2_OH_PARAM__7': 0.8401067331433296, 'surf_2_conc': 0.8704239353153669, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 9.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 12-09 15:13:29] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.0, 'surf_1_OH_PARAM__1': 0.0, 'surf_1_OH_PARAM__2': 0.0, 'surf_1_OH_PARAM__3': 0.0, 'surf_1_OH_PARAM__4': 0.0, 'surf_1_OH_PARAM__5': 0.0, 'surf_1_OH_PARAM__6': 0.0, 'surf_1_OH_PARAM__7': 1.0, 'surf_1_conc': 6.0, 'surf_2_OH_PARAM__0': 0.0, 'surf_2_OH_PARAM__1': 1.0, 'surf_2_OH_PARAM__2': 0.0, 'surf_2_OH_PARAM__3': 0.0, 'surf_2_OH_PARAM__4': 0.0, 'surf_2_OH_PARAM__5': 0.0, 'surf_2_OH_PARAM__6': 0.0, 'surf_2_OH_PARAM__7': 0.0, 'surf_2_conc': 1.0, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 9.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 12-09 15:13:29] ax.service.ax_client: Generated new trial 4 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 6, 'surf_2_conc': 1, 'drug_conc': 25.0, 'surf_1': 's8', 'surf_2': 's2'} using model Sobol.
[WARNING 12-09 15:13:29] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.646189839579165, 'surf_1_OH_PARAM__1': 0.22333460953086615, 'surf_1_OH_PARAM__2': 0.8648456698283553, 'surf_1_OH_PARAM__3': 0.4481635941192508, 'surf_1_OH_PARAM__4': 0.16660409048199654, 'surf_1_OH_PARAM__5': 0.42312610801309347, 'surf_1_OH_PARAM__6': 0.08627703133970499, 'surf_1_OH_PARAM__7': 0.08409794885665178, 'surf_1_conc': 0.7309354781252891, 'surf_2_OH_PARAM__0': 0.05029252264648676, 'surf_2_OH_PARAM__1': 0.244063813239336, 'surf_2_OH_PARAM__2': 0.35698860697448254, 'surf_2_OH_PARAM__3': 0.9101361995562911, 'surf_2_OH_PARAM__4': 0.9280751440674067, 'surf_2_OH_PARAM__5': 0.9429942891001701, 'surf_2_OH_PARAM__6': 0.09781260415911674, 'surf_2_OH_PARAM__7': 0.28036365658044815, 'surf_2_conc': 7.094456439767052, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 9.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 12-09 15:13:29] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.0, 'surf_1_OH_PARAM__1': 0.0, 'surf_1_OH_PARAM__2': 1.0, 'surf_1_OH_PARAM__3': 0.0, 'surf_1_OH_PARAM__4': 0.0, 'surf_1_OH_PARAM__5': 0.0, 'surf_1_OH_PARAM__6': 0.0, 'surf_1_OH_PARAM__7': 0.0, 'surf_1_conc': 1.0, 'surf_2_OH_PARAM__0': 0.0, 'surf_2_OH_PARAM__1': 0.0, 'surf_2_OH_PARAM__2': 0.0, 'surf_2_OH_PARAM__3': 0.0, 'surf_2_OH_PARAM__4': 0.0, 'surf_2_OH_PARAM__5': 1.0, 'surf_2_OH_PARAM__6': 0.0, 'surf_2_OH_PARAM__7': 0.0, 'surf_2_conc': 7.0, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 9.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 12-09 15:13:29] ax.service.ax_client: Generated new trial 5 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 1, 'surf_2_conc': 7, 'drug_conc': 25.0, 'surf_1': 's3', 'surf_2': 's6'} using model Sobol.
[WARNING 12-09 15:13:29] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.9102572910487652, 'surf_1_OH_PARAM__1': 0.7486569778993726, 'surf_1_OH_PARAM__2': 0.2607321487739682, 'surf_1_OH_PARAM__3': 0.9729755138978362, 'surf_1_OH_PARAM__4': 0.2682954967021942, 'surf_1_OH_PARAM__5': 0.13277419470250607, 'surf_1_OH_PARAM__6': 0.6701254975050688, 'surf_1_OH_PARAM__7': 0.259271957911551, 'surf_1_conc': 5.266538712526952, 'surf_2_OH_PARAM__0': 0.3643949683755636, 'surf_2_OH_PARAM__1': 0.4753902219235897, 'surf_2_OH_PARAM__2': 0.06781440135091543, 'surf_2_OH_PARAM__3': 0.4680949365720153, 'surf_2_OH_PARAM__4': 0.006253433413803577, 'surf_2_OH_PARAM__5': 0.6846372140571475, 'surf_2_OH_PARAM__6': 0.5008517447859049, 'surf_2_OH_PARAM__7': 0.21747455559670925, 'surf_2_conc': 3.6224101894548912, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 9.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 12-09 15:13:29] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.0, 'surf_1_OH_PARAM__1': 0.0, 'surf_1_OH_PARAM__2': 0.0, 'surf_1_OH_PARAM__3': 1.0, 'surf_1_OH_PARAM__4': 0.0, 'surf_1_OH_PARAM__5': 0.0, 'surf_1_OH_PARAM__6': 0.0, 'surf_1_OH_PARAM__7': 0.0, 'surf_1_conc': 5.0, 'surf_2_OH_PARAM__0': 0.0, 'surf_2_OH_PARAM__1': 0.0, 'surf_2_OH_PARAM__2': 0.0, 'surf_2_OH_PARAM__3': 0.0, 'surf_2_OH_PARAM__4': 0.0, 'surf_2_OH_PARAM__5': 1.0, 'surf_2_OH_PARAM__6': 0.0, 'surf_2_OH_PARAM__7': 0.0, 'surf_2_conc': 4.0, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 9.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 12-09 15:13:29] ax.service.ax_client: Generated new trial 6 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 5, 'surf_2_conc': 4, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's6'} using model Sobol.

******************************************************************************** 6/12 ********************************************************************************


******************************************************************************** 7/12 ********************************************************************************


******************************************************************************** 8/12 ********************************************************************************

[WARNING 12-09 15:13:29] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.35194186121225357, 'surf_1_OH_PARAM__1': 0.04843629151582718, 'surf_1_OH_PARAM__2': 0.4287887029349804, 'surf_1_OH_PARAM__3': 0.7056423630565405, 'surf_1_OH_PARAM__4': 0.6538111651316285, 'surf_1_OH_PARAM__5': 0.6504170466214418, 'surf_1_OH_PARAM__6': 0.21070234943181276, 'surf_1_OH_PARAM__7': 0.12861953675746918, 'surf_1_conc': 1.778108398166802, 'surf_2_OH_PARAM__0': 0.44229301903396845, 'surf_2_OH_PARAM__1': 0.004012584686279297, 'surf_2_OH_PARAM__2': 0.6312204096466303, 'surf_2_OH_PARAM__3': 0.7511614607647061, 'surf_2_OH_PARAM__4': 0.24758564773947, 'surf_2_OH_PARAM__5': 0.13247471023350954, 'surf_2_OH_PARAM__6': 0.794850705191493, 'surf_2_OH_PARAM__7': 0.950657051987946, 'surf_2_conc': 2.3659654821281695, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 9.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 12-09 15:13:29] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.0, 'surf_1_OH_PARAM__1': 0.0, 'surf_1_OH_PARAM__2': 0.0, 'surf_1_OH_PARAM__3': 1.0, 'surf_1_OH_PARAM__4': 0.0, 'surf_1_OH_PARAM__5': 0.0, 'surf_1_OH_PARAM__6': 0.0, 'surf_1_OH_PARAM__7': 0.0, 'surf_1_conc': 2.0, 'surf_2_OH_PARAM__0': 0.0, 'surf_2_OH_PARAM__1': 0.0, 'surf_2_OH_PARAM__2': 0.0, 'surf_2_OH_PARAM__3': 0.0, 'surf_2_OH_PARAM__4': 0.0, 'surf_2_OH_PARAM__5': 0.0, 'surf_2_OH_PARAM__6': 0.0, 'surf_2_OH_PARAM__7': 1.0, 'surf_2_conc': 2.0, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 9.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 12-09 15:13:29] ax.service.ax_client: Generated new trial 7 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 2, 'surf_2_conc': 2, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's8'} using model Sobol.
[WARNING 12-09 15:13:29] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.05381631292402744, 'surf_1_OH_PARAM__1': 0.15691270120441914, 'surf_1_OH_PARAM__2': 0.00012561772018671036, 'surf_1_OH_PARAM__3': 0.2618719441816211, 'surf_1_OH_PARAM__4': 0.32395338267087936, 'surf_1_OH_PARAM__5': 0.8169594034552574, 'surf_1_OH_PARAM__6': 0.1541270622983575, 'surf_1_OH_PARAM__7': 0.21616561710834503, 'surf_1_conc': 2.767123916017302, 'surf_2_OH_PARAM__0': 0.953785072080791, 'surf_2_OH_PARAM__1': 0.33400780986994505, 'surf_2_OH_PARAM__2': 0.765036566182971, 'surf_2_OH_PARAM__3': 0.1120701814070344, 'surf_2_OH_PARAM__4': 0.33324664924293756, 'surf_2_OH_PARAM__5': 0.8971317335963249, 'surf_2_OH_PARAM__6': 0.8318079998716712, 'surf_2_OH_PARAM__7': 0.3738770429044962, 'surf_2_conc': 1.5811553855161742, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 9.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 12-09 15:13:30] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.0, 'surf_1_OH_PARAM__1': 0.0, 'surf_1_OH_PARAM__2': 0.0, 'surf_1_OH_PARAM__3': 0.0, 'surf_1_OH_PARAM__4': 0.0, 'surf_1_OH_PARAM__5': 1.0, 'surf_1_OH_PARAM__6': 0.0, 'surf_1_OH_PARAM__7': 0.0, 'surf_1_conc': 3.0, 'surf_2_OH_PARAM__0': 1.0, 'surf_2_OH_PARAM__1': 0.0, 'surf_2_OH_PARAM__2': 0.0, 'surf_2_OH_PARAM__3': 0.0, 'surf_2_OH_PARAM__4': 0.0, 'surf_2_OH_PARAM__5': 0.0, 'surf_2_OH_PARAM__6': 0.0, 'surf_2_OH_PARAM__7': 0.0, 'surf_2_conc': 2.0, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 9.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 12-09 15:13:30] ax.service.ax_client: Generated new trial 8 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 3, 'surf_2_conc': 2, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's1'} using model Sobol.
[WARNING 12-09 15:13:30] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.22257908806204796, 'surf_1_OH_PARAM__1': 0.9116974119096994, 'surf_1_OH_PARAM__2': 0.362719202414155, 'surf_1_OH_PARAM__3': 0.4228450935333967, 'surf_1_OH_PARAM__4': 0.3940055724233389, 'surf_1_OH_PARAM__5': 0.7344711646437645, 'surf_1_OH_PARAM__6': 0.8991437628865242, 'surf_1_OH_PARAM__7': 0.907904502004385, 'surf_1_conc': 5.9939059720774, 'surf_2_OH_PARAM__0': 0.3918965384364128, 'surf_2_OH_PARAM__1': 0.6724702576175332, 'surf_2_OH_PARAM__2': 0.9711245838552713, 'surf_2_OH_PARAM__3': 0.9735961463302374, 'surf_2_OH_PARAM__4': 0.11951401550322771, 'surf_2_OH_PARAM__5': 0.8671636246144772, 'surf_2_OH_PARAM__6': 0.9043967174366117, 'surf_2_OH_PARAM__7': 0.4842697074636817, 'surf_2_conc': 2.88558589892719, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 9.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 12-09 15:13:30] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.0, 'surf_1_OH_PARAM__1': 1.0, 'surf_1_OH_PARAM__2': 0.0, 'surf_1_OH_PARAM__3': 0.0, 'surf_1_OH_PARAM__4': 0.0, 'surf_1_OH_PARAM__5': 0.0, 'surf_1_OH_PARAM__6': 0.0, 'surf_1_OH_PARAM__7': 0.0, 'surf_1_conc': 6.0, 'surf_2_OH_PARAM__0': 0.0, 'surf_2_OH_PARAM__1': 0.0, 'surf_2_OH_PARAM__2': 0.0, 'surf_2_OH_PARAM__3': 1.0, 'surf_2_OH_PARAM__4': 0.0, 'surf_2_OH_PARAM__5': 0.0, 'surf_2_OH_PARAM__6': 0.0, 'surf_2_OH_PARAM__7': 0.0, 'surf_2_conc': 3.0, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 9.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 12-09 15:13:30] ax.service.ax_client: Generated new trial 9 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 6, 'surf_2_conc': 3, 'drug_conc': 25.0, 'surf_1': 's2', 'surf_2': 's4'} using model Sobol.

******************************************************************************** 9/12 ********************************************************************************


******************************************************************************** 10/12 ********************************************************************************


******************************************************************************** 11/12 ********************************************************************************

[WARNING 12-09 15:13:30] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.9480367777869105, 'surf_1_OH_PARAM__1': 0.11476567853242159, 'surf_1_OH_PARAM__2': 0.6901191268116236, 'surf_1_OH_PARAM__3': 0.5198388751596212, 'surf_1_OH_PARAM__4': 0.8717060135677457, 'surf_1_OH_PARAM__5': 0.10919220466166735, 'surf_1_OH_PARAM__6': 0.017853361554443836, 'surf_1_OH_PARAM__7': 0.008741733618080616, 'surf_1_conc': 1.724452348372955, 'surf_2_OH_PARAM__0': 0.5383095247671008, 'surf_2_OH_PARAM__1': 0.4179309895262122, 'surf_2_OH_PARAM__2': 0.22334840334951878, 'surf_2_OH_PARAM__3': 0.20315648149698973, 'surf_2_OH_PARAM__4': 0.5301546920090914, 'surf_2_OH_PARAM__5': 0.20769708324223757, 'surf_2_OH_PARAM__6': 0.025393766351044178, 'surf_2_OH_PARAM__7': 0.9186676135286689, 'surf_2_conc': 6.621954946420416, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 9.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 12-09 15:13:30] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 1.0, 'surf_1_OH_PARAM__1': 0.0, 'surf_1_OH_PARAM__2': 0.0, 'surf_1_OH_PARAM__3': 0.0, 'surf_1_OH_PARAM__4': 0.0, 'surf_1_OH_PARAM__5': 0.0, 'surf_1_OH_PARAM__6': 0.0, 'surf_1_OH_PARAM__7': 0.0, 'surf_1_conc': 2.0, 'surf_2_OH_PARAM__0': 0.0, 'surf_2_OH_PARAM__1': 0.0, 'surf_2_OH_PARAM__2': 0.0, 'surf_2_OH_PARAM__3': 0.0, 'surf_2_OH_PARAM__4': 0.0, 'surf_2_OH_PARAM__5': 0.0, 'surf_2_OH_PARAM__6': 0.0, 'surf_2_OH_PARAM__7': 1.0, 'surf_2_conc': 7.0, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 9.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 12-09 15:13:30] ax.service.ax_client: Generated new trial 10 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 2, 'surf_2_conc': 7, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's8'} using model Sobol.
[WARNING 12-09 15:13:30] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.4453170169144869, 'surf_1_OH_PARAM__1': 0.8782243756577373, 'surf_1_OH_PARAM__2': 0.6522081829607487, 'surf_1_OH_PARAM__3': 0.695832715369761, 'surf_1_OH_PARAM__4': 0.7778550526127219, 'surf_1_OH_PARAM__5': 0.83951236307621, 'surf_1_OH_PARAM__6': 0.6867371900007129, 'surf_1_OH_PARAM__7': 0.5617806268855929, 'surf_1_conc': 0.6262509509151057, 'surf_2_OH_PARAM__0': 0.7944518029689789, 'surf_2_OH_PARAM__1': 0.6156727708876133, 'surf_2_OH_PARAM__2': 0.2780009740963578, 'surf_2_OH_PARAM__3': 0.6280586328357458, 'surf_2_OH_PARAM__4': 0.10905736219137907, 'surf_2_OH_PARAM__5': 0.8079182747751474, 'surf_2_OH_PARAM__6': 0.8765483675524592, 'surf_2_OH_PARAM__7': 0.0799939064309001, 'surf_2_conc': 7.942579320250415, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 9.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 12-09 15:13:30] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.0, 'surf_1_OH_PARAM__1': 1.0, 'surf_1_OH_PARAM__2': 0.0, 'surf_1_OH_PARAM__3': 0.0, 'surf_1_OH_PARAM__4': 0.0, 'surf_1_OH_PARAM__5': 0.0, 'surf_1_OH_PARAM__6': 0.0, 'surf_1_OH_PARAM__7': 0.0, 'surf_1_conc': 1.0, 'surf_2_OH_PARAM__0': 0.0, 'surf_2_OH_PARAM__1': 0.0, 'surf_2_OH_PARAM__2': 0.0, 'surf_2_OH_PARAM__3': 0.0, 'surf_2_OH_PARAM__4': 0.0, 'surf_2_OH_PARAM__5': 0.0, 'surf_2_OH_PARAM__6': 1.0, 'surf_2_OH_PARAM__7': 0.0, 'surf_2_conc': 8.0, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[1, 10]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 9.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 12-09 15:13:30] ax.service.ax_client: Generated new trial 11 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 1, 'surf_2_conc': 8, 'drug_conc': 25.0, 'surf_1': 's2', 'surf_2': 's7'} using model Sobol.

******************************************************************************** 12/12 ********************************************************************************

Time taken for optimization: 0.02 mins
Time taken for optimization: 1.2 seconds

# process results

In [10]:
ax_client = hf.load_design_optimizer(n)
ax_client.experiment.trials

{0: Trial(experiment_name='drug_surfactant', index=0, status=TrialStatus.RUNNING, arm=Arm(name='0_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 3, 'surf_2_conc': 1, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's6'})),
 1: Trial(experiment_name='drug_surfactant', index=1, status=TrialStatus.RUNNING, arm=Arm(name='1_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 1, 'surf_2_conc': 5, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's4'})),
 2: Trial(experiment_name='drug_surfactant', index=2, status=TrialStatus.RUNNING, arm=Arm(name='2_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 1, 'surf_2_conc': 3, 'drug_conc': 25.0, 'surf_1': 's2', 'surf_2': 's6'})),
 3: Trial(experiment_name='drug_surfactant', index=3, status=TrialStatus.RUNNING, arm=Arm(name='3_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 4, 'surf_2_conc': 2, 'drug_conc': 25.0, 'surf_1': 's3', 'surf_2': 's4'})),
 4: Trial(experiment_name='drug_surfactant', index=4, status=TrialStatus.RUNNING, arm=Arm(name='4_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 6, 'surf_2_conc': 1, 'drug_conc': 25.0, 'surf_1': 's8', 'surf_2': 's2'})),
 5: Trial(experiment_name='drug_surfactant', index=5, status=TrialStatus.RUNNING, arm=Arm(name='5_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 1, 'surf_2_conc': 7, 'drug_conc': 25.0, 'surf_1': 's3', 'surf_2': 's6'})),
 6: Trial(experiment_name='drug_surfactant', index=6, status=TrialStatus.RUNNING, arm=Arm(name='6_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 5, 'surf_2_conc': 4, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's6'})),
 7: Trial(experiment_name='drug_surfactant', index=7, status=TrialStatus.RUNNING, arm=Arm(name='7_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 2, 'surf_2_conc': 2, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's8'})),
 8: Trial(experiment_name='drug_surfactant', index=8, status=TrialStatus.RUNNING, arm=Arm(name='8_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 3, 'surf_2_conc': 2, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's1'})),
 9: Trial(experiment_name='drug_surfactant', index=9, status=TrialStatus.RUNNING, arm=Arm(name='9_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 6, 'surf_2_conc': 3, 'drug_conc': 25.0, 'surf_1': 's2', 'surf_2': 's4'})),
 10: Trial(experiment_name='drug_surfactant', index=10, status=TrialStatus.RUNNING, arm=Arm(name='10_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 2, 'surf_2_conc': 7, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's8'})),
 11: Trial(experiment_name='drug_surfactant', index=11, status=TrialStatus.RUNNING, arm=Arm(name='11_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 1, 'surf_2_conc': 8, 'drug_conc': 25.0, 'surf_1': 's2', 'surf_2': 's7'}))}

In [11]:
df_design, df_vol = hf.design_to_vol (n)
df_design

,trial_index,drug_name,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,drug_conc,surf_1,surf_2,surf_conc,obj_surf_conc
0,0,IBP,0.2063,0.3073,0.0373,3,1,25.0,s7,s6,4,NaN
1,1,IBP,0.2063,0.3073,0.0373,1,5,25.0,s4,s4,6,NaN
2,2,IBP,0.2063,0.3073,0.0373,1,3,25.0,s2,s6,4,NaN
3,3,IBP,0.2063,0.3073,0.0373,4,2,25.0,s3,s4,6,NaN
4,4,IBP,0.2063,0.3073,0.0373,6,1,25.0,s8,s2,7,NaN
5,5,IBP,0.2063,0.3073,0.0373,1,7,25.0,s3,s6,8,NaN
6,6,IBP,0.2063,0.3073,0.0373,5,4,25.0,s4,s6,9,NaN
7,7,IBP,0.2063,0.3073,0.0373,2,2,25.0,s4,s8,4,NaN
8,8,IBP,0.2063,0.3073,0.0373,3,2,25.0,s6,s1,5,NaN
9,9,IBP,0.2063,0.3073,0.0373,6,3,25.0,s2,s4,9,NaN
10,10,IBP,0.2063,0.3073,0.0373,2,7,25.0,s1,s8,9,NaN
11,11,IBP,0.2063,0.3073,0.0373,1,8,25.0,s2,s7,9,NaN

In [12]:
df_vol

,trial_index,drug_name,drug,s1,s2,s3,s4,s5,s6,s7,s8,dmso,water,IBP
0,0,IBP,180.0,0.0,0.0,0.0,0.0,0.0,12.0,36.0,0.0,0.0,1152.0,180.0
1,1,IBP,180.0,0.0,0.0,0.0,72.0,0.0,0.0,0.0,0.0,0.0,1128.0,180.0
2,2,IBP,180.0,0.0,12.0,0.0,0.0,0.0,36.0,0.0,0.0,0.0,1152.0,180.0
3,3,IBP,180.0,0.0,0.0,48.0,24.0,0.0,0.0,0.0,0.0,0.0,1128.0,180.0
4,4,IBP,180.0,0.0,12.0,0.0,0.0,0.0,0.0,0.0,72.0,0.0,1116.0,180.0
5,5,IBP,180.0,0.0,0.0,12.0,0.0,0.0,84.0,0.0,0.0,0.0,1104.0,180.0
6,6,IBP,180.0,0.0,0.0,0.0,60.0,0.0,48.0,0.0,0.0,0.0,1092.0,180.0
7,7,IBP,180.0,0.0,0.0,0.0,24.0,0.0,0.0,0.0,24.0,0.0,1152.0,180.0
8,8,IBP,180.0,24.0,0.0,0.0,0.0,0.0,36.0,0.0,0.0,0.0,1140.0,180.0
9,9,IBP,180.0,0.0,72.0,0.0,36.0,0.0,0.0,0.0,0.0,0.0,1092.0,180.0
10,10,IBP,180.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,84.0,0.0,1092.0,180.0
11,11,IBP,180.0,0.0,12.0,0.0,0.0,0.0,0.0,96.0,0.0,0.0,1092.0,180.0

In [13]:
df_vol.sum()

trial_index                                      66
drug_name      IBPIBPIBPIBPIBPIBPIBPIBPIBPIBPIBPIBP
drug                                         2160.0
s1                                             48.0
s2                                            108.0
s3                                             60.0
s4                                            216.0
s5                                              0.0
s6                                            216.0
s7                                            132.0
s8                                            180.0
dmso                                            0.0
water                                       13440.0
IBP                                          2160.0
dtype: object

In [14]:
plate_well = input("Enter the plate well starting well (e.g., F1): ")
deepplate_well = input("Enter the deep plate well starting well (e.g., F1): ")



print("Please confirm the following information:")
print("Wellplate will start at: " + plate_well)
print("Deep plate will start at: " + deepplate_well)



print()
print("*******************************************************")
print("Continue if correct, or rerun this cell if incorrect.")
print("*******************************************************")

Please confirm the following information:
Wellplate will start at: F1
Deep plate will start at: D1

*******************************************************
Continue if correct, or rerun this cell if incorrect.
*******************************************************

In [15]:
hf.generate_protocol(df_vol=df_vol, iteration=n, plate_well=plate_well, deepplate_well=deepplate_well)

✅ Successfully wrote to: protocol/otflex_0.py

In [19]:
df_absorbance = hf.process_absorbance(iteration=n, threshold=0.06)
df_absorbance

    trial_index  success
0             0        0
1             1        0
2             2        0
3             3        0
4             4        0
5             5        0
6             6        0
7             7        0
8             8        0
9             9        0
10           10        1
11           11        0

In [20]:
results = hf.build_results(n, df_absorbance)
results

,trial_index,drug_name,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,drug_conc,surf_1,surf_2,surf_conc,obj_surf_conc,success
0,0,IBP,0.2063,0.3073,0.0373,3,1,25.0,s7,s6,4,100,0
1,1,IBP,0.2063,0.3073,0.0373,1,5,25.0,s4,s4,6,100,0
2,2,IBP,0.2063,0.3073,0.0373,1,3,25.0,s2,s6,4,100,0
3,3,IBP,0.2063,0.3073,0.0373,4,2,25.0,s3,s4,6,100,0
4,4,IBP,0.2063,0.3073,0.0373,6,1,25.0,s8,s2,7,100,0
5,5,IBP,0.2063,0.3073,0.0373,1,7,25.0,s3,s6,8,100,0
6,6,IBP,0.2063,0.3073,0.0373,5,4,25.0,s4,s6,9,100,0
7,7,IBP,0.2063,0.3073,0.0373,2,2,25.0,s4,s8,4,100,0
8,8,IBP,0.2063,0.3073,0.0373,3,2,25.0,s6,s1,5,100,0
9,9,IBP,0.2063,0.3073,0.0373,6,3,25.0,s2,s4,9,100,0
10,10,IBP,0.2063,0.3073,0.0373,2,7,25.0,s1,s8,9,9,1
11,11,IBP,0.2063,0.3073,0.0373,1,8,25.0,s2,s7,9,100,0

# load the results to the optimizer

In [21]:
ax_client = hf.load_data_to_optimizer(iteration = n, results = results)
ax_client

[INFO 12-09 17:32:28] ax.service.ax_client: Completed trial 0 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 12-09 17:32:28] ax.service.ax_client: Completed trial 1 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 12-09 17:32:28] ax.service.ax_client: Completed trial 2 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 12-09 17:32:28] ax.service.ax_client: Completed trial 3 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 12-09 17:32:28] ax.service.ax_client: Completed trial 4 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 12-09 17:32:28] ax.service.ax_client: Completed trial 5 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 12-09 17:32:28] ax.service.ax_client: Completed trial 6 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 12-09 17:32:28] ax.service.ax_client: Completed trial 7 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 12-09 17:32:28] ax.service.ax_client: Completed trial 8 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 12-09 17:32:29] ax.service.ax_client: Completed trial 9 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 12-09 17:32:29] ax.service.ax_client: Completed trial 10 with data: {'obj_surf_conc': (9.0, None)}.
[INFO 12-09 17:32:29] ax.service.ax_client: Completed trial 11 with data: {'obj_surf_conc': (100.0, None)}.

AxClient(experiment=Experiment(drug_surfactant))