# import libraries

In [1]:
import pandas as pd
from ax.service.ax_client import AxClient, ObjectiveProperties
import matplotlib.pyplot as pltF
from ax.modelbridge.registry import Models
from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy   
import time

import sys
sys.path.append('../')
import helper_functions as hf

/var/folders/9p/f66yhymx35939zzlg51g0rrc0000gn/T/ipykernel_79093/1227705463.py:5: DeprecationWarning: Please import from 'ax.generation_strategy.generation_strategy' instead of 'ax.modelbridge.generation_strategy'. The latter is deprecated and will be removed in a future release.
  from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy

# initialize the optimizer

In [2]:
ax_client_init_file_name = 'optimizer/optimizer_00.json'
ax_client = hf.optimizer_init()
ax_client

[INFO 12-09 12:01:27] ax.service.utils.instantiation: Inferred value type of ParameterType.STRING for parameter surf_1. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/service/utils/instantiation.py:258: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "surf_1". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return ChoiceParameter(
[INFO 12-09 12:01:27] ax.service.utils.instantiation: Inferred value type of ParameterType.STRING for parameter surf_2. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/service/utils/instantiation.py:258: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "surf_2". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return ChoiceParameter(

AxClient(experiment=Experiment(drug_surfactant))

In [3]:
ax_client.save_to_json_file(ax_client_init_file_name)

# generate recommendations

In [4]:
n = hf.get_iteration_number()

for i in range(3):
    print("Very Important: Please Confirm the Iteration Number is Iteration " + str(n))

print()

list_of_drugs = (['IBP'])*8 #+ ['LOV']  + ['DCF']  + ['GLV'] ) * 

for i in range(3):
    print("Very Important: Please Confirm the Drugs are: ", list_of_drugs)

Very Important: Please Confirm the Iteration Number is Iteration 0
Very Important: Please Confirm the Iteration Number is Iteration 0
Very Important: Please Confirm the Iteration Number is Iteration 0

Very Important: Please Confirm the Drugs are:  ['IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP']
Very Important: Please Confirm the Drugs are:  ['IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP']
Very Important: Please Confirm the Drugs are:  ['IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP']

In [5]:
time_start = time.time()



df_design, ax_client,_,_ = hf.run_optimizer(current_iteration=n, drug_list= list_of_drugs, bopt=0)

time_end = time.time()
time_duration = round((time_end - time_start)/60,2)

print("Time taken for optimization: " + str(time_duration) + " mins")
print("Time taken for optimization: " + str(time_duration * 60) + " seconds")

[WARNING 12-09 12:01:34] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.47510719299316406, 'surf_1_OH_PARAM__1': 0.592523992061615, 'surf_1_OH_PARAM__2': 0.4944792091846466, 'surf_1_OH_PARAM__3': 0.3138517439365387, 'surf_1_OH_PARAM__4': 0.9560918211936951, 'surf_1_OH_PARAM__5': 0.08330223709344864, 'surf_1_OH_PARAM__6': 0.09876348823308945, 'surf_1_OH_PARAM__7': 0.3474661111831665, 'surf_1_conc': 17.438300347001555, 'surf_2_OH_PARAM__0': 0.7615082859992981, 'surf_2_OH_PARAM__1': 0.8828067779541016, 'surf_2_OH_PARAM__2': 0.880169153213501, 'surf_2_OH_PARAM__3': 0.8024652004241943, 'surf_2_OH_PARAM__4': 0.8510614633560181, 'surf_2_OH_PARAM__5': 0.3646984398365021, 'surf_2_OH_PARAM__6': 0.9519653916358948, 'surf_2_OH_PARAM__7': 0.22200752794742584, 'surf_2_conc': 14.301773561046124, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[1, 20]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[1, 20]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 12-09 12:01:34] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.0, 'surf_1_OH_PARAM__1': 0.0, 'surf_1_OH_PARAM__2': 0.0, 'surf_1_OH_PARAM__3': 0.0, 'surf_1_OH_PARAM__4': 1.0, 'surf_1_OH_PARAM__5': 0.0, 'surf_1_OH_PARAM__6': 0.0, 'surf_1_OH_PARAM__7': 0.0, 'surf_1_conc': 17.0, 'surf_2_OH_PARAM__0': 0.0, 'surf_2_OH_PARAM__1': 0.0, 'surf_2_OH_PARAM__2': 0.0, 'surf_2_OH_PARAM__3': 0.0, 'surf_2_OH_PARAM__4': 0.0, 'surf_2_OH_PARAM__5': 0.0, 'surf_2_OH_PARAM__6': 1.0, 'surf_2_OH_PARAM__7': 0.0, 'surf_2_conc': 14.0, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[1, 20]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[1, 20]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 12-09 12:01:34] ax.service.ax_client: Generated new trial 0 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 17, 'surf_2_conc': 14, 'drug_conc': 25.0, 'surf_1': 's5', 'surf_2': 's7'} using model Sobol.
[WARNING 12-09 12:01:34] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.7027725810185075, 'surf_1_OH_PARAM__1': 0.3893421981483698, 'surf_1_OH_PARAM__2': 0.5738334404304624, 'surf_1_OH_PARAM__3': 0.7244136435911059, 'surf_1_OH_PARAM__4': 0.3094446621835232, 'surf_1_OH_PARAM__5': 0.6977694006636739, 'surf_1_OH_PARAM__6': 0.9842043370008469, 'surf_1_OH_PARAM__7': 0.6977998036891222, 'surf_1_conc': 6.374994293968733, 'surf_2_OH_PARAM__0': 0.1852993257343769, 'surf_2_OH_PARAM__1': 0.15290994476526976, 'surf_2_OH_PARAM__2': 0.128479091450572, 'surf_2_OH_PARAM__3': 0.0012486493214964867, 'surf_2_OH_PARAM__4': 0.25389708671718836, 'surf_2_OH_PARAM__5': 0.7091244384646416, 'surf_2_OH_PARAM__6': 0.07303992100059986, 'surf_2_OH_PARAM__7': 0.6562753710895777, 'surf_2_conc': 1.8291514760460892, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[1, 20]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[1, 20]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 12-09 12:01:34] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.0, 'surf_1_OH_PARAM__1': 0.0, 'surf_1_OH_PARAM__2': 0.0, 'surf_1_OH_PARAM__3': 0.0, 'surf_1_OH_PARAM__4': 0.0, 'surf_1_OH_PARAM__5': 0.0, 'surf_1_OH_PARAM__6': 1.0, 'surf_1_OH_PARAM__7': 0.0, 'surf_1_conc': 6.0, 'surf_2_OH_PARAM__0': 0.0, 'surf_2_OH_PARAM__1': 0.0, 'surf_2_OH_PARAM__2': 0.0, 'surf_2_OH_PARAM__3': 0.0, 'surf_2_OH_PARAM__4': 0.0, 'surf_2_OH_PARAM__5': 1.0, 'surf_2_OH_PARAM__6': 0.0, 'surf_2_OH_PARAM__7': 0.0, 'surf_2_conc': 2.0, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[1, 20]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[1, 20]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])

******************************************************************************** 1/8 ********************************************************************************


******************************************************************************** 2/8 ********************************************************************************

[INFO 12-09 12:01:34] ax.service.ax_client: Generated new trial 1 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 6, 'surf_2_conc': 2, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's6'} using model Sobol.
[WARNING 12-09 12:01:34] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.9980894811451435, 'surf_1_OH_PARAM__1': 0.8950253129005432, 'surf_1_OH_PARAM__2': 0.0517491465434432, 'surf_1_OH_PARAM__3': 0.1986861890181899, 'surf_1_OH_PARAM__4': 0.12985710054636002, 'surf_1_OH_PARAM__5': 0.996299784630537, 'surf_1_OH_PARAM__6': 0.275143182836473, 'surf_1_OH_PARAM__7': 0.8964208867400885, 'surf_1_conc': 4.630774235389643, 'surf_2_OH_PARAM__0': 0.4959833202883601, 'surf_2_OH_PARAM__1': 0.3786125211045146, 'surf_2_OH_PARAM__2': 0.4174167728051543, 'surf_2_OH_PARAM__3': 0.6229616766795516, 'surf_2_OH_PARAM__4': 0.6755504813045263, 'surf_2_OH_PARAM__5': 0.9204920185729861, 'surf_2_OH_PARAM__6': 0.545155543833971, 'surf_2_OH_PARAM__7': 0.8453393913805485, 'surf_2_conc': 19.737401971039585, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[1, 20]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[1, 20]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 12-09 12:01:34] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 1.0, 'surf_1_OH_PARAM__1': 0.0, 'surf_1_OH_PARAM__2': 0.0, 'surf_1_OH_PARAM__3': 0.0, 'surf_1_OH_PARAM__4': 0.0, 'surf_1_OH_PARAM__5': 0.0, 'surf_1_OH_PARAM__6': 0.0, 'surf_1_OH_PARAM__7': 0.0, 'surf_1_conc': 5.0, 'surf_2_OH_PARAM__0': 0.0, 'surf_2_OH_PARAM__1': 0.0, 'surf_2_OH_PARAM__2': 0.0, 'surf_2_OH_PARAM__3': 0.0, 'surf_2_OH_PARAM__4': 0.0, 'surf_2_OH_PARAM__5': 1.0, 'surf_2_OH_PARAM__6': 0.0, 'surf_2_OH_PARAM__7': 0.0, 'surf_2_conc': 20.0, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[1, 20]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[1, 20]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 12-09 12:01:34] ax.service.ax_client: Generated new trial 2 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 5, 'surf_2_conc': 20, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's6'} using model Sobol.
[WARNING 12-09 12:01:35] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.21012416016310453, 'surf_1_OH_PARAM__1': 0.06695806887000799, 'surf_1_OH_PARAM__2': 0.8801251268014312, 'surf_1_OH_PARAM__3': 0.8592321565374732, 'surf_1_OH_PARAM__4': 0.6046750647947192, 'surf_1_OH_PARAM__5': 0.34765296522527933, 'surf_1_OH_PARAM__6': 0.6438527125865221, 'surf_1_OH_PARAM__7': 0.05925553198903799, 'surf_1_conc': 13.557830498252269, 'surf_2_OH_PARAM__0': 0.5757627785205841, 'surf_2_OH_PARAM__1': 0.6492655696347356, 'surf_2_OH_PARAM__2': 0.6696330225095153, 'surf_2_OH_PARAM__3': 0.3213788513094187, 'surf_2_OH_PARAM__4': 0.21021556202322245, 'surf_2_OH_PARAM__5': 0.013436364009976387, 'surf_2_OH_PARAM__6': 0.4161672554910183, 'surf_2_OH_PARAM__7': 0.2841336764395237, 'surf_2_conc': 7.3432192779806265, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[1, 20]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[1, 20]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 12-09 12:01:35] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.0, 'surf_1_OH_PARAM__1': 0.0, 'surf_1_OH_PARAM__2': 1.0, 'surf_1_OH_PARAM__3': 0.0, 'surf_1_OH_PARAM__4': 0.0, 'surf_1_OH_PARAM__5': 0.0, 'surf_1_OH_PARAM__6': 0.0, 'surf_1_OH_PARAM__7': 0.0, 'surf_1_conc': 14.0, 'surf_2_OH_PARAM__0': 0.0, 'surf_2_OH_PARAM__1': 0.0, 'surf_2_OH_PARAM__2': 1.0, 'surf_2_OH_PARAM__3': 0.0, 'surf_2_OH_PARAM__4': 0.0, 'surf_2_OH_PARAM__5': 0.0, 'surf_2_OH_PARAM__6': 0.0, 'surf_2_OH_PARAM__7': 0.0, 'surf_2_conc': 7.0, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[1, 20]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[1, 20]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 12-09 12:01:35] ax.service.ax_client: Generated new trial 3 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 14, 'surf_2_conc': 7, 'drug_conc': 25.0, 'surf_1': 's3', 'surf_2': 's3'} using model Sobol.

******************************************************************************** 3/8 ********************************************************************************


******************************************************************************** 4/8 ********************************************************************************


******************************************************************************** 5/8 ********************************************************************************

[WARNING 12-09 12:01:35] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.0037634940817952156, 'surf_1_OH_PARAM__1': 0.8141217147931457, 'surf_1_OH_PARAM__2': 0.7406759671866894, 'surf_1_OH_PARAM__3': 0.9561039302498102, 'surf_1_OH_PARAM__4': 0.6756732063367963, 'surf_1_OH_PARAM__5': 0.21041523758322, 'surf_1_OH_PARAM__6': 0.3966235024854541, 'surf_1_OH_PARAM__7': 0.8127681268379092, 'surf_1_conc': 1.8717729267641345, 'surf_2_OH_PARAM__0': 0.012163537554442883, 'surf_2_OH_PARAM__1': 0.3733033752068877, 'surf_2_OH_PARAM__2': 0.5632305471226573, 'surf_2_OH_PARAM__3': 0.7179085658863187, 'surf_2_OH_PARAM__4': 0.4923010217025876, 'surf_2_OH_PARAM__5': 0.23102684877812862, 'surf_2_OH_PARAM__6': 0.3515354748815298, 'surf_2_OH_PARAM__7': 0.42559066507965326, 'surf_2_conc': 9.340511259616166, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[1, 20]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[1, 20]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 12-09 12:01:35] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.0, 'surf_1_OH_PARAM__1': 0.0, 'surf_1_OH_PARAM__2': 0.0, 'surf_1_OH_PARAM__3': 1.0, 'surf_1_OH_PARAM__4': 0.0, 'surf_1_OH_PARAM__5': 0.0, 'surf_1_OH_PARAM__6': 0.0, 'surf_1_OH_PARAM__7': 0.0, 'surf_1_conc': 2.0, 'surf_2_OH_PARAM__0': 0.0, 'surf_2_OH_PARAM__1': 0.0, 'surf_2_OH_PARAM__2': 0.0, 'surf_2_OH_PARAM__3': 1.0, 'surf_2_OH_PARAM__4': 0.0, 'surf_2_OH_PARAM__5': 0.0, 'surf_2_OH_PARAM__6': 0.0, 'surf_2_OH_PARAM__7': 0.0, 'surf_2_conc': 9.0, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[1, 20]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[1, 20]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 12-09 12:01:35] ax.service.ax_client: Generated new trial 4 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 2, 'surf_2_conc': 9, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's4'} using model Sobol.
[WARNING 12-09 12:01:35] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.7919747997075319, 'surf_1_OH_PARAM__1': 0.14230436831712723, 'surf_1_OH_PARAM__2': 0.32001492008566856, 'surf_1_OH_PARAM__3': 0.1168289352208376, 'surf_1_OH_PARAM__4': 0.09004639647901058, 'surf_1_OH_PARAM__5': 0.5710381083190441, 'surf_1_OH_PARAM__6': 0.5281581114977598, 'surf_1_OH_PARAM__7': 0.2275558952242136, 'surf_1_conc': 10.691235723590479, 'surf_2_OH_PARAM__0': 0.9316533505916595, 'surf_2_OH_PARAM__1': 0.5987899238243699, 'surf_2_OH_PARAM__2': 0.3187428740784526, 'surf_2_OH_PARAM__3': 0.48033642023801804, 'surf_2_OH_PARAM__4': 0.9029426071792841, 'surf_2_OH_PARAM__5': 0.8279017796739936, 'surf_2_OH_PARAM__6': 0.7225421201437712, 'surf_2_OH_PARAM__7': 0.9849752793088555, 'surf_2_conc': 16.78979355690893, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[1, 20]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[1, 20]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 12-09 12:01:35] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 1.0, 'surf_1_OH_PARAM__1': 0.0, 'surf_1_OH_PARAM__2': 0.0, 'surf_1_OH_PARAM__3': 0.0, 'surf_1_OH_PARAM__4': 0.0, 'surf_1_OH_PARAM__5': 0.0, 'surf_1_OH_PARAM__6': 0.0, 'surf_1_OH_PARAM__7': 0.0, 'surf_1_conc': 11.0, 'surf_2_OH_PARAM__0': 0.0, 'surf_2_OH_PARAM__1': 0.0, 'surf_2_OH_PARAM__2': 0.0, 'surf_2_OH_PARAM__3': 0.0, 'surf_2_OH_PARAM__4': 0.0, 'surf_2_OH_PARAM__5': 0.0, 'surf_2_OH_PARAM__6': 0.0, 'surf_2_OH_PARAM__7': 1.0, 'surf_2_conc': 17.0, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[1, 20]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[1, 20]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 12-09 12:01:35] ax.service.ax_client: Generated new trial 5 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 11, 'surf_2_conc': 17, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's8'} using model Sobol.
[WARNING 12-09 12:01:35] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.5266867866739631, 'surf_1_OH_PARAM__1': 0.6363143939524889, 'surf_1_OH_PARAM__2': 0.8055066149681807, 'surf_1_OH_PARAM__3': 0.5870164316147566, 'surf_1_OH_PARAM__4': 0.4727299530059099, 'surf_1_OH_PARAM__5': 0.8730935426428914, 'surf_1_OH_PARAM__6': 0.22922175470739603, 'surf_1_OH_PARAM__7': 0.42812816612422466, 'surf_1_conc': 20.313905733067934, 'surf_2_OH_PARAM__0': 0.7464571064338088, 'surf_2_OH_PARAM__1': 0.8691950300708413, 'surf_2_OH_PARAM__2': 0.10801602341234684, 'surf_2_OH_PARAM__3': 0.8979023471474648, 'surf_2_OH_PARAM__4': 0.04359014052897692, 'surf_2_OH_PARAM__5': 0.5541562102735043, 'surf_2_OH_PARAM__6': 0.13191866129636765, 'surf_2_OH_PARAM__7': 0.5480780145153403, 'surf_2_conc': 4.854283997833226, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[1, 20]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[1, 20]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 12-09 12:01:35] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.0, 'surf_1_OH_PARAM__1': 0.0, 'surf_1_OH_PARAM__2': 0.0, 'surf_1_OH_PARAM__3': 0.0, 'surf_1_OH_PARAM__4': 0.0, 'surf_1_OH_PARAM__5': 1.0, 'surf_1_OH_PARAM__6': 0.0, 'surf_1_OH_PARAM__7': 0.0, 'surf_1_conc': 20.0, 'surf_2_OH_PARAM__0': 0.0, 'surf_2_OH_PARAM__1': 0.0, 'surf_2_OH_PARAM__2': 0.0, 'surf_2_OH_PARAM__3': 1.0, 'surf_2_OH_PARAM__4': 0.0, 'surf_2_OH_PARAM__5': 0.0, 'surf_2_OH_PARAM__6': 0.0, 'surf_2_OH_PARAM__7': 0.0, 'surf_2_conc': 5.0, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[1, 20]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[1, 20]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 12-09 12:01:35] ax.service.ax_client: Generated new trial 6 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 20, 'surf_2_conc': 5, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's4'} using model Sobol.

******************************************************************************** 6/8 ********************************************************************************


******************************************************************************** 7/8 ********************************************************************************


******************************************************************************** 8/8 ********************************************************************************

[WARNING 12-09 12:01:35] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.2992635518312454, 'surf_1_OH_PARAM__1': 0.33938270527869463, 'surf_1_OH_PARAM__2': 0.13386736623942852, 'surf_1_OH_PARAM__3': 0.4977578576654196, 'surf_1_OH_PARAM__4': 0.7614970216527581, 'surf_1_OH_PARAM__5': 0.47047845274209976, 'surf_1_OH_PARAM__6': 0.8440250419080257, 'surf_1_OH_PARAM__7': 0.5304149826988578, 'surf_1_conc': 9.123780270764753, 'surf_2_OH_PARAM__0': 0.322420347481966, 'surf_2_OH_PARAM__1': 0.09510925319045782, 'surf_2_OH_PARAM__2': 0.8518096599727869, 'surf_2_OH_PARAM__3': 0.15971978474408388, 'surf_2_OH_PARAM__4': 0.5704492647200823, 'surf_2_OH_PARAM__5': 0.39466689992696047, 'surf_2_OH_PARAM__6': 0.7529881149530411, 'surf_2_OH_PARAM__7': 0.11172501649707556, 'surf_2_conc': 12.225736937487703, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[1, 20]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[1, 20]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 12-09 12:01:35] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.0, 'surf_1_OH_PARAM__1': 0.0, 'surf_1_OH_PARAM__2': 0.0, 'surf_1_OH_PARAM__3': 0.0, 'surf_1_OH_PARAM__4': 0.0, 'surf_1_OH_PARAM__5': 0.0, 'surf_1_OH_PARAM__6': 1.0, 'surf_1_OH_PARAM__7': 0.0, 'surf_1_conc': 9.0, 'surf_2_OH_PARAM__0': 0.0, 'surf_2_OH_PARAM__1': 0.0, 'surf_2_OH_PARAM__2': 1.0, 'surf_2_OH_PARAM__3': 0.0, 'surf_2_OH_PARAM__4': 0.0, 'surf_2_OH_PARAM__5': 0.0, 'surf_2_OH_PARAM__6': 0.0, 'surf_2_OH_PARAM__7': 0.0, 'surf_2_conc': 12.0, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[1, 20]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[1, 20]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 12-09 12:01:35] ax.service.ax_client: Generated new trial 7 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 9, 'surf_2_conc': 12, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's3'} using model Sobol.

Time taken for optimization: 0.01 mins
Time taken for optimization: 0.6 seconds

# process results

In [6]:
ax_client = hf.load_design_optimizer(n)
ax_client.experiment.trials

{0: Trial(experiment_name='drug_surfactant', index=0, status=TrialStatus.RUNNING, arm=Arm(name='0_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 17, 'surf_2_conc': 14, 'drug_conc': 25.0, 'surf_1': 's5', 'surf_2': 's7'})),
 1: Trial(experiment_name='drug_surfactant', index=1, status=TrialStatus.RUNNING, arm=Arm(name='1_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 6, 'surf_2_conc': 2, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's6'})),
 2: Trial(experiment_name='drug_surfactant', index=2, status=TrialStatus.RUNNING, arm=Arm(name='2_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 5, 'surf_2_conc': 20, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's6'})),
 3: Trial(experiment_name='drug_surfactant', index=3, status=TrialStatus.RUNNING, arm=Arm(name='3_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 14, 'surf_2_conc': 7, 'drug_conc': 25.0, 'surf_1': 's3', 'surf_2': 's3'})),
 4: Trial(experiment_name='drug_surfactant', index=4, status=TrialStatus.RUNNING, arm=Arm(name='4_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 2, 'surf_2_conc': 9, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's4'})),
 5: Trial(experiment_name='drug_surfactant', index=5, status=TrialStatus.RUNNING, arm=Arm(name='5_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 11, 'surf_2_conc': 17, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's8'})),
 6: Trial(experiment_name='drug_surfactant', index=6, status=TrialStatus.RUNNING, arm=Arm(name='6_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 20, 'surf_2_conc': 5, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's4'})),
 7: Trial(experiment_name='drug_surfactant', index=7, status=TrialStatus.RUNNING, arm=Arm(name='7_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 9, 'surf_2_conc': 12, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's3'}))}

In [7]:
df_design, df_vol = hf.design_to_vol (n)
df_design

,trial_index,drug_name,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,drug_conc,surf_1,surf_2,surf_conc,obj_surf_conc
0,0,IBP,0.2063,0.3073,0.0373,17,14,25.0,s5,s7,31,NaN
1,1,IBP,0.2063,0.3073,0.0373,6,2,25.0,s7,s6,8,NaN
2,2,IBP,0.2063,0.3073,0.0373,5,20,25.0,s1,s6,25,NaN
3,3,IBP,0.2063,0.3073,0.0373,14,7,25.0,s3,s3,21,NaN
4,4,IBP,0.2063,0.3073,0.0373,2,9,25.0,s4,s4,11,NaN
5,5,IBP,0.2063,0.3073,0.0373,11,17,25.0,s1,s8,28,NaN
6,6,IBP,0.2063,0.3073,0.0373,20,5,25.0,s6,s4,25,NaN
7,7,IBP,0.2063,0.3073,0.0373,9,12,25.0,s7,s3,21,NaN

In [8]:
df_vol

,trial_index,drug_name,drug,s1,s2,s3,s4,s5,s6,s7,s8,dmso,water,IBP
0,0,IBP,180.0,0.0,0.0,0.0,0.0,204.0,0.0,168.0,0.0,0.0,828.0,180.0
1,1,IBP,180.0,0.0,0.0,0.0,0.0,0.0,24.0,72.0,0.0,0.0,1104.0,180.0
2,2,IBP,180.0,60.0,0.0,0.0,0.0,0.0,240.0,0.0,0.0,0.0,900.0,180.0
3,3,IBP,180.0,0.0,0.0,252.0,0.0,0.0,0.0,0.0,0.0,0.0,948.0,180.0
4,4,IBP,180.0,0.0,0.0,0.0,132.0,0.0,0.0,0.0,0.0,0.0,1068.0,180.0
5,5,IBP,180.0,132.0,0.0,0.0,0.0,0.0,0.0,0.0,204.0,0.0,864.0,180.0
6,6,IBP,180.0,0.0,0.0,0.0,60.0,0.0,240.0,0.0,0.0,0.0,900.0,180.0
7,7,IBP,180.0,0.0,0.0,144.0,0.0,0.0,0.0,108.0,0.0,0.0,948.0,180.0

In [9]:
df_vol.sum()

trial_index                          28
drug_name      IBPIBPIBPIBPIBPIBPIBPIBP
drug                             1440.0
s1                                192.0
s2                                  0.0
s3                                396.0
s4                                192.0
s5                                204.0
s6                                504.0
s7                                348.0
s8                                204.0
dmso                                0.0
water                            7560.0
IBP                              1440.0
dtype: object

In [10]:
plate_well = input("Enter the plate well starting well (e.g., F1): ")
deepplate_well = input("Enter the deep plate well starting well (e.g., F1): ")



print("Please confirm the following information:")
print("Wellplate will start at: " + plate_well)
print("Deep plate will start at: " + deepplate_well)



print()
print("*******************************************************")
print("Continue if correct, or rerun this cell if incorrect.")
print("*******************************************************")

Please confirm the following information:
Wellplate will start at: A1
Deep plate will start at: A1

*******************************************************
Continue if correct, or rerun this cell if incorrect.
*******************************************************

In [11]:
hf.generate_protocol(df_vol=df_vol, iteration=n, plate_well=plate_well, deepplate_well=deepplate_well)

✅ Successfully wrote to: protocol/otflex_0.py

In [12]:
df_absorbance = hf.process_absorbance(iteration=n, threshold=0.06)
df_absorbance

   trial_index  success
0            0        0
1            1        0
2            2        1
3            3        0
4            4        0
5            5        0
6            6        1
7            7        1

In [13]:
results = hf.build_results(n, df_absorbance)
results

,trial_index,drug_name,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,drug_conc,surf_1,surf_2,surf_conc,obj_surf_conc,success
0,0,IBP,0.2063,0.3073,0.0373,17,14,25.0,s5,s7,31,100,0
1,1,IBP,0.2063,0.3073,0.0373,6,2,25.0,s7,s6,8,100,0
2,2,IBP,0.2063,0.3073,0.0373,5,20,25.0,s1,s6,25,25,1
3,3,IBP,0.2063,0.3073,0.0373,14,7,25.0,s3,s3,21,100,0
4,4,IBP,0.2063,0.3073,0.0373,2,9,25.0,s4,s4,11,100,0
5,5,IBP,0.2063,0.3073,0.0373,11,17,25.0,s1,s8,28,100,0
6,6,IBP,0.2063,0.3073,0.0373,20,5,25.0,s6,s4,25,25,1
7,7,IBP,0.2063,0.3073,0.0373,9,12,25.0,s7,s3,21,21,1

# load the results to the optimizer

In [14]:
ax_client = hf.load_data_to_optimizer(iteration = n, results = results)
ax_client

[INFO 12-09 13:12:09] ax.service.ax_client: Completed trial 0 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 12-09 13:12:09] ax.service.ax_client: Completed trial 1 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 12-09 13:12:09] ax.service.ax_client: Completed trial 2 with data: {'obj_surf_conc': (25.0, None)}.
[INFO 12-09 13:12:09] ax.service.ax_client: Completed trial 3 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 12-09 13:12:09] ax.service.ax_client: Completed trial 4 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 12-09 13:12:09] ax.service.ax_client: Completed trial 5 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 12-09 13:12:09] ax.service.ax_client: Completed trial 6 with data: {'obj_surf_conc': (25.0, None)}.
[INFO 12-09 13:12:09] ax.service.ax_client: Completed trial 7 with data: {'obj_surf_conc': (21.0, None)}.

AxClient(experiment=Experiment(drug_surfactant))