# import libraries

In [1]:
import pandas as pd
from ax.service.ax_client import AxClient, ObjectiveProperties
import matplotlib.pyplot as plt
from ax.modelbridge.registry import Models
from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy   
import time


import sys
sys.path.append('../')
import helper_functions as hf

/var/folders/9p/f66yhymx35939zzlg51g0rrc0000gn/T/ipykernel_14088/3307975217.py:5: DeprecationWarning: Please import from 'ax.generation_strategy.generation_strategy' instead of 'ax.modelbridge.generation_strategy'. The latter is deprecated and will be removed in a future release.
  from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy

# generate recommendations

In [2]:
print("List of available drugs:")
print("=====================================")
for drug in hf.normalize_drug_properties_dict.keys():
    print(f"{drug}:   {hf.normalize_drug_properties_dict[drug]['full_name']}")

List of available drugs:
=====================================
IBP:   Ibuprofen
DCF:   Diclofenac
LOV:   Lovastatin
ITZ:   Itraconazole
RPD:   Risperidone
GLV:   Griseofulvin
CTZ:   Clotrimazole
GBC:   Glibenclamide/Glyburide

In [3]:
drug = input("Enter the drug name (abbreviation): ")


print("Please confirm the following information:")
print()
print("Drug:                ", drug, " (",hf.normalize_drug_properties_dict[drug]['full_name'],")")
print("Stock solution conc: ", hf.normalize_drug_properties_dict[drug]['drug_stock_conc'], "mg/mL")
print("Molecular weight:    ",hf.normalize_drug_properties_dict[drug]['normalized_properties']['Drug_MW'] * 1000)
print("LogP:                ", hf.normalize_drug_properties_dict[drug]['normalized_properties']['Drug_LogP'] * 10)
print("TPSA:                ", hf.normalize_drug_properties_dict[drug]['normalized_properties']['Drug_TPSA'] * 1000)



print()
print("*******************************************************")
print("Continue if correct, or rerun this cell if incorrect.")
print("*******************************************************")

Please confirm the following information:

Drug:                 GBC  ( Glibenclamide/Glyburide )
Stock solution conc:  25 mg/mL
Molecular weight:     494.0
LogP:                 3.6420000000000003
TPSA:                 113.60000000000001

*******************************************************
Continue if correct, or rerun this cell if incorrect.
*******************************************************

In [4]:
n = hf.get_iteration_number()

for i in range(3):
    print("Very Important: Please Confirm the Iteration Number is Iteration " + str(n))

Very Important: Please Confirm the Iteration Number is Iteration 26
Very Important: Please Confirm the Iteration Number is Iteration 26
Very Important: Please Confirm the Iteration Number is Iteration 26

In [5]:
time_start = time.time()


df_design, ax_client = hf.run_optimizer(current_iteration=n, drug = drug, bopt = 1, n_trials=3)

time_end = time.time()
time_duration = round((time_end - time_start)/60,2)

print("Time taken for optimization: " + str(time_duration) + " mins")
print("Time taken for optimization: " + str(time_duration * 60) + " seconds")

**************************************************************************************************************

Generating Bayesian Optimization trials for
Drug name:  Glibenclamide/Glyburide GBC  | Iteration:  26

**************************************************************************************************************

[INFO 07-10 10:29:59] ax.service.ax_client: Generated new trial 78 with parameters {'Drug_MW': 0.494, 'Drug_LogP': 0.3642, 'Drug_TPSA': 0.1136, 's1': 0, 's2': 28, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 100, 's8': 0, 'surfactant_conc': 100, 'drug_conc': 100} using model SAASBO.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
[INFO 07-10 10:30:51] ax.service.ax_client: Generated new trial 79 with parameters {'Drug_MW': 0.494, 'Drug_LogP': 0.3642, 'Drug_TPSA': 0.1136, 's1': 0, 's2': 100, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 100, 's8': 2, 'surfactant_conc': 100, 'drug_conc': 100} using model SAASBO.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
[INFO 07-10 10:31:44] ax.service.ax_client: Generated new trial 80 with parameters {'Drug_MW': 0.494, 'Drug_LogP': 0.3642, 'Drug_TPSA': 0.1136, 's1': 0, 's2': 0, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 84, 's8': 15, 'surfactant_conc': 100, 'drug_conc': 100} using model SAASBO.

Time taken for optimization: 3.33 mins
Time taken for optimization: 199.8 seconds

# process results

In [6]:
ax_client = hf.load_design_optimizer(n)
ax_client.experiment.trials

{0: Trial(experiment_name='drug_surfactant', index=0, status=TrialStatus.COMPLETED, arm=Arm(name='0_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 47, 's2': 60, 's3': 50, 's4': 31, 's5': 96, 's6': 8, 's7': 9, 's8': 35, 'surfactant_conc': 85, 'drug_conc': 100})),
 1: Trial(experiment_name='drug_surfactant', index=1, status=TrialStatus.COMPLETED, arm=Arm(name='1_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 74, 's2': 0, 's3': 88, 's4': 66, 's5': 22, 's6': 52, 's7': 58, 's8': 79, 'surfactant_conc': 35, 'drug_conc': 100})),
 2: Trial(experiment_name='drug_surfactant', index=2, status=TrialStatus.COMPLETED, arm=Arm(name='2_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 78, 's2': 88, 's3': 1, 's4': 3, 's5': 32, 's6': 94, 's7': 44, 's8': 58, 'surfactant_conc': 1, 'drug_conc': 100})),
 3: Trial(experiment_name='drug_surfactant', index=3, status=TrialStatus.COMPLETED, arm=Arm(name='3_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 0, 's2': 100, 's3': 100, 's4': 100, 's5': 0, 's6': 100, 's7': 100, 's8': 0, 'surfactant_conc': 100, 'drug_conc': 100})),
 4: Trial(experiment_name='drug_surfactant', index=4, status=TrialStatus.COMPLETED, arm=Arm(name='4_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 0, 's2': 0, 's3': 0, 's4': 100, 's5': 0, 's6': 0, 's7': 100, 's8': 0, 'surfactant_conc': 100, 'drug_conc': 100})),
 5: Trial(experiment_name='drug_surfactant', index=5, status=TrialStatus.COMPLETED, arm=Arm(name='5_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 100, 's2': 0, 's3': 0, 's4': 100, 's5': 100, 's6': 0, 's7': 100, 's8': 0, 'surfactant_conc': 1, 'drug_conc': 100})),
 6: Trial(experiment_name='drug_surfactant', index=6, status=TrialStatus.COMPLETED, arm=Arm(name='6_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 0, 's2': 0, 's3': 100, 's4': 0, 's5': 0, 's6': 0, 's7': 100, 's8': 0, 'surfactant_conc': 100, 'drug_conc': 100})),
 7: Trial(experiment_name='drug_surfactant', index=7, status=TrialStatus.COMPLETED, arm=Arm(name='7_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 0, 's2': 100, 's3': 0, 's4': 100, 's5': 0, 's6': 0, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 8: Trial(experiment_name='drug_surfactant', index=8, status=TrialStatus.COMPLETED, arm=Arm(name='8_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 0, 's2': 0, 's3': 0, 's4': 100, 's5': 0, 's6': 100, 's7': 0, 's8': 0, 'surfactant_conc': 100, 'drug_conc': 100})),
 9: Trial(experiment_name='drug_surfactant', index=9, status=TrialStatus.COMPLETED, arm=Arm(name='9_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 0, 's2': 0, 's3': 100, 's4': 100, 's5': 0, 's6': 0, 's7': 0, 's8': 0, 'surfactant_conc': 1, 'drug_conc': 100})),
 10: Trial(experiment_name='drug_surfactant', index=10, status=TrialStatus.COMPLETED, arm=Arm(name='10_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 0, 's2': 0, 's3': 0, 's4': 0, 's5': 0, 's6': 100, 's7': 100, 's8': 0, 'surfactant_conc': 100, 'drug_conc': 100})),
 11: Trial(experiment_name='drug_surfactant', index=11, status=TrialStatus.COMPLETED, arm=Arm(name='11_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 0, 's2': 0, 's3': 0, 's4': 0, 's5': 0, 's6': 100, 's7': 100, 's8': 0, 'surfactant_conc': 1, 'drug_conc': 100})),
 12: Trial(experiment_name='drug_surfactant', index=12, status=TrialStatus.COMPLETED, arm=Arm(name='12_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 100, 's2': 0, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 0, 's8': 0, 'surfactant_conc': 100, 'drug_conc': 100})),
 13: Trial(experiment_name='drug_surfactant', index=13, status=TrialStatus.COMPLETED, arm=Arm(name='13_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 0, 's2': 0, 's3': 100, 's4': 0, 's5': 100, 's6': 100, 's7': 0, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 14: Trial(experiment_name='drug_surfactant', index=14, status=TrialStatus.COMPLETED, arm=Arm(name='14_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 100, 's2': 100, 's3': 0, 's4': 100, 's5': 0, 's6': 100, 's7': 0, 's8': 0, 'surfactant_conc': 99, 'drug_conc': 100})),
 15: Trial(experiment_name='drug_surfactant', index=15, status=TrialStatus.COMPLETED, arm=Arm(name='15_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 0, 's2': 0, 's3': 100, 's4': 0, 's5': 0, 's6': 100, 's7': 0, 's8': 100, 'surfactant_conc': 91, 'drug_conc': 100})),
 16: Trial(experiment_name='drug_surfactant', index=16, status=TrialStatus.COMPLETED, arm=Arm(name='16_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 100, 's2': 0, 's3': 0, 's4': 100, 's5': 0, 's6': 0, 's7': 100, 's8': 100, 'surfactant_conc': 92, 'drug_conc': 100})),
 17: Trial(experiment_name='drug_surfactant', index=17, status=TrialStatus.COMPLETED, arm=Arm(name='17_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 100, 's2': 0, 's3': 100, 's4': 100, 's5': 0, 's6': 100, 's7': 0, 's8': 0, 'surfactant_conc': 90, 'drug_conc': 100})),
 18: Trial(experiment_name='drug_surfactant', index=18, status=TrialStatus.COMPLETED, arm=Arm(name='18_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 0, 's2': 0, 's3': 0, 's4': 0, 's5': 0, 's6': 20, 's7': 0, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 19: Trial(experiment_name='drug_surfactant', index=19, status=TrialStatus.COMPLETED, arm=Arm(name='19_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 0, 's2': 0, 's3': 0, 's4': 0, 's5': 0, 's6': 100, 's7': 0, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 20: Trial(experiment_name='drug_surfactant', index=20, status=TrialStatus.COMPLETED, arm=Arm(name='20_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 0, 's2': 0, 's3': 100, 's4': 0, 's5': 0, 's6': 0, 's7': 0, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 21: Trial(experiment_name='drug_surfactant', index=21, status=TrialStatus.COMPLETED, arm=Arm(name='21_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 0, 's2': 0, 's3': 1, 's4': 0, 's5': 0, 's6': 0, 's7': 0, 's8': 0, 'surfactant_conc': 91, 'drug_conc': 100})),
 22: Trial(experiment_name='drug_surfactant', index=22, status=TrialStatus.COMPLETED, arm=Arm(name='22_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 100, 's2': 0, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 0, 's8': 0, 'surfactant_conc': 91, 'drug_conc': 100})),
 23: Trial(experiment_name='drug_surfactant', index=23, status=TrialStatus.COMPLETED, arm=Arm(name='23_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 100, 's2': 0, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 0, 's8': 0, 'surfactant_conc': 97, 'drug_conc': 100})),
 24: Trial(experiment_name='drug_surfactant', index=24, status=TrialStatus.COMPLETED, arm=Arm(name='24_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 0, 's2': 0, 's3': 0, 's4': 45, 's5': 0, 's6': 20, 's7': 17, 's8': 0, 'surfactant_conc': 91, 'drug_conc': 100})),
 25: Trial(experiment_name='drug_surfactant', index=25, status=TrialStatus.COMPLETED, arm=Arm(name='25_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 0, 's2': 100, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 0, 's8': 0, 'surfactant_conc': 91, 'drug_conc': 100})),
 26: Trial(experiment_name='drug_surfactant', index=26, status=TrialStatus.COMPLETED, arm=Arm(name='26_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 100, 's2': 0, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 100, 's8': 0, 'surfactant_conc': 91, 'drug_conc': 100})),
 27: Trial(experiment_name='drug_surfactant', index=27, status=TrialStatus.COMPLETED, arm=Arm(name='27_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 100, 's2': 100, 's3': 100, 's4': 0, 's5': 0, 's6': 0, 's7': 0, 's8': 0, 'surfactant_conc': 91, 'drug_conc': 100})),
 28: Trial(experiment_name='drug_surfactant', index=28, status=TrialStatus.COMPLETED, arm=Arm(name='28_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 6, 's2': 48, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 0, 's8': 0, 'surfactant_conc': 91, 'drug_conc': 100})),
 29: Trial(experiment_name='drug_surfactant', index=29, status=TrialStatus.COMPLETED, arm=Arm(name='29_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 0, 's2': 1, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 0, 's8': 0, 'surfactant_conc': 98, 'drug_conc': 100})),
 30: Trial(experiment_name='drug_surfactant', index=30, status=TrialStatus.COMPLETED, arm=Arm(name='30_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 100, 's2': 0, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 0, 's8': 0, 'surfactant_conc': 80, 'drug_conc': 100})),
 31: Trial(experiment_name='drug_surfactant', index=31, status=TrialStatus.COMPLETED, arm=Arm(name='31_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 0, 's2': 100, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 0, 's8': 0, 'surfactant_conc': 85, 'drug_conc': 100})),
 32: Trial(experiment_name='drug_surfactant', index=32, status=TrialStatus.COMPLETED, arm=Arm(name='32_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 100, 's2': 0, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 0, 's8': 100, 'surfactant_conc': 75, 'drug_conc': 100})),
 33: Trial(experiment_name='drug_surfactant', index=33, status=TrialStatus.COMPLETED, arm=Arm(name='33_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 100, 's2': 0, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 0, 's8': 0, 'surfactant_conc': 62, 'drug_conc': 100})),
 34: Trial(experiment_name='drug_surfactant', index=34, status=TrialStatus.COMPLETED, arm=Arm(name='34_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 100, 's2': 0, 's3': 0, 's4': 0, 's5': 100, 's6': 0, 's7': 0, 's8': 0, 'surfactant_conc': 68, 'drug_conc': 100})),
 35: Trial(experiment_name='drug_surfactant', index=35, status=TrialStatus.COMPLETED, arm=Arm(name='35_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 100, 's2': 0, 's3': 100, 's4': 0, 's5': 0, 's6': 0, 's7': 0, 's8': 0, 'surfactant_conc': 57, 'drug_conc': 100})),
 36: Trial(experiment_name='drug_surfactant', index=36, status=TrialStatus.COMPLETED, arm=Arm(name='36_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 100, 's2': 0, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 0, 's8': 0, 'surfactant_conc': 49, 'drug_conc': 100})),
 37: Trial(experiment_name='drug_surfactant', index=37, status=TrialStatus.COMPLETED, arm=Arm(name='37_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 100, 's2': 0, 's3': 0, 's4': 0, 's5': 0, 's6': 100, 's7': 0, 's8': 0, 'surfactant_conc': 59, 'drug_conc': 100})),
 38: Trial(experiment_name='drug_surfactant', index=38, status=TrialStatus.COMPLETED, arm=Arm(name='38_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 84, 's2': 0, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 0, 's8': 0, 'surfactant_conc': 71, 'drug_conc': 100})),
 39: Trial(experiment_name='drug_surfactant', index=39, status=TrialStatus.COMPLETED, arm=Arm(name='39_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 100, 's2': 100, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 0, 's8': 100, 'surfactant_conc': 7, 'drug_conc': 100})),
 40: Trial(experiment_name='drug_surfactant', index=40, status=TrialStatus.COMPLETED, arm=Arm(name='40_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 0, 's2': 100, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 100, 's8': 0, 'surfactant_conc': 40, 'drug_conc': 100})),
 41: Trial(experiment_name='drug_surfactant', index=41, status=TrialStatus.COMPLETED, arm=Arm(name='41_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 100, 's2': 0, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 0, 's8': 0, 'surfactant_conc': 21, 'drug_conc': 100})),
 42: Trial(experiment_name='drug_surfactant', index=42, status=TrialStatus.COMPLETED, arm=Arm(name='42_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 0, 's2': 0, 's3': 0, 's4': 0, 's5': 21, 's6': 0, 's7': 0, 's8': 0, 'surfactant_conc': 28, 'drug_conc': 100})),
 43: Trial(experiment_name='drug_surfactant', index=43, status=TrialStatus.COMPLETED, arm=Arm(name='43_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 0, 's2': 0, 's3': 0, 's4': 100, 's5': 63, 's6': 100, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 44: Trial(experiment_name='drug_surfactant', index=44, status=TrialStatus.COMPLETED, arm=Arm(name='44_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 0, 's2': 0, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 100, 's8': 0, 'surfactant_conc': 39, 'drug_conc': 100})),
 45: Trial(experiment_name='drug_surfactant', index=45, status=TrialStatus.COMPLETED, arm=Arm(name='45_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 31, 's2': 0, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 0, 's8': 0, 'surfactant_conc': 13, 'drug_conc': 100})),
 46: Trial(experiment_name='drug_surfactant', index=46, status=TrialStatus.COMPLETED, arm=Arm(name='46_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 0, 's2': 100, 's3': 100, 's4': 0, 's5': 21, 's6': 0, 's7': 0, 's8': 0, 'surfactant_conc': 31, 'drug_conc': 100})),
 47: Trial(experiment_name='drug_surfactant', index=47, status=TrialStatus.COMPLETED, arm=Arm(name='47_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 0, 's2': 0, 's3': 0, 's4': 0, 's5': 23, 's6': 0, 's7': 100, 's8': 0, 'surfactant_conc': 42, 'drug_conc': 100})),
 48: Trial(experiment_name='drug_surfactant', index=48, status=TrialStatus.COMPLETED, arm=Arm(name='48_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 0, 's2': 0, 's3': 0, 's4': 0, 's5': 2, 's6': 0, 's7': 0, 's8': 0, 'surfactant_conc': 4, 'drug_conc': 100})),
 49: Trial(experiment_name='drug_surfactant', index=49, status=TrialStatus.COMPLETED, arm=Arm(name='49_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 0, 's2': 0, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 1, 's8': 0, 'surfactant_conc': 33, 'drug_conc': 100})),
 50: Trial(experiment_name='drug_surfactant', index=50, status=TrialStatus.COMPLETED, arm=Arm(name='50_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 68, 's2': 0, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 47, 's8': 0, 'surfactant_conc': 1, 'drug_conc': 100})),
 51: Trial(experiment_name='drug_surfactant', index=51, status=TrialStatus.COMPLETED, arm=Arm(name='51_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 43, 's2': 0, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 10, 's8': 0, 'surfactant_conc': 18, 'drug_conc': 100})),
 52: Trial(experiment_name='drug_surfactant', index=52, status=TrialStatus.COMPLETED, arm=Arm(name='52_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 46, 's2': 0, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 0, 's8': 0, 'surfactant_conc': 24, 'drug_conc': 100})),
 53: Trial(experiment_name='drug_surfactant', index=53, status=TrialStatus.COMPLETED, arm=Arm(name='53_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 39, 's2': 0, 's3': 0, 's4': 54, 's5': 0, 's6': 0, 's7': 100, 's8': 0, 'surfactant_conc': 17, 'drug_conc': 100})),
 54: Trial(experiment_name='drug_surfactant', index=54, status=TrialStatus.COMPLETED, arm=Arm(name='54_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 19, 's2': 0, 's3': 0, 's4': 0, 's5': 14, 's6': 0, 's7': 0, 's8': 0, 'surfactant_conc': 40, 'drug_conc': 100})),
 55: Trial(experiment_name='drug_surfactant', index=55, status=TrialStatus.COMPLETED, arm=Arm(name='55_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 29, 's2': 0, 's3': 0, 's4': 0, 's5': 21, 's6': 0, 's7': 0, 's8': 0, 'surfactant_conc': 16, 'drug_conc': 100})),
 56: Trial(experiment_name='drug_surfactant', index=56, status=TrialStatus.COMPLETED, arm=Arm(name='56_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 29, 's2': 0, 's3': 0, 's4': 0, 's5': 55, 's6': 0, 's7': 0, 's8': 0, 'surfactant_conc': 15, 'drug_conc': 100})),
 57: Trial(experiment_name='drug_surfactant', index=57, status=TrialStatus.COMPLETED, arm=Arm(name='57_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 52, 's2': 0, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 0, 's8': 62, 'surfactant_conc': 100, 'drug_conc': 100})),
 58: Trial(experiment_name='drug_surfactant', index=58, status=TrialStatus.COMPLETED, arm=Arm(name='58_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 31, 's2': 6, 's3': 0, 's4': 100, 's5': 64, 's6': 20, 's7': 0, 's8': 0, 'surfactant_conc': 12, 'drug_conc': 100})),
 59: Trial(experiment_name='drug_surfactant', index=59, status=TrialStatus.COMPLETED, arm=Arm(name='59_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 31, 's2': 31, 's3': 0, 's4': 100, 's5': 66, 's6': 27, 's7': 100, 's8': 34, 'surfactant_conc': 11, 'drug_conc': 100})),
 60: Trial(experiment_name='drug_surfactant', index=60, status=TrialStatus.COMPLETED, arm=Arm(name='60_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 0, 's2': 0, 's3': 0, 's4': 0, 's5': 22, 's6': 0, 's7': 31, 's8': 0, 'surfactant_conc': 28, 'drug_conc': 100})),
 61: Trial(experiment_name='drug_surfactant', index=61, status=TrialStatus.COMPLETED, arm=Arm(name='61_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 0, 's2': 0, 's3': 0, 's4': 16, 's5': 21, 's6': 0, 's7': 72, 's8': 0, 'surfactant_conc': 28, 'drug_conc': 100})),
 62: Trial(experiment_name='drug_surfactant', index=62, status=TrialStatus.COMPLETED, arm=Arm(name='62_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 0, 's2': 26, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 89, 's8': 15, 'surfactant_conc': 57, 'drug_conc': 100})),
 63: Trial(experiment_name='drug_surfactant', index=63, status=TrialStatus.COMPLETED, arm=Arm(name='63_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 100, 's2': 0, 's3': 13, 's4': 0, 's5': 1, 's6': 0, 's7': 0, 's8': 0, 'surfactant_conc': 28, 'drug_conc': 100})),
 64: Trial(experiment_name='drug_surfactant', index=64, status=TrialStatus.COMPLETED, arm=Arm(name='64_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 100, 's2': 0, 's3': 7, 's4': 0, 's5': 10, 's6': 0, 's7': 100, 's8': 0, 'surfactant_conc': 28, 'drug_conc': 100})),
 65: Trial(experiment_name='drug_surfactant', index=65, status=TrialStatus.COMPLETED, arm=Arm(name='65_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 31, 's2': 0, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 0, 's8': 0, 'surfactant_conc': 39, 'drug_conc': 100})),
 66: Trial(experiment_name='drug_surfactant', index=66, status=TrialStatus.COMPLETED, arm=Arm(name='66_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 20, 's2': 0, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 0, 's8': 0, 'surfactant_conc': 14, 'drug_conc': 100})),

In [7]:
df_conc, df_vol = hf.design_to_conc_to_vol (n)

In [8]:
plate_well = input("Enter the plate well starting well (e.g., F1): ")
deepplate_well = input("Enter the deep plate well starting well (e.g., F1): ")


print("Please confirm the following information:")
print("Wellplate will start at: " + plate_well)
print("Deep plate will start at: " + deepplate_well)

print()
print("*******************************************************")
print("Continue if correct, or rerun this cell if incorrect.")
print("*******************************************************")

Please confirm the following information:
Wellplate will start at: H1
Deep plate will start at: E1

*******************************************************
Continue if correct, or rerun this cell if incorrect.
*******************************************************

In [9]:
hf.generate_protocol(df_vol=df_vol, iteration=n, plate_well=plate_well, deepplate_well=deepplate_well)

✅ Successfully wrote to: protocol/otflex_26.py

In [10]:
df_absorbance = hf.process_absorbance(iteration=n, threshold=0.1)
df_absorbance

   trial_index  success
0            0        0
1            1        0
2            2        0

In [11]:
results = hf.build_results(n, df_conc, df_absorbance)
results

,trial_index,s1,s2,s3,s4,s5,s6,s7,s8,surfactant_input,drug_conc,success,complexity
0,78,0,28,0,0,0,0,100,0,50.0,25.0,0,2
1,79,0,100,0,0,0,0,100,2,50.0,25.0,0,3
2,80,0,0,0,0,0,0,84,15,50.0,25.0,0,2

In [12]:
norm_results = hf.normalize_data(results, 'normalize')

In [13]:
norm_results

,trial_index,s1,s2,s3,s4,s5,s6,s7,s8,surfactant_input,drug_conc,success,complexity
0,78,0,28,0,0,0,0,100,0,1.0,1.0,0.0,0.250
1,79,0,100,0,0,0,0,100,2,1.0,1.0,0.0,0.375
2,80,0,0,0,0,0,0,84,15,1.0,1.0,0.0,0.250

# load the results to the optimizer

In [14]:
ax_client = hf.load_data_to_optimizer(iteration = n, norm_results = norm_results)
ax_client

[INFO 07-10 11:16:25] ax.service.ax_client: Completed trial 78 with data: {'success': (0.0, None), 'surfactant_input': (1.0, None), 'complexity': (1.0, None)}.
[INFO 07-10 11:16:25] ax.service.ax_client: Completed trial 79 with data: {'success': (0.0, None), 'surfactant_input': (1.0, None), 'complexity': (1.0, None)}.
[INFO 07-10 11:16:25] ax.service.ax_client: Completed trial 80 with data: {'success': (0.0, None), 'surfactant_input': (1.0, None), 'complexity': (1.0, None)}.

Trial 78: success=0 → overriding surfactant_input & complexity to 1
Trial 79: success=0 → overriding surfactant_input & complexity to 1
Trial 80: success=0 → overriding surfactant_input & complexity to 1

AxClient(experiment=Experiment(drug_surfactant))