# import libraries

In [1]:
import pandas as pd
from ax.service.ax_client import AxClient, ObjectiveProperties
import matplotlib.pyplot as plt
from ax.modelbridge.factory import Models
from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy   


import sys
sys.path.append('../')
import helper_functions as hf

# initialize the optimizer

In [2]:
ax_client_init_file_name = 'optimizer/optimizer_00.json'
ax_client = hf.optimizer_init()
ax_client

[INFO 06-02 15:52:06] ax.service.ax_client: Starting optimization with verbose logging. To disable logging, set the `verbose_logging` argument to `False`. Note that float values in the logs are rounded to 6 decimal points.
[INFO 06-02 15:52:06] ax.service.utils.instantiation: Created search space: SearchSpace(parameters=[RangeParameter(name='s1', parameter_type=INT, range=[0, 100]), RangeParameter(name='s2', parameter_type=INT, range=[0, 100]), RangeParameter(name='s3', parameter_type=INT, range=[0, 100]), RangeParameter(name='s4', parameter_type=INT, range=[0, 100]), RangeParameter(name='s5', parameter_type=INT, range=[0, 100]), RangeParameter(name='s6', parameter_type=INT, range=[0, 100]), RangeParameter(name='s7', parameter_type=INT, range=[0, 100]), RangeParameter(name='s8', parameter_type=INT, range=[0, 100]), RangeParameter(name='s9', parameter_type=INT, range=[0, 100]), RangeParameter(name='surfactant_conc', parameter_type=INT, range=[1, 100]), RangeParameter(name='drug_conc', parameter_type=INT, range=[1, 100])], parameter_constraints=[]).

AxClient(experiment=Experiment(drug_surfactant))

In [3]:
ax_client.save_to_json_file(ax_client_init_file_name)

[INFO 06-02 15:52:09] ax.service.ax_client: Saved JSON-serialized state of optimization to `optimizer/optimizer_00.json`.

# generate recommendations

In [4]:
n = hf.get_iteration_number()

for i in range(3):
    print("Very Important: Please Confirm the Iteration Number is Iteration " + str(n))

Very Important: Please Confirm the Iteration Number is Iteration 0
Very Important: Please Confirm the Iteration Number is Iteration 0
Very Important: Please Confirm the Iteration Number is Iteration 0

In [5]:
df_design, ax_client = hf.run_optimizer(current_iteration=n, n_trials=6)

[INFO 06-02 15:52:15] ax.service.ax_client: Starting optimization with verbose logging. To disable logging, set the `verbose_logging` argument to `False`. Note that float values in the logs are rounded to 6 decimal points.
c:\Users\yunhe\anaconda3\envs\drug_surfactant\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 06-02 15:52:15] ax.service.ax_client: Generated new trial 0 with parameters {'s1': 47, 's2': 59, 's3': 49, 's4': 31, 's5': 96, 's6': 8, 's7': 9, 's8': 35, 's9': 85, 'surfactant_conc': 77, 'drug_conc': 89} using model Sobol.
c:\Users\yunhe\anaconda3\envs\drug_surfactant\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 06-02 15:52:15] ax.service.ax_client: Generated new trial 1 with parameters {'s1': 92, 's2': 28, 's3': 51, 's4': 69, 's5': 27, 's6': 83, 's7': 70, 's8': 58, 's9': 36, 'surfactant_conc': 30, 'drug_conc': 3} using model Sobol.
c:\Users\yunhe\anaconda3\envs\drug_surfactant\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 06-02 15:52:15] ax.service.ax_client: Generated new trial 2 with parameters {'s1': 53, 's2': 81, 's3': 8, 's4': 21, 's5': 17, 's6': 73, 's7': 48, 's8': 97, 's9': 20, 'surfactant_conc': 14, 'drug_conc': 29} using model Sobol.
c:\Users\yunhe\anaconda3\envs\drug_surfactant\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 06-02 15:52:15] ax.service.ax_client: Generated new trial 3 with parameters {'s1': 7, 's2': 7, 's3': 92, 's4': 84, 's5': 61, 's6': 49, 's7': 82, 's8': 24, 's9': 69, 'surfactant_conc': 68, 'drug_conc': 69} using model Sobol.
c:\Users\yunhe\anaconda3\envs\drug_surfactant\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 06-02 15:52:15] ax.service.ax_client: Generated new trial 4 with parameters {'s1': 21, 's2': 88, 's3': 68, 's4': 90, 's5': 72, 's6': 15, 's7': 35, 's8': 81, 's9': 3, 'surfactant_conc': 50, 'drug_conc': 41} using model Sobol.
c:\Users\yunhe\anaconda3\envs\drug_surfactant\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 06-02 15:52:15] ax.service.ax_client: Generated new trial 5 with parameters {'s1': 65, 's2': 24, 's3': 32, 's4': 2, 's5': 2, 's6': 93, 's7': 95, 's8': 1, 's9': 55, 'surfactant_conc': 95, 'drug_conc': 51} using model Sobol.
[INFO 06-02 15:52:15] ax.service.ax_client: Saved JSON-serialized state of optimization to `optimizer/optimizer_0.json`.

# process results

In [6]:
ax_client = hf.load_design_optimizer(n)
ax_client.experiment.trials

[INFO 06-02 15:52:21] ax.service.ax_client: Starting optimization with verbose logging. To disable logging, set the `verbose_logging` argument to `False`. Note that float values in the logs are rounded to 6 decimal points.

{0: Trial(experiment_name='drug_surfactant', index=0, status=TrialStatus.RUNNING, arm=Arm(name='0_0', parameters={'s1': 47, 's2': 59, 's3': 49, 's4': 31, 's5': 96, 's6': 8, 's7': 9, 's8': 35, 's9': 85, 'surfactant_conc': 77, 'drug_conc': 89})),
 1: Trial(experiment_name='drug_surfactant', index=1, status=TrialStatus.RUNNING, arm=Arm(name='1_0', parameters={'s1': 92, 's2': 28, 's3': 51, 's4': 69, 's5': 27, 's6': 83, 's7': 70, 's8': 58, 's9': 36, 'surfactant_conc': 30, 'drug_conc': 3})),
 2: Trial(experiment_name='drug_surfactant', index=2, status=TrialStatus.RUNNING, arm=Arm(name='2_0', parameters={'s1': 53, 's2': 81, 's3': 8, 's4': 21, 's5': 17, 's6': 73, 's7': 48, 's8': 97, 's9': 20, 'surfactant_conc': 14, 'drug_conc': 29})),
 3: Trial(experiment_name='drug_surfactant', index=3, status=TrialStatus.RUNNING, arm=Arm(name='3_0', parameters={'s1': 7, 's2': 7, 's3': 92, 's4': 84, 's5': 61, 's6': 49, 's7': 82, 's8': 24, 's9': 69, 'surfactant_conc': 68, 'drug_conc': 69})),
 4: Trial(experiment_name='drug_surfactant', index=4, status=TrialStatus.RUNNING, arm=Arm(name='4_0', parameters={'s1': 21, 's2': 88, 's3': 68, 's4': 90, 's5': 72, 's6': 15, 's7': 35, 's8': 81, 's9': 3, 'surfactant_conc': 50, 'drug_conc': 41})),
 5: Trial(experiment_name='drug_surfactant', index=5, status=TrialStatus.RUNNING, arm=Arm(name='5_0', parameters={'s1': 65, 's2': 24, 's3': 32, 's4': 2, 's5': 2, 's6': 93, 's7': 95, 's8': 1, 's9': 55, 'surfactant_conc': 95, 'drug_conc': 51}))}

In [7]:
df_conc, df_vol = hf.design_to_conc_to_vol (n)

In [8]:
plate_well = input("Enter the plate well starting well (e.g., F1): ")
deepplate_well = input("Enter the deep plate well starting well (e.g., F1): ")


print("Please confirm the following information:")
print("Wellplate will start at: " + plate_well)
print("Deep plate will start at: " + deepplate_well)

print()
print("*******************************************************")
print("Continue if correct, or rerun this cell if incorrect.")
print("*******************************************************")

Please confirm the following information:
Wellplate will start at: A1
Deep plate will start at: A1

*******************************************************
Continue if correct, or rerun this cell if incorrect.
*******************************************************

In [9]:

hf.generate_protocol(df_vol=df_vol, iteration=n, plate_well=plate_well, deepplate_well=deepplate_well)

✅ Successfully wrote to: protocol/otflex_0.py

In [14]:
df_absorbance = hf.process_absorbance(iteration=n)

In [18]:
results = hf.build_results(n, df_conc, df_absorbance)

In [19]:
results

,trial_index,s1,s2,s3,s4,s5,s6,s7,s8,s9,surfactant_conc,drug_conc,success,micelle_drug_conc,complexity
0,0,47,59,49,31,96,8,9,35,85,38.5,22.25,0,0.000,9
1,1,92,28,51,69,27,83,70,58,36,15.0,0.75,0,0.000,9
2,2,53,81,8,21,17,73,48,97,20,7.0,7.25,0,0.000,9
3,3,7,7,92,84,61,49,82,24,69,34.0,17.25,1,1.725,9
4,4,21,88,68,90,72,15,35,81,3,25.0,10.25,0,0.000,9
5,5,65,24,32,2,2,93,95,1,55,47.5,12.75,0,0.000,9

In [20]:
norm_results = hf.normalize_data(results, 'normalize')

In [21]:
norm_results

,trial_index,s1,s2,s3,s4,s5,s6,s7,s8,s9,surfactant_conc,drug_conc,success,micelle_drug_conc,complexity
0,0,47,59,49,31,96,8,9,35,85,0.77,22.25,0,0.00,1.0
1,1,92,28,51,69,27,83,70,58,36,0.30,0.75,0,0.00,1.0
2,2,53,81,8,21,17,73,48,97,20,0.14,7.25,0,0.00,1.0
3,3,7,7,92,84,61,49,82,24,69,0.68,17.25,1,0.69,1.0
4,4,21,88,68,90,72,15,35,81,3,0.50,10.25,0,0.00,1.0
5,5,65,24,32,2,2,93,95,1,55,0.95,12.75,0,0.00,1.0

# load the results to the optimizer

In [22]:
ax_client = hf.load_data_to_optimizer(iteration = n, norm_results = norm_results)
ax_client

[INFO 06-02 17:30:46] ax.service.ax_client: Starting optimization with verbose logging. To disable logging, set the `verbose_logging` argument to `False`. Note that float values in the logs are rounded to 6 decimal points.
[INFO 06-02 17:30:46] ax.service.ax_client: Completed trial 0 with data: {'micelle_drug_conc': (0.0, None), 'surfactant_conc': (0.77, None), 'complexity': (1.0, None)}.
[INFO 06-02 17:30:46] ax.service.ax_client: Completed trial 1 with data: {'micelle_drug_conc': (0.0, None), 'surfactant_conc': (0.3, None), 'complexity': (1.0, None)}.
[INFO 06-02 17:30:46] ax.service.ax_client: Completed trial 2 with data: {'micelle_drug_conc': (0.0, None), 'surfactant_conc': (0.14, None), 'complexity': (1.0, None)}.
[INFO 06-02 17:30:46] ax.service.ax_client: Completed trial 3 with data: {'micelle_drug_conc': (0.69, None), 'surfactant_conc': (0.68, None), 'complexity': (1.0, None)}.
[INFO 06-02 17:30:46] ax.service.ax_client: Completed trial 4 with data: {'micelle_drug_conc': (0.0, None), 'surfactant_conc': (0.5, None), 'complexity': (1.0, None)}.
[INFO 06-02 17:30:46] ax.service.ax_client: Completed trial 5 with data: {'micelle_drug_conc': (0.0, None), 'surfactant_conc': (0.95, None), 'complexity': (1.0, None)}.
[INFO 06-02 17:30:46] ax.service.ax_client: Saved JSON-serialized state of optimization to `optimizer/optimizer_0_loaded.json`.

AxClient(experiment=Experiment(drug_surfactant))