# import libraries

In [1]:
import pandas as pd
from ax.service.ax_client import AxClient, ObjectiveProperties
import matplotlib.pyplot as plt
from ax.modelbridge.registry import Models
from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy   
import time


import sys
sys.path.append('../')
import helper_functions as hf

/var/folders/hk/7jjnrbrj53n1t8_bmkhf0_k00000gn/T/ipykernel_74736/3307975217.py:5: DeprecationWarning: Please import from 'ax.generation_strategy.generation_strategy' instead of 'ax.modelbridge.generation_strategy'. The latter is deprecated and will be removed in a future release.
  from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy

# generate recommendations

In [2]:
n = hf.get_iteration_number()

for i in range(3):
    print("Very Important: Please Confirm the Iteration Number is Iteration " + str(n))

print()

list_of_drugs = ['IBP'] * 2 + ['LOV'] * 2 + ['GBC'] * 2 + ['CTZ'] * 2
for i in range(3):
    print("Very Important: Please Confirm the Drugs are: ", list_of_drugs)

Very Important: Please Confirm the Iteration Number is Iteration 1
Very Important: Please Confirm the Iteration Number is Iteration 1
Very Important: Please Confirm the Iteration Number is Iteration 1

Very Important: Please Confirm the Drugs are:  ['IBP', 'IBP', 'LOV', 'LOV', 'GBC', 'GBC', 'CTZ', 'CTZ']
Very Important: Please Confirm the Drugs are:  ['IBP', 'IBP', 'LOV', 'LOV', 'GBC', 'GBC', 'CTZ', 'CTZ']
Very Important: Please Confirm the Drugs are:  ['IBP', 'IBP', 'LOV', 'LOV', 'GBC', 'GBC', 'CTZ', 'CTZ']

In [3]:
time_start = time.time()


df_design, ax_client = hf.run_optimizer(current_iteration=n, drug_list= list_of_drugs,  bopt = 1)

time_end = time.time()
time_duration = round((time_end - time_start)/60,2)

print("Time taken for optimization: " + str(time_duration) + " mins")
print("Time taken for optimization: " + str(time_duration * 60) + " seconds")

[WARNING 07-11 09:02:40] ax.modelbridge.transforms.standardize_y: Outcome complexity is constant, within tolerance.
[WARNING 07-11 09:02:40] ax.modelbridge.transforms.standardize_y: Outcome success is constant, within tolerance.
[WARNING 07-11 09:02:40] ax.modelbridge.transforms.standardize_y: Outcome surfactant_input is constant, within tolerance.

**************************************************************************************************** 1  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Ibuprofen IBP  | Iteration:  1

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/botorch/models/utils/assorted.py:273: InputDataWarning: Data (outcome observations) is not standardized (std = tensor([0., 0., 0.], dtype=torch.float64), mean = tensor([0., 0., 0.], dtype=torch.float64)).Please consider scaling the input to zero mean and unit variance.
  check_standardization(Y=train_Y, raise_on_fail=raise_on_fail)
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:486: RuntimeWarning: divide by zero encountered in scalar divide
  inv_model_std_quality = max_std if max_std > 1 / min_std else min_std
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:489: RuntimeWarning: divide by zero encountered in scalar divide
  return 1 / inv_model_std_quality
[INFO 07-11 09:02:42] ax.service.ax_client: Generated new trial 8 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 100, 's2': 100, 's3': 0, 's4': 100, 's5': 0, 's6': 0, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100} using model BO_MIXED.
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
[WARNING 07-11 09:02:42] ax.modelbridge.transforms.standardize_y: Outcome complexity is constant, within tolerance.
[WARNING 07-11 09:02:42] ax.modelbridge.transforms.standardize_y: Outcome success is constant, within tolerance.
[WARNING 07-11 09:02:42] ax.modelbridge.transforms.standardize_y: Outcome surfactant_input is constant, within tolerance.

**************************************************************************************************** 2  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Ibuprofen IBP  | Iteration:  1

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:486: RuntimeWarning: divide by zero encountered in scalar divide
  inv_model_std_quality = max_std if max_std > 1 / min_std else min_std
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:489: RuntimeWarning: divide by zero encountered in scalar divide
  return 1 / inv_model_std_quality
[INFO 07-11 09:02:45] ax.service.ax_client: Generated new trial 9 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 0, 's2': 100, 's3': 100, 's4': 0, 's5': 100, 's6': 100, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100} using model BO_MIXED.
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
[WARNING 07-11 09:02:45] ax.modelbridge.transforms.standardize_y: Outcome complexity is constant, within tolerance.
[WARNING 07-11 09:02:45] ax.modelbridge.transforms.standardize_y: Outcome success is constant, within tolerance.
[WARNING 07-11 09:02:45] ax.modelbridge.transforms.standardize_y: Outcome surfactant_input is constant, within tolerance.

**************************************************************************************************** 3  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Lovastatin LOV  | Iteration:  1

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:486: RuntimeWarning: divide by zero encountered in scalar divide
  inv_model_std_quality = max_std if max_std > 1 / min_std else min_std
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:489: RuntimeWarning: divide by zero encountered in scalar divide
  return 1 / inv_model_std_quality
[INFO 07-11 09:02:48] ax.service.ax_client: Generated new trial 10 with parameters {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 's1': 0, 's2': 0, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 0, 's8': 4, 'surfactant_conc': 1, 'drug_conc': 100} using model BO_MIXED.
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
[WARNING 07-11 09:02:48] ax.modelbridge.transforms.standardize_y: Outcome complexity is constant, within tolerance.
[WARNING 07-11 09:02:48] ax.modelbridge.transforms.standardize_y: Outcome success is constant, within tolerance.
[WARNING 07-11 09:02:48] ax.modelbridge.transforms.standardize_y: Outcome surfactant_input is constant, within tolerance.

**************************************************************************************************** 4  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Lovastatin LOV  | Iteration:  1

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:486: RuntimeWarning: divide by zero encountered in scalar divide
  inv_model_std_quality = max_std if max_std > 1 / min_std else min_std
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:489: RuntimeWarning: divide by zero encountered in scalar divide
  return 1 / inv_model_std_quality
[INFO 07-11 09:02:50] ax.service.ax_client: Generated new trial 11 with parameters {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 's1': 0, 's2': 0, 's3': 100, 's4': 0, 's5': 100, 's6': 100, 's7': 0, 's8': 0, 'surfactant_conc': 1, 'drug_conc': 100} using model BO_MIXED.
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
[WARNING 07-11 09:02:50] ax.modelbridge.transforms.standardize_y: Outcome complexity is constant, within tolerance.
[WARNING 07-11 09:02:50] ax.modelbridge.transforms.standardize_y: Outcome success is constant, within tolerance.
[WARNING 07-11 09:02:50] ax.modelbridge.transforms.standardize_y: Outcome surfactant_input is constant, within tolerance.

**************************************************************************************************** 5  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Glibenclamide/Glyburide GBC  | Iteration:  1

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:486: RuntimeWarning: divide by zero encountered in scalar divide
  inv_model_std_quality = max_std if max_std > 1 / min_std else min_std
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:489: RuntimeWarning: divide by zero encountered in scalar divide
  return 1 / inv_model_std_quality
[INFO 07-11 09:02:53] ax.service.ax_client: Generated new trial 12 with parameters {'Drug_MW': 0.494, 'Drug_LogP': 0.3642, 'Drug_TPSA': 0.1136, 's1': 100, 's2': 0, 's3': 0, 's4': 100, 's5': 0, 's6': 0, 's7': 0, 's8': 0, 'surfactant_conc': 1, 'drug_conc': 100} using model BO_MIXED.
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
[WARNING 07-11 09:02:53] ax.modelbridge.transforms.standardize_y: Outcome complexity is constant, within tolerance.
[WARNING 07-11 09:02:53] ax.modelbridge.transforms.standardize_y: Outcome success is constant, within tolerance.
[WARNING 07-11 09:02:53] ax.modelbridge.transforms.standardize_y: Outcome surfactant_input is constant, within tolerance.

**************************************************************************************************** 6  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Glibenclamide/Glyburide GBC  | Iteration:  1

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:486: RuntimeWarning: divide by zero encountered in scalar divide
  inv_model_std_quality = max_std if max_std > 1 / min_std else min_std
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:489: RuntimeWarning: divide by zero encountered in scalar divide
  return 1 / inv_model_std_quality
[INFO 07-11 09:02:56] ax.service.ax_client: Generated new trial 13 with parameters {'Drug_MW': 0.494, 'Drug_LogP': 0.3642, 'Drug_TPSA': 0.1136, 's1': 100, 's2': 100, 's3': 0, 's4': 100, 's5': 0, 's6': 0, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100} using model BO_MIXED.
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
[WARNING 07-11 09:02:56] ax.modelbridge.transforms.standardize_y: Outcome complexity is constant, within tolerance.
[WARNING 07-11 09:02:56] ax.modelbridge.transforms.standardize_y: Outcome success is constant, within tolerance.
[WARNING 07-11 09:02:56] ax.modelbridge.transforms.standardize_y: Outcome surfactant_input is constant, within tolerance.

**************************************************************************************************** 7  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Clotrimazole CTZ  | Iteration:  1

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:486: RuntimeWarning: divide by zero encountered in scalar divide
  inv_model_std_quality = max_std if max_std > 1 / min_std else min_std
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:489: RuntimeWarning: divide by zero encountered in scalar divide
  return 1 / inv_model_std_quality
[INFO 07-11 09:02:58] ax.service.ax_client: Generated new trial 14 with parameters {'Drug_MW': 0.3448, 'Drug_LogP': 0.5377, 'Drug_TPSA': 0.0178, 's1': 100, 's2': 0, 's3': 0, 's4': 100, 's5': 0, 's6': 0, 's7': 0, 's8': 0, 'surfactant_conc': 1, 'drug_conc': 100} using model BO_MIXED.
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
[WARNING 07-11 09:02:58] ax.modelbridge.transforms.standardize_y: Outcome complexity is constant, within tolerance.
[WARNING 07-11 09:02:58] ax.modelbridge.transforms.standardize_y: Outcome success is constant, within tolerance.
[WARNING 07-11 09:02:58] ax.modelbridge.transforms.standardize_y: Outcome surfactant_input is constant, within tolerance.

**************************************************************************************************** 8  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Clotrimazole CTZ  | Iteration:  1

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:486: RuntimeWarning: divide by zero encountered in scalar divide
  inv_model_std_quality = max_std if max_std > 1 / min_std else min_std
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:489: RuntimeWarning: divide by zero encountered in scalar divide
  return 1 / inv_model_std_quality
[INFO 07-11 09:03:01] ax.service.ax_client: Generated new trial 15 with parameters {'Drug_MW': 0.3448, 'Drug_LogP': 0.5377, 'Drug_TPSA': 0.0178, 's1': 0, 's2': 0, 's3': 100, 's4': 0, 's5': 100, 's6': 100, 's7': 0, 's8': 0, 'surfactant_conc': 1, 'drug_conc': 100} using model BO_MIXED.

Time taken for optimization: 0.36 mins
Time taken for optimization: 21.599999999999998 seconds

# process results

In [5]:
ax_client = hf.load_design_optimizer(n)
ax_client.experiment.trials

{0: Trial(experiment_name='drug_surfactant', index=0, status=TrialStatus.COMPLETED, arm=Arm(name='0_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 47, 's2': 60, 's3': 49, 's4': 31, 's5': 96, 's6': 8, 's7': 9, 's8': 35, 'surfactant_conc': 86, 'drug_conc': 100})),
 1: Trial(experiment_name='drug_surfactant', index=1, status=TrialStatus.COMPLETED, arm=Arm(name='1_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 74, 's2': 0, 's3': 88, 's4': 66, 's5': 22, 's6': 52, 's7': 58, 's8': 79, 'surfactant_conc': 35, 'drug_conc': 100})),
 2: Trial(experiment_name='drug_surfactant', index=2, status=TrialStatus.COMPLETED, arm=Arm(name='2_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 's1': 78, 's2': 89, 's3': 1, 's4': 3, 's5': 32, 's6': 93, 's7': 44, 's8': 58, 'surfactant_conc': 1, 'drug_conc': 100})),
 3: Trial(experiment_name='drug_surfactant', index=3, status=TrialStatus.COMPLETED, arm=Arm(name='3_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 's1': 0, 's2': 46, 's3': 61, 's4': 95, 's5': 62, 's6': 50, 's7': 98, 's8': 0, 'surfactant_conc': 52, 'drug_conc': 100})),
 4: Trial(experiment_name='drug_surfactant', index=4, status=TrialStatus.COMPLETED, arm=Arm(name='4_0', parameters={'Drug_MW': 0.494, 'Drug_LogP': 0.3642, 'Drug_TPSA': 0.1136, 's1': 16, 's2': 82, 's3': 86, 's4': 84, 's5': 71, 's6': 23, 's7': 35, 's8': 64, 'surfactant_conc': 21, 'drug_conc': 100})),
 5: Trial(experiment_name='drug_surfactant', index=5, status=TrialStatus.COMPLETED, arm=Arm(name='5_0', parameters={'Drug_MW': 0.494, 'Drug_LogP': 0.3642, 'Drug_TPSA': 0.1136, 's1': 93, 's2': 27, 's3': 26, 's4': 18, 's5': 47, 's6': 67, 's7': 83, 's8': 22, 'surfactant_conc': 71, 'drug_conc': 100})),
 6: Trial(experiment_name='drug_surfactant', index=6, status=TrialStatus.COMPLETED, arm=Arm(name='6_0', parameters={'Drug_MW': 0.3448, 'Drug_LogP': 0.5377, 'Drug_TPSA': 0.0178, 's1': 59, 's2': 65, 's3': 62, 's4': 55, 's5': 7, 's6': 76, 's7': 19, 's8': 43, 'surfactant_conc': 93, 'drug_conc': 100})),
 7: Trial(experiment_name='drug_surfactant', index=7, status=TrialStatus.COMPLETED, arm=Arm(name='7_0', parameters={'Drug_MW': 0.3448, 'Drug_LogP': 0.5377, 'Drug_TPSA': 0.0178, 's1': 31, 's2': 20, 's3': 25, 's4': 46, 's5': 87, 's6': 31, 's7': 74, 's8': 99, 'surfactant_conc': 44, 'drug_conc': 100})),
 8: Trial(experiment_name='drug_surfactant', index=8, status=TrialStatus.RUNNING, arm=Arm(name='8_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 100, 's2': 100, 's3': 0, 's4': 100, 's5': 0, 's6': 0, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 9: Trial(experiment_name='drug_surfactant', index=9, status=TrialStatus.RUNNING, arm=Arm(name='9_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 0, 's2': 0, 's3': 100, 's4': 0, 's5': 100, 's6': 100, 's7': 0, 's8': 0, 'surfactant_conc': 1, 'drug_conc': 100})),
 10: Trial(experiment_name='drug_surfactant', index=10, status=TrialStatus.RUNNING, arm=Arm(name='10_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 's1': 100, 's2': 100, 's3': 0, 's4': 100, 's5': 0, 's6': 0, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 11: Trial(experiment_name='drug_surfactant', index=11, status=TrialStatus.RUNNING, arm=Arm(name='11_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 's1': 0, 's2': 100, 's3': 100, 's4': 0, 's5': 0, 's6': 0, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 12: Trial(experiment_name='drug_surfactant', index=12, status=TrialStatus.RUNNING, arm=Arm(name='12_0', parameters={'Drug_MW': 0.494, 'Drug_LogP': 0.3642, 'Drug_TPSA': 0.1136, 's1': 0, 's2': 0, 's3': 0, 's4': 100, 's5': 0, 's6': 0, 's7': 0, 's8': 0, 'surfactant_conc': 1, 'drug_conc': 100})),
 13: Trial(experiment_name='drug_surfactant', index=13, status=TrialStatus.RUNNING, arm=Arm(name='13_0', parameters={'Drug_MW': 0.494, 'Drug_LogP': 0.3642, 'Drug_TPSA': 0.1136, 's1': 0, 's2': 100, 's3': 100, 's4': 0, 's5': 100, 's6': 100, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 14: Trial(experiment_name='drug_surfactant', index=14, status=TrialStatus.RUNNING, arm=Arm(name='14_0', parameters={'Drug_MW': 0.3448, 'Drug_LogP': 0.5377, 'Drug_TPSA': 0.0178, 's1': 100, 's2': 0, 's3': 0, 's4': 100, 's5': 0, 's6': 0, 's7': 0, 's8': 0, 'surfactant_conc': 1, 'drug_conc': 100})),
 15: Trial(experiment_name='drug_surfactant', index=15, status=TrialStatus.RUNNING, arm=Arm(name='15_0', parameters={'Drug_MW': 0.3448, 'Drug_LogP': 0.5377, 'Drug_TPSA': 0.0178, 's1': 100, 's2': 100, 's3': 0, 's4': 100, 's5': 0, 's6': 0, 's7': 100, 's8': 0, 'surfactant_conc': 1, 'drug_conc': 100}))}

In [6]:
df_conc, df_vol = hf.design_to_conc_to_vol (n)

In [6]:
plate_well = input("Enter the plate well starting well (e.g., F1): ")
deepplate_well = input("Enter the deep plate well starting well (e.g., F1): ")


print("Please confirm the following information:")
print("Wellplate will start at: " + plate_well)
print("Deep plate will start at: " + deepplate_well)

print()
print("*******************************************************")
print("Continue if correct, or rerun this cell if incorrect.")
print("*******************************************************")

Please confirm the following information:
Wellplate will start at: H1
Deep plate will start at: J1

*******************************************************
Continue if correct, or rerun this cell if incorrect.
*******************************************************

In [11]:
hf.generate_protocol(df_vol=df_vol, iteration=n, plate_well=plate_well, deepplate_well=deepplate_well)

✅ Successfully wrote to: protocol/otflex_1.py

In [7]:
df_absorbance = hf.process_absorbance(iteration=n, threshold=0.1)
df_absorbance

   trial_index  success
0            0        1
1            1        0
2            2        1
3            3        0
4            4        1
5            5        0
6            6        1
7            7        0

In [8]:
results = hf.build_results(n, df_conc, df_absorbance)
results

,trial_index,drug_name,s1,s2,s3,s4,s5,s6,s7,s8,surfactant_input,drug_conc,success,complexity
0,8,IBP,100,100,0,100,0,0,100,100,50.0,25.0,1,5
1,9,IBP,0,0,100,0,100,100,0,0,0.5,25.0,0,3
2,10,LOV,100,100,0,100,0,0,100,100,50.0,25.0,1,5
3,11,LOV,0,100,100,0,0,0,100,100,50.0,25.0,0,4
4,12,GBC,0,0,0,100,0,0,0,0,0.5,25.0,1,1
5,13,GBC,0,100,100,0,100,100,100,100,50.0,25.0,0,6
6,14,CTZ,100,0,0,100,0,0,0,0,0.5,25.0,1,2
7,15,CTZ,100,100,0,100,0,0,100,0,0.5,25.0,0,4

In [9]:
norm_results = hf.normalize_data(results, 'normalize')

In [10]:
norm_results

,trial_index,drug_name,s1,s2,s3,s4,s5,s6,s7,s8,surfactant_input,drug_conc,success,complexity
0,8,IBP,100,100,0,100,0,0,100,100,1.00,1.0,1.0,0.625
1,9,IBP,0,0,100,0,100,100,0,0,0.01,1.0,0.0,0.375
2,10,LOV,100,100,0,100,0,0,100,100,1.00,1.0,1.0,0.625
3,11,LOV,0,100,100,0,0,0,100,100,1.00,1.0,0.0,0.500
4,12,GBC,0,0,0,100,0,0,0,0,0.01,1.0,1.0,0.125
5,13,GBC,0,100,100,0,100,100,100,100,1.00,1.0,0.0,0.750
6,14,CTZ,100,0,0,100,0,0,0,0,0.01,1.0,1.0,0.250
7,15,CTZ,100,100,0,100,0,0,100,0,0.01,1.0,0.0,0.500

# load the results to the optimizer

In [11]:
ax_client = hf.load_data_to_optimizer(iteration = n, norm_results = norm_results)
ax_client

[INFO 07-11 08:55:35] ax.service.ax_client: Completed trial 8 with data: {'success': (1.0, None), 'surfactant_input': (1.0, None), 'complexity': (0.625, None)}.
[INFO 07-11 08:55:35] ax.service.ax_client: Completed trial 9 with data: {'success': (0.0, None), 'surfactant_input': (1.0, None), 'complexity': (1.0, None)}.
[INFO 07-11 08:55:35] ax.service.ax_client: Completed trial 10 with data: {'success': (1.0, None), 'surfactant_input': (1.0, None), 'complexity': (0.625, None)}.
[INFO 07-11 08:55:35] ax.service.ax_client: Completed trial 11 with data: {'success': (0.0, None), 'surfactant_input': (1.0, None), 'complexity': (1.0, None)}.
[INFO 07-11 08:55:35] ax.service.ax_client: Completed trial 12 with data: {'success': (1.0, None), 'surfactant_input': (0.01, None), 'complexity': (0.125, None)}.
[INFO 07-11 08:55:35] ax.service.ax_client: Completed trial 13 with data: {'success': (0.0, None), 'surfactant_input': (1.0, None), 'complexity': (1.0, None)}.
[INFO 07-11 08:55:35] ax.service.ax_client: Completed trial 14 with data: {'success': (1.0, None), 'surfactant_input': (0.01, None), 'complexity': (0.25, None)}.
[INFO 07-11 08:55:35] ax.service.ax_client: Completed trial 15 with data: {'success': (0.0, None), 'surfactant_input': (1.0, None), 'complexity': (1.0, None)}.

Trial 8: success=1 → using surfactant_input=1.0, complexity=0.625
Trial 9: success=0 → overriding surfactant_input & complexity to 1
Trial 10: success=1 → using surfactant_input=1.0, complexity=0.625
Trial 11: success=0 → overriding surfactant_input & complexity to 1
Trial 12: success=1 → using surfactant_input=0.01, complexity=0.125
Trial 13: success=0 → overriding surfactant_input & complexity to 1
Trial 14: success=1 → using surfactant_input=0.01, complexity=0.25
Trial 15: success=0 → overriding surfactant_input & complexity to 1

AxClient(experiment=Experiment(drug_surfactant))