# import libraries

In [1]:
import pandas as pd
from ax.service.ax_client import AxClient, ObjectiveProperties
import matplotlib.pyplot as plt
from ax.modelbridge.factory import Models
from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy   


import sys
sys.path.append('../')
import helper_functions as hf

# initialize the optimizer

In [2]:
ax_client_init_file_name = 'optimizer/optimizer_00.json'
ax_client = hf.optimizer_init()
ax_client

[INFO 06-17 15:37:16] ax.service.ax_client: Starting optimization with verbose logging. To disable logging, set the `verbose_logging` argument to `False`. Note that float values in the logs are rounded to 6 decimal points.
[INFO 06-17 15:37:16] ax.service.utils.instantiation: Due to non-specification, we will use the heuristic for selecting objective thresholds.
[INFO 06-17 15:37:16] ax.service.utils.instantiation: Created search space: SearchSpace(parameters=[RangeParameter(name='s1', parameter_type=INT, range=[0, 100]), RangeParameter(name='s2', parameter_type=INT, range=[0, 100]), RangeParameter(name='s3', parameter_type=INT, range=[0, 100]), RangeParameter(name='s4', parameter_type=INT, range=[0, 100]), RangeParameter(name='s5', parameter_type=INT, range=[0, 100]), RangeParameter(name='s6', parameter_type=INT, range=[0, 100]), RangeParameter(name='s7', parameter_type=INT, range=[0, 100]), RangeParameter(name='s8', parameter_type=INT, range=[0, 100]), RangeParameter(name='surfactant_conc', parameter_type=INT, range=[1, 100]), RangeParameter(name='drug_conc', parameter_type=INT, range=[1, 100])], parameter_constraints=[]).

AxClient(experiment=Experiment(drug_surfactant))

In [3]:
ax_client.save_to_json_file(ax_client_init_file_name)

[INFO 06-17 15:37:19] ax.service.ax_client: Saved JSON-serialized state of optimization to `optimizer/optimizer_00.json`.

# generate recommendations

In [4]:
n = hf.get_iteration_number()

for i in range(3):
    print("Very Important: Please Confirm the Iteration Number is Iteration " + str(n))

Very Important: Please Confirm the Iteration Number is Iteration 0
Very Important: Please Confirm the Iteration Number is Iteration 0
Very Important: Please Confirm the Iteration Number is Iteration 0

In [5]:
df_design, ax_client = hf.run_optimizer(current_iteration=n, n_trials=6)

[INFO 06-17 15:37:23] ax.service.ax_client: Starting optimization with verbose logging. To disable logging, set the `verbose_logging` argument to `False`. Note that float values in the logs are rounded to 6 decimal points.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 06-17 15:37:23] ax.service.ax_client: Generated new trial 0 with parameters {'s1': 47, 's2': 59, 's3': 49, 's4': 31, 's5': 96, 's6': 8, 's7': 9, 's8': 35, 'surfactant_conc': 85, 'drug_conc': 77} using model Sobol.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 06-17 15:37:23] ax.service.ax_client: Generated new trial 1 with parameters {'s1': 95, 's2': 22, 's3': 76, 's4': 63, 's5': 42, 's6': 71, 's7': 55, 's8': 99, 'surfactant_conc': 35, 'drug_conc': 3} using model Sobol.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 06-17 15:37:23] ax.service.ax_client: Generated new trial 2 with parameters {'s1': 52, 's2': 98, 's3': 4, 's4': 13, 's5': 22, 's6': 89, 's7': 28, 's8': 56, 'surfactant_conc': 18, 'drug_conc': 33} using model Sobol.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 06-17 15:37:23] ax.service.ax_client: Generated new trial 3 with parameters {'s1': 6, 's2': 33, 's3': 71, 's4': 83, 's5': 63, 's6': 25, 's7': 87, 's8': 16, 'surfactant_conc': 68, 'drug_conc': 59} using model Sobol.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 06-17 15:37:23] ax.service.ax_client: Generated new trial 4 with parameters {'s1': 25, 's2': 86, 's3': 97, 's4': 99, 's5': 58, 's6': 17, 's7': 47, 's8': 64, 'surfactant_conc': 1, 'drug_conc': 24} using model Sobol.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 06-17 15:37:23] ax.service.ax_client: Generated new trial 5 with parameters {'s1': 72, 's2': 45, 's3': 28, 's4': 4, 's5': 5, 's6': 54, 's7': 93, 's8': 2, 'surfactant_conc': 51, 'drug_conc': 99} using model Sobol.
[INFO 06-17 15:37:23] ax.service.ax_client: Saved JSON-serialized state of optimization to `optimizer/optimizer_0.json`.

# process results

In [6]:
ax_client = hf.load_design_optimizer(n)
ax_client.experiment.trials

[INFO 06-17 15:37:28] ax.service.ax_client: Starting optimization with verbose logging. To disable logging, set the `verbose_logging` argument to `False`. Note that float values in the logs are rounded to 6 decimal points.

{0: Trial(experiment_name='drug_surfactant', index=0, status=TrialStatus.RUNNING, arm=Arm(name='0_0', parameters={'s1': 47, 's2': 59, 's3': 49, 's4': 31, 's5': 96, 's6': 8, 's7': 9, 's8': 35, 'surfactant_conc': 85, 'drug_conc': 77})),
 1: Trial(experiment_name='drug_surfactant', index=1, status=TrialStatus.RUNNING, arm=Arm(name='1_0', parameters={'s1': 95, 's2': 22, 's3': 76, 's4': 63, 's5': 42, 's6': 71, 's7': 55, 's8': 99, 'surfactant_conc': 35, 'drug_conc': 3})),
 2: Trial(experiment_name='drug_surfactant', index=2, status=TrialStatus.RUNNING, arm=Arm(name='2_0', parameters={'s1': 52, 's2': 98, 's3': 4, 's4': 13, 's5': 22, 's6': 89, 's7': 28, 's8': 56, 'surfactant_conc': 18, 'drug_conc': 33})),
 3: Trial(experiment_name='drug_surfactant', index=3, status=TrialStatus.RUNNING, arm=Arm(name='3_0', parameters={'s1': 6, 's2': 33, 's3': 71, 's4': 83, 's5': 63, 's6': 25, 's7': 87, 's8': 16, 'surfactant_conc': 68, 'drug_conc': 59})),
 4: Trial(experiment_name='drug_surfactant', index=4, status=TrialStatus.RUNNING, arm=Arm(name='4_0', parameters={'s1': 25, 's2': 86, 's3': 97, 's4': 99, 's5': 58, 's6': 17, 's7': 47, 's8': 64, 'surfactant_conc': 1, 'drug_conc': 24})),
 5: Trial(experiment_name='drug_surfactant', index=5, status=TrialStatus.RUNNING, arm=Arm(name='5_0', parameters={'s1': 72, 's2': 45, 's3': 28, 's4': 4, 's5': 5, 's6': 54, 's7': 93, 's8': 2, 'surfactant_conc': 51, 'drug_conc': 99}))}

In [7]:
df_conc, df_vol = hf.design_to_conc_to_vol (n)

In [8]:
plate_well = input("Enter the plate well starting well (e.g., F1): ")
deepplate_well = input("Enter the deep plate well starting well (e.g., F1): ")


print("Please confirm the following information:")
print("Wellplate will start at: " + plate_well)
print("Deep plate will start at: " + deepplate_well)

print()
print("*******************************************************")
print("Continue if correct, or rerun this cell if incorrect.")
print("*******************************************************")

Please confirm the following information:
Wellplate will start at: C1
Deep plate will start at: F1

*******************************************************
Continue if correct, or rerun this cell if incorrect.
*******************************************************

In [9]:

hf.generate_protocol(df_vol=df_vol, iteration=n, plate_well=plate_well, deepplate_well=deepplate_well)

✅ Successfully wrote to: protocol/otflex_0.py

In [10]:
df_absorbance = hf.process_absorbance(iteration=n)
df_absorbance

   trial_index  success
0            0        0
1            1        0
2            2        0
3            3        0
4            4        0
5            5        0

In [11]:
results = hf.build_results(n, df_conc, df_absorbance)

In [12]:
results

,trial_index,s1,s2,s3,s4,s5,s6,s7,s8,surfactant_conc,drug_conc,success,micelle_drug_conc,complexity
0,0,47,59,49,31,96,8,9,35,42.5,19.25,0,0.0,8
1,1,95,22,76,63,42,71,55,99,17.5,0.75,0,0.0,8
2,2,52,98,4,13,22,89,28,56,9.0,8.25,0,0.0,8
3,3,6,33,71,83,63,25,87,16,34.0,14.75,0,0.0,8
4,4,25,86,97,99,58,17,47,64,0.5,6.00,0,0.0,8
5,5,72,45,28,4,5,54,93,2,25.5,24.75,0,0.0,8

In [13]:
norm_results = hf.normalize_data(results, 'normalize')

In [14]:
norm_results

,trial_index,s1,s2,s3,s4,s5,s6,s7,s8,surfactant_conc,drug_conc,success,micelle_drug_conc,complexity
0,0,47,59,49,31,96,8,9,35,0.85,19.25,0,0.0,1.0
1,1,95,22,76,63,42,71,55,99,0.35,0.75,0,0.0,1.0
2,2,52,98,4,13,22,89,28,56,0.18,8.25,0,0.0,1.0
3,3,6,33,71,83,63,25,87,16,0.68,14.75,0,0.0,1.0
4,4,25,86,97,99,58,17,47,64,0.01,6.00,0,0.0,1.0
5,5,72,45,28,4,5,54,93,2,0.51,24.75,0,0.0,1.0

# load the results to the optimizer

In [15]:
ax_client = hf.load_data_to_optimizer(iteration = n, norm_results = norm_results)
ax_client

[INFO 06-17 16:42:19] ax.service.ax_client: Starting optimization with verbose logging. To disable logging, set the `verbose_logging` argument to `False`. Note that float values in the logs are rounded to 6 decimal points.
[INFO 06-17 16:42:19] ax.service.ax_client: Completed trial 0 with data: {'micelle_drug_conc': (0.0, None), 'surfactant_conc': (0.85, None), 'complexity': (1.0, None)}.
[INFO 06-17 16:42:19] ax.service.ax_client: Completed trial 1 with data: {'micelle_drug_conc': (0.0, None), 'surfactant_conc': (0.35, None), 'complexity': (1.0, None)}.
[INFO 06-17 16:42:19] ax.service.ax_client: Completed trial 2 with data: {'micelle_drug_conc': (0.0, None), 'surfactant_conc': (0.18, None), 'complexity': (1.0, None)}.
[INFO 06-17 16:42:19] ax.service.ax_client: Completed trial 3 with data: {'micelle_drug_conc': (0.0, None), 'surfactant_conc': (0.68, None), 'complexity': (1.0, None)}.
[INFO 06-17 16:42:19] ax.service.ax_client: Completed trial 4 with data: {'micelle_drug_conc': (0.0, None), 'surfactant_conc': (0.01, None), 'complexity': (1.0, None)}.
[INFO 06-17 16:42:19] ax.service.ax_client: Completed trial 5 with data: {'micelle_drug_conc': (0.0, None), 'surfactant_conc': (0.51, None), 'complexity': (1.0, None)}.
[INFO 06-17 16:42:19] ax.service.ax_client: Saved JSON-serialized state of optimization to `optimizer/optimizer_0_loaded.json`.

AxClient(experiment=Experiment(drug_surfactant))