# import libraries

In [1]:
import pandas as pd
from ax.service.ax_client import AxClient, ObjectiveProperties
import matplotlib.pyplot as plt
from ax.modelbridge.registry import Models
from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy   
import time


import sys
sys.path.append('../')
import helper_functions as hf

/var/folders/hk/7jjnrbrj53n1t8_bmkhf0_k00000gn/T/ipykernel_30666/3307975217.py:5: DeprecationWarning: Please import from 'ax.generation_strategy.generation_strategy' instead of 'ax.modelbridge.generation_strategy'. The latter is deprecated and will be removed in a future release.
  from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy

# generate recommendations

In [2]:
n = hf.get_iteration_number()

for i in range(3):
    print("Very Important: Please Confirm the Iteration Number is Iteration " + str(n))

print()

list_of_drugs = (['IBP']  + ['LOV']  + ['DCF']  + ['GLV']) * 2

for i in range(3):
    print("Very Important: Please Confirm the Drugs are: ", list_of_drugs)

Very Important: Please Confirm the Iteration Number is Iteration 4
Very Important: Please Confirm the Iteration Number is Iteration 4
Very Important: Please Confirm the Iteration Number is Iteration 4

Very Important: Please Confirm the Drugs are:  ['IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV']
Very Important: Please Confirm the Drugs are:  ['IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV']
Very Important: Please Confirm the Drugs are:  ['IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV']

In [3]:
time_start = time.time()


df_design, ax_client, data_so_far, best_concs = hf.run_optimizer(current_iteration=n, drug_list= list_of_drugs,  bopt = 1)

time_end = time.time()
time_duration = round((time_end - time_start)/60,2)

print("Time taken for optimization: " + str(time_duration) + " mins")
print("Time taken for optimization: " + str(time_duration * 60) + " seconds")

******************************************************************************** 1/8 ********************************************************************************

更新约束 (drug=IBP)：surf_1_conc+surf_2_conc <= 34.0，>=1

[INFO 07-31 07:49:37] ax.service.ax_client: Generated new trial 56 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 14, 'surf_2_conc': 18, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's6'} using model BoTorch.
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

******************************************************************************** 2/8 ********************************************************************************

更新约束 (drug=LOV)：surf_1_conc+surf_2_conc <= 29.0，>=1

[INFO 07-31 07:49:46] ax.service.ax_client: Generated new trial 57 with parameters {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 0, 'surf_2_conc': 29, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's8'} using model BoTorch.
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

******************************************************************************** 3/8 ********************************************************************************

更新约束 (drug=DCF)：surf_1_conc+surf_2_conc <= 31.0，>=1

[INFO 07-31 07:49:51] ax.service.ax_client: Generated new trial 58 with parameters {'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 17, 'surf_2_conc': 13, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's6'} using model BoTorch.
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

******************************************************************************** 4/8 ********************************************************************************

更新约束 (drug=GLV)：surf_1_conc+surf_2_conc <= 53.0，>=1

[INFO 07-31 07:50:00] ax.service.ax_client: Generated new trial 59 with parameters {'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 0, 'surf_2_conc': 53, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's8'} using model BoTorch.
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

******************************************************************************** 5/8 ********************************************************************************

更新约束 (drug=IBP)：surf_1_conc+surf_2_conc <= 34.0，>=1

[INFO 07-31 07:50:05] ax.service.ax_client: Generated new trial 60 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 21, 'surf_2_conc': 13, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's6'} using model BoTorch.
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

******************************************************************************** 6/8 ********************************************************************************

更新约束 (drug=LOV)：surf_1_conc+surf_2_conc <= 29.0，>=1

[INFO 07-31 07:50:14] ax.service.ax_client: Generated new trial 61 with parameters {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 0, 'surf_2_conc': 29, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's8'} using model BoTorch.
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

******************************************************************************** 7/8 ********************************************************************************

更新约束 (drug=DCF)：surf_1_conc+surf_2_conc <= 31.0，>=1

[INFO 07-31 07:50:19] ax.service.ax_client: Generated new trial 62 with parameters {'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 22, 'surf_2_conc': 7, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's6'} using model BoTorch.
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

******************************************************************************** 8/8 ********************************************************************************

更新约束 (drug=GLV)：surf_1_conc+surf_2_conc <= 53.0，>=1

[INFO 07-31 07:50:29] ax.service.ax_client: Generated new trial 63 with parameters {'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 0, 'surf_2_conc': 53, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's8'} using model BoTorch.

Time taken for optimization: 0.94 mins
Time taken for optimization: 56.4 seconds

In [5]:
best_concs

{'IBP': 35.0, 'LOV': 30.0, 'DCF': 32.0, 'GLV': 54.0}

# process results

In [6]:
ax_client = hf.load_design_optimizer(n)
ax_client.get_trials_data_frame()

/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

,trial_index,arm_name,trial_status,generation_node,obj_surf_conc,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,drug_conc,surf_1,surf_2
0,0,0_0,COMPLETED,GenerationStep_0,35.0,0.2063,0.3073,0.0373,29,6,25.0,s7,s6
1,1,1_0,COMPLETED,GenerationStep_0,50.0,0.4045,0.4196,0.0728,6,44,25.0,s4,s4
2,2,2_0,COMPLETED,GenerationStep_0,100.0,0.2962,0.4364,0.0493,4,27,25.0,s2,s6
3,3,3_0,COMPLETED,GenerationStep_0,92.0,0.3528,0.2810,0.0711,91,1,25.0,s1,s2
4,4,4_0,COMPLETED,GenerationStep_0,46.0,0.2063,0.3073,0.0373,32,14,25.0,s3,s4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,59,59_0,RUNNING,GenerationStep_1,NaN,0.3528,0.2810,0.0711,0,53,25.0,s4,s8
60,60,60_0,RUNNING,GenerationStep_1,NaN,0.2063,0.3073,0.0373,21,13,25.0,s7,s6
61,61,57_0,RUNNING,GenerationStep_1,NaN,0.4045,0.4196,0.0728,0,29,25.0,s4,s8
62,62,62_0,RUNNING,GenerationStep_1,NaN,0.2962,0.4364,0.0493,22,7,25.0,s7,s6
63,63,59_0,RUNNING,GenerationStep_1,NaN,0.3528,0.2810,0.0711,0,53,25.0,s4,s8

In [8]:
df_design, df_vol = hf.design_to_vol (n)
df_design['constraint'] = df_design['drug_name'].map(best_concs).fillna(0.0)
df_design

,trial_index,drug_name,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,drug_conc,surf_1,surf_2,surf_conc,obj_surf_conc,constraint
0,56,IBP,0.2063,0.3073,0.0373,14,18,25.0,s7,s6,32,NaN,35.0
1,57,LOV,0.4045,0.4196,0.0728,0,29,25.0,s4,s8,29,NaN,30.0
2,58,DCF,0.2962,0.4364,0.0493,17,13,25.0,s7,s6,30,NaN,32.0
3,59,GLV,0.3528,0.2810,0.0711,0,53,25.0,s4,s8,53,NaN,54.0
4,60,IBP,0.2063,0.3073,0.0373,21,13,25.0,s7,s6,34,NaN,35.0
5,61,LOV,0.4045,0.4196,0.0728,0,29,25.0,s4,s8,29,NaN,30.0
6,62,DCF,0.2962,0.4364,0.0493,22,7,25.0,s7,s6,29,NaN,32.0
7,63,GLV,0.3528,0.2810,0.0711,0,53,25.0,s4,s8,53,NaN,54.0

In [9]:
df_vol

,trial_index,drug_name,drug,s1,s2,s3,s4,s5,s6,s7,s8,dmso,water,IBP,LOV,DCF,GLV
0,56,IBP,180.0,0.0,0.0,0.0,0.0,0.0,216.0,168.0,0.0,0.0,816.0,180.0,0.0,0.0,0.0
1,57,LOV,180.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,348.0,0.0,852.0,0.0,180.0,0.0,0.0
2,58,DCF,180.0,0.0,0.0,0.0,0.0,0.0,156.0,204.0,0.0,0.0,840.0,0.0,0.0,180.0,0.0
3,59,GLV,180.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,636.0,0.0,564.0,0.0,0.0,0.0,180.0
4,60,IBP,180.0,0.0,0.0,0.0,0.0,0.0,156.0,252.0,0.0,0.0,792.0,180.0,0.0,0.0,0.0
5,61,LOV,180.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,348.0,0.0,852.0,0.0,180.0,0.0,0.0
6,62,DCF,180.0,0.0,0.0,0.0,0.0,0.0,84.0,264.0,0.0,0.0,852.0,0.0,0.0,180.0,0.0
7,63,GLV,180.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,636.0,0.0,564.0,0.0,0.0,0.0,180.0

In [10]:
df_vol[['s1', 's2', 's3', 's4', 's5', 's6', 's7', 's8']].sum()

s1       0.0
s2       0.0
s3       0.0
s4       0.0
s5       0.0
s6     612.0
s7     888.0
s8    1968.0
dtype: float64

In [11]:
plate_well = input("Enter the plate well starting well (e.g., F1): ")
deepplate_well = input("Enter the deep plate well starting well (e.g., F1): ")


print("Please confirm the following information:")
print("Wellplate will start at: " + plate_well)
print("Deep plate will start at: " + deepplate_well)

print()
print("*******************************************************")
print("Continue if correct, or rerun this cell if incorrect.")
print("*******************************************************")

Please confirm the following information:
Wellplate will start at:
Deep plate will start at:

*******************************************************
Continue if correct, or rerun this cell if incorrect.
*******************************************************

In [9]:
hf.generate_protocol(df_vol=df_vol, iteration=n, plate_well=plate_well, deepplate_well=deepplate_well)

✅ Successfully wrote to: protocol/otflex_4.py

In [12]:
df_absorbance = hf.process_absorbance(iteration=n, threshold=0.06)
df_absorbance

   trial_index  success
0            0        1
1            1        0
2            2        1
3            3        1
4            4        1
5            5        0
6            6        1
7            7        1

In [13]:
results = hf.build_results(n, df_absorbance)
results

,trial_index,drug_name,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,drug_conc,surf_1,surf_2,surf_conc,obj_surf_conc,success
0,56,IBP,0.2063,0.3073,0.0373,14,18,25.0,s7,s6,32,32,1
1,57,LOV,0.4045,0.4196,0.0728,0,29,25.0,s4,s8,29,100,0
2,58,DCF,0.2962,0.4364,0.0493,17,13,25.0,s7,s6,30,30,1
3,59,GLV,0.3528,0.2810,0.0711,0,53,25.0,s4,s8,53,53,1
4,60,IBP,0.2063,0.3073,0.0373,21,13,25.0,s7,s6,34,34,1
5,61,LOV,0.4045,0.4196,0.0728,0,29,25.0,s4,s8,29,100,0
6,62,DCF,0.2962,0.4364,0.0493,22,7,25.0,s7,s6,29,29,1
7,63,GLV,0.3528,0.2810,0.0711,0,53,25.0,s4,s8,53,53,1

# load the results to the optimizer

In [14]:
ax_client = hf.load_data_to_optimizer(iteration = n, results = results)
ax_client

[INFO 07-31 07:54:55] ax.service.ax_client: Completed trial 56 with data: {'obj_surf_conc': (32.0, None)}.
[INFO 07-31 07:54:55] ax.service.ax_client: Completed trial 57 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 07:54:55] ax.service.ax_client: Completed trial 58 with data: {'obj_surf_conc': (30.0, None)}.
[INFO 07-31 07:54:55] ax.service.ax_client: Completed trial 59 with data: {'obj_surf_conc': (53.0, None)}.
[INFO 07-31 07:54:55] ax.service.ax_client: Completed trial 60 with data: {'obj_surf_conc': (34.0, None)}.
[INFO 07-31 07:54:55] ax.service.ax_client: Completed trial 61 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-31 07:54:55] ax.service.ax_client: Completed trial 62 with data: {'obj_surf_conc': (29.0, None)}.
[INFO 07-31 07:54:55] ax.service.ax_client: Completed trial 63 with data: {'obj_surf_conc': (53.0, None)}.

AxClient(experiment=Experiment(drug_surfactant))