# import libraries

In [2]:
import pandas as pd
from ax.service.ax_client import AxClient, ObjectiveProperties
import matplotlib.pyplot as pltF
from ax.modelbridge.registry import Models
from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy   
import time

import sys
sys.path.append('../')
import helper_functions as hf

ModuleNotFoundError: No module named 'ax.modelbridge'

# initialize the optimizer

In [ ]:
ax_client_init_file_name = 'optimizer/optimizer_00.json'
ax_client = hf.optimizer_init()
ax_client

[INFO 11-24 11:10:14] ax.service.utils.instantiation: Inferred value type of ParameterType.STRING for parameter surf_1. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
c:\Users\yunhe\anaconda3\envs\drug_surfactant\Lib\site-packages\ax\service\utils\instantiation.py:258: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "surf_1". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return ChoiceParameter(
[INFO 11-24 11:10:14] ax.service.utils.instantiation: Inferred value type of ParameterType.STRING for parameter surf_2. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
c:\Users\yunhe\anaconda3\envs\drug_surfactant\Lib\site-packages\ax\service\utils\instantiation.py:258: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "surf_2". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return ChoiceParameter(

AxClient(experiment=Experiment(drug_surfactant))

In [ ]:
ax_client.save_to_json_file(ax_client_init_file_name)

# generate recommendations

In [ ]:
n = hf.get_iteration_number()

for i in range(3):
    print("Very Important: Please Confirm the Iteration Number is Iteration " + str(n))

print()

list_of_drugs = (['IBP'])*32 #+ ['LOV']  + ['DCF']  + ['GLV'] ) * 

for i in range(3):
    print("Very Important: Please Confirm the Drugs are: ", list_of_drugs)

Very Important: Please Confirm the Iteration Number is Iteration 0
Very Important: Please Confirm the Iteration Number is Iteration 0
Very Important: Please Confirm the Iteration Number is Iteration 0

Very Important: Please Confirm the Drugs are:  ['IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP']
Very Important: Please Confirm the Drugs are:  ['IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP']
Very Important: Please Confirm the Drugs are:  ['IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP', 'IBP']

In [ ]:
time_start = time.time()



df_design, ax_client,_,_ = hf.run_optimizer(current_iteration=n, drug_list= list_of_drugs, bopt=0)

time_end = time.time()
time_duration = round((time_end - time_start)/60,2)

print("Time taken for optimization: " + str(time_duration) + " mins")
print("Time taken for optimization: " + str(time_duration * 60) + " seconds")

******************************************************************************** 1/32 ********************************************************************************

[WARNING 11-24 11:10:15] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.7027725810185075, 'surf_1_OH_PARAM__1': 0.3893421981483698, 'surf_1_OH_PARAM__2': 0.5738334404304624, 'surf_1_OH_PARAM__3': 0.7244136435911059, 'surf_1_OH_PARAM__4': 0.3094446621835232, 'surf_1_OH_PARAM__5': 0.6977694006636739, 'surf_1_OH_PARAM__6': 0.9842043370008469, 'surf_1_OH_PARAM__7': 0.6977998036891222, 'surf_1_conc': 29.168704478252284, 'surf_2_OH_PARAM__0': 0.1852993257343769, 'surf_2_OH_PARAM__1': 0.15290994476526976, 'surf_2_OH_PARAM__2': 0.128479091450572, 'surf_2_OH_PARAM__3': 0.0012486493214964867, 'surf_2_OH_PARAM__4': 0.25389708671718836, 'surf_2_OH_PARAM__5': 0.7091244384646416, 'surf_2_OH_PARAM__6': 0.07303992100059986, 'surf_2_OH_PARAM__7': 0.6562753710895777, 'surf_2_conc': 6.21217983706111, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 11-24 11:10:15] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2063), 'Drug_LogP': np.float64(0.3073), 'Drug_TPSA': np.float64(0.0373), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(1.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(29.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(1.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(6.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 11-24 11:10:15] ax.service.ax_client: Generated new trial 0 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 29, 'surf_2_conc': 6, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's6'} using model Sobol.

******************************************************************************** 2/32 ********************************************************************************

[WARNING 11-24 11:10:15] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.0037634940817952156, 'surf_1_OH_PARAM__1': 0.8141217147931457, 'surf_1_OH_PARAM__2': 0.7406759671866894, 'surf_1_OH_PARAM__3': 0.9561039302498102, 'surf_1_OH_PARAM__4': 0.6756732063367963, 'surf_1_OH_PARAM__5': 0.21041523758322, 'surf_1_OH_PARAM__6': 0.3966235024854541, 'surf_1_OH_PARAM__7': 0.8127681268379092, 'surf_1_conc': 6.427418335804287, 'surf_2_OH_PARAM__0': 0.012163537554442883, 'surf_2_OH_PARAM__1': 0.3733033752068877, 'surf_2_OH_PARAM__2': 0.5632305471226573, 'surf_2_OH_PARAM__3': 0.7179085658863187, 'surf_2_OH_PARAM__4': 0.4923010217025876, 'surf_2_OH_PARAM__5': 0.23102684877812862, 'surf_2_OH_PARAM__6': 0.3515354748815298, 'surf_2_OH_PARAM__7': 0.42559066507965326, 'surf_2_conc': 44.144577165127544, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 11-24 11:10:16] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2063), 'Drug_LogP': np.float64(0.3073), 'Drug_TPSA': np.float64(0.0373), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(1.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(6.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(1.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(44.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 11-24 11:10:16] ax.service.ax_client: Generated new trial 1 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 6, 'surf_2_conc': 44, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's4'} using model Sobol.

******************************************************************************** 3/32 ********************************************************************************

[WARNING 11-24 11:10:16] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.3404636224731803, 'surf_1_OH_PARAM__1': 0.9537274660542607, 'surf_1_OH_PARAM__2': 0.8137485692277551, 'surf_1_OH_PARAM__3': 0.013394019566476345, 'surf_1_OH_PARAM__4': 0.34946224465966225, 'surf_1_OH_PARAM__5': 0.2596472976729274, 'surf_1_OH_PARAM__6': 0.46504735853523016, 'surf_1_OH_PARAM__7': 0.7799381567165256, 'surf_1_conc': 3.9371326733264325, 'surf_2_OH_PARAM__0': 0.5236278707161546, 'surf_2_OH_PARAM__1': 0.04333105310797691, 'surf_2_OH_PARAM__2': 0.946794874034822, 'surf_2_OH_PARAM__3': 0.4187682056799531, 'surf_2_OH_PARAM__4': 0.07875171024352312, 'surf_2_OH_PARAM__5': 0.9976675165817142, 'surf_2_OH_PARAM__6': 0.275210446678102, 'surf_2_OH_PARAM__7': 0.750421991571784, 'surf_2_conc': 26.82320756362775, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 11-24 11:10:16] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2063), 'Drug_LogP': np.float64(0.3073), 'Drug_TPSA': np.float64(0.0373), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(1.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(4.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(1.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(26.999999999999996), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 11-24 11:10:16] ax.service.ax_client: Generated new trial 2 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 4, 'surf_2_conc': 27, 'drug_conc': 25.0, 'surf_1': 's2', 'surf_2': 's6'} using model Sobol.

******************************************************************************** 4/32 ********************************************************************************

[WARNING 11-24 11:10:17] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.8165709199383855, 'surf_1_OH_PARAM__1': 0.5260122045874596, 'surf_1_OH_PARAM__2': 0.6405113516375422, 'surf_1_OH_PARAM__3': 0.3824504045769572, 'surf_1_OH_PARAM__4': 0.5489866910502315, 'surf_1_OH_PARAM__5': 0.6568444883450866, 'surf_1_OH_PARAM__6': 0.1568917753174901, 'surf_1_OH_PARAM__7': 0.47708667628467083, 'surf_1_conc': 90.710474595474, 'surf_2_OH_PARAM__0': 0.22666261810809374, 'surf_2_OH_PARAM__1': 0.5391370002180338, 'surf_2_OH_PARAM__2': 0.4761995505541563, 'surf_2_OH_PARAM__3': 0.22314942255616188, 'surf_2_OH_PARAM__4': 0.37901090551167727, 'surf_2_OH_PARAM__5': 0.2875765720382333, 'surf_2_OH_PARAM__6': 0.2433986896649003, 'surf_2_OH_PARAM__7': 0.12754740566015244, 'surf_2_conc': 1.0129365993072093, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 11-24 11:10:17] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2063), 'Drug_LogP': np.float64(0.3073), 'Drug_TPSA': np.float64(0.0373), 'surf_1_OH_PARAM__0': np.float64(1.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(91.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(1.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(1.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 11-24 11:10:17] ax.service.ax_client: Generated new trial 3 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 91, 'surf_2_conc': 1, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's2'} using model Sobol.

******************************************************************************** 5/32 ********************************************************************************

[WARNING 11-24 11:10:17] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.8914620978757739, 'surf_1_OH_PARAM__1': 0.280865803360939, 'surf_1_OH_PARAM__2': 0.9967592135071754, 'surf_1_OH_PARAM__3': 0.3080728258937597, 'surf_1_OH_PARAM__4': 0.7293922426179051, 'surf_1_OH_PARAM__5': 0.7696071183308959, 'surf_1_OH_PARAM__6': 0.9118743576109409, 'surf_1_OH_PARAM__7': 0.6449064332991838, 'surf_1_conc': 31.65860466825548, 'surf_2_OH_PARAM__0': 0.6659942548722029, 'surf_2_OH_PARAM__1': 0.4516969919204712, 'surf_2_OH_PARAM__2': 0.26041840948164463, 'surf_2_OH_PARAM__3': 0.862021173350513, 'surf_2_OH_PARAM__4': 0.16725186351686716, 'surf_2_OH_PARAM__5': 0.4444979326799512, 'surf_2_OH_PARAM__6': 0.05164653342217207, 'surf_2_OH_PARAM__7': 0.019188699312508106, 'surf_2_conc': 14.26254850493282, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 11-24 11:10:18] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2063), 'Drug_LogP': np.float64(0.3073), 'Drug_TPSA': np.float64(0.0373), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(1.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(31.999999999999996), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(1.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(14.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 11-24 11:10:18] ax.service.ax_client: Generated new trial 4 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 32, 'surf_2_conc': 14, 'drug_conc': 25.0, 'surf_1': 's3', 'surf_2': 's4'} using model Sobol.

******************************************************************************** 6/32 ********************************************************************************

[WARNING 11-24 11:10:18] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.6576682087033987, 'surf_1_OH_PARAM__1': 0.7555750254541636, 'surf_1_OH_PARAM__2': 0.37869725562632084, 'surf_1_OH_PARAM__3': 0.7712999228388071, 'surf_1_OH_PARAM__4': 0.830823921598494, 'surf_1_OH_PARAM__5': 0.5338208433240652, 'surf_1_OH_PARAM__6': 0.33171852212399244, 'surf_1_OH_PARAM__7': 0.9482461418956518, 'surf_1_conc': 17.818472541409264, 'surf_2_OH_PARAM__0': 0.9840333992615342, 'surf_2_OH_PARAM__1': 0.20476824790239334, 'surf_2_OH_PARAM__2': 0.03352485876530409, 'surf_2_OH_PARAM__3': 0.2637761337682605, 'surf_2_OH_PARAM__4': 0.7768327426165342, 'surf_2_OH_PARAM__5': 0.1871174182742834, 'surf_2_OH_PARAM__6': 0.5782067673280835, 'surf_2_OH_PARAM__7': 0.4550788877531886, 'surf_2_conc': 76.1693715907736, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 11-24 11:10:18] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2063), 'Drug_LogP': np.float64(0.3073), 'Drug_TPSA': np.float64(0.0373), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(1.0), 'surf_1_conc': np.float64(18.0), 'surf_2_OH_PARAM__0': np.float64(1.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(76.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 11-24 11:10:18] ax.service.ax_client: Generated new trial 5 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 18, 'surf_2_conc': 76, 'drug_conc': 25.0, 'surf_1': 's8', 'surf_2': 's1'} using model Sobol.

******************************************************************************** 7/32 ********************************************************************************

[WARNING 11-24 11:10:19] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.4341551195830107, 'surf_1_OH_PARAM__1': 0.8013951778411865, 'surf_1_OH_PARAM__2': 0.1917425012215972, 'surf_1_OH_PARAM__3': 0.607687178067863, 'surf_1_OH_PARAM__4': 0.5676763271912932, 'surf_1_OH_PARAM__5': 0.795466797426343, 'surf_1_OH_PARAM__6': 0.9557190500199795, 'surf_1_OH_PARAM__7': 0.9993892572820187, 'surf_1_conc': 58.7124254503707, 'surf_2_OH_PARAM__0': 0.8799140024930239, 'surf_2_OH_PARAM__1': 0.9711983148008585, 'surf_2_OH_PARAM__2': 0.60481789521873, 'surf_2_OH_PARAM__3': 0.14747854508459568, 'surf_2_OH_PARAM__4': 0.4559036837890744, 'surf_2_OH_PARAM__5': 0.10055346880108118, 'surf_2_OH_PARAM__6': 0.9689407683908939, 'surf_2_OH_PARAM__7': 0.8401067331433296, 'surf_2_conc': 3.2411974882323107, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 11-24 11:10:19] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2063), 'Drug_LogP': np.float64(0.3073), 'Drug_TPSA': np.float64(0.0373), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(1.0), 'surf_1_conc': np.float64(59.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(1.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(3.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 11-24 11:10:19] ax.service.ax_client: Generated new trial 6 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 59, 'surf_2_conc': 3, 'drug_conc': 25.0, 'surf_1': 's8', 'surf_2': 's2'} using model Sobol.

******************************************************************************** 8/32 ********************************************************************************

[WARNING 11-24 11:10:19] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.646189839579165, 'surf_1_OH_PARAM__1': 0.22333460953086615, 'surf_1_OH_PARAM__2': 0.8648456698283553, 'surf_1_OH_PARAM__3': 0.4481635941192508, 'surf_1_OH_PARAM__4': 0.16660409048199654, 'surf_1_OH_PARAM__5': 0.42312610801309347, 'surf_1_OH_PARAM__6': 0.08627703133970499, 'surf_1_OH_PARAM__7': 0.08409794885665178, 'surf_1_conc': 1.832361531917527, 'surf_2_OH_PARAM__0': 0.05029252264648676, 'surf_2_OH_PARAM__1': 0.244063813239336, 'surf_2_OH_PARAM__2': 0.35698860697448254, 'surf_2_OH_PARAM__3': 0.9101361995562911, 'surf_2_OH_PARAM__4': 0.9280751440674067, 'surf_2_OH_PARAM__5': 0.9429942891001701, 'surf_2_OH_PARAM__6': 0.09781260415911674, 'surf_2_OH_PARAM__7': 0.28036365658044815, 'surf_2_conc': 66.10403906081247, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 11-24 11:10:20] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2063), 'Drug_LogP': np.float64(0.3073), 'Drug_TPSA': np.float64(0.0373), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(1.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(2.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(1.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(66.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 11-24 11:10:20] ax.service.ax_client: Generated new trial 7 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 2, 'surf_2_conc': 66, 'drug_conc': 25.0, 'surf_1': 's3', 'surf_2': 's6'} using model Sobol.

******************************************************************************** 9/32 ********************************************************************************

[WARNING 11-24 11:10:20] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.9102572910487652, 'surf_1_OH_PARAM__1': 0.7486569778993726, 'surf_1_OH_PARAM__2': 0.2607321487739682, 'surf_1_OH_PARAM__3': 0.9729755138978362, 'surf_1_OH_PARAM__4': 0.2682954967021942, 'surf_1_OH_PARAM__5': 0.13277419470250607, 'surf_1_OH_PARAM__6': 0.6701254975050688, 'surf_1_OH_PARAM__7': 0.259271957911551, 'surf_1_conc': 47.642036747518276, 'surf_2_OH_PARAM__0': 0.3643949683755636, 'surf_2_OH_PARAM__1': 0.4753902219235897, 'surf_2_OH_PARAM__2': 0.06781440135091543, 'surf_2_OH_PARAM__3': 0.4680949365720153, 'surf_2_OH_PARAM__4': 0.006253433413803577, 'surf_2_OH_PARAM__5': 0.6846372140571475, 'surf_2_OH_PARAM__6': 0.5008517447859049, 'surf_2_OH_PARAM__7': 0.21747455559670925, 'surf_2_conc': 31.0363087412915, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 11-24 11:10:20] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2063), 'Drug_LogP': np.float64(0.3073), 'Drug_TPSA': np.float64(0.0373), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(1.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(48.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(1.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(31.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 11-24 11:10:20] ax.service.ax_client: Generated new trial 8 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 48, 'surf_2_conc': 31, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's6'} using model Sobol.

******************************************************************************** 10/32 ********************************************************************************

[WARNING 11-24 11:10:21] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.35194186121225357, 'surf_1_OH_PARAM__1': 0.04843629151582718, 'surf_1_OH_PARAM__2': 0.4287887029349804, 'surf_1_OH_PARAM__3': 0.7056423630565405, 'surf_1_OH_PARAM__4': 0.6538111651316285, 'surf_1_OH_PARAM__5': 0.6504170466214418, 'surf_1_OH_PARAM__6': 0.21070234943181276, 'surf_1_OH_PARAM__7': 0.12861953675746918, 'surf_1_conc': 12.408827082922066, 'surf_2_OH_PARAM__0': 0.44229301903396845, 'surf_2_OH_PARAM__1': 0.004012584686279297, 'surf_2_OH_PARAM__2': 0.6312204096466303, 'surf_2_OH_PARAM__3': 0.7511614607647061, 'surf_2_OH_PARAM__4': 0.24758564773947, 'surf_2_OH_PARAM__5': 0.13247471023350954, 'surf_2_OH_PARAM__6': 0.794850705191493, 'surf_2_OH_PARAM__7': 0.950657051987946, 'surf_2_conc': 18.346194329952205, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 11-24 11:10:21] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2063), 'Drug_LogP': np.float64(0.3073), 'Drug_TPSA': np.float64(0.0373), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(1.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(12.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(1.0), 'surf_2_conc': np.float64(18.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 11-24 11:10:21] ax.service.ax_client: Generated new trial 9 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 12, 'surf_2_conc': 18, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's8'} using model Sobol.

******************************************************************************** 11/32 ********************************************************************************

[WARNING 11-24 11:10:21] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.05381631292402744, 'surf_1_OH_PARAM__1': 0.15691270120441914, 'surf_1_OH_PARAM__2': 0.00012561772018671036, 'surf_1_OH_PARAM__3': 0.2618719441816211, 'surf_1_OH_PARAM__4': 0.32395338267087936, 'surf_1_OH_PARAM__5': 0.8169594034552574, 'surf_1_OH_PARAM__6': 0.1541270622983575, 'surf_1_OH_PARAM__7': 0.21616561710834503, 'surf_1_conc': 22.397901813330538, 'surf_2_OH_PARAM__0': 0.953785072080791, 'surf_2_OH_PARAM__1': 0.33400780986994505, 'surf_2_OH_PARAM__2': 0.765036566182971, 'surf_2_OH_PARAM__3': 0.1120701814070344, 'surf_2_OH_PARAM__4': 0.33324664924293756, 'surf_2_OH_PARAM__5': 0.8971317335963249, 'surf_2_OH_PARAM__6': 0.8318079998716712, 'surf_2_OH_PARAM__7': 0.3738770429044962, 'surf_2_conc': 10.419598070598727, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 11-24 11:10:22] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2063), 'Drug_LogP': np.float64(0.3073), 'Drug_TPSA': np.float64(0.0373), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(1.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(22.0), 'surf_2_OH_PARAM__0': np.float64(1.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(10.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 11-24 11:10:22] ax.service.ax_client: Generated new trial 10 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 22, 'surf_2_conc': 10, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's1'} using model Sobol.

******************************************************************************** 12/32 ********************************************************************************

[WARNING 11-24 11:10:22] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.22257908806204796, 'surf_1_OH_PARAM__1': 0.9116974119096994, 'surf_1_OH_PARAM__2': 0.362719202414155, 'surf_1_OH_PARAM__3': 0.4228450935333967, 'surf_1_OH_PARAM__4': 0.3940055724233389, 'surf_1_OH_PARAM__5': 0.7344711646437645, 'surf_1_OH_PARAM__6': 0.8991437628865242, 'surf_1_OH_PARAM__7': 0.907904502004385, 'surf_1_conc': 54.988459307088405, 'surf_2_OH_PARAM__0': 0.3918965384364128, 'surf_2_OH_PARAM__1': 0.6724702576175332, 'surf_2_OH_PARAM__2': 0.9711245838552713, 'surf_2_OH_PARAM__3': 0.9735961463302374, 'surf_2_OH_PARAM__4': 0.11951401550322771, 'surf_2_OH_PARAM__5': 0.8671636246144772, 'surf_2_OH_PARAM__6': 0.9043967174366117, 'surf_2_OH_PARAM__7': 0.4842697074636817, 'surf_2_conc': 23.594369996732805, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 11-24 11:10:22] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2063), 'Drug_LogP': np.float64(0.3073), 'Drug_TPSA': np.float64(0.0373), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(1.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(55.00000000000001), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(1.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(24.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 11-24 11:10:22] ax.service.ax_client: Generated new trial 11 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 55, 'surf_2_conc': 24, 'drug_conc': 25.0, 'surf_1': 's2', 'surf_2': 's4'} using model Sobol.

******************************************************************************** 13/32 ********************************************************************************

[WARNING 11-24 11:10:23] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.9480367777869105, 'surf_1_OH_PARAM__1': 0.11476567853242159, 'surf_1_OH_PARAM__2': 0.6901191268116236, 'surf_1_OH_PARAM__3': 0.5198388751596212, 'surf_1_OH_PARAM__4': 0.8717060135677457, 'surf_1_OH_PARAM__5': 0.10919220466166735, 'surf_1_OH_PARAM__6': 0.017853361554443836, 'surf_1_OH_PARAM__7': 0.008741733618080616, 'surf_1_conc': 11.866900003462153, 'surf_2_OH_PARAM__0': 0.5383095247671008, 'surf_2_OH_PARAM__1': 0.4179309895262122, 'surf_2_OH_PARAM__2': 0.22334840334951878, 'surf_2_OH_PARAM__3': 0.20315648149698973, 'surf_2_OH_PARAM__4': 0.5301546920090914, 'surf_2_OH_PARAM__5': 0.20769708324223757, 'surf_2_OH_PARAM__6': 0.025393766351044178, 'surf_2_OH_PARAM__7': 0.9186676135286689, 'surf_2_conc': 61.33176537846707, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 11-24 11:10:23] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2063), 'Drug_LogP': np.float64(0.3073), 'Drug_TPSA': np.float64(0.0373), 'surf_1_OH_PARAM__0': np.float64(1.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(12.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(1.0), 'surf_2_conc': np.float64(61.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 11-24 11:10:23] ax.service.ax_client: Generated new trial 12 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 12, 'surf_2_conc': 61, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's8'} using model Sobol.

******************************************************************************** 14/32 ********************************************************************************

[WARNING 11-24 11:10:23] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.7454932015389204, 'surf_1_OH_PARAM__1': 0.6090512117370963, 'surf_1_OH_PARAM__2': 0.18534020334482193, 'surf_1_OH_PARAM__3': 0.05752731300890446, 'surf_1_OH_PARAM__4': 0.6919204751029611, 'surf_1_OH_PARAM__5': 0.337288286536932, 'surf_1_OH_PARAM__6': 0.722794646397233, 'surf_1_OH_PARAM__7': 0.33551318291574717, 'surf_1_conc': 37.652576544635146, 'surf_2_OH_PARAM__0': 0.8451177291572094, 'surf_2_OH_PARAM__1': 0.17658027168363333, 'surf_2_OH_PARAM__2': 0.449501889757812, 'surf_2_OH_PARAM__3': 0.6686047567054629, 'surf_2_OH_PARAM__4': 0.4207717077806592, 'surf_2_OH_PARAM__5': 0.418088098987937, 'surf_2_OH_PARAM__6': 0.623990680091083, 'surf_2_OH_PARAM__7': 0.6065109232440591, 'surf_2_conc': 48.23486914514189, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 11-24 11:10:24] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2063), 'Drug_LogP': np.float64(0.3073), 'Drug_TPSA': np.float64(0.0373), 'surf_1_OH_PARAM__0': np.float64(1.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(38.0), 'surf_2_OH_PARAM__0': np.float64(1.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(48.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 11-24 11:10:24] ax.service.ax_client: Generated new trial 13 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 38, 'surf_2_conc': 48, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's1'} using model Sobol.

******************************************************************************** 15/32 ********************************************************************************

[WARNING 11-24 11:10:24] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.4453170169144869, 'surf_1_OH_PARAM__1': 0.8782243756577373, 'surf_1_OH_PARAM__2': 0.6522081829607487, 'surf_1_OH_PARAM__3': 0.695832715369761, 'surf_1_OH_PARAM__4': 0.7778550526127219, 'surf_1_OH_PARAM__5': 0.83951236307621, 'surf_1_OH_PARAM__6': 0.6867371900007129, 'surf_1_OH_PARAM__7': 0.5617806268855929, 'surf_1_conc': 0.7750459018324687, 'surf_2_OH_PARAM__0': 0.7944518029689789, 'surf_2_OH_PARAM__1': 0.6156727708876133, 'surf_2_OH_PARAM__2': 0.2780009740963578, 'surf_2_OH_PARAM__3': 0.6280586328357458, 'surf_2_OH_PARAM__4': 0.10905736219137907, 'surf_2_OH_PARAM__5': 0.8079182747751474, 'surf_2_OH_PARAM__6': 0.8765483675524592, 'surf_2_OH_PARAM__7': 0.0799939064309001, 'surf_2_conc': 74.67009558956173, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 11-24 11:10:24] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2063), 'Drug_LogP': np.float64(0.3073), 'Drug_TPSA': np.float64(0.0373), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(1.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(1.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(1.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(75.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 11-24 11:10:24] ax.service.ax_client: Generated new trial 14 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 1, 'surf_2_conc': 75, 'drug_conc': 25.0, 'surf_1': 's2', 'surf_2': 's7'} using model Sobol.

******************************************************************************** 16/32 ********************************************************************************

[WARNING 11-24 11:10:25] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.7198516996577382, 'surf_1_OH_PARAM__1': 0.08140712603926659, 'surf_1_OH_PARAM__2': 0.2911311574280262, 'surf_1_OH_PARAM__3': 0.3556164288893342, 'surf_1_OH_PARAM__4': 0.48761264607310295, 'surf_1_OH_PARAM__5': 0.4417724655941129, 'surf_1_OH_PARAM__6': 0.3025247287005186, 'surf_1_OH_PARAM__7': 0.3964893165975809, 'surf_1_conc': 56.619272475685754, 'surf_2_OH_PARAM__0': 0.15229429583996534, 'surf_2_OH_PARAM__1': 0.356540659442544, 'surf_2_OH_PARAM__2': 0.5258455807343125, 'surf_2_OH_PARAM__3': 0.42956517171114683, 'surf_2_OH_PARAM__4': 0.5109158344566822, 'surf_2_OH_PARAM__5': 0.1485361335799098, 'surf_2_OH_PARAM__6': 0.00542872678488493, 'surf_2_OH_PARAM__7': 0.518290433101356, 'surf_2_conc': 11.800258698046653, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 11-24 11:10:25] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2063), 'Drug_LogP': np.float64(0.3073), 'Drug_TPSA': np.float64(0.0373), 'surf_1_OH_PARAM__0': np.float64(1.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(57.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(1.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(12.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 11-24 11:10:25] ax.service.ax_client: Generated new trial 15 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 57, 'surf_2_conc': 12, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's3'} using model Sobol.

******************************************************************************** 17/32 ********************************************************************************

[WARNING 11-24 11:10:25] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.2438110401853919, 'surf_1_OH_PARAM__1': 0.3997935736551881, 'surf_1_OH_PARAM__2': 0.22337034903466702, 'surf_1_OH_PARAM__3': 0.22479456383734941, 'surf_1_OH_PARAM__4': 0.6607676399871707, 'surf_1_OH_PARAM__5': 0.606548965908587, 'surf_1_OH_PARAM__6': 0.07161107286810875, 'surf_1_OH_PARAM__7': 0.8438729187473655, 'surf_1_conc': 48.754452554351666, 'surf_2_OH_PARAM__0': 0.6053192680701613, 'surf_2_OH_PARAM__1': 0.8528652302920818, 'surf_2_OH_PARAM__2': 0.05109788477420807, 'surf_2_OH_PARAM__3': 0.2495697196573019, 'surf_2_OH_PARAM__4': 0.9683328233659267, 'surf_2_OH_PARAM__5': 0.5664031440392137, 'surf_2_OH_PARAM__6': 0.47400805819779634, 'surf_2_OH_PARAM__7': 0.3909298898652196, 'surf_2_conc': 34.89962083257327, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 11-24 11:10:26] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2063), 'Drug_LogP': np.float64(0.3073), 'Drug_TPSA': np.float64(0.0373), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(1.0), 'surf_1_conc': np.float64(49.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(1.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(35.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 11-24 11:10:26] ax.service.ax_client: Generated new trial 16 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 49, 'surf_2_conc': 35, 'drug_conc': 25.0, 'surf_1': 's8', 'surf_2': 's5'} using model Sobol.

******************************************************************************** 18/32 ********************************************************************************

[WARNING 11-24 11:10:26] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.5525535298511386, 'surf_1_OH_PARAM__1': 0.8343729265034199, 'surf_1_OH_PARAM__2': 0.08722709026187658, 'surf_1_OH_PARAM__3': 0.4540436826646328, 'surf_1_OH_PARAM__4': 0.29259072430431843, 'surf_1_OH_PARAM__5': 0.11026078928261995, 'surf_1_OH_PARAM__6': 0.5474980240687728, 'surf_1_OH_PARAM__7': 0.7294100727885962, 'surf_1_conc': 14.65570851227315, 'surf_2_OH_PARAM__0': 0.7129643261432648, 'surf_2_OH_PARAM__1': 0.6362412124872208, 'surf_2_OH_PARAM__2': 0.741685968823731, 'surf_2_OH_PARAM__3': 0.5331231839954853, 'surf_2_OH_PARAM__4': 0.7855948284268379, 'surf_2_OH_PARAM__5': 0.11844571586698294, 'surf_2_OH_PARAM__6': 0.1956188390031457, 'surf_2_OH_PARAM__7': 0.6284456308931112, 'surf_2_conc': 22.21335907658219, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 11-24 11:10:26] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2063), 'Drug_LogP': np.float64(0.3073), 'Drug_TPSA': np.float64(0.0373), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(1.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(15.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(1.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(22.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 11-24 11:10:26] ax.service.ax_client: Generated new trial 17 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 15, 'surf_2_conc': 22, 'drug_conc': 25.0, 'surf_1': 's2', 'surf_2': 's5'} using model Sobol.

******************************************************************************** 19/32 ********************************************************************************

[WARNING 11-24 11:10:27] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.8541583204641938, 'surf_1_OH_PARAM__1': 0.9446455668658018, 'surf_1_OH_PARAM__2': 0.4828129131346941, 'surf_1_OH_PARAM__3': 0.5139582464471459, 'surf_1_OH_PARAM__4': 0.7477040914818645, 'surf_1_OH_PARAM__5': 0.42040957417339087, 'surf_1_OH_PARAM__6': 0.6198213873431087, 'surf_1_OH_PARAM__7': 0.6757971551269293, 'surf_1_conc': 23.510891031634284, 'surf_2_OH_PARAM__0': 0.20150060392916203, 'surf_2_OH_PARAM__1': 0.9625209225341678, 'surf_2_OH_PARAM__2': 0.8733200514689088, 'surf_2_OH_PARAM__3': 0.3301771506667137, 'surf_2_OH_PARAM__4': 0.6374948471784592, 'surf_2_OH_PARAM__5': 0.8518336657434702, 'surf_2_OH_PARAM__6': 0.1781935691833496, 'surf_2_OH_PARAM__7': 0.04702694807201624, 'surf_2_conc': 5.016725282596592, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 11-24 11:10:27] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2063), 'Drug_LogP': np.float64(0.3073), 'Drug_TPSA': np.float64(0.0373), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(1.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(24.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(1.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(5.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 11-24 11:10:27] ax.service.ax_client: Generated new trial 18 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 24, 'surf_2_conc': 5, 'drug_conc': 25.0, 'surf_1': 's2', 'surf_2': 's2'} using model Sobol.

******************************************************************************** 20/32 ********************************************************************************

[WARNING 11-24 11:10:27] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.14792540669441223, 'surf_1_OH_PARAM__1': 0.7680423492565751, 'surf_1_OH_PARAM__2': 0.7938574934378266, 'surf_1_OH_PARAM__3': 0.2716812901198864, 'surf_1_OH_PARAM__4': 0.1979858260601759, 'surf_1_OH_PARAM__5': 0.6301223877817392, 'surf_1_OH_PARAM__6': 0.7394149294123054, 'surf_1_OH_PARAM__7': 0.5953873647376895, 'surf_1_conc': 9.577059369361008, 'surf_2_OH_PARAM__0': 0.30640305019915104, 'surf_2_OH_PARAM__1': 0.7855802914127707, 'surf_2_OH_PARAM__2': 0.14608508069068193, 'surf_2_OH_PARAM__3': 0.4851806703954935, 'surf_2_OH_PARAM__4': 0.44441676419228315, 'surf_2_OH_PARAM__5': 0.041260442696511745, 'surf_2_OH_PARAM__6': 0.9997474420815706, 'surf_2_OH_PARAM__7': 0.7209834046661854, 'surf_2_conc': 54.31220334780393, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 11-24 11:10:28] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2063), 'Drug_LogP': np.float64(0.3073), 'Drug_TPSA': np.float64(0.0373), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(1.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(10.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(1.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(53.99999999999999), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 11-24 11:10:28] ax.service.ax_client: Generated new trial 19 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 10, 'surf_2_conc': 54, 'drug_conc': 25.0, 'surf_1': 's3', 'surf_2': 's7'} using model Sobol.

******************************************************************************** 21/32 ********************************************************************************

[WARNING 11-24 11:10:28] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.9358830591663718, 'surf_1_OH_PARAM__1': 0.18985203467309475, 'surf_1_OH_PARAM__2': 0.1534834736958146, 'surf_1_OH_PARAM__3': 0.6744288094341755, 'surf_1_OH_PARAM__4': 0.5365389855578542, 'surf_1_OH_PARAM__5': 0.026336385868489742, 'surf_1_OH_PARAM__6': 0.37484809197485447, 'surf_1_OH_PARAM__7': 0.44622459448873997, 'surf_1_conc': 54.128601905114614, 'surf_2_OH_PARAM__0': 0.640344494022429, 'surf_2_OH_PARAM__1': 0.06154337618499994, 'surf_2_OH_PARAM__2': 0.8938459428027272, 'surf_2_OH_PARAM__3': 0.6915781563147902, 'surf_2_OH_PARAM__4': 0.9097444824874401, 'surf_2_OH_PARAM__5': 0.8838772159069777, 'surf_2_OH_PARAM__6': 0.1207550410181284, 'surf_2_OH_PARAM__7': 0.15732644870877266, 'surf_2_conc': 16.571087564088796, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 11-24 11:10:28] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2063), 'Drug_LogP': np.float64(0.3073), 'Drug_TPSA': np.float64(0.0373), 'surf_1_OH_PARAM__0': np.float64(1.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(53.99999999999999), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(1.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(17.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 11-24 11:10:28] ax.service.ax_client: Generated new trial 20 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 54, 'surf_2_conc': 17, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's5'} using model Sobol.

******************************************************************************** 22/32 ********************************************************************************

[WARNING 11-24 11:10:29] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.4129083873704076, 'surf_1_OH_PARAM__1': 0.25814648251980543, 'surf_1_OH_PARAM__2': 0.3316030306741595, 'surf_1_OH_PARAM__3': 0.8052188456058502, 'surf_1_OH_PARAM__4': 0.36191759444773197, 'surf_1_OH_PARAM__5': 0.925341616384685, 'surf_1_OH_PARAM__6': 0.003194071352481842, 'surf_1_OH_PARAM__7': 0.8113342961296439, 'surf_1_conc': 39.89965513121095, 'surf_2_OH_PARAM__0': 0.12462494987994432, 'surf_2_OH_PARAM__1': 0.5578928655013442, 'surf_2_OH_PARAM__2': 0.43496744707226753, 'surf_2_OH_PARAM__3': 0.88719860650599, 'surf_2_OH_PARAM__4': 0.6163755692541599, 'surf_2_OH_PARAM__5': 0.33100103214383125, 'surf_2_OH_PARAM__6': 0.40165114775300026, 'surf_2_OH_PARAM__7': 0.7850932125002146, 'surf_2_conc': 42.82506105075702, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 11-24 11:10:29] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2063), 'Drug_LogP': np.float64(0.3073), 'Drug_TPSA': np.float64(0.0373), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(1.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(40.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(1.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(43.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 11-24 11:10:29] ax.service.ax_client: Generated new trial 21 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 40, 'surf_2_conc': 43, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's4'} using model Sobol.

******************************************************************************** 23/32 ********************************************************************************

[WARNING 11-24 11:10:29] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.392640957608819, 'surf_1_OH_PARAM__1': 0.7278563287109137, 'surf_1_OH_PARAM__2': 0.9119742270559072, 'surf_1_OH_PARAM__3': 0.4762555668130517, 'surf_1_OH_PARAM__4': 0.6355105107650161, 'surf_1_OH_PARAM__5': 0.03165755607187748, 'surf_1_OH_PARAM__6': 0.25849262066185474, 'surf_1_OH_PARAM__7': 0.15998325124382973, 'surf_1_conc': 30.225823327366875, 'surf_2_OH_PARAM__0': 0.9094400303438306, 'surf_2_OH_PARAM__1': 0.5186056746169925, 'surf_2_OH_PARAM__2': 0.23700773064047098, 'surf_2_OH_PARAM__3': 0.28282213769853115, 'surf_2_OH_PARAM__4': 0.7129229009151459, 'surf_2_OH_PARAM__5': 0.5398333314806223, 'surf_2_OH_PARAM__6': 0.9213557811453938, 'surf_2_OH_PARAM__7': 0.9833714375272393, 'surf_2_conc': 2.393681131451912, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 11-24 11:10:30] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2063), 'Drug_LogP': np.float64(0.3073), 'Drug_TPSA': np.float64(0.0373), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(1.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(30.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(1.0), 'surf_2_conc': np.float64(2.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 11-24 11:10:30] ax.service.ax_client: Generated new trial 22 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 30, 'surf_2_conc': 2, 'drug_conc': 25.0, 'surf_1': 's3', 'surf_2': 's8'} using model Sobol.

******************************************************************************** 24/32 ********************************************************************************

[WARNING 11-24 11:10:30] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.8853499367833138, 'surf_1_OH_PARAM__1': 0.7845924524590373, 'surf_1_OH_PARAM__2': 0.6049572415649891, 'surf_1_OH_PARAM__3': 0.10715376306325197, 'surf_1_OH_PARAM__4': 0.4660176485776901, 'surf_1_OH_PARAM__5': 0.8838576506823301, 'surf_1_OH_PARAM__6': 0.11346115171909332, 'surf_1_OH_PARAM__7': 0.5839379588142037, 'surf_1_conc': 63.392245281032785, 'surf_2_OH_PARAM__0': 0.33148154709488153, 'surf_2_OH_PARAM__1': 0.022705611772835255, 'surf_2_OH_PARAM__2': 0.7154174596071243, 'surf_2_OH_PARAM__3': 0.10332099627703428, 'surf_2_OH_PARAM__4': 0.7643711641430855, 'surf_2_OH_PARAM__5': 0.2374759465456009, 'surf_2_OH_PARAM__6': 0.5777383772656322, 'surf_2_OH_PARAM__7': 0.1055211266502738, 'surf_2_conc': 25.442089034762883, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 11-24 11:10:30] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2063), 'Drug_LogP': np.float64(0.3073), 'Drug_TPSA': np.float64(0.0373), 'surf_1_OH_PARAM__0': np.float64(1.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(62.99999999999999), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(1.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(25.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 11-24 11:10:30] ax.service.ax_client: Generated new trial 23 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 63, 'surf_2_conc': 25, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's5'} using model Sobol.

******************************************************************************** 25/32 ********************************************************************************

[WARNING 11-24 11:10:31] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.8421991895884275, 'surf_1_OH_PARAM__1': 0.037435720674693584, 'surf_1_OH_PARAM__2': 0.7736422857269645, 'surf_1_OH_PARAM__3': 0.20452812314033508, 'surf_1_OH_PARAM__4': 0.255859000608325, 'surf_1_OH_PARAM__5': 0.5601570438593626, 'surf_1_OH_PARAM__6': 0.8606164688244462, 'surf_1_OH_PARAM__7': 0.29013406950980425, 'surf_1_conc': 8.71726160368515, 'surf_2_OH_PARAM__0': 0.7681264448910952, 'surf_2_OH_PARAM__1': 0.9861833518370986, 'surf_2_OH_PARAM__2': 0.5484528578817844, 'surf_2_OH_PARAM__3': 0.9999699480831623, 'surf_2_OH_PARAM__4': 0.533112246543169, 'surf_2_OH_PARAM__5': 0.018054652959108353, 'surf_2_OH_PARAM__6': 0.6272199684754014, 'surf_2_OH_PARAM__7': 0.24725438095629215, 'surf_2_conc': 40.33147262851095, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 11-24 11:10:31] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2063), 'Drug_LogP': np.float64(0.3073), 'Drug_TPSA': np.float64(0.0373), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(1.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(9.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(1.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(40.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 11-24 11:10:31] ax.service.ax_client: Generated new trial 24 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 9, 'surf_2_conc': 40, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's4'} using model Sobol.

******************************************************************************** 26/32 ********************************************************************************

[WARNING 11-24 11:10:31] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.6091375378891826, 'surf_1_OH_PARAM__1': 0.5590655812993646, 'surf_1_OH_PARAM__2': 0.3509022416546941, 'surf_1_OH_PARAM__3': 0.7498436979949474, 'surf_1_OH_PARAM__4': 0.18540065921843052, 'surf_1_OH_PARAM__5': 0.7609091391786933, 'surf_1_OH_PARAM__6': 0.38199259154498577, 'surf_1_OH_PARAM__7': 0.11570627335458994, 'surf_1_conc': 40.80301561344687, 'surf_2_OH_PARAM__0': 0.5828387038782239, 'surf_2_OH_PARAM__1': 0.7333884378895164, 'surf_2_OH_PARAM__2': 0.7747913720086217, 'surf_2_OH_PARAM__3': 0.37826118245720863, 'surf_2_OH_PARAM__4': 0.39241870027035475, 'surf_2_OH_PARAM__5': 0.3542982554063201, 'surf_2_OH_PARAM__6': 0.22528947796672583, 'surf_2_OH_PARAM__7': 0.30916691198945045, 'surf_2_conc': 50.09890708231382, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 11-24 11:10:32] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2063), 'Drug_LogP': np.float64(0.3073), 'Drug_TPSA': np.float64(0.0373), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(1.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(41.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(1.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(50.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 11-24 11:10:32] ax.service.ax_client: Generated new trial 25 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 41, 'surf_2_conc': 50, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's3'} using model Sobol.

******************************************************************************** 27/32 ********************************************************************************

[WARNING 11-24 11:10:32] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.5010437332093716, 'surf_1_OH_PARAM__1': 0.17908282671123743, 'surf_1_OH_PARAM__2': 0.6709027606993914, 'surf_1_OH_PARAM__3': 0.7654574485495687, 'surf_1_OH_PARAM__4': 0.7068067481741309, 'surf_1_OH_PARAM__5': 0.9717336036264896, 'surf_1_OH_PARAM__6': 0.8079389156773686, 'surf_1_OH_PARAM__7': 0.3671520622447133, 'surf_1_conc': 4.9944516896997015, 'surf_2_OH_PARAM__0': 0.25663285702466965, 'surf_2_OH_PARAM__1': 0.659941803663969, 'surf_2_OH_PARAM__2': 0.9303235113620758, 'surf_2_OH_PARAM__3': 0.13676025718450546, 'surf_2_OH_PARAM__4': 0.8841005377471447, 'surf_2_OH_PARAM__5': 0.7533652121201158, 'surf_2_OH_PARAM__6': 0.7465128526091576, 'surf_2_OH_PARAM__7': 0.5767243774607778, 'surf_2_conc': 32.28303019424979, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 11-24 11:10:32] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2063), 'Drug_LogP': np.float64(0.3073), 'Drug_TPSA': np.float64(0.0373), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(1.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(5.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(1.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(31.999999999999996), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 11-24 11:10:32] ax.service.ax_client: Generated new trial 26 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 5, 'surf_2_conc': 32, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's3'} using model Sobol.

******************************************************************************** 28/32 ********************************************************************************

[WARNING 11-24 11:10:33] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.02499699406325817, 'surf_1_OH_PARAM__1': 0.37243035808205605, 'surf_1_OH_PARAM__2': 0.8453534990549088, 'surf_1_OH_PARAM__3': 0.6306235576048493, 'surf_1_OH_PARAM__4': 0.379111684858799, 'surf_1_OH_PARAM__5': 0.07271215319633484, 'surf_1_OH_PARAM__6': 0.5701034953817725, 'surf_1_OH_PARAM__7': 0.8767996802926064, 'surf_1_conc': 88.66086364336562, 'surf_2_OH_PARAM__0': 0.9910930804908276, 'surf_2_OH_PARAM__1': 0.16361508704721928, 'surf_2_OH_PARAM__2': 0.3969839895144105, 'surf_2_OH_PARAM__3': 0.44175045657902956, 'surf_2_OH_PARAM__4': 0.5917301215231419, 'surf_2_OH_PARAM__5': 0.46150540094822645, 'surf_2_OH_PARAM__6': 0.7778343018144369, 'surf_2_OH_PARAM__7': 0.44960598926991224, 'surf_2_conc': 7.987793793647642, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 11-24 11:10:33] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2063), 'Drug_LogP': np.float64(0.3073), 'Drug_TPSA': np.float64(0.0373), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(1.0), 'surf_1_conc': np.float64(89.0), 'surf_2_OH_PARAM__0': np.float64(1.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(8.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 11-24 11:10:33] ax.service.ax_client: Generated new trial 27 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 89, 'surf_2_conc': 8, 'drug_conc': 25.0, 'surf_1': 's8', 'surf_2': 's1'} using model Sobol.

******************************************************************************** 29/32 ********************************************************************************

[WARNING 11-24 11:10:33] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.20059426873922348, 'surf_1_OH_PARAM__1': 0.6175836734473705, 'surf_1_OH_PARAM__2': 0.5184635920450091, 'surf_1_OH_PARAM__3': 0.5557414852082729, 'surf_1_OH_PARAM__4': 0.34079562686383724, 'surf_1_OH_PARAM__5': 0.49901285767555237, 'surf_1_OH_PARAM__6': 0.31507655046880245, 'surf_1_OH_PARAM__7': 0.2473028339445591, 'surf_1_conc': 33.94901833757274, 'surf_2_OH_PARAM__0': 0.42871573474258184, 'surf_2_OH_PARAM__1': 0.8135398775339127, 'surf_2_OH_PARAM__2': 0.3706407221034169, 'surf_2_OH_PARAM__3': 0.5805010590702295, 'surf_2_OH_PARAM__4': 0.8620071038603783, 'surf_2_OH_PARAM__5': 0.30641486402601004, 'surf_2_OH_PARAM__6': 0.95446702465415, 'surf_2_OH_PARAM__7': 0.3411578144878149, 'surf_2_conc': 19.713895068036223, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 11-24 11:10:34] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2063), 'Drug_LogP': np.float64(0.3073), 'Drug_TPSA': np.float64(0.0373), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(1.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(34.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(1.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(20.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 11-24 11:10:34] ax.service.ax_client: Generated new trial 28 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 34, 'surf_2_conc': 20, 'drug_conc': 25.0, 'surf_1': 's2', 'surf_2': 's7'} using model Sobol.

******************************************************************************** 30/32 ********************************************************************************

[WARNING 11-24 11:10:34] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.49682669807225466, 'surf_1_OH_PARAM__1': 0.09598503075540066, 'surf_1_OH_PARAM__2': 0.10699216369539499, 'surf_1_OH_PARAM__3': 0.023119434714317322, 'surf_1_OH_PARAM__4': 0.22350993938744068, 'surf_1_OH_PARAM__5': 0.1956146815791726, 'surf_1_OH_PARAM__6': 0.9265710720792413, 'surf_1_OH_PARAM__7': 0.40856800973415375, 'surf_1_conc': 15.57158847827846, 'surf_2_OH_PARAM__0': 0.2357076331973076, 'surf_2_OH_PARAM__1': 0.5920103415846825, 'surf_2_OH_PARAM__2': 0.08150656893849373, 'surf_2_OH_PARAM__3': 0.045654887333512306, 'surf_2_OH_PARAM__4': 0.19000205304473639, 'surf_2_OH_PARAM__5': 0.0639231689274311, 'surf_2_OH_PARAM__6': 0.4274004492908716, 'surf_2_OH_PARAM__7': 0.1533144935965538, 'surf_2_conc': 83.14412023576416, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 11-24 11:10:34] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2063), 'Drug_LogP': np.float64(0.3073), 'Drug_TPSA': np.float64(0.0373), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(1.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(16.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(1.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(83.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 11-24 11:10:34] ax.service.ax_client: Generated new trial 29 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 16, 'surf_2_conc': 83, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's2'} using model Sobol.

******************************************************************************** 31/32 ********************************************************************************

[WARNING 11-24 11:10:35] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.017459824681282043, 'surf_1_OH_PARAM__1': 0.5640227841213346, 'surf_1_OH_PARAM__2': 0.24344110395759344, 'surf_1_OH_PARAM__3': 0.3960658386349678, 'surf_1_OH_PARAM__4': 0.1543691474944353, 'surf_1_OH_PARAM__5': 0.25019257608801126, 'surf_1_OH_PARAM__6': 0.6615071715787053, 'surf_1_OH_PARAM__7': 0.9585480121895671, 'surf_1_conc': 71.87292332512442, 'surf_2_OH_PARAM__0': 0.11353677604347467, 'surf_2_OH_PARAM__1': 0.9449812602251768, 'surf_2_OH_PARAM__2': 0.6898561762645841, 'surf_2_OH_PARAM__3': 0.7657455643638968, 'surf_2_OH_PARAM__4': 0.8783514639362693, 'surf_2_OH_PARAM__5': 0.5289214178919792, 'surf_2_OH_PARAM__6': 0.7299102591350675, 'surf_2_OH_PARAM__7': 0.6643620645627379, 'surf_2_conc': 14.797081153766754, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 11-24 11:10:35] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2063), 'Drug_LogP': np.float64(0.3073), 'Drug_TPSA': np.float64(0.0373), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(1.0), 'surf_1_conc': np.float64(72.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(1.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(15.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 11-24 11:10:35] ax.service.ax_client: Generated new trial 30 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 72, 'surf_2_conc': 15, 'drug_conc': 25.0, 'surf_1': 's8', 'surf_2': 's2'} using model Sobol.

******************************************************************************** 32/32 ********************************************************************************

[WARNING 11-24 11:10:35] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.8054242124781013, 'surf_1_OH_PARAM__1': 0.3922045771032572, 'surf_1_OH_PARAM__2': 0.8208413263782859, 'surf_1_OH_PARAM__3': 0.5480828434228897, 'surf_1_OH_PARAM__4': 0.6111001977697015, 'surf_1_OH_PARAM__5': 0.9062322787940502, 'surf_1_OH_PARAM__6': 0.2964596822857857, 'surf_1_OH_PARAM__7': 0.12188619561493397, 'surf_1_conc': 13.920323539841602, 'surf_2_OH_PARAM__0': 0.9396560657769442, 'surf_2_OH_PARAM__1': 0.21558845043182373, 'surf_2_OH_PARAM__2': 0.4420876847580075, 'surf_2_OH_PARAM__3': 0.036017315462231636, 'surf_2_OH_PARAM__4': 0.4765002429485321, 'surf_2_OH_PARAM__5': 0.4363199034705758, 'surf_2_OH_PARAM__6': 0.3588539185002446, 'surf_2_OH_PARAM__7': 0.22960593458265066, 'surf_2_conc': 52.93304265790624, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[WARNING 11-24 11:10:36] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2063), 'Drug_LogP': np.float64(0.3073), 'Drug_TPSA': np.float64(0.0373), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(1.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(14.0), 'surf_2_OH_PARAM__0': np.float64(1.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(52.99999999999999), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc <= -1.0)])
[INFO 11-24 11:10:36] ax.service.ax_client: Generated new trial 31 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 14, 'surf_2_conc': 53, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's1'} using model Sobol.

Time taken for optimization: 0.36 mins
Time taken for optimization: 21.599999999999998 seconds

# process results

In [ ]:
ax_client = hf.load_design_optimizer(n)
ax_client.experiment.trials

{0: Trial(experiment_name='drug_surfactant', index=0, status=TrialStatus.RUNNING, arm=Arm(name='0_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 29, 'surf_2_conc': 6, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's6'})),
 1: Trial(experiment_name='drug_surfactant', index=1, status=TrialStatus.RUNNING, arm=Arm(name='1_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 6, 'surf_2_conc': 44, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's4'})),
 2: Trial(experiment_name='drug_surfactant', index=2, status=TrialStatus.RUNNING, arm=Arm(name='2_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 4, 'surf_2_conc': 27, 'drug_conc': 25.0, 'surf_1': 's2', 'surf_2': 's6'})),
 3: Trial(experiment_name='drug_surfactant', index=3, status=TrialStatus.RUNNING, arm=Arm(name='3_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 91, 'surf_2_conc': 1, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's2'})),
 4: Trial(experiment_name='drug_surfactant', index=4, status=TrialStatus.RUNNING, arm=Arm(name='4_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 32, 'surf_2_conc': 14, 'drug_conc': 25.0, 'surf_1': 's3', 'surf_2': 's4'})),
 5: Trial(experiment_name='drug_surfactant', index=5, status=TrialStatus.RUNNING, arm=Arm(name='5_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 18, 'surf_2_conc': 76, 'drug_conc': 25.0, 'surf_1': 's8', 'surf_2': 's1'})),
 6: Trial(experiment_name='drug_surfactant', index=6, status=TrialStatus.RUNNING, arm=Arm(name='6_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 59, 'surf_2_conc': 3, 'drug_conc': 25.0, 'surf_1': 's8', 'surf_2': 's2'})),
 7: Trial(experiment_name='drug_surfactant', index=7, status=TrialStatus.RUNNING, arm=Arm(name='7_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 2, 'surf_2_conc': 66, 'drug_conc': 25.0, 'surf_1': 's3', 'surf_2': 's6'})),
 8: Trial(experiment_name='drug_surfactant', index=8, status=TrialStatus.RUNNING, arm=Arm(name='8_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 48, 'surf_2_conc': 31, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's6'})),
 9: Trial(experiment_name='drug_surfactant', index=9, status=TrialStatus.RUNNING, arm=Arm(name='9_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 12, 'surf_2_conc': 18, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's8'})),
 10: Trial(experiment_name='drug_surfactant', index=10, status=TrialStatus.RUNNING, arm=Arm(name='10_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 22, 'surf_2_conc': 10, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's1'})),
 11: Trial(experiment_name='drug_surfactant', index=11, status=TrialStatus.RUNNING, arm=Arm(name='11_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 55, 'surf_2_conc': 24, 'drug_conc': 25.0, 'surf_1': 's2', 'surf_2': 's4'})),
 12: Trial(experiment_name='drug_surfactant', index=12, status=TrialStatus.RUNNING, arm=Arm(name='12_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 12, 'surf_2_conc': 61, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's8'})),
 13: Trial(experiment_name='drug_surfactant', index=13, status=TrialStatus.RUNNING, arm=Arm(name='13_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 38, 'surf_2_conc': 48, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's1'})),
 14: Trial(experiment_name='drug_surfactant', index=14, status=TrialStatus.RUNNING, arm=Arm(name='14_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 1, 'surf_2_conc': 75, 'drug_conc': 25.0, 'surf_1': 's2', 'surf_2': 's7'})),
 15: Trial(experiment_name='drug_surfactant', index=15, status=TrialStatus.RUNNING, arm=Arm(name='15_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 57, 'surf_2_conc': 12, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's3'})),
 16: Trial(experiment_name='drug_surfactant', index=16, status=TrialStatus.RUNNING, arm=Arm(name='16_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 49, 'surf_2_conc': 35, 'drug_conc': 25.0, 'surf_1': 's8', 'surf_2': 's5'})),
 17: Trial(experiment_name='drug_surfactant', index=17, status=TrialStatus.RUNNING, arm=Arm(name='17_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 15, 'surf_2_conc': 22, 'drug_conc': 25.0, 'surf_1': 's2', 'surf_2': 's5'})),
 18: Trial(experiment_name='drug_surfactant', index=18, status=TrialStatus.RUNNING, arm=Arm(name='18_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 24, 'surf_2_conc': 5, 'drug_conc': 25.0, 'surf_1': 's2', 'surf_2': 's2'})),
 19: Trial(experiment_name='drug_surfactant', index=19, status=TrialStatus.RUNNING, arm=Arm(name='19_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 10, 'surf_2_conc': 54, 'drug_conc': 25.0, 'surf_1': 's3', 'surf_2': 's7'})),
 20: Trial(experiment_name='drug_surfactant', index=20, status=TrialStatus.RUNNING, arm=Arm(name='20_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 54, 'surf_2_conc': 17, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's5'})),
 21: Trial(experiment_name='drug_surfactant', index=21, status=TrialStatus.RUNNING, arm=Arm(name='21_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 40, 'surf_2_conc': 43, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's4'})),
 22: Trial(experiment_name='drug_surfactant', index=22, status=TrialStatus.RUNNING, arm=Arm(name='22_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 30, 'surf_2_conc': 2, 'drug_conc': 25.0, 'surf_1': 's3', 'surf_2': 's8'})),
 23: Trial(experiment_name='drug_surfactant', index=23, status=TrialStatus.RUNNING, arm=Arm(name='23_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 63, 'surf_2_conc': 25, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's5'})),
 24: Trial(experiment_name='drug_surfactant', index=24, status=TrialStatus.RUNNING, arm=Arm(name='24_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 9, 'surf_2_conc': 40, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's4'})),
 25: Trial(experiment_name='drug_surfactant', index=25, status=TrialStatus.RUNNING, arm=Arm(name='25_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 41, 'surf_2_conc': 50, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's3'})),
 26: Trial(experiment_name='drug_surfactant', index=26, status=TrialStatus.RUNNING, arm=Arm(name='26_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 5, 'surf_2_conc': 32, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's3'})),
 27: Trial(experiment_name='drug_surfactant', index=27, status=TrialStatus.RUNNING, arm=Arm(name='27_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 89, 'surf_2_conc': 8, 'drug_conc': 25.0, 'surf_1': 's8', 'surf_2': 's1'})),
 28: Trial(experiment_name='drug_surfactant', index=28, status=TrialStatus.RUNNING, arm=Arm(name='28_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 34, 'surf_2_conc': 20, 'drug_conc': 25.0, 'surf_1': 's2', 'surf_2': 's7'})),
 29: Trial(experiment_name='drug_surfactant', index=29, status=TrialStatus.RUNNING, arm=Arm(name='29_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 16, 'surf_2_conc': 83, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's2'})),
 30: Trial(experiment_name='drug_surfactant', index=30, status=TrialStatus.RUNNING, arm=Arm(name='30_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 72, 'surf_2_conc': 15, 'drug_conc': 25.0, 'surf_1': 's8', 'surf_2': 's2'})),
 31: Trial(experiment_name='drug_surfactant', index=31, status=TrialStatus.RUNNING, arm=Arm(name='31_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 14, 'surf_2_conc': 53, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's1'}))}

In [ ]:
df_design, df_vol = hf.design_to_vol (n)
df_design

,trial_index,drug_name,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,drug_conc,surf_1,surf_2,surf_conc,obj_surf_conc
0,0,IBP,0.2063,0.3073,0.0373,29,6,25.0,s7,s6,35,NaN
1,1,IBP,0.2063,0.3073,0.0373,6,44,25.0,s4,s4,50,NaN
2,2,IBP,0.2063,0.3073,0.0373,4,27,25.0,s2,s6,31,NaN
3,3,IBP,0.2063,0.3073,0.0373,91,1,25.0,s1,s2,92,NaN
4,4,IBP,0.2063,0.3073,0.0373,32,14,25.0,s3,s4,46,NaN
5,5,IBP,0.2063,0.3073,0.0373,18,76,25.0,s8,s1,94,NaN
6,6,IBP,0.2063,0.3073,0.0373,59,3,25.0,s8,s2,62,NaN
7,7,IBP,0.2063,0.3073,0.0373,2,66,25.0,s3,s6,68,NaN
8,8,IBP,0.2063,0.3073,0.0373,48,31,25.0,s4,s6,79,NaN
9,9,IBP,0.2063,0.3073,0.0373,12,18,25.0,s4,s8,30,NaN
10,10,IBP,0.2063,0.3073,0.0373,22,10,25.0,s6,s1,32,NaN
11,11,IBP,0.2063,0.3073,0.0373,55,24,25.0,s2,s4,79,NaN
12,12,IBP,0.2063,0.3073,0.0373,12,61,25.0,s1,s8,73,NaN
13,13,IBP,0.2063,0.3073,0.0373,38,48,25.0,s1,s1,86,NaN
14,14,IBP,0.2063,0.3073,0.0373,1,75,25.0,s2,s7,76,NaN
15,15,IBP,0.2063,0.3073,0.0373,57,12,25.0,s1,s3,69,NaN
16,16,IBP,0.2063,0.3073,0.0373,49,35,25.0,s8,s5,84,NaN
17,17,IBP,0.2063,0.3073,0.0373,15,22,25.0,s2,s5,37,NaN
18,18,IBP,0.2063,0.3073,0.0373,24,5,25.0,s2,s2,29,NaN
19,19,IBP,0.2063,0.3073,0.0373,10,54,25.0,s3,s7,64,NaN
20,20,IBP,0.2063,0.3073,0.0373,54,17,25.0,s1,s5,71,NaN
21,21,IBP,0.2063,0.3073,0.0373,40,43,25.0,s6,s4,83,NaN
22,22,IBP,0.2063,0.3073,0.0373,30,2,25.0,s3,s8,32,NaN
23,23,IBP,0.2063,0.3073,0.0373,63,25,25.0,s1,s5,88,NaN
24,24,IBP,0.2063,0.3073,0.0373,9,40,25.0,s7,s4,49,NaN
25,25,IBP,0.2063,0.3073,0.0373,41,50,25.0,s6,s3,91,NaN
26,26,IBP,0.2063,0.3073,0.0373,5,32,25.0,s6,s3,37,NaN
27,27,IBP,0.2063,0.3073,0.0373,89,8,25.0,s8,s1,97,NaN
28,28,IBP,0.2063,0.3073,0.0373,34,20,25.0,s2,s7,54,NaN
29,29,IBP,0.2063,0.3073,0.0373,16,83,25.0,s7,s2,99,NaN
30,30,IBP,0.2063,0.3073,0.0373,72,15,25.0,s8,s2,87,NaN
31,31,IBP,0.2063,0.3073,0.0373,14,53,25.0,s6,s1,67,NaN

In [ ]:
df_vol

,trial_index,drug_name,drug,s1,s2,s3,s4,s5,s6,s7,s8,dmso,water,IBP
0,0,IBP,180.0,0.0,0.0,0.0,0.0,0.0,72.0,348.0,0.0,0.0,780.0,180.0
1,1,IBP,180.0,0.0,0.0,0.0,600.0,0.0,0.0,0.0,0.0,0.0,600.0,180.0
2,2,IBP,180.0,0.0,48.0,0.0,0.0,0.0,324.0,0.0,0.0,0.0,828.0,180.0
3,3,IBP,180.0,1092.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,96.0,180.0
4,4,IBP,180.0,0.0,0.0,384.0,168.0,0.0,0.0,0.0,0.0,0.0,648.0,180.0
5,5,IBP,180.0,912.0,0.0,0.0,0.0,0.0,0.0,0.0,216.0,0.0,72.0,180.0
6,6,IBP,180.0,0.0,36.0,0.0,0.0,0.0,0.0,0.0,708.0,0.0,456.0,180.0
7,7,IBP,180.0,0.0,0.0,24.0,0.0,0.0,792.0,0.0,0.0,0.0,384.0,180.0
8,8,IBP,180.0,0.0,0.0,0.0,576.0,0.0,372.0,0.0,0.0,0.0,252.0,180.0
9,9,IBP,180.0,0.0,0.0,0.0,144.0,0.0,0.0,0.0,216.0,0.0,840.0,180.0
10,10,IBP,180.0,120.0,0.0,0.0,0.0,0.0,264.0,0.0,0.0,0.0,816.0,180.0
11,11,IBP,180.0,0.0,660.0,0.0,288.0,0.0,0.0,0.0,0.0,0.0,252.0,180.0
12,12,IBP,180.0,144.0,0.0,0.0,0.0,0.0,0.0,0.0,732.0,0.0,324.0,180.0
13,13,IBP,180.0,1032.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,168.0,180.0
14,14,IBP,180.0,0.0,12.0,0.0,0.0,0.0,0.0,900.0,0.0,0.0,288.0,180.0
15,15,IBP,180.0,684.0,0.0,144.0,0.0,0.0,0.0,0.0,0.0,0.0,372.0,180.0
16,16,IBP,180.0,0.0,0.0,0.0,0.0,420.0,0.0,0.0,588.0,0.0,192.0,180.0
17,17,IBP,180.0,0.0,180.0,0.0,0.0,264.0,0.0,0.0,0.0,0.0,756.0,180.0
18,18,IBP,180.0,0.0,348.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,852.0,180.0
19,19,IBP,180.0,0.0,0.0,120.0,0.0,0.0,0.0,648.0,0.0,0.0,432.0,180.0
20,20,IBP,180.0,648.0,0.0,0.0,0.0,204.0,0.0,0.0,0.0,0.0,348.0,180.0
21,21,IBP,180.0,0.0,0.0,0.0,516.0,0.0,480.0,0.0,0.0,0.0,204.0,180.0
22,22,IBP,180.0,0.0,0.0,360.0,0.0,0.0,0.0,0.0,24.0,0.0,816.0,180.0
23,23,IBP,180.0,756.0,0.0,0.0,0.0,300.0,0.0,0.0,0.0,0.0,144.0,180.0
24,24,IBP,180.0,0.0,0.0,0.0,480.0,0.0,0.0,108.0,0.0,0.0,612.0,180.0
25,25,IBP,180.0,0.0,0.0,600.0,0.0,0.0,492.0,0.0,0.0,0.0,108.0,180.0
26,26,IBP,180.0,0.0,0.0,384.0,0.0,0.0,60.0,0.0,0.0,0.0,756.0,180.0
27,27,IBP,180.0,96.0,0.0,0.0,0.0,0.0,0.0,0.0,1068.0,0.0,36.0,180.0
28,28,IBP,180.0,0.0,408.0,0.0,0.0,0.0,0.0,240.0,0.0,0.0,552.0,180.0
29,29,IBP,180.0,0.0,996.0,0.0,0.0,0.0,0.0,192.0,0.0,0.0,12.0,180.0
30,30,IBP,180.0,0.0,180.0,0.0,0.0,0.0,0.0,0.0,864.0,0.0,156.0,180.0
31,31,IBP,180.0,636.0,0.0,0.0,0.0,0.0,168.0,0.0,0.0,0.0,396.0,180.0

In [ ]:
df_vol.sum()

trial_index                                                  496
drug_name      IBPIBPIBPIBPIBPIBPIBPIBPIBPIBPIBPIBPIBPIBPIBPI...
drug                                                      5760.0
s1                                                        6120.0
s2                                                        2880.0
s3                                                        2016.0
s4                                                        2772.0
s5                                                        1188.0
s6                                                        3024.0
s7                                                        2436.0
s8                                                        4416.0
dmso                                                         0.0
water                                                    13548.0
IBP                                                       5760.0
dtype: object

In [ ]:
plate_well = input("Enter the plate well starting well (e.g., F1): ")
deepplate_well = input("Enter the deep plate well starting well (e.g., F1): ")



print("Please confirm the following information:")
print("Wellplate will start at: " + plate_well)
print("Deep plate will start at: " + deepplate_well)



print()
print("*******************************************************")
print("Continue if correct, or rerun this cell if incorrect.")
print("*******************************************************")

Please confirm the following information:
Wellplate will start at: A1
Deep plate will start at: A!

*******************************************************
Continue if correct, or rerun this cell if incorrect.
*******************************************************

In [ ]:
hf.generate_protocol(df_vol=df_vol, iteration=n, plate_well=plate_well, deepplate_well=deepplate_well)

🔍 Scanning for data block...
⚠️ start_idx not found — no '#####' or 'data = [' detected after the marker.
⚠️ end_idx not found — no closing '#####' line detected after data block.
❌ Could not locate the block to replace.
⚠️ start_idx not found. Check the lines after the marker:

In [ ]:
df_absorbance = hf.process_absorbance(iteration=n, threshold=0.06)
df_absorbance

    trial_index  success
0             0        1
1             1        1
2             2        0
3             3        1
4             4        1
5             5        1
6             6        1
7             7        0
8             8        1
9             9        1
10           10        0
11           11        0
12           12        1
13           13        0
14           14        0
15           15        0
16           16        1
17           17        0
18           18        0
19           19        0
20           20        0
21           21        0
22           22        0
23           23        0
24           24        1
25           25        0
26           26        0
27           27        1
28           28        1
29           29        0
30           30        1
31           31        1

In [ ]:
results = hf.build_results(n, df_absorbance)
results

,trial_index,drug_name,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,drug_conc,surf_1,surf_2,surf_conc,obj_surf_conc,success
0,0,IBP,0.2063,0.3073,0.0373,29,6,25.0,s7,s6,35,35,1
1,1,IBP,0.2063,0.3073,0.0373,6,44,25.0,s4,s4,50,50,1
2,2,IBP,0.2063,0.3073,0.0373,4,27,25.0,s2,s6,31,100,0
3,3,IBP,0.2063,0.3073,0.0373,91,1,25.0,s1,s2,92,92,1
4,4,IBP,0.2063,0.3073,0.0373,32,14,25.0,s3,s4,46,46,1
5,5,IBP,0.2063,0.3073,0.0373,18,76,25.0,s8,s1,94,94,1
6,6,IBP,0.2063,0.3073,0.0373,59,3,25.0,s8,s2,62,62,1
7,7,IBP,0.2063,0.3073,0.0373,2,66,25.0,s3,s6,68,100,0
8,8,IBP,0.2063,0.3073,0.0373,48,31,25.0,s4,s6,79,79,1
9,9,IBP,0.2063,0.3073,0.0373,12,18,25.0,s4,s8,30,30,1
10,10,IBP,0.2063,0.3073,0.0373,22,10,25.0,s6,s1,32,100,0
11,11,IBP,0.2063,0.3073,0.0373,55,24,25.0,s2,s4,79,100,0
12,12,IBP,0.2063,0.3073,0.0373,12,61,25.0,s1,s8,73,73,1
13,13,IBP,0.2063,0.3073,0.0373,38,48,25.0,s1,s1,86,100,0
14,14,IBP,0.2063,0.3073,0.0373,1,75,25.0,s2,s7,76,100,0
15,15,IBP,0.2063,0.3073,0.0373,57,12,25.0,s1,s3,69,100,0
16,16,IBP,0.2063,0.3073,0.0373,49,35,25.0,s8,s5,84,84,1
17,17,IBP,0.2063,0.3073,0.0373,15,22,25.0,s2,s5,37,100,0
18,18,IBP,0.2063,0.3073,0.0373,24,5,25.0,s2,s2,29,100,0
19,19,IBP,0.2063,0.3073,0.0373,10,54,25.0,s3,s7,64,100,0
20,20,IBP,0.2063,0.3073,0.0373,54,17,25.0,s1,s5,71,100,0
21,21,IBP,0.2063,0.3073,0.0373,40,43,25.0,s6,s4,83,100,0
22,22,IBP,0.2063,0.3073,0.0373,30,2,25.0,s3,s8,32,100,0
23,23,IBP,0.2063,0.3073,0.0373,63,25,25.0,s1,s5,88,100,0
24,24,IBP,0.2063,0.3073,0.0373,9,40,25.0,s7,s4,49,49,1
25,25,IBP,0.2063,0.3073,0.0373,41,50,25.0,s6,s3,91,100,0
26,26,IBP,0.2063,0.3073,0.0373,5,32,25.0,s6,s3,37,100,0
27,27,IBP,0.2063,0.3073,0.0373,89,8,25.0,s8,s1,97,97,1
28,28,IBP,0.2063,0.3073,0.0373,34,20,25.0,s2,s7,54,54,1
29,29,IBP,0.2063,0.3073,0.0373,16,83,25.0,s7,s2,99,100,0
30,30,IBP,0.2063,0.3073,0.0373,72,15,25.0,s8,s2,87,87,1
31,31,IBP,0.2063,0.3073,0.0373,14,53,25.0,s6,s1,67,67,1

# load the results to the optimizer

In [ ]:
ax_client = hf.load_data_to_optimizer(iteration = n, results = results)
ax_client

[INFO 11-24 11:10:40] ax.service.ax_client: Completed trial 0 with data: {'obj_surf_conc': (35.0, None)}.
[INFO 11-24 11:10:40] ax.service.ax_client: Completed trial 1 with data: {'obj_surf_conc': (50.0, None)}.
[INFO 11-24 11:10:40] ax.service.ax_client: Completed trial 2 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 11-24 11:10:40] ax.service.ax_client: Completed trial 3 with data: {'obj_surf_conc': (92.0, None)}.
[INFO 11-24 11:10:40] ax.service.ax_client: Completed trial 4 with data: {'obj_surf_conc': (46.0, None)}.
[INFO 11-24 11:10:40] ax.service.ax_client: Completed trial 5 with data: {'obj_surf_conc': (94.0, None)}.
[INFO 11-24 11:10:40] ax.service.ax_client: Completed trial 6 with data: {'obj_surf_conc': (62.0, None)}.
[INFO 11-24 11:10:40] ax.service.ax_client: Completed trial 7 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 11-24 11:10:40] ax.service.ax_client: Completed trial 8 with data: {'obj_surf_conc': (79.0, None)}.
[INFO 11-24 11:10:40] ax.service.ax_client: Completed trial 9 with data: {'obj_surf_conc': (30.0, None)}.
[INFO 11-24 11:10:40] ax.service.ax_client: Completed trial 10 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 11-24 11:10:40] ax.service.ax_client: Completed trial 11 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 11-24 11:10:40] ax.service.ax_client: Completed trial 12 with data: {'obj_surf_conc': (73.0, None)}.
[INFO 11-24 11:10:40] ax.service.ax_client: Completed trial 13 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 11-24 11:10:40] ax.service.ax_client: Completed trial 14 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 11-24 11:10:40] ax.service.ax_client: Completed trial 15 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 11-24 11:10:41] ax.service.ax_client: Completed trial 16 with data: {'obj_surf_conc': (84.0, None)}.
[INFO 11-24 11:10:41] ax.service.ax_client: Completed trial 17 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 11-24 11:10:41] ax.service.ax_client: Completed trial 18 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 11-24 11:10:41] ax.service.ax_client: Completed trial 19 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 11-24 11:10:41] ax.service.ax_client: Completed trial 20 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 11-24 11:10:41] ax.service.ax_client: Completed trial 21 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 11-24 11:10:41] ax.service.ax_client: Completed trial 22 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 11-24 11:10:41] ax.service.ax_client: Completed trial 23 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 11-24 11:10:41] ax.service.ax_client: Completed trial 24 with data: {'obj_surf_conc': (49.0, None)}.
[INFO 11-24 11:10:41] ax.service.ax_client: Completed trial 25 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 11-24 11:10:41] ax.service.ax_client: Completed trial 26 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 11-24 11:10:41] ax.service.ax_client: Completed trial 27 with data: {'obj_surf_conc': (97.0, None)}.
[INFO 11-24 11:10:41] ax.service.ax_client: Completed trial 28 with data: {'obj_surf_conc': (54.0, None)}.
[INFO 11-24 11:10:41] ax.service.ax_client: Completed trial 29 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 11-24 11:10:41] ax.service.ax_client: Completed trial 30 with data: {'obj_surf_conc': (87.0, None)}.
[INFO 11-24 11:10:41] ax.service.ax_client: Completed trial 31 with data: {'obj_surf_conc': (67.0, None)}.

AxClient(experiment=Experiment(drug_surfactant))