# import libraries

In [1]:
import pandas as pd
from ax.service.ax_client import AxClient, ObjectiveProperties
import matplotlib.pyplot as plt
from ax.modelbridge.registry import Models
from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy   
import time

import sys
sys.path.append('../')
import helper_functions as hf

/var/folders/hk/7jjnrbrj53n1t8_bmkhf0_k00000gn/T/ipykernel_57948/1711932296.py:5: DeprecationWarning: Please import from 'ax.generation_strategy.generation_strategy' instead of 'ax.modelbridge.generation_strategy'. The latter is deprecated and will be removed in a future release.
  from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy

# initialize the optimizer

In [2]:
ax_client_init_file_name = 'optimizer/optimizer_00.json'
ax_client = hf.optimizer_init()
ax_client

ValueError: Parameter constraint should be of form <parameter_name> >= <other_parameter_name> for order constraints or `<parameter_name> + <other_parameter_name> >= x, where any number of terms can be added and `x` is a float bound. Acceptable comparison operators are ">=" and "<=".

In [4]:
ax_client.save_to_json_file(ax_client_init_file_name)

# generate recommendations

In [5]:
n = hf.get_iteration_number()

for i in range(3):
    print("Very Important: Please Confirm the Iteration Number is Iteration " + str(n))

print()

list_of_drugs = ['IBP'] * 2 + ['LOV'] * 2 + ['DCF'] * 2 + ['GLV'] * 2

for i in range(3):
    print("Very Important: Please Confirm the Drugs are: ", list_of_drugs)

Very Important: Please Confirm the Iteration Number is Iteration 0
Very Important: Please Confirm the Iteration Number is Iteration 0
Very Important: Please Confirm the Iteration Number is Iteration 0

Very Important: Please Confirm the Drugs are:  ['IBP', 'IBP', 'LOV', 'LOV', 'DCF', 'DCF', 'GLV', 'GLV']
Very Important: Please Confirm the Drugs are:  ['IBP', 'IBP', 'LOV', 'LOV', 'DCF', 'DCF', 'GLV', 'GLV']
Very Important: Please Confirm the Drugs are:  ['IBP', 'IBP', 'LOV', 'LOV', 'DCF', 'DCF', 'GLV', 'GLV']

In [6]:
time_start = time.time()



df_design, ax_client = hf.run_optimizer(current_iteration=n, drug_list= list_of_drugs, bopt=0)

time_end = time.time()
time_duration = round((time_end - time_start)/60,2)

print("Time taken for optimization: " + str(time_duration) + " mins")
print("Time taken for optimization: " + str(time_duration * 60) + " seconds")

[INFO 07-11 09:33:24] ax.service.ax_client: Generated new trial 0 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 48, 's2': 60, 's3': 49, 's4': 31, 's5': 96, 's6': 8, 's7': 9, 's8': 35, 'surfactant_conc': 86, 'drug_conc': 100} using model Sobol.
[INFO 07-11 09:33:24] ax.service.ax_client: Generated new trial 1 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 74, 's2': 0, 's3': 88, 's4': 66, 's5': 22, 's6': 52, 's7': 58, 's8': 79, 'surfactant_conc': 35, 'drug_conc': 100} using model Sobol.
[INFO 07-11 09:33:24] ax.service.ax_client: Generated new trial 2 with parameters {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 's1': 78, 's2': 88, 's3': 1, 's4': 3, 's5': 32, 's6': 94, 's7': 44, 's8': 58, 'surfactant_conc': 1, 'drug_conc': 100} using model Sobol.
[INFO 07-11 09:33:24] ax.service.ax_client: Generated new trial 3 with parameters {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 's1': 0, 's2': 46, 's3': 61, 's4': 94, 's5': 63, 's6': 49, 's7': 98, 's8': 0, 'surfactant_conc': 52, 'drug_conc': 100} using model Sobol.
[INFO 07-11 09:33:24] ax.service.ax_client: Generated new trial 4 with parameters {'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 's1': 16, 's2': 82, 's3': 85, 's4': 84, 's5': 71, 's6': 23, 's7': 35, 's8': 65, 'surfactant_conc': 21, 'drug_conc': 100} using model Sobol.
[INFO 07-11 09:33:24] ax.service.ax_client: Generated new trial 5 with parameters {'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 's1': 93, 's2': 27, 's3': 27, 's4': 17, 's5': 47, 's6': 67, 's7': 83, 's8': 22, 'surfactant_conc': 71, 'drug_conc': 100} using model Sobol.
[INFO 07-11 09:33:24] ax.service.ax_client: Generated new trial 6 with parameters {'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 's1': 59, 's2': 65, 's3': 62, 's4': 55, 's5': 7, 's6': 76, 's7': 19, 's8': 43, 'surfactant_conc': 94, 'drug_conc': 100} using model Sobol.
[INFO 07-11 09:33:24] ax.service.ax_client: Generated new trial 7 with parameters {'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 's1': 31, 's2': 19, 's3': 25, 's4': 46, 's5': 87, 's6': 32, 's7': 74, 's8': 99, 'surfactant_conc': 44, 'drug_conc': 100} using model Sobol.

**************************************************************************************************** 1  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Ibuprofen IBP  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************
**************************************************************************************************** 2  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Ibuprofen IBP  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************
**************************************************************************************************** 3  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Lovastatin LOV  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************
**************************************************************************************************** 4  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Lovastatin LOV  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************
**************************************************************************************************** 5  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Diclofenac DCF  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************
**************************************************************************************************** 6  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Diclofenac DCF  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************
**************************************************************************************************** 7  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Griseofulvin GLV  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************
**************************************************************************************************** 8  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Griseofulvin GLV  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************
Time taken for optimization: 0.0 mins
Time taken for optimization: 0.0 seconds

# process results

In [7]:
ax_client = hf.load_design_optimizer(n)
ax_client.experiment.trials

{0: Trial(experiment_name='drug_surfactant', index=0, status=TrialStatus.RUNNING, arm=Arm(name='0_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 48, 's2': 60, 's3': 49, 's4': 31, 's5': 96, 's6': 8, 's7': 9, 's8': 35, 'surfactant_conc': 86, 'drug_conc': 100})),
 1: Trial(experiment_name='drug_surfactant', index=1, status=TrialStatus.RUNNING, arm=Arm(name='1_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 74, 's2': 0, 's3': 88, 's4': 66, 's5': 22, 's6': 52, 's7': 58, 's8': 79, 'surfactant_conc': 35, 'drug_conc': 100})),
 2: Trial(experiment_name='drug_surfactant', index=2, status=TrialStatus.RUNNING, arm=Arm(name='2_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 's1': 78, 's2': 88, 's3': 1, 's4': 3, 's5': 32, 's6': 94, 's7': 44, 's8': 58, 'surfactant_conc': 1, 'drug_conc': 100})),
 3: Trial(experiment_name='drug_surfactant', index=3, status=TrialStatus.RUNNING, arm=Arm(name='3_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 's1': 0, 's2': 46, 's3': 61, 's4': 94, 's5': 63, 's6': 49, 's7': 98, 's8': 0, 'surfactant_conc': 52, 'drug_conc': 100})),
 4: Trial(experiment_name='drug_surfactant', index=4, status=TrialStatus.RUNNING, arm=Arm(name='4_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 's1': 16, 's2': 82, 's3': 85, 's4': 84, 's5': 71, 's6': 23, 's7': 35, 's8': 65, 'surfactant_conc': 21, 'drug_conc': 100})),
 5: Trial(experiment_name='drug_surfactant', index=5, status=TrialStatus.RUNNING, arm=Arm(name='5_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 's1': 93, 's2': 27, 's3': 27, 's4': 17, 's5': 47, 's6': 67, 's7': 83, 's8': 22, 'surfactant_conc': 71, 'drug_conc': 100})),
 6: Trial(experiment_name='drug_surfactant', index=6, status=TrialStatus.RUNNING, arm=Arm(name='6_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 's1': 59, 's2': 65, 's3': 62, 's4': 55, 's5': 7, 's6': 76, 's7': 19, 's8': 43, 'surfactant_conc': 94, 'drug_conc': 100})),
 7: Trial(experiment_name='drug_surfactant', index=7, status=TrialStatus.RUNNING, arm=Arm(name='7_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 's1': 31, 's2': 19, 's3': 25, 's4': 46, 's5': 87, 's6': 32, 's7': 74, 's8': 99, 'surfactant_conc': 44, 'drug_conc': 100}))}

In [8]:
df_conc, df_vol = hf.design_to_conc_to_vol (n)

In [9]:
df_conc

,trial_index,drug_name,surfactant_conc,drug_conc,s1,s2,s3,s4,s5,s6,s7,s8
0,0,IBP,43.0,25.0,6.142857,7.678571,6.270833,3.967262,12.285714,1.023810,1.151786,4.479167
1,1,IBP,17.5,25.0,2.949886,0.000000,3.507973,2.630979,0.876993,2.072893,2.312073,3.149203
2,2,LOV,0.5,25.0,0.097990,0.110553,0.001256,0.003769,0.040201,0.118090,0.055276,0.072864
3,3,LOV,26.0,25.0,0.000000,2.909976,3.858881,5.946472,3.985401,3.099757,6.199513,0.000000
4,4,DCF,10.5,25.0,0.364425,1.867679,1.936009,1.913232,1.617137,0.523861,0.797180,1.480477
5,5,DCF,35.5,25.0,8.620104,2.502611,2.502611,1.575718,4.356397,6.210183,7.693211,2.039164
6,6,GLV,47.0,25.0,7.183938,7.914508,7.549223,6.696891,0.852332,9.253886,2.313472,5.235751
7,7,GLV,22.0,25.0,1.651332,1.012107,1.331719,2.450363,4.634383,1.704600,3.941889,5.273608

In [10]:
df_vol

,trial_index,drug_name,drug,s1,s2,s3,s4,s5,s6,s7,s8,dmso,water,IBP,LOV,DCF,GLV
0,0,IBP,180.0,147.428571,184.285714,150.500000,95.214286,294.857143,24.571429,27.642857,107.500000,0.0,168.0,180.0,0.0,0.0,0.0
1,1,IBP,180.0,70.797267,0.000000,84.191344,63.143508,21.047836,49.749431,55.489749,75.580866,0.0,780.0,180.0,0.0,0.0,0.0
2,2,LOV,180.0,2.351759,2.653266,0.030151,0.090452,0.964824,2.834171,1.326633,1.748744,0.0,1188.0,0.0,180.0,0.0,0.0
3,3,LOV,180.0,0.000000,69.839416,92.613139,142.715328,95.649635,74.394161,148.788321,0.000000,0.0,576.0,0.0,180.0,0.0,0.0
4,4,DCF,180.0,8.746204,44.824295,46.464208,45.917570,38.811280,12.572668,19.132321,35.531453,0.0,948.0,0.0,0.0,180.0,0.0
5,5,DCF,180.0,206.882507,60.062663,60.062663,37.817232,104.553525,149.044386,184.637076,48.939948,0.0,348.0,0.0,0.0,180.0,0.0
6,6,GLV,180.0,172.414508,189.948187,181.181347,160.725389,20.455959,222.093264,55.523316,125.658031,0.0,72.0,0.0,0.0,0.0,180.0
7,7,GLV,180.0,39.631961,24.290557,31.961259,58.808717,111.225182,40.910412,94.605327,126.566586,0.0,672.0,0.0,0.0,0.0,180.0

In [ ]:
plate_well = input("Enter the plate well starting well (e.g., F1): ")
deepplate_well = input("Enter the deep plate well starting well (e.g., F1): ")



print("Please confirm the following information:")
print("Wellplate will start at: " + plate_well)
print("Deep plate will start at: " + deepplate_well)



print()
print("*******************************************************")
print("Continue if correct, or rerun this cell if incorrect.")
print("*******************************************************")

Please confirm the following information:
Wellplate will start at: E1
Deep plate will start at: G7

*******************************************************
Continue if correct, or rerun this cell if incorrect.
*******************************************************

In [ ]:
hf.generate_protocol(df_vol=df_vol, iteration=n, plate_well=plate_well, deepplate_well=deepplate_well)

✅ Successfully wrote to: protocol/otflex_0.py

In [20]:
df_absorbance = hf.process_absorbance(iteration=n)
df_absorbance

   trial_index  success
0            0        0
1            1        0
2            2        0
3            3        0
4            4        0
5            5        0
6            6        0
7            7        0

In [21]:
df_conc

,trial_index,drug_name,surfactant_conc,drug_conc,s1,s2,s3,s4,s5,s6,s7,s8
0,0,IBP,43.0,25.0,6.142857,7.678571,6.270833,3.967262,12.285714,1.023810,1.151786,4.479167
1,1,IBP,17.5,25.0,2.949886,0.000000,3.507973,2.630979,0.876993,2.072893,2.312073,3.149203
2,2,LOV,0.5,25.0,0.097990,0.110553,0.001256,0.003769,0.040201,0.118090,0.055276,0.072864
3,3,LOV,26.0,25.0,0.000000,2.909976,3.858881,5.946472,3.985401,3.099757,6.199513,0.000000
4,4,DCF,10.5,25.0,0.364425,1.867679,1.936009,1.913232,1.617137,0.523861,0.797180,1.480477
5,5,DCF,35.5,25.0,8.620104,2.502611,2.502611,1.575718,4.356397,6.210183,7.693211,2.039164
6,6,GLV,47.0,25.0,7.183938,7.914508,7.549223,6.696891,0.852332,9.253886,2.313472,5.235751
7,7,GLV,22.0,25.0,1.651332,1.012107,1.331719,2.450363,4.634383,1.704600,3.941889,5.273608

In [22]:
results = hf.build_results(n, df_conc, df_absorbance)

In [23]:
results

,trial_index,drug_name,s1,s2,s3,s4,s5,s6,s7,s8,surfactant_input,drug_conc,success,complexity
0,0,IBP,48,60,49,31,96,8,9,35,43.0,25.0,0,8
1,1,IBP,74,0,88,66,22,52,58,79,17.5,25.0,0,7
2,2,LOV,78,88,1,3,32,94,44,58,0.5,25.0,0,8
3,3,LOV,0,46,61,94,63,49,98,0,26.0,25.0,0,6
4,4,DCF,16,82,85,84,71,23,35,65,10.5,25.0,0,8
5,5,DCF,93,27,27,17,47,67,83,22,35.5,25.0,0,8
6,6,GLV,59,65,62,55,7,76,19,43,47.0,25.0,0,8
7,7,GLV,31,19,25,46,87,32,74,99,22.0,25.0,0,8

In [24]:
norm_results = hf.normalize_data(results, 'normalize')

In [25]:
norm_results

,trial_index,drug_name,s1,s2,s3,s4,s5,s6,s7,s8,surfactant_input,drug_conc,success,complexity
0,0,IBP,48,60,49,31,96,8,9,35,0.86,1.0,0.0,1.000
1,1,IBP,74,0,88,66,22,52,58,79,0.35,1.0,0.0,0.875
2,2,LOV,78,88,1,3,32,94,44,58,0.01,1.0,0.0,1.000
3,3,LOV,0,46,61,94,63,49,98,0,0.52,1.0,0.0,0.750
4,4,DCF,16,82,85,84,71,23,35,65,0.21,1.0,0.0,1.000
5,5,DCF,93,27,27,17,47,67,83,22,0.71,1.0,0.0,1.000
6,6,GLV,59,65,62,55,7,76,19,43,0.94,1.0,0.0,1.000
7,7,GLV,31,19,25,46,87,32,74,99,0.44,1.0,0.0,1.000

# load the results to the optimizer

In [26]:
ax_client = hf.load_data_to_optimizer(iteration = n, norm_results = norm_results)
ax_client

[INFO 07-11 11:45:33] ax.service.ax_client: Completed trial 0 with data: {'success': (0.0, None), 'surfactant_input': (1.0, None), 'complexity': (1.0, None)}.
[INFO 07-11 11:45:33] ax.service.ax_client: Completed trial 1 with data: {'success': (0.0, None), 'surfactant_input': (1.0, None), 'complexity': (1.0, None)}.
[INFO 07-11 11:45:33] ax.service.ax_client: Completed trial 2 with data: {'success': (0.0, None), 'surfactant_input': (1.0, None), 'complexity': (1.0, None)}.
[INFO 07-11 11:45:33] ax.service.ax_client: Completed trial 3 with data: {'success': (0.0, None), 'surfactant_input': (1.0, None), 'complexity': (1.0, None)}.
[INFO 07-11 11:45:33] ax.service.ax_client: Completed trial 4 with data: {'success': (0.0, None), 'surfactant_input': (1.0, None), 'complexity': (1.0, None)}.
[INFO 07-11 11:45:33] ax.service.ax_client: Completed trial 5 with data: {'success': (0.0, None), 'surfactant_input': (1.0, None), 'complexity': (1.0, None)}.
[INFO 07-11 11:45:33] ax.service.ax_client: Completed trial 6 with data: {'success': (0.0, None), 'surfactant_input': (1.0, None), 'complexity': (1.0, None)}.
[INFO 07-11 11:45:33] ax.service.ax_client: Completed trial 7 with data: {'success': (0.0, None), 'surfactant_input': (1.0, None), 'complexity': (1.0, None)}.

Trial 0: success=0 → overriding surfactant_input & complexity to 1
Trial 1: success=0 → overriding surfactant_input & complexity to 1
Trial 2: success=0 → overriding surfactant_input & complexity to 1
Trial 3: success=0 → overriding surfactant_input & complexity to 1
Trial 4: success=0 → overriding surfactant_input & complexity to 1
Trial 5: success=0 → overriding surfactant_input & complexity to 1
Trial 6: success=0 → overriding surfactant_input & complexity to 1
Trial 7: success=0 → overriding surfactant_input & complexity to 1

AxClient(experiment=Experiment(drug_surfactant))