# import libraries

In [1]:
import pandas as pd
from ax.service.ax_client import AxClient, ObjectiveProperties
import matplotlib.pyplot as plt
from ax.modelbridge.registry import Models
from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy   
import time

import sys
sys.path.append('../')
import helper_functions as hf

/var/folders/hk/7jjnrbrj53n1t8_bmkhf0_k00000gn/T/ipykernel_69700/1711932296.py:5: DeprecationWarning: Please import from 'ax.generation_strategy.generation_strategy' instead of 'ax.modelbridge.generation_strategy'. The latter is deprecated and will be removed in a future release.
  from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy

# initialize the optimizer

In [2]:
ax_client_init_file_name = 'optimizer/optimizer_00.json'
ax_client = hf.optimizer_init()
ax_client

[WARNING 07-28 07:53:10] ax.service.utils.instantiation: Objective thresholds were not set. They will be selected using a heuristic, but should be specified on the objective for best performance.
[INFO 07-28 07:53:10] ax.service.utils.instantiation: Inferred value type of ParameterType.STRING for parameter surf_1. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/service/utils/instantiation.py:258: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "surf_1". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return ChoiceParameter(
[INFO 07-28 07:53:10] ax.service.utils.instantiation: Inferred value type of ParameterType.STRING for parameter surf_2. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/service/utils/instantiation.py:258: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "surf_2". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return ChoiceParameter(
[INFO 07-28 07:53:10] ax.service.utils.instantiation: Inferred value type of ParameterType.STRING for parameter surf_3. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/service/utils/instantiation.py:258: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "surf_3". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return ChoiceParameter(

AxClient(experiment=Experiment(drug_surfactant))

In [3]:
ax_client.save_to_json_file(ax_client_init_file_name)

# generate recommendations

In [4]:
n = hf.get_iteration_number()

for i in range(3):
    print("Very Important: Please Confirm the Iteration Number is Iteration " + str(n))

print()

list_of_drugs = ['IBP'] + ['LOV'] + ['DCF'] + ['GLV']
number_of_micelles = 8

for i in range(3):
    print("Very Important: Please Confirm the Drugs are: ", list_of_drugs * number_of_micelles)

Very Important: Please Confirm the Iteration Number is Iteration 0
Very Important: Please Confirm the Iteration Number is Iteration 0
Very Important: Please Confirm the Iteration Number is Iteration 0

Very Important: Please Confirm the Drugs are:  ['IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV']
Very Important: Please Confirm the Drugs are:  ['IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV']
Very Important: Please Confirm the Drugs are:  ['IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV']

In [5]:
time_start = time.time()



df_design, ax_client = hf.run_optimizer(current_iteration=n, number_of_micelles= number_of_micelles,list_of_drugs = list_of_drugs, bopt=0)

time_end = time.time()
time_duration = round((time_end - time_start)/60,2)

print("Time taken for optimization: " + str(time_duration) + " mins")
print("Time taken for optimization: " + str(time_duration * 60) + " seconds")

[WARNING 07-28 07:53:12] ax.modelbridge.transforms.int_to_float: Unable to round {'surf_1_OH_PARAM__0': 0.9114058297127485, 'surf_1_OH_PARAM__1': 0.12204514164477587, 'surf_1_OH_PARAM__2': 0.6231948798522353, 'surf_1_OH_PARAM__3': 0.528020117431879, 'surf_1_OH_PARAM__4': 0.12346591055393219, 'surf_1_OH_PARAM__5': 0.9443953456357121, 'surf_1_OH_PARAM__6': 0.8819846520200372, 'surf_1_OH_PARAM__7': 0.9761280156672001, 'surf_1_conc': 12.311933713330905, 'surf_2_OH_PARAM__0': 0.47298688627779484, 'surf_2_OH_PARAM__1': 0.3318925853818655, 'surf_2_OH_PARAM__2': 0.05016717687249184, 'surf_2_OH_PARAM__3': 0.19726090878248215, 'surf_2_OH_PARAM__4': 0.09863798227161169, 'surf_2_OH_PARAM__5': 0.9639844475314021, 'surf_2_OH_PARAM__6': 0.4952889485284686, 'surf_2_OH_PARAM__7': 0.568336077965796, 'surf_2_conc': 39.48095865415554, 'surf_3_OH_PARAM__0': 0.45170615427196026, 'surf_3_OH_PARAM__1': 0.49170129653066397, 'surf_3_OH_PARAM__2': 0.5686638671904802, 'surf_3_OH_PARAM__3': 0.3353493716567755, 'surf_3_OH_PARAM__4': 0.2346917986869812, 'surf_3_OH_PARAM__5': 0.6671444671228528, 'surf_3_OH_PARAM__6': 0.9587146146222949, 'surf_3_OH_PARAM__7': 0.18187612108886242, 'surf_3_conc': 19.825477309313563, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc + -1.0*surf_3_conc <= -1.0)])

**************************************************************************************************** 1  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[WARNING 07-28 07:53:12] ax.modelbridge.transforms.int_to_float: Unable to round {'surf_1_OH_PARAM__0': 0.0, 'surf_1_OH_PARAM__1': 0.0, 'surf_1_OH_PARAM__2': 0.0, 'surf_1_OH_PARAM__3': 0.0, 'surf_1_OH_PARAM__4': 0.0, 'surf_1_OH_PARAM__5': 0.0, 'surf_1_OH_PARAM__6': 0.0, 'surf_1_OH_PARAM__7': 1.0, 'surf_1_conc': 12.0, 'surf_2_OH_PARAM__0': 0.0, 'surf_2_OH_PARAM__1': 0.0, 'surf_2_OH_PARAM__2': 0.0, 'surf_2_OH_PARAM__3': 0.0, 'surf_2_OH_PARAM__4': 0.0, 'surf_2_OH_PARAM__5': 1.0, 'surf_2_OH_PARAM__6': 0.0, 'surf_2_OH_PARAM__7': 0.0, 'surf_2_conc': 39.0, 'surf_3_OH_PARAM__0': 0.0, 'surf_3_OH_PARAM__1': 0.0, 'surf_3_OH_PARAM__2': 0.0, 'surf_3_OH_PARAM__3': 0.0, 'surf_3_OH_PARAM__4': 0.0, 'surf_3_OH_PARAM__5': 0.0, 'surf_3_OH_PARAM__6': 1.0, 'surf_3_OH_PARAM__7': 0.0, 'surf_3_conc': 20.0, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc + -1.0*surf_3_conc <= -1.0)])
[INFO 07-28 07:53:12] ax.service.ax_client: Generated new trial 0 with parameters {'surf_1_conc': 12, 'surf_2_conc': 39, 'surf_3_conc': 20, 'drug_conc': 25.0, 'surf_1': 's8', 'surf_2': 's6', 'surf_3': 's7'} using model Sobol.
[WARNING 07-28 07:53:12] ax.modelbridge.transforms.int_to_float: Unable to round {'surf_1_OH_PARAM__0': 0.17962588649243116, 'surf_1_OH_PARAM__1': 0.252715477719903, 'surf_1_OH_PARAM__2': 0.8015768546611071, 'surf_1_OH_PARAM__3': 0.7976525351405144, 'surf_1_OH_PARAM__4': 0.6558348573744297, 'surf_1_OH_PARAM__5': 0.2981837596744299, 'surf_1_OH_PARAM__6': 0.6854272913187742, 'surf_1_OH_PARAM__7': 0.16153204068541527, 'surf_1_conc': 50.78568743723018, 'surf_2_OH_PARAM__0': 0.6756753399968147, 'surf_2_OH_PARAM__1': 0.6964397290721536, 'surf_2_OH_PARAM__2': 0.6209493521600962, 'surf_2_OH_PARAM__3': 0.35185046680271626, 'surf_2_OH_PARAM__4': 0.2766580758616328, 'surf_2_OH_PARAM__5': 0.022430391050875187, 'surf_2_OH_PARAM__6': 0.03286267351359129, 'surf_2_OH_PARAM__7': 0.4212197130545974, 'surf_2_conc': 4.355204568334072, 'surf_3_OH_PARAM__0': 0.7282344242557883, 'surf_3_OH_PARAM__1': 0.07807696610689163, 'surf_3_OH_PARAM__2': 0.7561172908172011, 'surf_3_OH_PARAM__3': 0.6241495190188289, 'surf_3_OH_PARAM__4': 0.44303253572434187, 'surf_3_OH_PARAM__5': 0.9537138026207685, 'surf_3_OH_PARAM__6': 0.5561841437593102, 'surf_3_OH_PARAM__7': 0.5710560707375407, 'surf_3_conc': 39.638575508323235, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc + -1.0*surf_3_conc <= -1.0)])
[WARNING 07-28 07:53:12] ax.modelbridge.transforms.int_to_float: Unable to round {'surf_1_OH_PARAM__0': 0.0, 'surf_1_OH_PARAM__1': 0.0, 'surf_1_OH_PARAM__2': 1.0, 'surf_1_OH_PARAM__3': 0.0, 'surf_1_OH_PARAM__4': 0.0, 'surf_1_OH_PARAM__5': 0.0, 'surf_1_OH_PARAM__6': 0.0, 'surf_1_OH_PARAM__7': 0.0, 'surf_1_conc': 51.0, 'surf_2_OH_PARAM__0': 0.0, 'surf_2_OH_PARAM__1': 1.0, 'surf_2_OH_PARAM__2': 0.0, 'surf_2_OH_PARAM__3': 0.0, 'surf_2_OH_PARAM__4': 0.0, 'surf_2_OH_PARAM__5': 0.0, 'surf_2_OH_PARAM__6': 0.0, 'surf_2_OH_PARAM__7': 0.0, 'surf_2_conc': 4.0, 'surf_3_OH_PARAM__0': 0.0, 'surf_3_OH_PARAM__1': 0.0, 'surf_3_OH_PARAM__2': 0.0, 'surf_3_OH_PARAM__3': 0.0, 'surf_3_OH_PARAM__4': 0.0, 'surf_3_OH_PARAM__5': 1.0, 'surf_3_OH_PARAM__6': 0.0, 'surf_3_OH_PARAM__7': 0.0, 'surf_3_conc': 40.0, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc + -1.0*surf_3_conc <= -1.0)])
[INFO 07-28 07:53:12] ax.service.ax_client: Generated new trial 1 with parameters {'surf_1_conc': 51, 'surf_2_conc': 4, 'surf_3_conc': 40, 'drug_conc': 25.0, 'surf_1': 's3', 'surf_2': 's2', 'surf_3': 's6'} using model Sobol.

**************************************************************************************************** 2  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************
**************************************************************************************************** 3  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[WARNING 07-28 07:53:13] ax.modelbridge.transforms.int_to_float: Unable to round {'surf_1_OH_PARAM__0': 0.2560679577291012, 'surf_1_OH_PARAM__1': 0.16973726730793715, 'surf_1_OH_PARAM__2': 0.09652568213641644, 'surf_1_OH_PARAM__3': 0.48208999540656805, 'surf_1_OH_PARAM__4': 0.8239228408783674, 'surf_1_OH_PARAM__5': 0.44252450857311487, 'surf_1_OH_PARAM__6': 0.7984137935563922, 'surf_1_OH_PARAM__7': 0.8024126123636961, 'surf_1_conc': 0.6351051899342053, 'surf_2_OH_PARAM__0': 0.1987256957218051, 'surf_2_OH_PARAM__1': 0.4254197031259537, 'surf_2_OH_PARAM__2': 0.7683166107162833, 'surf_2_OH_PARAM__3': 0.09028095472604036, 'surf_2_OH_PARAM__4': 0.7124296892434359, 'surf_2_OH_PARAM__5': 0.4584317123517394, 'surf_2_OH_PARAM__6': 0.8598455209285021, 'surf_2_OH_PARAM__7': 0.024052626453340054, 'surf_2_conc': 55.59883474704206, 'surf_3_OH_PARAM__0': 0.3589434279128909, 'surf_3_OH_PARAM__1': 0.14834516309201717, 'surf_3_OH_PARAM__2': 0.9981758231297135, 'surf_3_OH_PARAM__3': 0.7194553045555949, 'surf_3_OH_PARAM__4': 0.03066192101687193, 'surf_3_OH_PARAM__5': 0.3439873168244958, 'surf_3_OH_PARAM__6': 0.08775488380342722, 'surf_3_OH_PARAM__7': 0.011810318566858768, 'surf_3_conc': 0.4009079922617785, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc + -1.0*surf_3_conc <= -1.0)])
[WARNING 07-28 07:53:13] ax.modelbridge.transforms.int_to_float: Unable to round {'surf_1_OH_PARAM__0': 0.0, 'surf_1_OH_PARAM__1': 0.0, 'surf_1_OH_PARAM__2': 0.0, 'surf_1_OH_PARAM__3': 0.0, 'surf_1_OH_PARAM__4': 1.0, 'surf_1_OH_PARAM__5': 0.0, 'surf_1_OH_PARAM__6': 0.0, 'surf_1_OH_PARAM__7': 0.0, 'surf_1_conc': 1.0, 'surf_2_OH_PARAM__0': 0.0, 'surf_2_OH_PARAM__1': 0.0, 'surf_2_OH_PARAM__2': 0.0, 'surf_2_OH_PARAM__3': 0.0, 'surf_2_OH_PARAM__4': 0.0, 'surf_2_OH_PARAM__5': 0.0, 'surf_2_OH_PARAM__6': 1.0, 'surf_2_OH_PARAM__7': 0.0, 'surf_2_conc': 56.0, 'surf_3_OH_PARAM__0': 0.0, 'surf_3_OH_PARAM__1': 0.0, 'surf_3_OH_PARAM__2': 1.0, 'surf_3_OH_PARAM__3': 0.0, 'surf_3_OH_PARAM__4': 0.0, 'surf_3_OH_PARAM__5': 0.0, 'surf_3_OH_PARAM__6': 0.0, 'surf_3_OH_PARAM__7': 0.0, 'surf_3_conc': 5.551115123125783e-17, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc + -1.0*surf_3_conc <= -1.0)])
[INFO 07-28 07:53:13] ax.service.ax_client: Generated new trial 2 with parameters {'surf_1_conc': 1, 'surf_2_conc': 56, 'surf_3_conc': 0, 'drug_conc': 25.0, 'surf_1': 's5', 'surf_2': 's7', 'surf_3': 's3'} using model Sobol.
[WARNING 07-28 07:53:13] ax.modelbridge.transforms.int_to_float: Unable to round {'surf_1_OH_PARAM__0': 0.35010251216590405, 'surf_1_OH_PARAM__1': 0.8362639378756285, 'surf_1_OH_PARAM__2': 0.8801511535421014, 'surf_1_OH_PARAM__3': 0.16749133076518774, 'surf_1_OH_PARAM__4': 0.04949513543397188, 'surf_1_OH_PARAM__5': 0.32705025654286146, 'surf_1_OH_PARAM__6': 0.38586085941642523, 'surf_1_OH_PARAM__7': 0.6715440489351749, 'surf_1_conc': 27.934195015281137, 'surf_2_OH_PARAM__0': 0.74383176676929, 'surf_2_OH_PARAM__1': 0.4442800786346197, 'surf_2_OH_PARAM__2': 0.9632726283743978, 'surf_2_OH_PARAM__3': 0.4106331327930093, 'surf_2_OH_PARAM__4': 0.3970977757126093, 'surf_2_OH_PARAM__5': 0.72989946231246, 'surf_2_OH_PARAM__6': 0.20246015768498182, 'surf_2_OH_PARAM__7': 0.8335360595956445, 'surf_2_conc': 6.413930561733748, 'surf_3_OH_PARAM__0': 0.03309438098222017, 'surf_3_OH_PARAM__1': 0.8238679971545935, 'surf_3_OH_PARAM__2': 0.4710205001756549, 'surf_3_OH_PARAM__3': 0.4003961328417063, 'surf_3_OH_PARAM__4': 0.5330627150833607, 'surf_3_OH_PARAM__5': 0.8024456761777401, 'surf_3_OH_PARAM__6': 0.49033475294709206, 'surf_3_OH_PARAM__7': 0.8601722866296768, 'surf_3_conc': 13.798804329873379, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc + -1.0*surf_3_conc <= -1.0)])
[WARNING 07-28 07:53:13] ax.modelbridge.transforms.int_to_float: Unable to round {'surf_1_OH_PARAM__0': 0.0, 'surf_1_OH_PARAM__1': 0.0, 'surf_1_OH_PARAM__2': 1.0, 'surf_1_OH_PARAM__3': 0.0, 'surf_1_OH_PARAM__4': 0.0, 'surf_1_OH_PARAM__5': 0.0, 'surf_1_OH_PARAM__6': 0.0, 'surf_1_OH_PARAM__7': 0.0, 'surf_1_conc': 28.000000000000004, 'surf_2_OH_PARAM__0': 0.0, 'surf_2_OH_PARAM__1': 0.0, 'surf_2_OH_PARAM__2': 1.0, 'surf_2_OH_PARAM__3': 0.0, 'surf_2_OH_PARAM__4': 0.0, 'surf_2_OH_PARAM__5': 0.0, 'surf_2_OH_PARAM__6': 0.0, 'surf_2_OH_PARAM__7': 0.0, 'surf_2_conc': 6.0, 'surf_3_OH_PARAM__0': 0.0, 'surf_3_OH_PARAM__1': 0.0, 'surf_3_OH_PARAM__2': 0.0, 'surf_3_OH_PARAM__3': 0.0, 'surf_3_OH_PARAM__4': 0.0, 'surf_3_OH_PARAM__5': 0.0, 'surf_3_OH_PARAM__6': 0.0, 'surf_3_OH_PARAM__7': 1.0, 'surf_3_conc': 14.0, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc + -1.0*surf_3_conc <= -1.0)])
[INFO 07-28 07:53:13] ax.service.ax_client: Generated new trial 3 with parameters {'surf_1_conc': 28, 'surf_2_conc': 6, 'surf_3_conc': 14, 'drug_conc': 25.0, 'surf_1': 's3', 'surf_2': 's3', 'surf_3': 's8'} using model Sobol.

**************************************************************************************************** 4  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************
**************************************************************************************************** 5  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[WARNING 07-28 07:53:13] ax.modelbridge.transforms.int_to_float: Unable to round {'surf_1_OH_PARAM__0': 0.9764733053743839, 'surf_1_OH_PARAM__1': 0.37518260069191456, 'surf_1_OH_PARAM__2': 0.9374336544424295, 'surf_1_OH_PARAM__3': 0.4561588242650032, 'surf_1_OH_PARAM__4': 0.27046515606343746, 'surf_1_OH_PARAM__5': 0.37585766054689884, 'surf_1_OH_PARAM__6': 0.08167941775172949, 'surf_1_OH_PARAM__7': 0.19148987904191017, 'surf_1_conc': 26.682993032702225, 'surf_2_OH_PARAM__0': 0.3180086314678192, 'surf_2_OH_PARAM__1': 0.2624216275289655, 'surf_2_OH_PARAM__2': 0.3588984711095691, 'surf_2_OH_PARAM__3': 0.8927187044173479, 'surf_2_OH_PARAM__4': 0.8873067069798708, 'surf_2_OH_PARAM__5': 0.7059583617374301, 'surf_2_OH_PARAM__6': 0.4678988056257367, 'surf_2_OH_PARAM__7': 0.382788585498929, 'surf_2_conc': 63.06170065867962, 'surf_3_OH_PARAM__0': 0.6993302786722779, 'surf_3_OH_PARAM__1': 0.4441341506317258, 'surf_3_OH_PARAM__2': 0.44190781842917204, 'surf_3_OH_PARAM__3': 0.7134312717244029, 'surf_3_OH_PARAM__4': 0.7230658372864127, 'surf_3_OH_PARAM__5': 0.4312653811648488, 'surf_3_OH_PARAM__6': 0.14133693277835846, 'surf_3_OH_PARAM__7': 0.046956829726696014, 'surf_3_conc': 2.671463620939143, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc + -1.0*surf_3_conc <= -1.0)])
[WARNING 07-28 07:53:13] ax.modelbridge.transforms.int_to_float: Unable to round {'surf_1_OH_PARAM__0': 1.0, 'surf_1_OH_PARAM__1': 0.0, 'surf_1_OH_PARAM__2': 0.0, 'surf_1_OH_PARAM__3': 0.0, 'surf_1_OH_PARAM__4': 0.0, 'surf_1_OH_PARAM__5': 0.0, 'surf_1_OH_PARAM__6': 0.0, 'surf_1_OH_PARAM__7': 0.0, 'surf_1_conc': 26.999999999999996, 'surf_2_OH_PARAM__0': 0.0, 'surf_2_OH_PARAM__1': 0.0, 'surf_2_OH_PARAM__2': 0.0, 'surf_2_OH_PARAM__3': 1.0, 'surf_2_OH_PARAM__4': 0.0, 'surf_2_OH_PARAM__5': 0.0, 'surf_2_OH_PARAM__6': 0.0, 'surf_2_OH_PARAM__7': 0.0, 'surf_2_conc': 62.99999999999999, 'surf_3_OH_PARAM__0': 0.0, 'surf_3_OH_PARAM__1': 0.0, 'surf_3_OH_PARAM__2': 0.0, 'surf_3_OH_PARAM__3': 0.0, 'surf_3_OH_PARAM__4': 1.0, 'surf_3_OH_PARAM__5': 0.0, 'surf_3_OH_PARAM__6': 0.0, 'surf_3_OH_PARAM__7': 0.0, 'surf_3_conc': 3.0, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc + -1.0*surf_3_conc <= -1.0)])
[INFO 07-28 07:53:13] ax.service.ax_client: Generated new trial 4 with parameters {'surf_1_conc': 27, 'surf_2_conc': 63, 'surf_3_conc': 3, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's4', 'surf_3': 's5'} using model Sobol.
[WARNING 07-28 07:53:13] ax.modelbridge.transforms.int_to_float: Unable to round {'surf_1_OH_PARAM__0': 0.3169923182576895, 'surf_1_OH_PARAM__1': 0.3291974626481533, 'surf_1_OH_PARAM__2': 0.409301626496017, 'surf_1_OH_PARAM__3': 0.533214527182281, 'surf_1_OH_PARAM__4': 0.532392106950283, 'surf_1_OH_PARAM__5': 0.8777251746505499, 'surf_1_OH_PARAM__6': 0.22371808160096407, 'surf_1_OH_PARAM__7': 0.021668685600161552, 'surf_1_conc': 39.93878002300726, 'surf_2_OH_PARAM__0': 0.1040501156821847, 'surf_2_OH_PARAM__1': 0.481212112121284, 'surf_2_OH_PARAM__2': 0.5762844681739807, 'surf_2_OH_PARAM__3': 0.7574788024649024, 'surf_2_OH_PARAM__4': 0.2969830175861716, 'surf_2_OH_PARAM__5': 0.21542021539062262, 'surf_2_OH_PARAM__6': 0.832483347505331, 'surf_2_OH_PARAM__7': 0.9635052643716335, 'surf_2_conc': 28.88920551689645, 'surf_3_OH_PARAM__0': 0.6065671406686306, 'surf_3_OH_PARAM__1': 0.16276684775948524, 'surf_3_OH_PARAM__2': 0.12199932336807251, 'surf_3_OH_PARAM__3': 0.3567525949329138, 'surf_3_OH_PARAM__4': 0.511098925024271, 'surf_3_OH_PARAM__5': 0.6118335211649537, 'surf_3_OH_PARAM__6': 0.7781963814049959, 'surf_3_OH_PARAM__7': 0.13104548212140799, 'surf_3_conc': 22.293154230425227, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc + -1.0*surf_3_conc <= -1.0)])
[WARNING 07-28 07:53:13] ax.modelbridge.transforms.int_to_float: Unable to round {'surf_1_OH_PARAM__0': 0.0, 'surf_1_OH_PARAM__1': 0.0, 'surf_1_OH_PARAM__2': 0.0, 'surf_1_OH_PARAM__3': 0.0, 'surf_1_OH_PARAM__4': 0.0, 'surf_1_OH_PARAM__5': 1.0, 'surf_1_OH_PARAM__6': 0.0, 'surf_1_OH_PARAM__7': 0.0, 'surf_1_conc': 40.0, 'surf_2_OH_PARAM__0': 0.0, 'surf_2_OH_PARAM__1': 0.0, 'surf_2_OH_PARAM__2': 0.0, 'surf_2_OH_PARAM__3': 0.0, 'surf_2_OH_PARAM__4': 0.0, 'surf_2_OH_PARAM__5': 0.0, 'surf_2_OH_PARAM__6': 0.0, 'surf_2_OH_PARAM__7': 1.0, 'surf_2_conc': 29.0, 'surf_3_OH_PARAM__0': 0.0, 'surf_3_OH_PARAM__1': 0.0, 'surf_3_OH_PARAM__2': 0.0, 'surf_3_OH_PARAM__3': 0.0, 'surf_3_OH_PARAM__4': 0.0, 'surf_3_OH_PARAM__5': 0.0, 'surf_3_OH_PARAM__6': 1.0, 'surf_3_OH_PARAM__7': 0.0, 'surf_3_conc': 22.0, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc + -1.0*surf_3_conc <= -1.0)])
[INFO 07-28 07:53:13] ax.service.ax_client: Generated new trial 5 with parameters {'surf_1_conc': 40, 'surf_2_conc': 29, 'surf_3_conc': 22, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's8', 'surf_3': 's7'} using model Sobol.

**************************************************************************************************** 6  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************
**************************************************************************************************** 7  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[WARNING 07-28 07:53:13] ax.modelbridge.transforms.int_to_float: Unable to round {'surf_1_OH_PARAM__0': 0.8822000976651907, 'surf_1_OH_PARAM__1': 0.6149514904245734, 'surf_1_OH_PARAM__2': 0.08642344642430544, 'surf_1_OH_PARAM__3': 0.14569633454084396, 'surf_1_OH_PARAM__4': 0.6073318542912602, 'surf_1_OH_PARAM__5': 0.26087836176157, 'surf_1_OH_PARAM__6': 0.7277211798354983, 'surf_1_OH_PARAM__7': 0.3418863546103239, 'surf_1_conc': 5.055642293922193, 'surf_2_OH_PARAM__0': 0.8666600184515119, 'surf_2_OH_PARAM__1': 0.3690495966002345, 'surf_2_OH_PARAM__2': 0.41323330346494913, 'surf_2_OH_PARAM__3': 0.6036806907504797, 'surf_2_OH_PARAM__4': 0.19115362502634525, 'surf_2_OH_PARAM__5': 0.48133616149425507, 'surf_2_OH_PARAM__6': 0.5937888957560062, 'surf_2_OH_PARAM__7': 0.6980686374008656, 'surf_2_conc': 24.22842274011027, 'surf_3_OH_PARAM__0': 0.8773827468976378, 'surf_3_OH_PARAM__1': 0.5259127067402005, 'surf_3_OH_PARAM__2': 0.9618588173761964, 'surf_3_OH_PARAM__3': 0.40644907392561436, 'surf_3_OH_PARAM__4': 0.213705912232399, 'surf_3_OH_PARAM__5': 0.9805594384670258, 'surf_3_OH_PARAM__6': 0.311998781748116, 'surf_3_OH_PARAM__7': 0.825059705413878, 'surf_3_conc': 17.84470131893631, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc + -1.0*surf_3_conc <= -1.0)])
[WARNING 07-28 07:53:13] ax.modelbridge.transforms.int_to_float: Unable to round {'surf_1_OH_PARAM__0': 1.0, 'surf_1_OH_PARAM__1': 0.0, 'surf_1_OH_PARAM__2': 0.0, 'surf_1_OH_PARAM__3': 0.0, 'surf_1_OH_PARAM__4': 0.0, 'surf_1_OH_PARAM__5': 0.0, 'surf_1_OH_PARAM__6': 0.0, 'surf_1_OH_PARAM__7': 0.0, 'surf_1_conc': 5.0, 'surf_2_OH_PARAM__0': 1.0, 'surf_2_OH_PARAM__1': 0.0, 'surf_2_OH_PARAM__2': 0.0, 'surf_2_OH_PARAM__3': 0.0, 'surf_2_OH_PARAM__4': 0.0, 'surf_2_OH_PARAM__5': 0.0, 'surf_2_OH_PARAM__6': 0.0, 'surf_2_OH_PARAM__7': 0.0, 'surf_2_conc': 24.0, 'surf_3_OH_PARAM__0': 0.0, 'surf_3_OH_PARAM__1': 0.0, 'surf_3_OH_PARAM__2': 0.0, 'surf_3_OH_PARAM__3': 0.0, 'surf_3_OH_PARAM__4': 0.0, 'surf_3_OH_PARAM__5': 1.0, 'surf_3_OH_PARAM__6': 0.0, 'surf_3_OH_PARAM__7': 0.0, 'surf_3_conc': 18.0, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc + -1.0*surf_3_conc <= -1.0)])
[INFO 07-28 07:53:13] ax.service.ax_client: Generated new trial 6 with parameters {'surf_1_conc': 5, 'surf_2_conc': 24, 'surf_3_conc': 18, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's1', 'surf_3': 's6'} using model Sobol.
[WARNING 07-28 07:53:13] ax.modelbridge.transforms.int_to_float: Unable to round {'surf_1_OH_PARAM__0': 0.12627893686294556, 'surf_1_OH_PARAM__1': 0.09906428214162588, 'surf_1_OH_PARAM__2': 0.029047919437289238, 'surf_1_OH_PARAM__3': 0.06716758292168379, 'surf_1_OH_PARAM__4': 0.5165753830224276, 'surf_1_OH_PARAM__5': 0.7746887765824795, 'surf_1_OH_PARAM__6': 0.07172936666756868, 'surf_1_OH_PARAM__7': 0.7186877587810159, 'surf_1_conc': 9.64247897724092, 'surf_2_OH_PARAM__0': 0.6521026091650128, 'surf_2_OH_PARAM__1': 0.8593875095248222, 'surf_2_OH_PARAM__2': 0.22396407555788755, 'surf_2_OH_PARAM__3': 0.0246007377281785, 'surf_2_OH_PARAM__4': 0.9643131084740162, 'surf_2_OH_PARAM__5': 0.7618962395936251, 'surf_2_OH_PARAM__6': 0.07265463657677174, 'surf_2_OH_PARAM__7': 0.3510022144764662, 'surf_2_conc': 1.2426398162697254, 'surf_3_OH_PARAM__0': 0.8580024400725961, 'surf_3_OH_PARAM__1': 0.7889401130378246, 'surf_3_OH_PARAM__2': 0.542269304394722, 'surf_3_OH_PARAM__3': 0.2448903927579522, 'surf_3_OH_PARAM__4': 0.034943463280797005, 'surf_3_OH_PARAM__5': 0.4855475975200534, 'surf_3_OH_PARAM__6': 0.7218258157372475, 'surf_3_OH_PARAM__7': 0.6548294592648745, 'surf_3_conc': 35.65247002207039, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc + -1.0*surf_3_conc <= -1.0)])
[WARNING 07-28 07:53:14] ax.modelbridge.transforms.int_to_float: Unable to round {'surf_1_OH_PARAM__0': 0.0, 'surf_1_OH_PARAM__1': 0.0, 'surf_1_OH_PARAM__2': 0.0, 'surf_1_OH_PARAM__3': 0.0, 'surf_1_OH_PARAM__4': 0.0, 'surf_1_OH_PARAM__5': 1.0, 'surf_1_OH_PARAM__6': 0.0, 'surf_1_OH_PARAM__7': 0.0, 'surf_1_conc': 10.0, 'surf_2_OH_PARAM__0': 0.0, 'surf_2_OH_PARAM__1': 0.0, 'surf_2_OH_PARAM__2': 0.0, 'surf_2_OH_PARAM__3': 0.0, 'surf_2_OH_PARAM__4': 1.0, 'surf_2_OH_PARAM__5': 0.0, 'surf_2_OH_PARAM__6': 0.0, 'surf_2_OH_PARAM__7': 0.0, 'surf_2_conc': 1.0, 'surf_3_OH_PARAM__0': 1.0, 'surf_3_OH_PARAM__1': 0.0, 'surf_3_OH_PARAM__2': 0.0, 'surf_3_OH_PARAM__3': 0.0, 'surf_3_OH_PARAM__4': 0.0, 'surf_3_OH_PARAM__5': 0.0, 'surf_3_OH_PARAM__6': 0.0, 'surf_3_OH_PARAM__7': 0.0, 'surf_3_conc': 36.0, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 99.0), ParameterConstraint(-1.0*surf_1_conc + -1.0*surf_2_conc + -1.0*surf_3_conc <= -1.0)])
[INFO 07-28 07:53:14] ax.service.ax_client: Generated new trial 7 with parameters {'surf_1_conc': 10, 'surf_2_conc': 1, 'surf_3_conc': 36, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'} using model Sobol.

**************************************************************************************************** 8  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************
Time taken for optimization: 0.03 mins
Time taken for optimization: 1.7999999999999998 seconds

# process results

In [6]:
ax_client = hf.load_design_optimizer(n)
ax_client.experiment.trials

{0: Trial(experiment_name='drug_surfactant', index=0, status=TrialStatus.RUNNING, arm=Arm(name='0_0', parameters={'surf_1_conc': 12, 'surf_2_conc': 39, 'surf_3_conc': 20, 'drug_conc': 25.0, 'surf_1': 's8', 'surf_2': 's6', 'surf_3': 's7'})),
 1: Trial(experiment_name='drug_surfactant', index=1, status=TrialStatus.RUNNING, arm=Arm(name='1_0', parameters={'surf_1_conc': 51, 'surf_2_conc': 4, 'surf_3_conc': 40, 'drug_conc': 25.0, 'surf_1': 's3', 'surf_2': 's2', 'surf_3': 's6'})),
 2: Trial(experiment_name='drug_surfactant', index=2, status=TrialStatus.RUNNING, arm=Arm(name='2_0', parameters={'surf_1_conc': 1, 'surf_2_conc': 56, 'surf_3_conc': 0, 'drug_conc': 25.0, 'surf_1': 's5', 'surf_2': 's7', 'surf_3': 's3'})),
 3: Trial(experiment_name='drug_surfactant', index=3, status=TrialStatus.RUNNING, arm=Arm(name='3_0', parameters={'surf_1_conc': 28, 'surf_2_conc': 6, 'surf_3_conc': 14, 'drug_conc': 25.0, 'surf_1': 's3', 'surf_2': 's3', 'surf_3': 's8'})),
 4: Trial(experiment_name='drug_surfactant', index=4, status=TrialStatus.RUNNING, arm=Arm(name='4_0', parameters={'surf_1_conc': 27, 'surf_2_conc': 63, 'surf_3_conc': 3, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's4', 'surf_3': 's5'})),
 5: Trial(experiment_name='drug_surfactant', index=5, status=TrialStatus.RUNNING, arm=Arm(name='5_0', parameters={'surf_1_conc': 40, 'surf_2_conc': 29, 'surf_3_conc': 22, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's8', 'surf_3': 's7'})),
 6: Trial(experiment_name='drug_surfactant', index=6, status=TrialStatus.RUNNING, arm=Arm(name='6_0', parameters={'surf_1_conc': 5, 'surf_2_conc': 24, 'surf_3_conc': 18, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's1', 'surf_3': 's6'})),
 7: Trial(experiment_name='drug_surfactant', index=7, status=TrialStatus.RUNNING, arm=Arm(name='7_0', parameters={'surf_1_conc': 10, 'surf_2_conc': 1, 'surf_3_conc': 36, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'}))}

In [7]:
df_design, df_vol = hf.design_to_vol (n, list_of_drugs, number_of_micelles)
df_design

,trial_index,surf_1_conc,surf_2_conc,surf_3_conc,drug_conc,surf_1,surf_2,surf_3,surf_conc,IBP_surf_conc,LOV_surf_conc,DCF_surf_conc,GLV_surf_conc
0,0,12,39,20,25.0,s8,s6,s7,71,NaN,NaN,NaN,NaN
1,1,51,4,40,25.0,s3,s2,s6,95,NaN,NaN,NaN,NaN
2,2,1,56,0,25.0,s5,s7,s3,57,NaN,NaN,NaN,NaN
3,3,28,6,14,25.0,s3,s3,s8,48,NaN,NaN,NaN,NaN
4,4,27,63,3,25.0,s1,s4,s5,93,NaN,NaN,NaN,NaN
5,5,40,29,22,25.0,s6,s8,s7,91,NaN,NaN,NaN,NaN
6,6,5,24,18,25.0,s1,s1,s6,47,NaN,NaN,NaN,NaN
7,7,10,1,36,25.0,s6,s5,s1,47,NaN,NaN,NaN,NaN

In [8]:
df_vol

,trial_index,drug_name,drug,s1,s2,s3,s4,s5,s6,s7,s8,dmso,water,IBP,LOV,DCF,GLV
0,0,IBP,180.0,0.0,0.0,0.0,0.0,0.0,468.0,240.0,144.0,0.0,348.0,180.0,0.0,0.0,0.0
1,0,LOV,180.0,0.0,0.0,0.0,0.0,0.0,468.0,240.0,144.0,0.0,348.0,0.0,180.0,0.0,0.0
2,0,DCF,180.0,0.0,0.0,0.0,0.0,0.0,468.0,240.0,144.0,0.0,348.0,0.0,0.0,180.0,0.0
3,0,GLV,180.0,0.0,0.0,0.0,0.0,0.0,468.0,240.0,144.0,0.0,348.0,0.0,0.0,0.0,180.0
4,1,IBP,180.0,0.0,48.0,612.0,0.0,0.0,480.0,0.0,0.0,0.0,60.0,180.0,0.0,0.0,0.0
5,1,LOV,180.0,0.0,48.0,612.0,0.0,0.0,480.0,0.0,0.0,0.0,60.0,0.0,180.0,0.0,0.0
6,1,DCF,180.0,0.0,48.0,612.0,0.0,0.0,480.0,0.0,0.0,0.0,60.0,0.0,0.0,180.0,0.0
7,1,GLV,180.0,0.0,48.0,612.0,0.0,0.0,480.0,0.0,0.0,0.0,60.0,0.0,0.0,0.0,180.0
8,2,IBP,180.0,0.0,0.0,0.0,0.0,12.0,0.0,672.0,0.0,0.0,516.0,180.0,0.0,0.0,0.0
9,2,LOV,180.0,0.0,0.0,0.0,0.0,12.0,0.0,672.0,0.0,0.0,516.0,0.0,180.0,0.0,0.0
10,2,DCF,180.0,0.0,0.0,0.0,0.0,12.0,0.0,672.0,0.0,0.0,516.0,0.0,0.0,180.0,0.0
11,2,GLV,180.0,0.0,0.0,0.0,0.0,12.0,0.0,672.0,0.0,0.0,516.0,0.0,0.0,0.0,180.0
12,3,IBP,180.0,0.0,0.0,408.0,0.0,0.0,0.0,0.0,168.0,0.0,624.0,180.0,0.0,0.0,0.0
13,3,LOV,180.0,0.0,0.0,408.0,0.0,0.0,0.0,0.0,168.0,0.0,624.0,0.0,180.0,0.0,0.0
14,3,DCF,180.0,0.0,0.0,408.0,0.0,0.0,0.0,0.0,168.0,0.0,624.0,0.0,0.0,180.0,0.0
15,3,GLV,180.0,0.0,0.0,408.0,0.0,0.0,0.0,0.0,168.0,0.0,624.0,0.0,0.0,0.0,180.0
16,4,IBP,180.0,324.0,0.0,0.0,756.0,36.0,0.0,0.0,0.0,0.0,84.0,180.0,0.0,0.0,0.0
17,4,LOV,180.0,324.0,0.0,0.0,756.0,36.0,0.0,0.0,0.0,0.0,84.0,0.0,180.0,0.0,0.0
18,4,DCF,180.0,324.0,0.0,0.0,756.0,36.0,0.0,0.0,0.0,0.0,84.0,0.0,0.0,180.0,0.0
19,4,GLV,180.0,324.0,0.0,0.0,756.0,36.0,0.0,0.0,0.0,0.0,84.0,0.0,0.0,0.0,180.0
20,5,IBP,180.0,0.0,0.0,0.0,0.0,0.0,480.0,264.0,348.0,0.0,108.0,180.0,0.0,0.0,0.0
21,5,LOV,180.0,0.0,0.0,0.0,0.0,0.0,480.0,264.0,348.0,0.0,108.0,0.0,180.0,0.0,0.0
22,5,DCF,180.0,0.0,0.0,0.0,0.0,0.0,480.0,264.0,348.0,0.0,108.0,0.0,0.0,180.0,0.0
23,5,GLV,180.0,0.0,0.0,0.0,0.0,0.0,480.0,264.0,348.0,0.0,108.0,0.0,0.0,0.0,180.0
24,6,IBP,180.0,348.0,0.0,0.0,0.0,0.0,216.0,0.0,0.0,0.0,636.0,180.0,0.0,0.0,0.0
25,6,LOV,180.0,348.0,0.0,0.0,0.0,0.0,216.0,0.0,0.0,0.0,636.0,0.0,180.0,0.0,0.0
26,6,DCF,180.0,348.0,0.0,0.0,0.0,0.0,216.0,0.0,0.0,0.0,636.0,0.0,0.0,180.0,0.0
27,6,GLV,180.0,348.0,0.0,0.0,0.0,0.0,216.0,0.0,0.0,0.0,636.0,0.0,0.0,0.0,180.0
28,7,IBP,180.0,432.0,0.0,0.0,0.0,12.0,120.0,0.0,0.0,0.0,636.0,180.0,0.0,0.0,0.0
29,7,LOV,180.0,432.0,0.0,0.0,0.0,12.0,120.0,0.0,0.0,0.0,636.0,0.0,180.0,0.0,0.0
30,7,DCF,180.0,432.0,0.0,0.0,0.0,12.0,120.0,0.0,0.0,0.0,636.0,0.0,0.0,180.0,0.0
31,7,GLV,180.0,432.0,0.0,0.0,0.0,12.0,120.0,0.0,0.0,0.0,636.0,0.0,0.0,0.0,180.0

In [9]:
plate_well = input("Enter the plate well starting well (e.g., F1): ")
deepplate_well = input("Enter the deep plate well starting well (e.g., F1): ")



print("Please confirm the following information:")
print("Wellplate will start at: " + plate_well)
print("Deep plate will start at: " + deepplate_well)



print()
print("*******************************************************")
print("Continue if correct, or rerun this cell if incorrect.")
print("*******************************************************")

Please confirm the following information:
Wellplate will start at: A1
Deep plate will start at: G9

*******************************************************
Continue if correct, or rerun this cell if incorrect.
*******************************************************

In [10]:
hf.generate_protocol(df_vol=df_vol, iteration=n, plate_well=plate_well, deepplate_well=deepplate_well)

✅ Successfully wrote to: protocol/otflex_0.py

In [11]:
df_absorbance = hf.process_absorbance(iteration=n, threshold=0.1)
df_absorbance

   trial_index  success
0            0        0
1            1        1
2            2        1
3            3        1
4            4        0
5            5        0
6            6        1
7            7        1

In [12]:
results = hf.build_results(n, df_absorbance)
results

,trial_index,drug_name,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,surf_3_conc,drug_conc,surf_1,surf_2,surf_3,surf_conc,obj_surf_conc,success
0,0,IBP,0.2063,0.3073,0.0373,6.342538,19.792553,10.062115,25.0,s8,s6,s7,36.197205,50.000000,0
1,1,IBP,0.2063,0.3073,0.0373,25.388954,2.403562,19.870581,25.0,s3,s2,s6,47.663097,47.663097,1
2,2,LOV,0.4045,0.4196,0.0728,0.561928,27.771701,0.445989,25.0,s5,s7,s3,28.779619,28.779619,1
3,3,LOV,0.4045,0.4196,0.0728,14.076332,3.422734,7.078612,25.0,s3,s3,s8,24.577678,24.577678,1
4,4,DCF,0.2962,0.4364,0.0493,13.456925,31.466190,1.570027,25.0,s1,s4,s5,46.493142,50.000000,0
5,5,DCF,0.2962,0.4364,0.0493,20.019197,14.549110,11.283737,25.0,s6,s8,s7,45.852044,50.000000,0
6,6,GLV,0.3528,0.2810,0.0711,2.750314,12.241791,9.081532,25.0,s1,s1,s6,24.073637,24.073637,1
7,7,GLV,0.3528,0.2810,0.0711,5.021025,0.862688,17.897261,25.0,s6,s5,s1,23.780974,23.780974,1

# load the results to the optimizer

In [13]:
ax_client = hf.load_data_to_optimizer(iteration = n, results = results)
ax_client

[INFO 07-16 11:51:37] ax.service.ax_client: Completed trial 0 with data: {'obj_surf_conc': (50.0, None)}.
[INFO 07-16 11:51:37] ax.service.ax_client: Completed trial 1 with data: {'obj_surf_conc': (47.663097, None)}.
[INFO 07-16 11:51:37] ax.service.ax_client: Completed trial 2 with data: {'obj_surf_conc': (28.779619, None)}.
[INFO 07-16 11:51:37] ax.service.ax_client: Completed trial 3 with data: {'obj_surf_conc': (24.577678, None)}.
[INFO 07-16 11:51:37] ax.service.ax_client: Completed trial 4 with data: {'obj_surf_conc': (50.0, None)}.
[INFO 07-16 11:51:37] ax.service.ax_client: Completed trial 5 with data: {'obj_surf_conc': (50.0, None)}.
[INFO 07-16 11:51:37] ax.service.ax_client: Completed trial 6 with data: {'obj_surf_conc': (24.073637, None)}.
[INFO 07-16 11:51:37] ax.service.ax_client: Completed trial 7 with data: {'obj_surf_conc': (23.780974, None)}.

AxClient(experiment=Experiment(drug_surfactant))