# import libraries

In [1]:
import pandas as pd
from ax.service.ax_client import AxClient, ObjectiveProperties
import matplotlib.pyplot as plt
from ax.modelbridge.registry import Models
from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy   
import time


import sys
sys.path.append('../')
import helper_functions as hf

/var/folders/9p/f66yhymx35939zzlg51g0rrc0000gn/T/ipykernel_3755/3307975217.py:5: DeprecationWarning: Please import from 'ax.generation_strategy.generation_strategy' instead of 'ax.modelbridge.generation_strategy'. The latter is deprecated and will be removed in a future release.
  from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy

# generate recommendations

In [2]:
n = hf.get_iteration_number()

for i in range(3):
    print("Very Important: Please Confirm the Iteration Number is Iteration " + str(n))

print()

list_of_drugs = (['IBP']  + ['LOV']  + ['DCF']  + ['GLV']) * 1

for i in range(3):
    print("Very Important: Please Confirm the Drugs are: ", list_of_drugs)

Very Important: Please Confirm the Iteration Number is Iteration 2
Very Important: Please Confirm the Iteration Number is Iteration 2
Very Important: Please Confirm the Iteration Number is Iteration 2

Very Important: Please Confirm the Drugs are:  ['IBP', 'LOV', 'DCF', 'GLV']
Very Important: Please Confirm the Drugs are:  ['IBP', 'LOV', 'DCF', 'GLV']
Very Important: Please Confirm the Drugs are:  ['IBP', 'LOV', 'DCF', 'GLV']

In [3]:
time_start = time.time()


df_design, ax_client = hf.run_optimizer(current_iteration=n, drug_list= list_of_drugs,  bopt = 2)

time_end = time.time()
time_duration = round((time_end - time_start)/60,2)

print("Time taken for optimization: " + str(time_duration) + " mins")
print("Time taken for optimization: " + str(time_duration * 60) + " seconds")

**************************************************************************************************** 1  out of  4 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Drug name:  Ibuprofen IBP  | Iteration:  2

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[INFO 07-18 10:49:47] ax.service.ax_client: Generated new trial 36 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 30, 'surf_2_conc': 12, 'surf_3_conc': 13, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's6', 'surf_3': 's8'} using model SAASBO.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

**************************************************************************************************** 2  out of  4 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Drug name:  Lovastatin LOV  | Iteration:  2

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[INFO 07-18 10:49:58] ax.service.ax_client: Generated new trial 37 with parameters {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 30, 'surf_2_conc': 12, 'surf_3_conc': 13, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's6', 'surf_3': 's8'} using model SAASBO.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

**************************************************************************************************** 3  out of  4 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Drug name:  Diclofenac DCF  | Iteration:  2

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[INFO 07-18 10:50:07] ax.service.ax_client: Generated new trial 38 with parameters {'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 30, 'surf_2_conc': 12, 'surf_3_conc': 13, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's6', 'surf_3': 's8'} using model SAASBO.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

**************************************************************************************************** 4  out of  4 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Drug name:  Griseofulvin GLV  | Iteration:  2

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[INFO 07-18 10:50:18] ax.service.ax_client: Generated new trial 39 with parameters {'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 30, 'surf_2_conc': 12, 'surf_3_conc': 13, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's6', 'surf_3': 's8'} using model SAASBO.

Time taken for optimization: 1.17 mins
Time taken for optimization: 70.19999999999999 seconds

# process results

In [4]:
ax_client = hf.load_design_optimizer(n)
ax_client.experiment.trials

{0: Trial(experiment_name='drug_surfactant', index=0, status=TrialStatus.COMPLETED, arm=Arm(name='0_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1': 's8', 'surf_1_conc': 12, 'surf_2': 's6', 'surf_2_conc': 39, 'surf_3': 's7', 'surf_3_conc': 20, 'drug_conc': 25.0})),
 1: Trial(experiment_name='drug_surfactant', index=1, status=TrialStatus.COMPLETED, arm=Arm(name='1_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1': 's3', 'surf_1_conc': 51, 'surf_2': 's2', 'surf_2_conc': 4, 'surf_3': 's6', 'surf_3_conc': 40, 'drug_conc': 25.0})),
 2: Trial(experiment_name='drug_surfactant', index=2, status=TrialStatus.COMPLETED, arm=Arm(name='2_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1': 's5', 'surf_1_conc': 1, 'surf_2': 's7', 'surf_2_conc': 56, 'surf_3': 's3', 'surf_3_conc': 0, 'drug_conc': 25.0})),
 3: Trial(experiment_name='drug_surfactant', index=3, status=TrialStatus.COMPLETED, arm=Arm(name='3_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1': 's3', 'surf_1_conc': 28, 'surf_2': 's3', 'surf_2_conc': 6, 'surf_3': 's8', 'surf_3_conc': 14, 'drug_conc': 25.0})),
 4: Trial(experiment_name='drug_surfactant', index=4, status=TrialStatus.COMPLETED, arm=Arm(name='4_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1': 's1', 'surf_1_conc': 27, 'surf_2': 's4', 'surf_2_conc': 63, 'surf_3': 's5', 'surf_3_conc': 3, 'drug_conc': 25.0})),
 5: Trial(experiment_name='drug_surfactant', index=5, status=TrialStatus.COMPLETED, arm=Arm(name='5_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1': 's6', 'surf_1_conc': 40, 'surf_2': 's8', 'surf_2_conc': 29, 'surf_3': 's7', 'surf_3_conc': 22, 'drug_conc': 25.0})),
 6: Trial(experiment_name='drug_surfactant', index=6, status=TrialStatus.COMPLETED, arm=Arm(name='6_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1': 's1', 'surf_1_conc': 5, 'surf_2': 's1', 'surf_2_conc': 24, 'surf_3': 's6', 'surf_3_conc': 18, 'drug_conc': 25.0})),
 7: Trial(experiment_name='drug_surfactant', index=7, status=TrialStatus.COMPLETED, arm=Arm(name='7_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1': 's6', 'surf_1_conc': 10, 'surf_2': 's5', 'surf_2_conc': 1, 'surf_3': 's1', 'surf_3_conc': 36, 'drug_conc': 25.0})),
 8: Trial(experiment_name='drug_surfactant', index=8, status=TrialStatus.COMPLETED, arm=Arm(name='8_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1': 's4', 'surf_1_conc': 4, 'surf_2': 's4', 'surf_2_conc': 15, 'surf_3': 's1', 'surf_3_conc': 50, 'drug_conc': 25.0})),
 9: Trial(experiment_name='drug_surfactant', index=9, status=TrialStatus.COMPLETED, arm=Arm(name='9_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1': 's3', 'surf_1_conc': 37, 'surf_2': 's4', 'surf_2_conc': 17, 'surf_3': 's5', 'surf_3_conc': 32, 'drug_conc': 25.0})),
 10: Trial(experiment_name='drug_surfactant', index=10, status=TrialStatus.COMPLETED, arm=Arm(name='10_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1': 's1', 'surf_1_conc': 30, 'surf_2': 's5', 'surf_2_conc': 3, 'surf_3': 's5', 'surf_3_conc': 54, 'drug_conc': 25.0})),
 11: Trial(experiment_name='drug_surfactant', index=11, status=TrialStatus.COMPLETED, arm=Arm(name='11_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1': 's4', 'surf_1_conc': 22, 'surf_2': 's7', 'surf_2_conc': 37, 'surf_3': 's3', 'surf_3_conc': 27, 'drug_conc': 25.0})),
 12: Trial(experiment_name='drug_surfactant', index=12, status=TrialStatus.COMPLETED, arm=Arm(name='12_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1': 's4', 'surf_1_conc': 59, 'surf_2': 's1', 'surf_2_conc': 21, 'surf_3': 's8', 'surf_3_conc': 6, 'drug_conc': 25.0})),
 13: Trial(experiment_name='drug_surfactant', index=13, status=TrialStatus.COMPLETED, arm=Arm(name='13_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1': 's2', 'surf_1_conc': 10, 'surf_2': 's8', 'surf_2_conc': 78, 'surf_3': 's3', 'surf_3_conc': 9, 'drug_conc': 25.0})),
 14: Trial(experiment_name='drug_surfactant', index=14, status=TrialStatus.COMPLETED, arm=Arm(name='14_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1': 's5', 'surf_1_conc': 22, 'surf_2': 's7', 'surf_2_conc': 17, 'surf_3': 's3', 'surf_3_conc': 16, 'drug_conc': 25.0})),
 15: Trial(experiment_name='drug_surfactant', index=15, status=TrialStatus.COMPLETED, arm=Arm(name='15_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1': 's5', 'surf_1_conc': 31, 'surf_2': 's4', 'surf_2_conc': 35, 'surf_3': 's1', 'surf_3_conc': 24, 'drug_conc': 25.0})),
 16: Trial(experiment_name='drug_surfactant', index=16, status=TrialStatus.COMPLETED, arm=Arm(name='16_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1': 's6', 'surf_1_conc': 50, 'surf_2': 's1', 'surf_2_conc': 0, 'surf_3': 's6', 'surf_3_conc': 13, 'drug_conc': 25.0})),
 17: Trial(experiment_name='drug_surfactant', index=17, status=TrialStatus.COMPLETED, arm=Arm(name='17_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1': 's8', 'surf_1_conc': 8, 'surf_2': 's6', 'surf_2_conc': 46, 'surf_3': 's4', 'surf_3_conc': 20, 'drug_conc': 25.0})),
 18: Trial(experiment_name='drug_surfactant', index=18, status=TrialStatus.COMPLETED, arm=Arm(name='18_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1': 's6', 'surf_1_conc': 20, 'surf_2': 's8', 'surf_2_conc': 62, 'surf_3': 's3', 'surf_3_conc': 1, 'drug_conc': 25.0})),
 19: Trial(experiment_name='drug_surfactant', index=19, status=TrialStatus.COMPLETED, arm=Arm(name='19_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1': 's6', 'surf_1_conc': 0, 'surf_2': 's7', 'surf_2_conc': 30, 'surf_3': 's2', 'surf_3_conc': 25, 'drug_conc': 25.0})),
 20: Trial(experiment_name='drug_surfactant', index=20, status=TrialStatus.COMPLETED, arm=Arm(name='20_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1': 's4', 'surf_1_conc': 63, 'surf_2': 's4', 'surf_2_conc': 14, 'surf_3': 's1', 'surf_3_conc': 9, 'drug_conc': 25.0})),
 21: Trial(experiment_name='drug_surfactant', index=21, status=TrialStatus.COMPLETED, arm=Arm(name='21_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1': 's3', 'surf_1_conc': 41, 'surf_2': 's7', 'surf_2_conc': 22, 'surf_3': 's7', 'surf_3_conc': 34, 'drug_conc': 25.0})),
 22: Trial(experiment_name='drug_surfactant', index=22, status=TrialStatus.COMPLETED, arm=Arm(name='22_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1': 's5', 'surf_1_conc': 28, 'surf_2': 's6', 'surf_2_conc': 39, 'surf_3': 's1', 'surf_3_conc': 29, 'drug_conc': 25.0})),
 23: Trial(experiment_name='drug_surfactant', index=23, status=TrialStatus.COMPLETED, arm=Arm(name='23_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1': 's4', 'surf_1_conc': 23, 'surf_2': 's4', 'surf_2_conc': 20, 'surf_3': 's5', 'surf_3_conc': 53, 'drug_conc': 25.0})),
 24: Trial(experiment_name='drug_surfactant', index=24, status=TrialStatus.COMPLETED, arm=Arm(name='24_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1': 's5', 'surf_1_conc': 18, 'surf_2': 's1', 'surf_2_conc': 9, 'surf_3': 's1', 'surf_3_conc': 36, 'drug_conc': 25.0})),
 25: Trial(experiment_name='drug_surfactant', index=25, status=TrialStatus.COMPLETED, arm=Arm(name='25_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1': 's1', 'surf_1_conc': 24, 'surf_2': 's6', 'surf_2_conc': 12, 'surf_3': 's8', 'surf_3_conc': 13, 'drug_conc': 25.0})),
 26: Trial(experiment_name='drug_surfactant', index=26, status=TrialStatus.COMPLETED, arm=Arm(name='26_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1': 's7', 'surf_1_conc': 33, 'surf_2': 's2', 'surf_2_conc': 41, 'surf_3': 's3', 'surf_3_conc': 21, 'drug_conc': 25.0})),
 27: Trial(experiment_name='drug_surfactant', index=27, status=TrialStatus.COMPLETED, arm=Arm(name='27_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1': 's1', 'surf_1_conc': 47, 'surf_2': 's8', 'surf_2_conc': 51, 'surf_3': 's6', 'surf_3_conc': 1, 'drug_conc': 25.0})),
 28: Trial(experiment_name='drug_surfactant', index=28, status=TrialStatus.COMPLETED, arm=Arm(name='28_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1': 's4', 'surf_1_conc': 48, 'surf_2': 's2', 'surf_2_conc': 19, 'surf_3': 's2', 'surf_3_conc': 15, 'drug_conc': 25.0})),
 29: Trial(experiment_name='drug_surfactant', index=29, status=TrialStatus.COMPLETED, arm=Arm(name='29_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1': 's2', 'surf_1_conc': 19, 'surf_2': 's6', 'surf_2_conc': 68, 'surf_3': 's5', 'surf_3_conc': 5, 'drug_conc': 25.0})),
 30: Trial(experiment_name='drug_surfactant', index=30, status=TrialStatus.COMPLETED, arm=Arm(name='30_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1': 's1', 'surf_1_conc': 7, 'surf_2': 's2', 'surf_2_conc': 27, 'surf_3': 's1', 'surf_3_conc': 25, 'drug_conc': 25.0})),
 31: Trial(experiment_name='drug_surfactant', index=31, status=TrialStatus.COMPLETED, arm=Arm(name='31_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1': 's7', 'surf_1_conc': 65, 'surf_2': 's4', 'surf_2_conc': 9, 'surf_3': 's4', 'surf_3_conc': 11, 'drug_conc': 25.0})),
 32: Trial(experiment_name='drug_surfactant', index=32, status=TrialStatus.COMPLETED, arm=Arm(name='32_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 0, 'surf_2_conc': 0, 'surf_3_conc': 0, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's6', 'surf_3': 's8'})),
 33: Trial(experiment_name='drug_surfactant', index=33, status=TrialStatus.COMPLETED, arm=Arm(name='33_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 0, 'surf_2_conc': 0, 'surf_3_conc': 0, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's6', 'surf_3': 's8'})),
 34: Trial(experiment_name='drug_surfactant', index=34, status=TrialStatus.COMPLETED, arm=Arm(name='34_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 0, 'surf_2_conc': 0, 'surf_3_conc': 0, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's6', 'surf_3': 's8'})),
 35: Trial(experiment_name='drug_surfactant', index=35, status=TrialStatus.COMPLETED, arm=Arm(name='35_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 0, 'surf_2_conc': 0, 'surf_3_conc': 0, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's6', 'surf_3': 's8'})),
 36: Trial(experiment_name='drug_surfactant', index=36, status=TrialStatus.RUNNING, arm=Arm(name='36_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 30, 'surf_2_conc': 12, 'surf_3_conc': 13, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's6', 'surf_3': 's8'})),
 37: Trial(experiment_name='drug_surfactant', index=37, status=TrialStatus.RUNNING, arm=Arm(name='37_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 30, 'surf_2_conc': 12, 'surf_3_conc': 13, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's6', 'surf_3': 's8'})),
 38: Trial(experiment_name='drug_surfactant', index=38, status=TrialStatus.RUNNING, arm=Arm(name='38_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 30, 'surf_2_conc': 12, 'surf_3_conc': 13, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's6', 'surf_3': 's8'})),
 39: Trial(experiment_name='drug_surfactant', index=39, status=TrialStatus.RUNNING, arm=Arm(name='39_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 30, 'surf_2_conc': 12, 'surf_3_conc': 13, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's6', 'surf_3': 's8'}))}

In [5]:
df_design, df_vol = hf.design_to_vol (n)
df_design

,trial_index,drug_name,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,surf_3_conc,drug_conc,surf_1,surf_2,surf_3,surf_conc,obj_surf_conc
0,36,IBP,0.2063,0.3073,0.0373,30,12,13,25.0,s1,s6,s8,55,NaN
1,37,LOV,0.4045,0.4196,0.0728,30,12,13,25.0,s1,s6,s8,55,NaN
2,38,DCF,0.2962,0.4364,0.0493,30,12,13,25.0,s1,s6,s8,55,NaN
3,39,GLV,0.3528,0.2810,0.0711,30,12,13,25.0,s1,s6,s8,55,NaN

In [6]:
df_vol

,trial_index,drug_name,drug,s1,s2,s3,s4,s5,s6,s7,s8,dmso,water,IBP,LOV,DCF,GLV
0,36,IBP,180.0,360.0,0.0,0.0,0.0,0.0,144.0,0.0,156.0,0.0,540.0,180.0,0.0,0.0,0.0
1,37,LOV,180.0,360.0,0.0,0.0,0.0,0.0,144.0,0.0,156.0,0.0,540.0,0.0,180.0,0.0,0.0
2,38,DCF,180.0,360.0,0.0,0.0,0.0,0.0,144.0,0.0,156.0,0.0,540.0,0.0,0.0,180.0,0.0
3,39,GLV,180.0,360.0,0.0,0.0,0.0,0.0,144.0,0.0,156.0,0.0,540.0,0.0,0.0,0.0,180.0

In [8]:
plate_well = input("Enter the plate well starting well (e.g., F1): ")
deepplate_well = input("Enter the deep plate well starting well (e.g., F1): ")


print("Please confirm the following information:")
print("Wellplate will start at: " + plate_well)
print("Deep plate will start at: " + deepplate_well)

print()
print("*******************************************************")
print("Continue if correct, or rerun this cell if incorrect.")
print("*******************************************************")

Please confirm the following information:
Wellplate will start at: A1
Deep plate will start at: F5

*******************************************************
Continue if correct, or rerun this cell if incorrect.
*******************************************************

In [9]:
hf.generate_protocol(df_vol=df_vol, iteration=n, plate_well=plate_well, deepplate_well=deepplate_well)

✅ Successfully wrote to: protocol/otflex_2.py

In [10]:
df_absorbance = hf.process_absorbance(iteration=n, threshold=0.06)
df_absorbance

   trial_index  success
0            0        1
1            1        0
2            2        1
3            3        1

In [11]:
results = hf.build_results(n, df_absorbance)
results

,trial_index,drug_name,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,surf_3_conc,drug_conc,surf_1,surf_2,surf_3,surf_conc,obj_surf_conc,success
0,36,IBP,0.2063,0.3073,0.0373,30,12,13,25.0,s1,s6,s8,55,55,1
1,37,LOV,0.4045,0.4196,0.0728,30,12,13,25.0,s1,s6,s8,55,100,0
2,38,DCF,0.2962,0.4364,0.0493,30,12,13,25.0,s1,s6,s8,55,55,1
3,39,GLV,0.3528,0.2810,0.0711,30,12,13,25.0,s1,s6,s8,55,55,1

# load the results to the optimizer

In [12]:
ax_client = hf.load_data_to_optimizer(iteration = n, results = results)
ax_client

[INFO 07-18 12:19:26] ax.service.ax_client: Completed trial 36 with data: {'obj_surf_conc': (55.0, None)}.
[INFO 07-18 12:19:26] ax.service.ax_client: Completed trial 37 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-18 12:19:26] ax.service.ax_client: Completed trial 38 with data: {'obj_surf_conc': (55.0, None)}.
[INFO 07-18 12:19:26] ax.service.ax_client: Completed trial 39 with data: {'obj_surf_conc': (55.0, None)}.

AxClient(experiment=Experiment(drug_surfactant))