# import libraries

In [1]:
import pandas as pd
from ax.service.ax_client import AxClient, ObjectiveProperties
import matplotlib.pyplot as plt
from ax.modelbridge.registry import Models
from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy   
import time


import sys
sys.path.append('../')
import helper_functions as hf

/var/folders/9p/f66yhymx35939zzlg51g0rrc0000gn/T/ipykernel_69095/3307975217.py:5: DeprecationWarning: Please import from 'ax.generation_strategy.generation_strategy' instead of 'ax.modelbridge.generation_strategy'. The latter is deprecated and will be removed in a future release.
  from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy

# generate recommendations

In [2]:
n = hf.get_iteration_number()

for i in range(3):
    print("Very Important: Please Confirm the Iteration Number is Iteration " + str(n))

print()

list_of_drugs = (['IBP']  + ['LOV']  + ['DCF']  + ['GLV']) * 2

for i in range(3):
    print("Very Important: Please Confirm the Drugs are: ", list_of_drugs)

Very Important: Please Confirm the Iteration Number is Iteration 25
Very Important: Please Confirm the Iteration Number is Iteration 25
Very Important: Please Confirm the Iteration Number is Iteration 25

Very Important: Please Confirm the Drugs are:  ['IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV']
Very Important: Please Confirm the Drugs are:  ['IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV']
Very Important: Please Confirm the Drugs are:  ['IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV']

In [3]:
time_start = time.time()


df_design, ax_client = hf.run_optimizer(current_iteration=n, drug_list= list_of_drugs,  bopt = 2)

time_end = time.time()
time_duration = round((time_end - time_start)/60,2)

print("Time taken for optimization: " + str(time_duration) + " mins")
print("Time taken for optimization: " + str(time_duration * 60) + " seconds")

**************************************************************************************************** 1  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Drug name:  Ibuprofen IBP  | Iteration:  25

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: divide by zero encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: overflow encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: invalid value encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: divide by zero encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: overflow encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: invalid value encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
[INFO 07-24 13:02:02] ax.service.ax_client: Generated new trial 132 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 51, 'surf_2_conc': 0, 'surf_3_conc': 0, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's7', 'surf_3': 's1'} using model SAASBO.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: divide by zero encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: overflow encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: invalid value encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(

**************************************************************************************************** 2  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Drug name:  Lovastatin LOV  | Iteration:  25

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: divide by zero encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: overflow encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: invalid value encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
[INFO 07-24 13:02:12] ax.service.ax_client: Generated new trial 133 with parameters {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 54, 'surf_2_conc': 0, 'surf_3_conc': 0, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's3', 'surf_3': 's6'} using model SAASBO.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: divide by zero encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: overflow encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: invalid value encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(

**************************************************************************************************** 3  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Drug name:  Diclofenac DCF  | Iteration:  25

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: divide by zero encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: overflow encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: invalid value encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
[INFO 07-24 13:02:21] ax.service.ax_client: Generated new trial 134 with parameters {'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 81, 'surf_2_conc': 0, 'surf_3_conc': 0, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's3', 'surf_3': 's1'} using model SAASBO.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: divide by zero encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: overflow encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: invalid value encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(

**************************************************************************************************** 4  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Drug name:  Griseofulvin GLV  | Iteration:  25

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: divide by zero encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: overflow encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: invalid value encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
[INFO 07-24 13:02:31] ax.service.ax_client: Generated new trial 135 with parameters {'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 57, 'surf_2_conc': 0, 'surf_3_conc': 0, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's3', 'surf_3': 's6'} using model SAASBO.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: divide by zero encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: overflow encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: invalid value encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(

**************************************************************************************************** 5  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Drug name:  Ibuprofen IBP  | Iteration:  25

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: divide by zero encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: overflow encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: invalid value encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
[INFO 07-24 13:02:43] ax.service.ax_client: Generated new trial 136 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 11, 'surf_2_conc': 0, 'surf_3_conc': 0, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's3', 'surf_3': 's6'} using model SAASBO.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: divide by zero encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: overflow encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: invalid value encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(

**************************************************************************************************** 6  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Drug name:  Lovastatin LOV  | Iteration:  25

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: divide by zero encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: overflow encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: invalid value encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
[INFO 07-24 13:02:52] ax.service.ax_client: Generated new trial 137 with parameters {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 6, 'surf_2_conc': 0, 'surf_3_conc': 0, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's7', 'surf_3': 's1'} using model SAASBO.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: divide by zero encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: overflow encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: invalid value encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(

**************************************************************************************************** 7  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Drug name:  Diclofenac DCF  | Iteration:  25

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: divide by zero encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: overflow encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: invalid value encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
[INFO 07-24 13:03:02] ax.service.ax_client: Generated new trial 138 with parameters {'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 17, 'surf_2_conc': 0, 'surf_3_conc': 0, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's3', 'surf_3': 's1'} using model SAASBO.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: divide by zero encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: overflow encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: invalid value encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(

**************************************************************************************************** 8  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Drug name:  Griseofulvin GLV  | Iteration:  25

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: divide by zero encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: overflow encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/models/model_utils.py:590: RuntimeWarning: invalid value encountered in matmul
  feas &= (A @ X_np.transpose() <= b).all(axis=0)
[INFO 07-24 13:03:13] ax.service.ax_client: Generated new trial 139 with parameters {'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 18, 'surf_2_conc': 0, 'surf_3_conc': 0, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's3', 'surf_3': 's1'} using model SAASBO.

Time taken for optimization: 1.87 mins
Time taken for optimization: 112.2 seconds

# process results

In [4]:
ax_client = hf.load_design_optimizer(n)
ax_client.get_trials_data_frame()

/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

,trial_index,arm_name,trial_status,generation_node,obj_surf_conc,Drug_MW,Drug_LogP,Drug_TPSA,surf_1,surf_1_conc,surf_2,surf_2_conc,surf_3,surf_3_conc,drug_conc
0,0,0_0,COMPLETED,None,100.0,0.2063,0.3073,0.0373,s8,12,s6,39,s7,20,25.0
1,1,1_0,COMPLETED,None,95.0,0.2063,0.3073,0.0373,s3,51,s2,4,s6,40,25.0
2,2,2_0,COMPLETED,None,100.0,0.4045,0.4196,0.0728,s5,1,s7,56,s3,0,25.0
3,3,3_0,COMPLETED,None,100.0,0.4045,0.4196,0.0728,s3,28,s3,6,s8,14,25.0
4,4,4_0,COMPLETED,None,100.0,0.2962,0.4364,0.0493,s1,27,s4,63,s5,3,25.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,135,135_0,RUNNING,GenerationStep_2,NaN,0.3528,0.2810,0.0711,s1,57,s3,0,s6,0,25.0
136,136,136_0,RUNNING,GenerationStep_2,NaN,0.2063,0.3073,0.0373,s1,11,s3,0,s6,0,25.0
137,137,137_0,RUNNING,GenerationStep_2,NaN,0.4045,0.4196,0.0728,s1,6,s7,0,s1,0,25.0
138,138,138_0,RUNNING,GenerationStep_2,NaN,0.2962,0.4364,0.0493,s1,17,s3,0,s1,0,25.0
139,139,139_0,RUNNING,GenerationStep_2,NaN,0.3528,0.2810,0.0711,s1,18,s3,0,s1,0,25.0

In [5]:
df_design, df_vol = hf.design_to_vol (n)
df_design

,trial_index,drug_name,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,surf_3_conc,drug_conc,surf_1,surf_2,surf_3,surf_conc,obj_surf_conc
0,132,IBP,0.2063,0.3073,0.0373,51,0,0,25.0,s1,s7,s1,51,NaN
1,133,LOV,0.4045,0.4196,0.0728,54,0,0,25.0,s1,s3,s6,54,NaN
2,134,DCF,0.2962,0.4364,0.0493,81,0,0,25.0,s1,s3,s1,81,NaN
3,135,GLV,0.3528,0.2810,0.0711,57,0,0,25.0,s1,s3,s6,57,NaN
4,136,IBP,0.2063,0.3073,0.0373,11,0,0,25.0,s1,s3,s6,11,NaN
5,137,LOV,0.4045,0.4196,0.0728,6,0,0,25.0,s1,s7,s1,6,NaN
6,138,DCF,0.2962,0.4364,0.0493,17,0,0,25.0,s1,s3,s1,17,NaN
7,139,GLV,0.3528,0.2810,0.0711,18,0,0,25.0,s1,s3,s1,18,NaN

In [6]:
df_vol

,trial_index,drug_name,drug,s1,s2,s3,s4,s5,s6,s7,s8,dmso,water,IBP,LOV,DCF,GLV
0,132,IBP,180.0,612.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,588.0,180.0,0.0,0.0,0.0
1,133,LOV,180.0,648.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,552.0,0.0,180.0,0.0,0.0
2,134,DCF,180.0,972.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,228.0,0.0,0.0,180.0,0.0
3,135,GLV,180.0,684.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,516.0,0.0,0.0,0.0,180.0
4,136,IBP,180.0,132.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1068.0,180.0,0.0,0.0,0.0
5,137,LOV,180.0,72.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1128.0,0.0,180.0,0.0,0.0
6,138,DCF,180.0,204.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,996.0,0.0,0.0,180.0,0.0
7,139,GLV,180.0,216.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,984.0,0.0,0.0,0.0,180.0

In [7]:
df_vol[['s1', 's2', 's3', 's4', 's5', 's6', 's7', 's8']].sum()

s1    3540.0
s2       0.0
s3       0.0
s4       0.0
s5       0.0
s6       0.0
s7       0.0
s8       0.0
dtype: float64

In [8]:
plate_well = input("Enter the plate well starting well (e.g., F1): ")
deepplate_well = input("Enter the deep plate well starting well (e.g., F1): ")


print("Please confirm the following information:")
print("Wellplate will start at: " + plate_well)
print("Deep plate will start at: " + deepplate_well)

print()
print("*******************************************************")
print("Continue if correct, or rerun this cell if incorrect.")
print("*******************************************************")

Please confirm the following information:
Wellplate will start at: G1
Deep plate will start at: B5

*******************************************************
Continue if correct, or rerun this cell if incorrect.
*******************************************************

In [9]:
hf.generate_protocol(df_vol=df_vol, iteration=n, plate_well=plate_well, deepplate_well=deepplate_well)

✅ Successfully wrote to: protocol/otflex_25.py

In [10]:
df_absorbance = hf.process_absorbance(iteration=n, threshold=0.06)
df_absorbance

   trial_index  success
0            0        1
1            1        1
2            2        0
3            3        1
4            4        1
5            5        0
6            6        0
7            7        0

In [11]:
results = hf.build_results(n, df_absorbance)
results

,trial_index,drug_name,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,surf_3_conc,drug_conc,surf_1,surf_2,surf_3,surf_conc,obj_surf_conc,success
0,132,IBP,0.2063,0.3073,0.0373,51,0,0,25.0,s1,s7,s1,51,51,1
1,133,LOV,0.4045,0.4196,0.0728,54,0,0,25.0,s1,s3,s6,54,54,1
2,134,DCF,0.2962,0.4364,0.0493,81,0,0,25.0,s1,s3,s1,81,100,0
3,135,GLV,0.3528,0.2810,0.0711,57,0,0,25.0,s1,s3,s6,57,57,1
4,136,IBP,0.2063,0.3073,0.0373,11,0,0,25.0,s1,s3,s6,11,11,1
5,137,LOV,0.4045,0.4196,0.0728,6,0,0,25.0,s1,s7,s1,6,100,0
6,138,DCF,0.2962,0.4364,0.0493,17,0,0,25.0,s1,s3,s1,17,100,0
7,139,GLV,0.3528,0.2810,0.0711,18,0,0,25.0,s1,s3,s1,18,100,0

# load the results to the optimizer

In [12]:
ax_client = hf.load_data_to_optimizer(iteration = n, results = results)
ax_client

[INFO 07-24 15:39:33] ax.service.ax_client: Completed trial 132 with data: {'obj_surf_conc': (51.0, None)}.
[INFO 07-24 15:39:33] ax.service.ax_client: Completed trial 133 with data: {'obj_surf_conc': (54.0, None)}.
[INFO 07-24 15:39:33] ax.service.ax_client: Completed trial 134 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-24 15:39:33] ax.service.ax_client: Completed trial 135 with data: {'obj_surf_conc': (57.0, None)}.
[INFO 07-24 15:39:33] ax.service.ax_client: Completed trial 136 with data: {'obj_surf_conc': (11.0, None)}.
[INFO 07-24 15:39:33] ax.service.ax_client: Completed trial 137 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-24 15:39:33] ax.service.ax_client: Completed trial 138 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-24 15:39:33] ax.service.ax_client: Completed trial 139 with data: {'obj_surf_conc': (100.0, None)}.

AxClient(experiment=Experiment(drug_surfactant))