# import libraries

In [1]:
import pandas as pd
from ax.service.ax_client import AxClient, ObjectiveProperties
import matplotlib.pyplot as plt
from ax.modelbridge.registry import Models
from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy   
import time


import sys
sys.path.append('../')
import helper_functions as hf

/var/folders/9p/f66yhymx35939zzlg51g0rrc0000gn/T/ipykernel_91475/3307975217.py:5: DeprecationWarning: Please import from 'ax.generation_strategy.generation_strategy' instead of 'ax.modelbridge.generation_strategy'. The latter is deprecated and will be removed in a future release.
  from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy

# generate recommendations

In [2]:
n = hf.get_iteration_number()

for i in range(3):
    print("Very Important: Please Confirm the Iteration Number is Iteration " + str(n))

print()

list_of_drugs = ['IBP'] * 2 + ['LOV'] * 2 + ['DCF'] * 2 + ['GLV'] * 2

for i in range(3):
    print("Very Important: Please Confirm the Drugs are: ", list_of_drugs)

Very Important: Please Confirm the Iteration Number is Iteration 4
Very Important: Please Confirm the Iteration Number is Iteration 4
Very Important: Please Confirm the Iteration Number is Iteration 4

Very Important: Please Confirm the Drugs are:  ['IBP', 'IBP', 'LOV', 'LOV', 'DCF', 'DCF', 'GLV', 'GLV']
Very Important: Please Confirm the Drugs are:  ['IBP', 'IBP', 'LOV', 'LOV', 'DCF', 'DCF', 'GLV', 'GLV']
Very Important: Please Confirm the Drugs are:  ['IBP', 'IBP', 'LOV', 'LOV', 'DCF', 'DCF', 'GLV', 'GLV']

In [3]:
time_start = time.time()


df_design, ax_client = hf.run_optimizer(current_iteration=n, drug_list= list_of_drugs,  bopt = 1)

time_end = time.time()
time_duration = round((time_end - time_start)/60,2)

print("Time taken for optimization: " + str(time_duration) + " mins")
print("Time taken for optimization: " + str(time_duration * 60) + " seconds")

**************************************************************************************************** 1  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Ibuprofen IBP  | Iteration:  4

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[INFO 07-17 09:27:25] ax.service.ax_client: Generated new trial 32 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 0.537324, 'surf_2_conc': 0.0, 'surf_3_conc': 21.19595, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'} using model BoTorch.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

**************************************************************************************************** 2  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Ibuprofen IBP  | Iteration:  4

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[INFO 07-17 09:27:29] ax.service.ax_client: Generated new trial 33 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 8.182763, 'surf_2_conc': 0.01273, 'surf_3_conc': 21.169963, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'} using model BoTorch.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

**************************************************************************************************** 3  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Lovastatin LOV  | Iteration:  4

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[INFO 07-17 09:27:34] ax.service.ax_client: Generated new trial 34 with parameters {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 3.094653, 'surf_2_conc': 0.0, 'surf_3_conc': 21.394074, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'} using model BoTorch.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

**************************************************************************************************** 4  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Lovastatin LOV  | Iteration:  4

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[INFO 07-17 09:27:39] ax.service.ax_client: Generated new trial 35 with parameters {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 2.601397, 'surf_2_conc': 0.0, 'surf_3_conc': 21.07508, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'} using model BoTorch.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

**************************************************************************************************** 5  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Diclofenac DCF  | Iteration:  4

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[INFO 07-17 09:27:43] ax.service.ax_client: Generated new trial 36 with parameters {'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 2.105863, 'surf_2_conc': 0.0, 'surf_3_conc': 21.170574, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'} using model BoTorch.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

**************************************************************************************************** 6  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Diclofenac DCF  | Iteration:  4

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[INFO 07-17 09:27:48] ax.service.ax_client: Generated new trial 37 with parameters {'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 2.078534, 'surf_2_conc': 0.484447, 'surf_3_conc': 21.329388, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'} using model BoTorch.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

**************************************************************************************************** 7  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Griseofulvin GLV  | Iteration:  4

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[INFO 07-17 09:27:53] ax.service.ax_client: Generated new trial 38 with parameters {'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 0.0, 'surf_2_conc': 0.0, 'surf_3_conc': 21.220286, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'} using model BoTorch.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

**************************************************************************************************** 8  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Griseofulvin GLV  | Iteration:  4

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[INFO 07-17 09:27:58] ax.service.ax_client: Generated new trial 39 with parameters {'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 0.0, 'surf_2_conc': 0.0, 'surf_3_conc': 21.341271, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'} using model BoTorch.

Time taken for optimization: 0.65 mins
Time taken for optimization: 39.0 seconds

# process results

In [4]:
ax_client = hf.load_design_optimizer(n)
ax_client.experiment.trials

{0: Trial(experiment_name='drug_surfactant', index=0, status=TrialStatus.COMPLETED, arm=Arm(name='0_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 6.342537747696042, 'surf_2_conc': 19.79255275800824, 'surf_3_conc': 10.062114521861076, 'drug_conc': 25.0, 'surf_1': 's8', 'surf_2': 's6', 'surf_3': 's7'})),
 1: Trial(experiment_name='drug_surfactant', index=1, status=TrialStatus.COMPLETED, arm=Arm(name='1_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 25.38895425386727, 'surf_2_conc': 2.403562143445015, 'surf_3_conc': 19.870580919086933, 'drug_conc': 25.0, 'surf_1': 's3', 'surf_2': 's2', 'surf_3': 's6'})),
 2: Trial(experiment_name='drug_surfactant', index=2, status=TrialStatus.COMPLETED, arm=Arm(name='2_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 0.5619284231215715, 'surf_2_conc': 27.77170091867447, 'surf_3_conc': 0.44598919339478016, 'drug_conc': 25.0, 'surf_1': 's5', 'surf_2': 's7', 'surf_3': 's3'})),
 3: Trial(experiment_name='drug_surfactant', index=3, status=TrialStatus.COMPLETED, arm=Arm(name='3_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 14.076332002878189, 'surf_2_conc': 3.4227336291223764, 'surf_3_conc': 7.078612456098199, 'drug_conc': 25.0, 'surf_1': 's3', 'surf_2': 's3', 'surf_3': 's8'})),
 4: Trial(experiment_name='drug_surfactant', index=4, status=TrialStatus.COMPLETED, arm=Arm(name='4_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 13.45692495815456, 'surf_2_conc': 31.46618972532451, 'surf_3_conc': 1.5700268559157848, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's4', 'surf_3': 's5'})),
 5: Trial(experiment_name='drug_surfactant', index=5, status=TrialStatus.COMPLETED, arm=Arm(name='5_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 20.0191970448941, 'surf_2_conc': 14.549109572544694, 'surf_3_conc': 11.283737001940608, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's8', 'surf_3': 's7'})),
 6: Trial(experiment_name='drug_surfactant', index=6, status=TrialStatus.COMPLETED, arm=Arm(name='6_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 2.750313561409712, 'surf_2_conc': 12.241790909320116, 'surf_3_conc': 9.081532154232264, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's1', 'surf_3': 's6'})),
 7: Trial(experiment_name='drug_surfactant', index=7, status=TrialStatus.COMPLETED, arm=Arm(name='7_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 5.021025240421295, 'surf_2_conc': 0.8626881986856461, 'surf_3_conc': 17.897260980680585, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'})),
 8: Trial(experiment_name='drug_surfactant', index=8, status=TrialStatus.COMPLETED, arm=Arm(name='8_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 5.668197774056159, 'surf_2_conc': 6.320464227528258, 'surf_3_conc': 11.327995239229978, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'})),
 9: Trial(experiment_name='drug_surfactant', index=9, status=TrialStatus.COMPLETED, arm=Arm(name='9_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 5.247318539742054, 'surf_2_conc': 6.494839715909041, 'surf_3_conc': 11.959136935574504, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'})),
 10: Trial(experiment_name='drug_surfactant', index=10, status=TrialStatus.COMPLETED, arm=Arm(name='10_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 5.470369224932467, 'surf_2_conc': 6.646012903549162, 'surf_3_conc': 11.399699381742582, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'})),
 11: Trial(experiment_name='drug_surfactant', index=11, status=TrialStatus.COMPLETED, arm=Arm(name='11_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 5.6194247088055045, 'surf_2_conc': 6.724490376492919, 'surf_3_conc': 11.689981851196462, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'})),
 12: Trial(experiment_name='drug_surfactant', index=12, status=TrialStatus.COMPLETED, arm=Arm(name='12_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 5.042465749720437, 'surf_2_conc': 6.0938792658471606, 'surf_3_conc': 11.534039075388225, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's1', 'surf_3': 's1'})),
 13: Trial(experiment_name='drug_surfactant', index=13, status=TrialStatus.COMPLETED, arm=Arm(name='13_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 5.374478446549213, 'surf_2_conc': 6.539092747379219, 'surf_3_conc': 11.844956084010157, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'})),
 14: Trial(experiment_name='drug_surfactant', index=14, status=TrialStatus.COMPLETED, arm=Arm(name='14_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 5.632743844336128, 'surf_2_conc': 6.382770638996576, 'surf_3_conc': 10.764404948215262, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'})),
 15: Trial(experiment_name='drug_surfactant', index=15, status=TrialStatus.COMPLETED, arm=Arm(name='15_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 5.901514901282581, 'surf_2_conc': 6.53012017608344, 'surf_3_conc': 12.174544873567378, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'})),
 16: Trial(experiment_name='drug_surfactant', index=16, status=TrialStatus.COMPLETED, arm=Arm(name='16_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 4.1014657460982935, 'surf_2_conc': 2.415786465498623e-17, 'surf_3_conc': 20.977722524417576, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'})),
 17: Trial(experiment_name='drug_surfactant', index=17, status=TrialStatus.COMPLETED, arm=Arm(name='17_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 4.068856266288576, 'surf_2_conc': 0.0, 'surf_3_conc': 21.37648519074993, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'})),
 18: Trial(experiment_name='drug_surfactant', index=18, status=TrialStatus.COMPLETED, arm=Arm(name='18_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 3.0838325421974484, 'surf_2_conc': 1.612001327112265e-18, 'surf_3_conc': 20.5897972286915, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'})),
 19: Trial(experiment_name='drug_surfactant', index=19, status=TrialStatus.COMPLETED, arm=Arm(name='19_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 4.124659871099773, 'surf_2_conc': 0.0, 'surf_3_conc': 21.081459840753297, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'})),
 20: Trial(experiment_name='drug_surfactant', index=20, status=TrialStatus.COMPLETED, arm=Arm(name='20_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 2.6725591497168923, 'surf_2_conc': 1.7380840631652225e-17, 'surf_3_conc': 20.91241781784725, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'})),
 21: Trial(experiment_name='drug_surfactant', index=21, status=TrialStatus.COMPLETED, arm=Arm(name='21_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 4.073511108902758, 'surf_2_conc': 0.0, 'surf_3_conc': 21.43403790179248, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'})),
 22: Trial(experiment_name='drug_surfactant', index=22, status=TrialStatus.COMPLETED, arm=Arm(name='22_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 3.960861453884924, 'surf_2_conc': 0.0, 'surf_3_conc': 21.229545554604286, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'})),
 23: Trial(experiment_name='drug_surfactant', index=23, status=TrialStatus.COMPLETED, arm=Arm(name='23_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 3.4572225844165247, 'surf_2_conc': 5.284867367817258e-15, 'surf_3_conc': 20.51801188458017, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'})),
 24: Trial(experiment_name='drug_surfactant', index=24, status=TrialStatus.COMPLETED, arm=Arm(name='24_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 3.4540533702457026, 'surf_2_conc': 2.923349497843976e-15, 'surf_3_conc': 20.991451133464853, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'})),
 25: Trial(experiment_name='drug_surfactant', index=25, status=TrialStatus.COMPLETED, arm=Arm(name='25_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 4.061353610195819, 'surf_2_conc': 5.0783153891298567e-17, 'surf_3_conc': 21.040603865846474, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'})),
 26: Trial(experiment_name='drug_surfactant', index=26, status=TrialStatus.COMPLETED, arm=Arm(name='26_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 2.292980798673601, 'surf_2_conc': 6.994903549029776e-16, 'surf_3_conc': 19.25956636895013, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'})),
 27: Trial(experiment_name='drug_surfactant', index=27, status=TrialStatus.COMPLETED, arm=Arm(name='27_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 1.7244701761129602, 'surf_2_conc': 0.0, 'surf_3_conc': 19.282680694649606, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'})),
 28: Trial(experiment_name='drug_surfactant', index=28, status=TrialStatus.COMPLETED, arm=Arm(name='28_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 4.362708314034968, 'surf_2_conc': 5.915596846217909, 'surf_3_conc': 11.544758751351168, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's1', 'surf_3': 's1'})),
 29: Trial(experiment_name='drug_surfactant', index=29, status=TrialStatus.COMPLETED, arm=Arm(name='29_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 5.429148868603685, 'surf_2_conc': 5.7993724732595195, 'surf_3_conc': 11.58454454918471, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's1', 'surf_3': 's1'})),
 30: Trial(experiment_name='drug_surfactant', index=30, status=TrialStatus.COMPLETED, arm=Arm(name='30_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 7.842217655762397, 'surf_2_conc': 1.0337760609728898e-16, 'surf_3_conc': 19.18240503559282, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'})),
 31: Trial(experiment_name='drug_surfactant', index=31, status=TrialStatus.COMPLETED, arm=Arm(name='31_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 8.31425270226393, 'surf_2_conc': 5.411696605876135e-16, 'surf_3_conc': 19.17308198901006, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'})),
 32: Trial(experiment_name='drug_surfactant', index=32, status=TrialStatus.RUNNING, arm=Arm(name='32_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 0.5373236995481776, 'surf_2_conc': 0.0, 'surf_3_conc': 21.19595006613784, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'})),
 33: Trial(experiment_name='drug_surfactant', index=33, status=TrialStatus.RUNNING, arm=Arm(name='33_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 8.182763232288005, 'surf_2_conc': 0.012729679475304258, 'surf_3_conc': 21.16996318041358, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'})),
 34: Trial(experiment_name='drug_surfactant', index=34, status=TrialStatus.RUNNING, arm=Arm(name='34_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 3.0946534296379085, 'surf_2_conc': 0.0, 'surf_3_conc': 21.394074416297066, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'})),
 35: Trial(experiment_name='drug_surfactant', index=35, status=TrialStatus.RUNNING, arm=Arm(name='35_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 2.6013972531176113, 'surf_2_conc': 0.0, 'surf_3_conc': 21.07508003216919, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'})),
 36: Trial(experiment_name='drug_surfactant', index=36, status=TrialStatus.RUNNING, arm=Arm(name='36_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 2.1058627444780367, 'surf_2_conc': 6.899389557889031e-13, 'surf_3_conc': 21.170574334433944, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'})),
 37: Trial(experiment_name='drug_surfactant', index=37, status=TrialStatus.RUNNING, arm=Arm(name='37_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 2.0785340160891286, 'surf_2_conc': 0.4844468715509036, 'surf_3_conc': 21.32938801004208, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'})),
 38: Trial(experiment_name='drug_surfactant', index=38, status=TrialStatus.RUNNING, arm=Arm(name='38_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 2.393523564579636e-15, 'surf_2_conc': 1.3484331597230628e-15, 'surf_3_conc': 21.22028605785046, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'})),
 39: Trial(experiment_name='drug_surfactant', index=39, status=TrialStatus.RUNNING, arm=Arm(name='39_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 2.0231749156057292e-16, 'surf_2_conc': 0.0, 'surf_3_conc': 21.34127097167323, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'}))}

In [5]:
df_design, df_vol = hf.design_to_vol (n)
df_design

,trial_index,drug_name,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,surf_3_conc,drug_conc,surf_1,surf_2,surf_3,surf_conc,obj_surf_conc
0,32,IBP,0.2063,0.3073,0.0373,5.373237e-01,0.000000e+00,21.195950,25.0,s6,s5,s1,21.733274,NaN
1,33,IBP,0.2063,0.3073,0.0373,8.182763e+00,1.272968e-02,21.169963,25.0,s6,s5,s1,29.365456,NaN
2,34,LOV,0.4045,0.4196,0.0728,3.094653e+00,0.000000e+00,21.394074,25.0,s6,s5,s1,24.488728,NaN
3,35,LOV,0.4045,0.4196,0.0728,2.601397e+00,0.000000e+00,21.075080,25.0,s6,s5,s1,23.676477,NaN
4,36,DCF,0.2962,0.4364,0.0493,2.105863e+00,6.899390e-13,21.170574,25.0,s6,s5,s1,23.276437,NaN
5,37,DCF,0.2962,0.4364,0.0493,2.078534e+00,4.844469e-01,21.329388,25.0,s6,s5,s1,23.892369,NaN
6,38,GLV,0.3528,0.2810,0.0711,2.393524e-15,1.348433e-15,21.220286,25.0,s6,s5,s1,21.220286,NaN
7,39,GLV,0.3528,0.2810,0.0711,2.023175e-16,0.000000e+00,21.341271,25.0,s6,s5,s1,21.341271,NaN

In [6]:
df_vol

,trial_index,drug_name,drug,s1,s2,s3,s4,s5,s6,s7,s8,dmso,water,IBP,LOV,DCF,GLV
0,32,IBP,180.0,508.702802,0.0,0.0,0.0,0.000000e+00,1.289577e+01,0.0,0.0,0.0,678.401430,180.0,0.0,0.0,0.0
1,33,IBP,180.0,508.079116,0.0,0.0,0.0,3.055123e-01,1.963863e+02,0.0,0.0,0.0,495.229054,180.0,0.0,0.0,0.0
2,34,LOV,180.0,513.457786,0.0,0.0,0.0,0.000000e+00,7.427168e+01,0.0,0.0,0.0,612.270532,0.0,180.0,0.0,0.0
3,35,LOV,180.0,505.801921,0.0,0.0,0.0,0.000000e+00,6.243353e+01,0.0,0.0,0.0,631.764545,0.0,180.0,0.0,0.0
4,36,DCF,180.0,508.093784,0.0,0.0,0.0,1.655853e-11,5.054071e+01,0.0,0.0,0.0,641.365510,0.0,0.0,180.0,0.0
5,37,DCF,180.0,511.905312,0.0,0.0,0.0,1.162672e+01,4.988482e+01,0.0,0.0,0.0,626.583146,0.0,0.0,180.0,0.0
6,38,GLV,180.0,509.286865,0.0,0.0,0.0,3.236240e-14,5.744457e-14,0.0,0.0,0.0,690.713135,0.0,0.0,0.0,180.0
7,39,GLV,180.0,512.190503,0.0,0.0,0.0,0.000000e+00,4.855620e-15,0.0,0.0,0.0,687.809497,0.0,0.0,0.0,180.0

In [7]:
plate_well = input("Enter the plate well starting well (e.g., F1): ")
deepplate_well = input("Enter the deep plate well starting well (e.g., F1): ")


print("Please confirm the following information:")
print("Wellplate will start at: " + plate_well)
print("Deep plate will start at: " + deepplate_well)

print()
print("*******************************************************")
print("Continue if correct, or rerun this cell if incorrect.")
print("*******************************************************")

Please confirm the following information:
Wellplate will start at: A1
Deep plate will start at: E1

*******************************************************
Continue if correct, or rerun this cell if incorrect.
*******************************************************

In [8]:
hf.generate_protocol(df_vol=df_vol, iteration=n, plate_well=plate_well, deepplate_well=deepplate_well)

✅ Successfully wrote to: protocol/otflex_4.py

In [9]:
df_absorbance = hf.process_absorbance(iteration=n, threshold=0.1)
df_absorbance

   trial_index  success
0            0        1
1            1        1
2            2        1
3            3        1
4            4        1
5            5        0
6            6        1
7            7        1

In [10]:
results = hf.build_results(n, df_absorbance)
results

,trial_index,drug_name,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,surf_3_conc,drug_conc,surf_1,surf_2,surf_3,surf_conc,obj_surf_conc,success
0,32,IBP,0.2063,0.3073,0.0373,5.373237e-01,0.000000e+00,21.195950,25.0,s6,s5,s1,21.733274,21.733274,1
1,33,IBP,0.2063,0.3073,0.0373,8.182763e+00,1.272968e-02,21.169963,25.0,s6,s5,s1,29.365456,29.365456,1
2,34,LOV,0.4045,0.4196,0.0728,3.094653e+00,0.000000e+00,21.394074,25.0,s6,s5,s1,24.488728,24.488728,1
3,35,LOV,0.4045,0.4196,0.0728,2.601397e+00,0.000000e+00,21.075080,25.0,s6,s5,s1,23.676477,23.676477,1
4,36,DCF,0.2962,0.4364,0.0493,2.105863e+00,6.899390e-13,21.170574,25.0,s6,s5,s1,23.276437,23.276437,1
5,37,DCF,0.2962,0.4364,0.0493,2.078534e+00,4.844469e-01,21.329388,25.0,s6,s5,s1,23.892369,50.000000,0
6,38,GLV,0.3528,0.2810,0.0711,2.393524e-15,1.348433e-15,21.220286,25.0,s6,s5,s1,21.220286,21.220286,1
7,39,GLV,0.3528,0.2810,0.0711,2.023175e-16,0.000000e+00,21.341271,25.0,s6,s5,s1,21.341271,21.341271,1

# load the results to the optimizer

In [11]:
ax_client = hf.load_data_to_optimizer(iteration = n, results = results)
ax_client

[INFO 07-17 11:33:07] ax.service.ax_client: Completed trial 32 with data: {'obj_surf_conc': (21.733274, None)}.
[INFO 07-17 11:33:07] ax.service.ax_client: Completed trial 33 with data: {'obj_surf_conc': (29.365456, None)}.
[INFO 07-17 11:33:07] ax.service.ax_client: Completed trial 34 with data: {'obj_surf_conc': (24.488728, None)}.
[INFO 07-17 11:33:07] ax.service.ax_client: Completed trial 35 with data: {'obj_surf_conc': (23.676477, None)}.
[INFO 07-17 11:33:07] ax.service.ax_client: Completed trial 36 with data: {'obj_surf_conc': (23.276437, None)}.
[INFO 07-17 11:33:07] ax.service.ax_client: Completed trial 37 with data: {'obj_surf_conc': (50.0, None)}.
[INFO 07-17 11:33:07] ax.service.ax_client: Completed trial 38 with data: {'obj_surf_conc': (21.220286, None)}.
[INFO 07-17 11:33:07] ax.service.ax_client: Completed trial 39 with data: {'obj_surf_conc': (21.341271, None)}.

AxClient(experiment=Experiment(drug_surfactant))