# import libraries

In [1]:
import pandas as pd
from ax.service.ax_client import AxClient, ObjectiveProperties
import matplotlib.pyplot as plt
from ax.modelbridge.factory import Models
from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy   


import sys
sys.path.append('../')
import helper_functions as hf

# generate recommendations

In [2]:
n = hf.get_iteration_number()

for i in range(3):
    print("Very Important: Please Confirm the Iteration Number is Iteration " + str(n))

Very Important: Please Confirm the Iteration Number is Iteration 2
Very Important: Please Confirm the Iteration Number is Iteration 2
Very Important: Please Confirm the Iteration Number is Iteration 2

In [5]:
df_design, ax_client = hf.run_optimizer(current_iteration=n, n_trials=6)

[INFO 06-03 11:13:13] ax.service.ax_client: Starting optimization with verbose logging. To disable logging, set the `verbose_logging` argument to `False`. Note that float values in the logs are rounded to 6 decimal points.
[INFO 06-03 11:30:48] ax.service.ax_client: Generated new trial 12 with parameters {'s1': 0, 's2': 0, 's3': 100, 's4': 84, 's5': 48, 's6': 48, 's7': 93, 's8': 5, 's9': 70, 'surfactant_conc': 1, 'drug_conc': 69} using model SAASBO.
c:\Users\yunhe\anaconda3\envs\drug_surfactant\Lib\site-packages\ax\core\data.py:295: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
[INFO 06-03 11:35:17] ax.service.ax_client: Generated new trial 13 with parameters {'s1': 0, 's2': 0, 's3': 100, 's4': 0, 's5': 100, 's6': 47, 's7': 100, 's8': 0, 's9': 0, 'surfactant_conc': 1, 'drug_conc': 100} using model SAASBO.
c:\Users\yunhe\anaconda3\envs\drug_surfactant\Lib\site-packages\ax\core\data.py:295: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
[INFO 06-03 11:43:04] ax.service.ax_client: Generated new trial 14 with parameters {'s1': 0, 's2': 0, 's3': 0, 's4': 100, 's5': 0, 's6': 46, 's7': 100, 's8': 0, 's9': 100, 'surfactant_conc': 1, 'drug_conc': 100} using model SAASBO.
c:\Users\yunhe\anaconda3\envs\drug_surfactant\Lib\site-packages\ax\core\data.py:295: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
[INFO 06-03 11:49:04] ax.service.ax_client: Generated new trial 15 with parameters {'s1': 0, 's2': 0, 's3': 0, 's4': 0, 's5': 100, 's6': 48, 's7': 100, 's8': 100, 's9': 69, 'surfactant_conc': 1, 'drug_conc': 1} using model SAASBO.
c:\Users\yunhe\anaconda3\envs\drug_surfactant\Lib\site-packages\ax\core\data.py:295: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
[INFO 06-03 11:55:05] ax.service.ax_client: Generated new trial 16 with parameters {'s1': 100, 's2': 0, 's3': 100, 's4': 100, 's5': 100, 's6': 50, 's7': 100, 's8': 0, 's9': 100, 'surfactant_conc': 1, 'drug_conc': 1} using model SAASBO.
c:\Users\yunhe\anaconda3\envs\drug_surfactant\Lib\site-packages\ax\core\data.py:295: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
[INFO 06-03 12:00:58] ax.service.ax_client: Generated new trial 17 with parameters {'s1': 0, 's2': 0, 's3': 100, 's4': 11, 's5': 0, 's6': 45, 's7': 100, 's8': 100, 's9': 68, 'surfactant_conc': 1, 'drug_conc': 100} using model SAASBO.
[INFO 06-03 12:00:58] ax.service.ax_client: Saved JSON-serialized state of optimization to `optimizer/optimizer_2.json`.

# process results

In [6]:
ax_client = hf.load_design_optimizer(n)
ax_client.experiment.trials

[INFO 06-03 12:06:41] ax.service.ax_client: Starting optimization with verbose logging. To disable logging, set the `verbose_logging` argument to `False`. Note that float values in the logs are rounded to 6 decimal points.

{0: Trial(experiment_name='drug_surfactant', index=0, status=TrialStatus.COMPLETED, arm=Arm(name='0_0', parameters={'s1': 47, 's2': 59, 's3': 49, 's4': 31, 's5': 96, 's6': 8, 's7': 9, 's8': 35, 's9': 85, 'surfactant_conc': 77, 'drug_conc': 89})),
 1: Trial(experiment_name='drug_surfactant', index=1, status=TrialStatus.COMPLETED, arm=Arm(name='1_0', parameters={'s1': 92, 's2': 28, 's3': 51, 's4': 69, 's5': 27, 's6': 83, 's7': 70, 's8': 58, 's9': 36, 'surfactant_conc': 30, 'drug_conc': 3})),
 2: Trial(experiment_name='drug_surfactant', index=2, status=TrialStatus.COMPLETED, arm=Arm(name='2_0', parameters={'s1': 53, 's2': 81, 's3': 8, 's4': 21, 's5': 17, 's6': 73, 's7': 48, 's8': 97, 's9': 20, 'surfactant_conc': 14, 'drug_conc': 29})),
 3: Trial(experiment_name='drug_surfactant', index=3, status=TrialStatus.COMPLETED, arm=Arm(name='3_0', parameters={'s1': 7, 's2': 7, 's3': 92, 's4': 84, 's5': 61, 's6': 49, 's7': 82, 's8': 24, 's9': 69, 'surfactant_conc': 68, 'drug_conc': 69})),
 4: Trial(experiment_name='drug_surfactant', index=4, status=TrialStatus.COMPLETED, arm=Arm(name='4_0', parameters={'s1': 21, 's2': 88, 's3': 68, 's4': 90, 's5': 72, 's6': 15, 's7': 35, 's8': 81, 's9': 3, 'surfactant_conc': 50, 'drug_conc': 41})),
 5: Trial(experiment_name='drug_surfactant', index=5, status=TrialStatus.COMPLETED, arm=Arm(name='5_0', parameters={'s1': 65, 's2': 24, 's3': 32, 's4': 2, 's5': 2, 's6': 93, 's7': 95, 's8': 1, 's9': 55, 'surfactant_conc': 95, 'drug_conc': 51})),
 6: Trial(experiment_name='drug_surfactant', index=6, status=TrialStatus.COMPLETED, arm=Arm(name='6_0', parameters={'s1': 0, 's2': 0, 's3': 100, 's4': 100, 's5': 57, 's6': 100, 's7': 68, 's8': 100, 's9': 100, 'surfactant_conc': 1, 'drug_conc': 78})),
 7: Trial(experiment_name='drug_surfactant', index=7, status=TrialStatus.COMPLETED, arm=Arm(name='7_0', parameters={'s1': 0, 's2': 0, 's3': 0, 's4': 100, 's5': 0, 's6': 100, 's7': 100, 's8': 100, 's9': 100, 'surfactant_conc': 1, 'drug_conc': 1})),
 8: Trial(experiment_name='drug_surfactant', index=8, status=TrialStatus.COMPLETED, arm=Arm(name='8_0', parameters={'s1': 0, 's2': 0, 's3': 100, 's4': 100, 's5': 59, 's6': 100, 's7': 58, 's8': 0, 's9': 0, 'surfactant_conc': 1, 'drug_conc': 100})),
 9: Trial(experiment_name='drug_surfactant', index=9, status=TrialStatus.COMPLETED, arm=Arm(name='9_0', parameters={'s1': 0, 's2': 0, 's3': 100, 's4': 0, 's5': 0, 's6': 0, 's7': 100, 's8': 100, 's9': 100, 'surfactant_conc': 1, 'drug_conc': 1})),
 10: Trial(experiment_name='drug_surfactant', index=10, status=TrialStatus.COMPLETED, arm=Arm(name='10_0', parameters={'s1': 0, 's2': 100, 's3': 100, 's4': 100, 's5': 0, 's6': 100, 's7': 100, 's8': 100, 's9': 100, 'surfactant_conc': 1, 'drug_conc': 100})),
 11: Trial(experiment_name='drug_surfactant', index=11, status=TrialStatus.COMPLETED, arm=Arm(name='11_0', parameters={'s1': 0, 's2': 0, 's3': 0, 's4': 0, 's5': 61, 's6': 100, 's7': 100, 's8': 100, 's9': 0, 'surfactant_conc': 1, 'drug_conc': 100})),
 12: Trial(experiment_name='drug_surfactant', index=12, status=TrialStatus.RUNNING, arm=Arm(name='12_0', parameters={'s1': 0, 's2': 0, 's3': 100, 's4': 84, 's5': 48, 's6': 48, 's7': 93, 's8': 5, 's9': 70, 'surfactant_conc': 1, 'drug_conc': 69})),
 13: Trial(experiment_name='drug_surfactant', index=13, status=TrialStatus.RUNNING, arm=Arm(name='13_0', parameters={'s1': 0, 's2': 0, 's3': 100, 's4': 0, 's5': 100, 's6': 47, 's7': 100, 's8': 0, 's9': 0, 'surfactant_conc': 1, 'drug_conc': 100})),
 14: Trial(experiment_name='drug_surfactant', index=14, status=TrialStatus.RUNNING, arm=Arm(name='14_0', parameters={'s1': 0, 's2': 0, 's3': 0, 's4': 100, 's5': 0, 's6': 46, 's7': 100, 's8': 0, 's9': 100, 'surfactant_conc': 1, 'drug_conc': 100})),
 15: Trial(experiment_name='drug_surfactant', index=15, status=TrialStatus.RUNNING, arm=Arm(name='15_0', parameters={'s1': 0, 's2': 0, 's3': 0, 's4': 0, 's5': 100, 's6': 48, 's7': 100, 's8': 100, 's9': 69, 'surfactant_conc': 1, 'drug_conc': 1})),
 16: Trial(experiment_name='drug_surfactant', index=16, status=TrialStatus.RUNNING, arm=Arm(name='16_0', parameters={'s1': 100, 's2': 0, 's3': 100, 's4': 100, 's5': 100, 's6': 50, 's7': 100, 's8': 0, 's9': 100, 'surfactant_conc': 1, 'drug_conc': 1})),
 17: Trial(experiment_name='drug_surfactant', index=17, status=TrialStatus.RUNNING, arm=Arm(name='17_0', parameters={'s1': 0, 's2': 0, 's3': 100, 's4': 11, 's5': 0, 's6': 45, 's7': 100, 's8': 100, 's9': 68, 'surfactant_conc': 1, 'drug_conc': 100}))}

In [7]:
df_conc, df_vol = hf.design_to_conc_to_vol (n)

In [10]:
plate_well = input("Enter the plate well starting well (e.g., F1): ")
deepplate_well = input("Enter the deep plate well starting well (e.g., F1): ")


print("Please confirm the following information:")
print("Wellplate will start at: " + plate_well)
print("Deep plate will start at: " + deepplate_well)

print()
print("*******************************************************")
print("Continue if correct, or rerun this cell if incorrect.")
print("*******************************************************")

Please confirm the following information:
Wellplate will start at: C1
Deep plate will start at: C1

*******************************************************
Continue if correct, or rerun this cell if incorrect.
*******************************************************

In [11]:

hf.generate_protocol(df_vol=df_vol, iteration=n, plate_well=plate_well, deepplate_well=deepplate_well)

✅ Successfully wrote to: protocol/otflex_2.py

In [12]:
df_absorbance = hf.process_absorbance(iteration=n)

In [13]:
results = hf.build_results(n, df_conc, df_absorbance)

In [14]:
results

,trial_index,s1,s2,s3,s4,s5,s6,s7,s8,s9,surfactant_conc,drug_conc,success,micelle_drug_conc,complexity
0,12,0,0,100,84,48,48,93,5,70,0.5,17.25,0,0.000,7
1,13,0,0,100,0,100,47,100,0,0,0.5,25.00,0,0.000,4
2,14,0,0,0,100,0,46,100,0,100,0.5,25.00,0,0.000,4
3,15,0,0,0,0,100,48,100,100,69,0.5,0.25,1,0.025,5
4,16,100,0,100,100,100,50,100,0,100,0.5,0.25,1,0.025,7
5,17,0,0,100,11,0,45,100,100,68,0.5,25.00,1,2.500,6

In [15]:
norm_results = hf.normalize_data(results, 'normalize')

In [16]:
norm_results

,trial_index,s1,s2,s3,s4,s5,s6,s7,s8,s9,surfactant_conc,drug_conc,success,micelle_drug_conc,complexity
0,12,0,0,100,84,48,48,93,5,70,0.01,17.25,0,0.00,0.777778
1,13,0,0,100,0,100,47,100,0,0,0.01,25.00,0,0.00,0.444444
2,14,0,0,0,100,0,46,100,0,100,0.01,25.00,0,0.00,0.444444
3,15,0,0,0,0,100,48,100,100,69,0.01,0.25,1,0.01,0.555556
4,16,100,0,100,100,100,50,100,0,100,0.01,0.25,1,0.01,0.777778
5,17,0,0,100,11,0,45,100,100,68,0.01,25.00,1,1.00,0.666667

# load the results to the optimizer

In [17]:
ax_client = hf.load_data_to_optimizer(iteration = n, norm_results = norm_results)
ax_client

[INFO 06-03 15:54:50] ax.service.ax_client: Starting optimization with verbose logging. To disable logging, set the `verbose_logging` argument to `False`. Note that float values in the logs are rounded to 6 decimal points.
[INFO 06-03 15:54:50] ax.service.ax_client: Completed trial 12 with data: {'micelle_drug_conc': (0.0, None), 'surfactant_conc': (0.01, None), 'complexity': (0.777778, None)}.
[INFO 06-03 15:54:50] ax.service.ax_client: Completed trial 13 with data: {'micelle_drug_conc': (0.0, None), 'surfactant_conc': (0.01, None), 'complexity': (0.444444, None)}.
[INFO 06-03 15:54:50] ax.service.ax_client: Completed trial 14 with data: {'micelle_drug_conc': (0.0, None), 'surfactant_conc': (0.01, None), 'complexity': (0.444444, None)}.
[INFO 06-03 15:54:50] ax.service.ax_client: Completed trial 15 with data: {'micelle_drug_conc': (0.01, None), 'surfactant_conc': (0.01, None), 'complexity': (0.555556, None)}.
[INFO 06-03 15:54:50] ax.service.ax_client: Completed trial 16 with data: {'micelle_drug_conc': (0.01, None), 'surfactant_conc': (0.01, None), 'complexity': (0.777778, None)}.
[INFO 06-03 15:54:50] ax.service.ax_client: Completed trial 17 with data: {'micelle_drug_conc': (1.0, None), 'surfactant_conc': (0.01, None), 'complexity': (0.666667, None)}.
[INFO 06-03 15:54:50] ax.service.ax_client: Saved JSON-serialized state of optimization to `optimizer/optimizer_2_loaded.json`.

AxClient(experiment=Experiment(drug_surfactant))