# import libraries

In [1]:
import pandas as pd
from ax.service.ax_client import AxClient, ObjectiveProperties
import matplotlib.pyplot as plt
from ax.modelbridge.registry import Models
from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy   
import time

import sys
sys.path.append('../')
import helper_functions as hf

/var/folders/9p/f66yhymx35939zzlg51g0rrc0000gn/T/ipykernel_92750/1711932296.py:5: DeprecationWarning: Please import from 'ax.generation_strategy.generation_strategy' instead of 'ax.modelbridge.generation_strategy'. The latter is deprecated and will be removed in a future release.
  from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy

# initialize the optimizer

In [2]:
ax_client_init_file_name = 'optimizer/optimizer_00.json'
ax_client = hf.optimizer_init()
ax_client

[INFO 07-17 11:35:54] ax.service.utils.instantiation: Inferred value type of ParameterType.STRING for parameter surf_1. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/service/utils/instantiation.py:258: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "surf_1". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return ChoiceParameter(
[INFO 07-17 11:35:54] ax.service.utils.instantiation: Inferred value type of ParameterType.STRING for parameter surf_2. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/service/utils/instantiation.py:258: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "surf_2". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return ChoiceParameter(
[INFO 07-17 11:35:54] ax.service.utils.instantiation: Inferred value type of ParameterType.STRING for parameter surf_3. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/service/utils/instantiation.py:258: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "surf_3". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return ChoiceParameter(

AxClient(experiment=Experiment(drug_surfactant))

In [3]:
ax_client.save_to_json_file(ax_client_init_file_name)

# generate recommendations

In [4]:
n = hf.get_iteration_number()

for i in range(3):
    print("Very Important: Please Confirm the Iteration Number is Iteration " + str(n))

print()

list_of_drugs = (['IBP'] * 2 + ['LOV'] * 2 + ['DCF'] * 2 + ['GLV'] * 2)*4

for i in range(3):
    print("Very Important: Please Confirm the Drugs are: ", list_of_drugs)

Very Important: Please Confirm the Iteration Number is Iteration 0
Very Important: Please Confirm the Iteration Number is Iteration 0
Very Important: Please Confirm the Iteration Number is Iteration 0

Very Important: Please Confirm the Drugs are:  ['IBP', 'IBP', 'LOV', 'LOV', 'DCF', 'DCF', 'GLV', 'GLV', 'IBP', 'IBP', 'LOV', 'LOV', 'DCF', 'DCF', 'GLV', 'GLV', 'IBP', 'IBP', 'LOV', 'LOV', 'DCF', 'DCF', 'GLV', 'GLV', 'IBP', 'IBP', 'LOV', 'LOV', 'DCF', 'DCF', 'GLV', 'GLV']
Very Important: Please Confirm the Drugs are:  ['IBP', 'IBP', 'LOV', 'LOV', 'DCF', 'DCF', 'GLV', 'GLV', 'IBP', 'IBP', 'LOV', 'LOV', 'DCF', 'DCF', 'GLV', 'GLV', 'IBP', 'IBP', 'LOV', 'LOV', 'DCF', 'DCF', 'GLV', 'GLV', 'IBP', 'IBP', 'LOV', 'LOV', 'DCF', 'DCF', 'GLV', 'GLV']
Very Important: Please Confirm the Drugs are:  ['IBP', 'IBP', 'LOV', 'LOV', 'DCF', 'DCF', 'GLV', 'GLV', 'IBP', 'IBP', 'LOV', 'LOV', 'DCF', 'DCF', 'GLV', 'GLV', 'IBP', 'IBP', 'LOV', 'LOV', 'DCF', 'DCF', 'GLV', 'GLV', 'IBP', 'IBP', 'LOV', 'LOV', 'DCF', 'DCF', 'GLV', 'GLV']

In [5]:
time_start = time.time()



df_design, ax_client = hf.run_optimizer(current_iteration=n, drug_list= list_of_drugs, bopt=0)

time_end = time.time()
time_duration = round((time_end - time_start)/60,2)

print("Time taken for optimization: " + str(time_duration) + " mins")
print("Time taken for optimization: " + str(time_duration * 60) + " seconds")

[WARNING 07-17 11:36:06] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.9114058297127485, 'surf_1_OH_PARAM__1': 0.12204514164477587, 'surf_1_OH_PARAM__2': 0.6231948798522353, 'surf_1_OH_PARAM__3': 0.528020117431879, 'surf_1_OH_PARAM__4': 0.12346591055393219, 'surf_1_OH_PARAM__5': 0.9443953456357121, 'surf_1_OH_PARAM__6': 0.8819846520200372, 'surf_1_OH_PARAM__7': 0.9761280156672001, 'surf_1_conc': 12.311933713330905, 'surf_2_OH_PARAM__0': 0.47298688627779484, 'surf_2_OH_PARAM__1': 0.3318925853818655, 'surf_2_OH_PARAM__2': 0.05016717687249184, 'surf_2_OH_PARAM__3': 0.19726090878248215, 'surf_2_OH_PARAM__4': 0.09863798227161169, 'surf_2_OH_PARAM__5': 0.9639844475314021, 'surf_2_OH_PARAM__6': 0.4952889485284686, 'surf_2_OH_PARAM__7': 0.568336077965796, 'surf_2_conc': 39.48095865415554, 'surf_3_OH_PARAM__0': 0.45170615427196026, 'surf_3_OH_PARAM__1': 0.49170129653066397, 'surf_3_OH_PARAM__2': 0.5686638671904802, 'surf_3_OH_PARAM__3': 0.3353493716567755, 'surf_3_OH_PARAM__4': 0.2346917986869812, 'surf_3_OH_PARAM__5': 0.6671444671228528, 'surf_3_OH_PARAM__6': 0.9587146146222949, 'surf_3_OH_PARAM__7': 0.18187612108886242, 'surf_3_conc': 19.825477309313563, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[WARNING 07-17 11:36:06] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2063), 'Drug_LogP': np.float64(0.3073), 'Drug_TPSA': np.float64(0.0373), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(1.0), 'surf_1_conc': np.float64(12.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(1.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(39.0), 'surf_3_OH_PARAM__0': np.float64(0.0), 'surf_3_OH_PARAM__1': np.float64(0.0), 'surf_3_OH_PARAM__2': np.float64(0.0), 'surf_3_OH_PARAM__3': np.float64(0.0), 'surf_3_OH_PARAM__4': np.float64(0.0), 'surf_3_OH_PARAM__5': np.float64(0.0), 'surf_3_OH_PARAM__6': np.float64(1.0), 'surf_3_OH_PARAM__7': np.float64(0.0), 'surf_3_conc': np.float64(20.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[INFO 07-17 11:36:06] ax.service.ax_client: Generated new trial 0 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 12, 'surf_2_conc': 39, 'surf_3_conc': 20, 'drug_conc': 25.0, 'surf_1': 's8', 'surf_2': 's6', 'surf_3': 's7'} using model Sobol.
[WARNING 07-17 11:36:06] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.17962588649243116, 'surf_1_OH_PARAM__1': 0.252715477719903, 'surf_1_OH_PARAM__2': 0.8015768546611071, 'surf_1_OH_PARAM__3': 0.7976525351405144, 'surf_1_OH_PARAM__4': 0.6558348573744297, 'surf_1_OH_PARAM__5': 0.2981837596744299, 'surf_1_OH_PARAM__6': 0.6854272913187742, 'surf_1_OH_PARAM__7': 0.16153204068541527, 'surf_1_conc': 50.78568743723018, 'surf_2_OH_PARAM__0': 0.6756753399968147, 'surf_2_OH_PARAM__1': 0.6964397290721536, 'surf_2_OH_PARAM__2': 0.6209493521600962, 'surf_2_OH_PARAM__3': 0.35185046680271626, 'surf_2_OH_PARAM__4': 0.2766580758616328, 'surf_2_OH_PARAM__5': 0.022430391050875187, 'surf_2_OH_PARAM__6': 0.03286267351359129, 'surf_2_OH_PARAM__7': 0.4212197130545974, 'surf_2_conc': 4.355204568334072, 'surf_3_OH_PARAM__0': 0.7282344242557883, 'surf_3_OH_PARAM__1': 0.07807696610689163, 'surf_3_OH_PARAM__2': 0.7561172908172011, 'surf_3_OH_PARAM__3': 0.6241495190188289, 'surf_3_OH_PARAM__4': 0.44303253572434187, 'surf_3_OH_PARAM__5': 0.9537138026207685, 'surf_3_OH_PARAM__6': 0.5561841437593102, 'surf_3_OH_PARAM__7': 0.5710560707375407, 'surf_3_conc': 39.638575508323235, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])

**************************************************************************************************** 1  out of  32 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Ibuprofen IBP  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************
**************************************************************************************************** 2  out of  32 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Ibuprofen IBP  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[WARNING 07-17 11:36:06] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2063), 'Drug_LogP': np.float64(0.3073), 'Drug_TPSA': np.float64(0.0373), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(1.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(51.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(1.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(4.0), 'surf_3_OH_PARAM__0': np.float64(0.0), 'surf_3_OH_PARAM__1': np.float64(0.0), 'surf_3_OH_PARAM__2': np.float64(0.0), 'surf_3_OH_PARAM__3': np.float64(0.0), 'surf_3_OH_PARAM__4': np.float64(0.0), 'surf_3_OH_PARAM__5': np.float64(1.0), 'surf_3_OH_PARAM__6': np.float64(0.0), 'surf_3_OH_PARAM__7': np.float64(0.0), 'surf_3_conc': np.float64(40.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[INFO 07-17 11:36:06] ax.service.ax_client: Generated new trial 1 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 51, 'surf_2_conc': 4, 'surf_3_conc': 40, 'drug_conc': 25.0, 'surf_1': 's3', 'surf_2': 's2', 'surf_3': 's6'} using model Sobol.
[WARNING 07-17 11:36:07] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_OH_PARAM__0': 0.2560679577291012, 'surf_1_OH_PARAM__1': 0.16973726730793715, 'surf_1_OH_PARAM__2': 0.09652568213641644, 'surf_1_OH_PARAM__3': 0.48208999540656805, 'surf_1_OH_PARAM__4': 0.8239228408783674, 'surf_1_OH_PARAM__5': 0.44252450857311487, 'surf_1_OH_PARAM__6': 0.7984137935563922, 'surf_1_OH_PARAM__7': 0.8024126123636961, 'surf_1_conc': 0.6351051899342053, 'surf_2_OH_PARAM__0': 0.1987256957218051, 'surf_2_OH_PARAM__1': 0.4254197031259537, 'surf_2_OH_PARAM__2': 0.7683166107162833, 'surf_2_OH_PARAM__3': 0.09028095472604036, 'surf_2_OH_PARAM__4': 0.7124296892434359, 'surf_2_OH_PARAM__5': 0.4584317123517394, 'surf_2_OH_PARAM__6': 0.8598455209285021, 'surf_2_OH_PARAM__7': 0.024052626453340054, 'surf_2_conc': 55.59883474704206, 'surf_3_OH_PARAM__0': 0.3589434279128909, 'surf_3_OH_PARAM__1': 0.14834516309201717, 'surf_3_OH_PARAM__2': 0.9981758231297135, 'surf_3_OH_PARAM__3': 0.7194553045555949, 'surf_3_OH_PARAM__4': 0.03066192101687193, 'surf_3_OH_PARAM__5': 0.3439873168244958, 'surf_3_OH_PARAM__6': 0.08775488380342722, 'surf_3_OH_PARAM__7': 0.011810318566858768, 'surf_3_conc': 0.4009079922617785, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[WARNING 07-17 11:36:07] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.4045), 'Drug_LogP': np.float64(0.4196), 'Drug_TPSA': np.float64(0.0728), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(1.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(1.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(1.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(56.0), 'surf_3_OH_PARAM__0': np.float64(0.0), 'surf_3_OH_PARAM__1': np.float64(0.0), 'surf_3_OH_PARAM__2': np.float64(1.0), 'surf_3_OH_PARAM__3': np.float64(0.0), 'surf_3_OH_PARAM__4': np.float64(0.0), 'surf_3_OH_PARAM__5': np.float64(0.0), 'surf_3_OH_PARAM__6': np.float64(0.0), 'surf_3_OH_PARAM__7': np.float64(0.0), 'surf_3_conc': np.float64(5.551115123125783e-17), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[INFO 07-17 11:36:07] ax.service.ax_client: Generated new trial 2 with parameters {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 1, 'surf_2_conc': 56, 'surf_3_conc': 0, 'drug_conc': 25.0, 'surf_1': 's5', 'surf_2': 's7', 'surf_3': 's3'} using model Sobol.
[WARNING 07-17 11:36:07] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_OH_PARAM__0': 0.35010251216590405, 'surf_1_OH_PARAM__1': 0.8362639378756285, 'surf_1_OH_PARAM__2': 0.8801511535421014, 'surf_1_OH_PARAM__3': 0.16749133076518774, 'surf_1_OH_PARAM__4': 0.04949513543397188, 'surf_1_OH_PARAM__5': 0.32705025654286146, 'surf_1_OH_PARAM__6': 0.38586085941642523, 'surf_1_OH_PARAM__7': 0.6715440489351749, 'surf_1_conc': 27.934195015281137, 'surf_2_OH_PARAM__0': 0.74383176676929, 'surf_2_OH_PARAM__1': 0.4442800786346197, 'surf_2_OH_PARAM__2': 0.9632726283743978, 'surf_2_OH_PARAM__3': 0.4106331327930093, 'surf_2_OH_PARAM__4': 0.3970977757126093, 'surf_2_OH_PARAM__5': 0.72989946231246, 'surf_2_OH_PARAM__6': 0.20246015768498182, 'surf_2_OH_PARAM__7': 0.8335360595956445, 'surf_2_conc': 6.413930561733748, 'surf_3_OH_PARAM__0': 0.03309438098222017, 'surf_3_OH_PARAM__1': 0.8238679971545935, 'surf_3_OH_PARAM__2': 0.4710205001756549, 'surf_3_OH_PARAM__3': 0.4003961328417063, 'surf_3_OH_PARAM__4': 0.5330627150833607, 'surf_3_OH_PARAM__5': 0.8024456761777401, 'surf_3_OH_PARAM__6': 0.49033475294709206, 'surf_3_OH_PARAM__7': 0.8601722866296768, 'surf_3_conc': 13.798804329873379, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])

**************************************************************************************************** 3  out of  32 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Lovastatin LOV  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************
**************************************************************************************************** 4  out of  32 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Lovastatin LOV  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[WARNING 07-17 11:36:07] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.4045), 'Drug_LogP': np.float64(0.4196), 'Drug_TPSA': np.float64(0.0728), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(1.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(28.000000000000004), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(1.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(6.0), 'surf_3_OH_PARAM__0': np.float64(0.0), 'surf_3_OH_PARAM__1': np.float64(0.0), 'surf_3_OH_PARAM__2': np.float64(0.0), 'surf_3_OH_PARAM__3': np.float64(0.0), 'surf_3_OH_PARAM__4': np.float64(0.0), 'surf_3_OH_PARAM__5': np.float64(0.0), 'surf_3_OH_PARAM__6': np.float64(0.0), 'surf_3_OH_PARAM__7': np.float64(1.0), 'surf_3_conc': np.float64(14.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[INFO 07-17 11:36:07] ax.service.ax_client: Generated new trial 3 with parameters {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 28, 'surf_2_conc': 6, 'surf_3_conc': 14, 'drug_conc': 25.0, 'surf_1': 's3', 'surf_2': 's3', 'surf_3': 's8'} using model Sobol.
[WARNING 07-17 11:36:07] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_OH_PARAM__0': 0.9764733053743839, 'surf_1_OH_PARAM__1': 0.37518260069191456, 'surf_1_OH_PARAM__2': 0.9374336544424295, 'surf_1_OH_PARAM__3': 0.4561588242650032, 'surf_1_OH_PARAM__4': 0.27046515606343746, 'surf_1_OH_PARAM__5': 0.37585766054689884, 'surf_1_OH_PARAM__6': 0.08167941775172949, 'surf_1_OH_PARAM__7': 0.19148987904191017, 'surf_1_conc': 26.682993032702225, 'surf_2_OH_PARAM__0': 0.3180086314678192, 'surf_2_OH_PARAM__1': 0.2624216275289655, 'surf_2_OH_PARAM__2': 0.3588984711095691, 'surf_2_OH_PARAM__3': 0.8927187044173479, 'surf_2_OH_PARAM__4': 0.8873067069798708, 'surf_2_OH_PARAM__5': 0.7059583617374301, 'surf_2_OH_PARAM__6': 0.4678988056257367, 'surf_2_OH_PARAM__7': 0.382788585498929, 'surf_2_conc': 63.06170065867962, 'surf_3_OH_PARAM__0': 0.6993302786722779, 'surf_3_OH_PARAM__1': 0.4441341506317258, 'surf_3_OH_PARAM__2': 0.44190781842917204, 'surf_3_OH_PARAM__3': 0.7134312717244029, 'surf_3_OH_PARAM__4': 0.7230658372864127, 'surf_3_OH_PARAM__5': 0.4312653811648488, 'surf_3_OH_PARAM__6': 0.14133693277835846, 'surf_3_OH_PARAM__7': 0.046956829726696014, 'surf_3_conc': 2.671463620939143, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[WARNING 07-17 11:36:07] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2962), 'Drug_LogP': np.float64(0.4364), 'Drug_TPSA': np.float64(0.0493), 'surf_1_OH_PARAM__0': np.float64(1.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(26.999999999999996), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(1.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(62.99999999999999), 'surf_3_OH_PARAM__0': np.float64(0.0), 'surf_3_OH_PARAM__1': np.float64(0.0), 'surf_3_OH_PARAM__2': np.float64(0.0), 'surf_3_OH_PARAM__3': np.float64(0.0), 'surf_3_OH_PARAM__4': np.float64(1.0), 'surf_3_OH_PARAM__5': np.float64(0.0), 'surf_3_OH_PARAM__6': np.float64(0.0), 'surf_3_OH_PARAM__7': np.float64(0.0), 'surf_3_conc': np.float64(3.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[INFO 07-17 11:36:07] ax.service.ax_client: Generated new trial 4 with parameters {'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 27, 'surf_2_conc': 63, 'surf_3_conc': 3, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's4', 'surf_3': 's5'} using model Sobol.
[WARNING 07-17 11:36:07] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_OH_PARAM__0': 0.3169923182576895, 'surf_1_OH_PARAM__1': 0.3291974626481533, 'surf_1_OH_PARAM__2': 0.409301626496017, 'surf_1_OH_PARAM__3': 0.533214527182281, 'surf_1_OH_PARAM__4': 0.532392106950283, 'surf_1_OH_PARAM__5': 0.8777251746505499, 'surf_1_OH_PARAM__6': 0.22371808160096407, 'surf_1_OH_PARAM__7': 0.021668685600161552, 'surf_1_conc': 39.93878002300726, 'surf_2_OH_PARAM__0': 0.1040501156821847, 'surf_2_OH_PARAM__1': 0.481212112121284, 'surf_2_OH_PARAM__2': 0.5762844681739807, 'surf_2_OH_PARAM__3': 0.7574788024649024, 'surf_2_OH_PARAM__4': 0.2969830175861716, 'surf_2_OH_PARAM__5': 0.21542021539062262, 'surf_2_OH_PARAM__6': 0.832483347505331, 'surf_2_OH_PARAM__7': 0.9635052643716335, 'surf_2_conc': 28.88920551689645, 'surf_3_OH_PARAM__0': 0.6065671406686306, 'surf_3_OH_PARAM__1': 0.16276684775948524, 'surf_3_OH_PARAM__2': 0.12199932336807251, 'surf_3_OH_PARAM__3': 0.3567525949329138, 'surf_3_OH_PARAM__4': 0.511098925024271, 'surf_3_OH_PARAM__5': 0.6118335211649537, 'surf_3_OH_PARAM__6': 0.7781963814049959, 'surf_3_OH_PARAM__7': 0.13104548212140799, 'surf_3_conc': 22.293154230425227, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])

**************************************************************************************************** 5  out of  32 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Diclofenac DCF  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************
**************************************************************************************************** 6  out of  32 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Diclofenac DCF  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[WARNING 07-17 11:36:07] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2962), 'Drug_LogP': np.float64(0.4364), 'Drug_TPSA': np.float64(0.0493), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(1.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(40.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(1.0), 'surf_2_conc': np.float64(29.0), 'surf_3_OH_PARAM__0': np.float64(0.0), 'surf_3_OH_PARAM__1': np.float64(0.0), 'surf_3_OH_PARAM__2': np.float64(0.0), 'surf_3_OH_PARAM__3': np.float64(0.0), 'surf_3_OH_PARAM__4': np.float64(0.0), 'surf_3_OH_PARAM__5': np.float64(0.0), 'surf_3_OH_PARAM__6': np.float64(1.0), 'surf_3_OH_PARAM__7': np.float64(0.0), 'surf_3_conc': np.float64(22.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[INFO 07-17 11:36:07] ax.service.ax_client: Generated new trial 5 with parameters {'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 40, 'surf_2_conc': 29, 'surf_3_conc': 22, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's8', 'surf_3': 's7'} using model Sobol.
[WARNING 07-17 11:36:07] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_OH_PARAM__0': 0.8822000976651907, 'surf_1_OH_PARAM__1': 0.6149514904245734, 'surf_1_OH_PARAM__2': 0.08642344642430544, 'surf_1_OH_PARAM__3': 0.14569633454084396, 'surf_1_OH_PARAM__4': 0.6073318542912602, 'surf_1_OH_PARAM__5': 0.26087836176157, 'surf_1_OH_PARAM__6': 0.7277211798354983, 'surf_1_OH_PARAM__7': 0.3418863546103239, 'surf_1_conc': 5.055642293922193, 'surf_2_OH_PARAM__0': 0.8666600184515119, 'surf_2_OH_PARAM__1': 0.3690495966002345, 'surf_2_OH_PARAM__2': 0.41323330346494913, 'surf_2_OH_PARAM__3': 0.6036806907504797, 'surf_2_OH_PARAM__4': 0.19115362502634525, 'surf_2_OH_PARAM__5': 0.48133616149425507, 'surf_2_OH_PARAM__6': 0.5937888957560062, 'surf_2_OH_PARAM__7': 0.6980686374008656, 'surf_2_conc': 24.22842274011027, 'surf_3_OH_PARAM__0': 0.8773827468976378, 'surf_3_OH_PARAM__1': 0.5259127067402005, 'surf_3_OH_PARAM__2': 0.9618588173761964, 'surf_3_OH_PARAM__3': 0.40644907392561436, 'surf_3_OH_PARAM__4': 0.213705912232399, 'surf_3_OH_PARAM__5': 0.9805594384670258, 'surf_3_OH_PARAM__6': 0.311998781748116, 'surf_3_OH_PARAM__7': 0.825059705413878, 'surf_3_conc': 17.84470131893631, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[WARNING 07-17 11:36:07] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.3528), 'Drug_LogP': np.float64(0.281), 'Drug_TPSA': np.float64(0.0711), 'surf_1_OH_PARAM__0': np.float64(1.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(5.0), 'surf_2_OH_PARAM__0': np.float64(1.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(24.0), 'surf_3_OH_PARAM__0': np.float64(0.0), 'surf_3_OH_PARAM__1': np.float64(0.0), 'surf_3_OH_PARAM__2': np.float64(0.0), 'surf_3_OH_PARAM__3': np.float64(0.0), 'surf_3_OH_PARAM__4': np.float64(0.0), 'surf_3_OH_PARAM__5': np.float64(1.0), 'surf_3_OH_PARAM__6': np.float64(0.0), 'surf_3_OH_PARAM__7': np.float64(0.0), 'surf_3_conc': np.float64(18.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[INFO 07-17 11:36:07] ax.service.ax_client: Generated new trial 6 with parameters {'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 5, 'surf_2_conc': 24, 'surf_3_conc': 18, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's1', 'surf_3': 's6'} using model Sobol.
[WARNING 07-17 11:36:07] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_OH_PARAM__0': 0.12627893686294556, 'surf_1_OH_PARAM__1': 0.09906428214162588, 'surf_1_OH_PARAM__2': 0.029047919437289238, 'surf_1_OH_PARAM__3': 0.06716758292168379, 'surf_1_OH_PARAM__4': 0.5165753830224276, 'surf_1_OH_PARAM__5': 0.7746887765824795, 'surf_1_OH_PARAM__6': 0.07172936666756868, 'surf_1_OH_PARAM__7': 0.7186877587810159, 'surf_1_conc': 9.64247897724092, 'surf_2_OH_PARAM__0': 0.6521026091650128, 'surf_2_OH_PARAM__1': 0.8593875095248222, 'surf_2_OH_PARAM__2': 0.22396407555788755, 'surf_2_OH_PARAM__3': 0.0246007377281785, 'surf_2_OH_PARAM__4': 0.9643131084740162, 'surf_2_OH_PARAM__5': 0.7618962395936251, 'surf_2_OH_PARAM__6': 0.07265463657677174, 'surf_2_OH_PARAM__7': 0.3510022144764662, 'surf_2_conc': 1.2426398162697254, 'surf_3_OH_PARAM__0': 0.8580024400725961, 'surf_3_OH_PARAM__1': 0.7889401130378246, 'surf_3_OH_PARAM__2': 0.542269304394722, 'surf_3_OH_PARAM__3': 0.2448903927579522, 'surf_3_OH_PARAM__4': 0.034943463280797005, 'surf_3_OH_PARAM__5': 0.4855475975200534, 'surf_3_OH_PARAM__6': 0.7218258157372475, 'surf_3_OH_PARAM__7': 0.6548294592648745, 'surf_3_conc': 35.65247002207039, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])

**************************************************************************************************** 7  out of  32 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Griseofulvin GLV  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************
**************************************************************************************************** 8  out of  32 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Griseofulvin GLV  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[WARNING 07-17 11:36:07] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.3528), 'Drug_LogP': np.float64(0.281), 'Drug_TPSA': np.float64(0.0711), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(1.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(10.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(1.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(1.0), 'surf_3_OH_PARAM__0': np.float64(1.0), 'surf_3_OH_PARAM__1': np.float64(0.0), 'surf_3_OH_PARAM__2': np.float64(0.0), 'surf_3_OH_PARAM__3': np.float64(0.0), 'surf_3_OH_PARAM__4': np.float64(0.0), 'surf_3_OH_PARAM__5': np.float64(0.0), 'surf_3_OH_PARAM__6': np.float64(0.0), 'surf_3_OH_PARAM__7': np.float64(0.0), 'surf_3_conc': np.float64(36.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[INFO 07-17 11:36:07] ax.service.ax_client: Generated new trial 7 with parameters {'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 10, 'surf_2_conc': 1, 'surf_3_conc': 36, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'} using model Sobol.
[WARNING 07-17 11:36:07] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.4224435454234481, 'surf_1_OH_PARAM__1': 0.19977690745145082, 'surf_1_OH_PARAM__2': 0.3014186229556799, 'surf_1_OH_PARAM__3': 0.8625649437308311, 'surf_1_OH_PARAM__4': 0.03661735542118549, 'surf_1_OH_PARAM__5': 0.7407889068126678, 'surf_1_OH_PARAM__6': 0.04222849942743778, 'surf_1_OH_PARAM__7': 0.6282185353338718, 'surf_1_conc': 3.6259277073262255, 'surf_2_OH_PARAM__0': 0.2668365081772208, 'surf_2_OH_PARAM__1': 0.573769161477685, 'surf_2_OH_PARAM__2': 0.45642962772399187, 'surf_2_OH_PARAM__3': 0.9343776302412152, 'surf_2_OH_PARAM__4': 0.7269435534253716, 'surf_2_OH_PARAM__5': 0.3297696793451905, 'surf_2_OH_PARAM__6': 0.02561117894947529, 'surf_2_OH_PARAM__7': 0.8498837547376752, 'surf_2_conc': 14.978639724029376, 'surf_3_OH_PARAM__0': 0.8012203481048346, 'surf_3_OH_PARAM__1': 0.5529626933857799, 'surf_3_OH_PARAM__2': 0.5809710854664445, 'surf_3_OH_PARAM__3': 0.7350325351580977, 'surf_3_OH_PARAM__4': 0.3697560029104352, 'surf_3_OH_PARAM__5': 0.39450092427432537, 'surf_3_OH_PARAM__6': 0.4601248623803258, 'surf_3_OH_PARAM__7': 0.1507212035357952, 'surf_3_conc': 50.44505995360238, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[WARNING 07-17 11:36:07] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2063), 'Drug_LogP': np.float64(0.3073), 'Drug_TPSA': np.float64(0.0373), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(1.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(4.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(1.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(15.0), 'surf_3_OH_PARAM__0': np.float64(1.0), 'surf_3_OH_PARAM__1': np.float64(0.0), 'surf_3_OH_PARAM__2': np.float64(0.0), 'surf_3_OH_PARAM__3': np.float64(0.0), 'surf_3_OH_PARAM__4': np.float64(0.0), 'surf_3_OH_PARAM__5': np.float64(0.0), 'surf_3_OH_PARAM__6': np.float64(0.0), 'surf_3_OH_PARAM__7': np.float64(0.0), 'surf_3_conc': np.float64(50.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[INFO 07-17 11:36:07] ax.service.ax_client: Generated new trial 8 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 4, 'surf_2_conc': 15, 'surf_3_conc': 50, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's4', 'surf_3': 's1'} using model Sobol.
[WARNING 07-17 11:36:07] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.5943049117922783, 'surf_1_OH_PARAM__1': 0.3208670374006033, 'surf_1_OH_PARAM__2': 0.9380170051008463, 'surf_1_OH_PARAM__3': 0.11958371475338936, 'surf_1_OH_PARAM__4': 0.07787942327558994, 'surf_1_OH_PARAM__5': 0.8403852349147201, 'surf_1_OH_PARAM__6': 0.7922507831826806, 'surf_1_OH_PARAM__7': 0.29523428808897734, 'surf_1_conc': 37.25776675649125, 'surf_2_OH_PARAM__0': 0.7706087958067656, 'surf_2_OH_PARAM__1': 0.9522485705092549, 'surf_2_OH_PARAM__2': 0.6485150596126914, 'surf_2_OH_PARAM__3': 0.9603525679558516, 'surf_2_OH_PARAM__4': 0.6390759833157063, 'surf_2_OH_PARAM__5': 0.01137983612716198, 'surf_2_OH_PARAM__6': 0.7238712208345532, 'surf_2_OH_PARAM__7': 0.24239308666437864, 'surf_2_conc': 16.565118290481735, 'surf_3_OH_PARAM__0': 0.20024037640541792, 'surf_3_OH_PARAM__1': 0.6161622395738959, 'surf_3_OH_PARAM__2': 0.017494486644864082, 'surf_3_OH_PARAM__3': 0.1884224722161889, 'surf_3_OH_PARAM__4': 0.7116954382508993, 'surf_3_OH_PARAM__5': 0.2896154588088393, 'surf_3_OH_PARAM__6': 0.5412617484107614, 'surf_3_OH_PARAM__7': 0.6587178660556674, 'surf_3_conc': 31.80687894137684, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])

**************************************************************************************************** 9  out of  32 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Ibuprofen IBP  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************
**************************************************************************************************** 10  out of  32 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Ibuprofen IBP  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[WARNING 07-17 11:36:07] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2063), 'Drug_LogP': np.float64(0.3073), 'Drug_TPSA': np.float64(0.0373), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(1.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(37.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(1.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(17.0), 'surf_3_OH_PARAM__0': np.float64(0.0), 'surf_3_OH_PARAM__1': np.float64(0.0), 'surf_3_OH_PARAM__2': np.float64(0.0), 'surf_3_OH_PARAM__3': np.float64(0.0), 'surf_3_OH_PARAM__4': np.float64(1.0), 'surf_3_OH_PARAM__5': np.float64(0.0), 'surf_3_OH_PARAM__6': np.float64(0.0), 'surf_3_OH_PARAM__7': np.float64(0.0), 'surf_3_conc': np.float64(31.999999999999996), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[INFO 07-17 11:36:07] ax.service.ax_client: Generated new trial 9 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 37, 'surf_2_conc': 17, 'surf_3_conc': 32, 'drug_conc': 25.0, 'surf_1': 's3', 'surf_2': 's4', 'surf_3': 's5'} using model Sobol.
[WARNING 07-17 11:36:07] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_OH_PARAM__0': 0.8293885281309485, 'surf_1_OH_PARAM__1': 0.4701617397367954, 'surf_1_OH_PARAM__2': 0.7281424719840288, 'surf_1_OH_PARAM__3': 0.8261396130546927, 'surf_1_OH_PARAM__4': 0.6193608287721872, 'surf_1_OH_PARAM__5': 0.6751277400180697, 'surf_1_OH_PARAM__6': 0.8213399183005095, 'surf_1_OH_PARAM__7': 0.3622663449496031, 'surf_1_conc': 29.66309042282231, 'surf_2_OH_PARAM__0': 0.15615521743893623, 'surf_2_OH_PARAM__1': 0.7388433953747153, 'surf_2_OH_PARAM__2': 0.9200469786301255, 'surf_2_OH_PARAM__3': 0.11192028410732746, 'surf_2_OH_PARAM__4': 0.9350545117631555, 'surf_2_OH_PARAM__5': 0.5841313051059842, 'surf_2_OH_PARAM__6': 0.6771329091861844, 'surf_2_OH_PARAM__7': 0.7432826459407806, 'surf_2_conc': 2.681027721672598, 'surf_3_OH_PARAM__0': 0.14831915870308876, 'surf_3_OH_PARAM__1': 0.8506738394498825, 'surf_3_OH_PARAM__2': 0.10183959733694792, 'surf_3_OH_PARAM__3': 0.6978492802008986, 'surf_3_OH_PARAM__4': 0.876647369004786, 'surf_3_OH_PARAM__5': 0.32261507399380207, 'surf_3_OH_PARAM__6': 0.2795875556766987, 'surf_3_OH_PARAM__7': 0.162459765560925, 'surf_3_conc': 54.490138965935294, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[WARNING 07-17 11:36:08] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.4045), 'Drug_LogP': np.float64(0.4196), 'Drug_TPSA': np.float64(0.0728), 'surf_1_OH_PARAM__0': np.float64(1.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(30.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(1.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(3.0), 'surf_3_OH_PARAM__0': np.float64(0.0), 'surf_3_OH_PARAM__1': np.float64(0.0), 'surf_3_OH_PARAM__2': np.float64(0.0), 'surf_3_OH_PARAM__3': np.float64(0.0), 'surf_3_OH_PARAM__4': np.float64(1.0), 'surf_3_OH_PARAM__5': np.float64(0.0), 'surf_3_OH_PARAM__6': np.float64(0.0), 'surf_3_OH_PARAM__7': np.float64(0.0), 'surf_3_conc': np.float64(53.99999999999999), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[INFO 07-17 11:36:08] ax.service.ax_client: Generated new trial 10 with parameters {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 30, 'surf_2_conc': 3, 'surf_3_conc': 54, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's5', 'surf_3': 's5'} using model Sobol.
[WARNING 07-17 11:36:08] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_OH_PARAM__0': 0.15951400250196457, 'surf_1_OH_PARAM__1': 0.605703984387219, 'surf_1_OH_PARAM__2': 0.558498676866293, 'surf_1_OH_PARAM__3': 0.7004688074812293, 'surf_1_OH_PARAM__4': 0.0034050485119223595, 'surf_1_OH_PARAM__5': 0.45838981214910746, 'surf_1_OH_PARAM__6': 0.2885520150884986, 'surf_1_OH_PARAM__7': 0.10006239544600248, 'surf_1_conc': 21.53291747694211, 'surf_2_OH_PARAM__0': 0.008681723847985268, 'surf_2_OH_PARAM__1': 0.8380766334012151, 'surf_2_OH_PARAM__2': 0.3605325426906347, 'surf_2_OH_PARAM__3': 0.6825157618150115, 'surf_2_OH_PARAM__4': 0.872835055924952, 'surf_2_OH_PARAM__5': 0.3084234157577157, 'surf_2_OH_PARAM__6': 0.9543564142659307, 'surf_2_OH_PARAM__7': 0.4768313495442271, 'surf_2_conc': 37.20441710262075, 'surf_3_OH_PARAM__0': 0.2835869863629341, 'surf_3_OH_PARAM__1': 0.19808861427009106, 'surf_3_OH_PARAM__2': 0.9276998592540622, 'surf_3_OH_PARAM__3': 0.013265383429825306, 'surf_3_OH_PARAM__4': 0.009088711813092232, 'surf_3_OH_PARAM__5': 0.17774699442088604, 'surf_3_OH_PARAM__6': 0.009657351300120354, 'surf_3_OH_PARAM__7': 0.3519681291654706, 'surf_3_conc': 27.255182053011747, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])

**************************************************************************************************** 11  out of  32 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Lovastatin LOV  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************
**************************************************************************************************** 12  out of  32 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Lovastatin LOV  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[WARNING 07-17 11:36:08] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.4045), 'Drug_LogP': np.float64(0.4196), 'Drug_TPSA': np.float64(0.0728), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(1.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(22.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(1.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(37.0), 'surf_3_OH_PARAM__0': np.float64(0.0), 'surf_3_OH_PARAM__1': np.float64(0.0), 'surf_3_OH_PARAM__2': np.float64(1.0), 'surf_3_OH_PARAM__3': np.float64(0.0), 'surf_3_OH_PARAM__4': np.float64(0.0), 'surf_3_OH_PARAM__5': np.float64(0.0), 'surf_3_OH_PARAM__6': np.float64(0.0), 'surf_3_OH_PARAM__7': np.float64(0.0), 'surf_3_conc': np.float64(26.999999999999996), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[INFO 07-17 11:36:08] ax.service.ax_client: Generated new trial 11 with parameters {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 22, 'surf_2_conc': 37, 'surf_3_conc': 27, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's7', 'surf_3': 's3'} using model Sobol.
[WARNING 07-17 11:36:08] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_OH_PARAM__0': 0.9238278167322278, 'surf_1_OH_PARAM__1': 0.7675898689776659, 'surf_1_OH_PARAM__2': 0.8604175979271531, 'surf_1_OH_PARAM__3': 0.9699599174782634, 'surf_1_OH_PARAM__4': 0.7212006105110049, 'surf_1_OH_PARAM__5': 0.7844110149890184, 'surf_1_OH_PARAM__6': 0.029039248824119568, 'surf_1_OH_PARAM__7': 0.7857074169442058, 'surf_1_conc': 58.821494407350734, 'surf_2_OH_PARAM__0': 0.843083567917347, 'surf_2_OH_PARAM__1': 0.18827860988676548, 'surf_2_OH_PARAM__2': 0.8063137903809547, 'surf_2_OH_PARAM__3': 0.7766755791381001, 'surf_2_OH_PARAM__4': 0.5034385146573186, 'surf_2_OH_PARAM__5': 0.740456017665565, 'surf_2_OH_PARAM__6': 0.5115090729668736, 'surf_2_OH_PARAM__7': 0.5028520645573735, 'surf_2_conc': 21.016340245091428, 'surf_3_OH_PARAM__0': 0.5052448296919465, 'surf_3_OH_PARAM__1': 0.3619551369920373, 'surf_3_OH_PARAM__2': 0.7402143161743879, 'surf_3_OH_PARAM__3': 0.786932684481144, 'surf_3_OH_PARAM__4': 0.30929498467594385, 'surf_3_OH_PARAM__5': 0.4509238647297025, 'surf_3_OH_PARAM__6': 0.47443585470318794, 'surf_3_OH_PARAM__7': 0.9009590521454811, 'surf_3_conc': 5.96325341443466, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[WARNING 07-17 11:36:08] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2962), 'Drug_LogP': np.float64(0.4364), 'Drug_TPSA': np.float64(0.0493), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(1.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(59.0), 'surf_2_OH_PARAM__0': np.float64(1.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(21.0), 'surf_3_OH_PARAM__0': np.float64(0.0), 'surf_3_OH_PARAM__1': np.float64(0.0), 'surf_3_OH_PARAM__2': np.float64(0.0), 'surf_3_OH_PARAM__3': np.float64(0.0), 'surf_3_OH_PARAM__4': np.float64(0.0), 'surf_3_OH_PARAM__5': np.float64(0.0), 'surf_3_OH_PARAM__6': np.float64(0.0), 'surf_3_OH_PARAM__7': np.float64(1.0), 'surf_3_conc': np.float64(6.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[INFO 07-17 11:36:08] ax.service.ax_client: Generated new trial 12 with parameters {'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 59, 'surf_2_conc': 21, 'surf_3_conc': 6, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's1', 'surf_3': 's8'} using model Sobol.
[WARNING 07-17 11:36:08] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_OH_PARAM__0': 0.49450589064508677, 'surf_1_OH_PARAM__1': 0.9715608041733503, 'surf_1_OH_PARAM__2': 0.8407086795195937, 'surf_1_OH_PARAM__3': 0.8165362002328038, 'surf_1_OH_PARAM__4': 0.24386355467140675, 'surf_1_OH_PARAM__5': 0.4292798535898328, 'surf_1_OH_PARAM__6': 0.7593635097146034, 'surf_1_OH_PARAM__7': 0.4886672608554363, 'surf_1_conc': 9.89975946694685, 'surf_2_OH_PARAM__0': 0.8505955804139376, 'surf_2_OH_PARAM__1': 0.12872799672186375, 'surf_2_OH_PARAM__2': 0.8604727787896991, 'surf_2_OH_PARAM__3': 0.5354771828278899, 'surf_2_OH_PARAM__4': 0.11118275113403797, 'surf_2_OH_PARAM__5': 0.6433649761602283, 'surf_2_OH_PARAM__6': 0.48848147597163916, 'surf_2_OH_PARAM__7': 0.994442543014884, 'surf_2_conc': 77.681062383011, 'surf_3_OH_PARAM__0': 0.6523410584777594, 'surf_3_OH_PARAM__1': 0.2306316653266549, 'surf_3_OH_PARAM__2': 0.7178702587261796, 'surf_3_OH_PARAM__3': 0.22155192494392395, 'surf_3_OH_PARAM__4': 0.6417272249236703, 'surf_3_OH_PARAM__5': 0.1994121540337801, 'surf_3_OH_PARAM__6': 0.5022303434088826, 'surf_3_OH_PARAM__7': 0.4165990725159645, 'surf_3_conc': 9.363261924378628, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])

**************************************************************************************************** 13  out of  32 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Diclofenac DCF  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************
**************************************************************************************************** 14  out of  32 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Diclofenac DCF  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[WARNING 07-17 11:36:08] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2962), 'Drug_LogP': np.float64(0.4364), 'Drug_TPSA': np.float64(0.0493), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(1.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(10.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(1.0), 'surf_2_conc': np.float64(78.0), 'surf_3_OH_PARAM__0': np.float64(0.0), 'surf_3_OH_PARAM__1': np.float64(0.0), 'surf_3_OH_PARAM__2': np.float64(1.0), 'surf_3_OH_PARAM__3': np.float64(0.0), 'surf_3_OH_PARAM__4': np.float64(0.0), 'surf_3_OH_PARAM__5': np.float64(0.0), 'surf_3_OH_PARAM__6': np.float64(0.0), 'surf_3_OH_PARAM__7': np.float64(0.0), 'surf_3_conc': np.float64(9.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[INFO 07-17 11:36:08] ax.service.ax_client: Generated new trial 13 with parameters {'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 10, 'surf_2_conc': 78, 'surf_3_conc': 9, 'drug_conc': 25.0, 'surf_1': 's2', 'surf_2': 's8', 'surf_3': 's3'} using model Sobol.
[WARNING 07-17 11:36:08] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_OH_PARAM__0': 0.8370933039113879, 'surf_1_OH_PARAM__1': 0.8006216287612915, 'surf_1_OH_PARAM__2': 0.31257559172809124, 'surf_1_OH_PARAM__3': 0.17698528431355953, 'surf_1_OH_PARAM__4': 0.9496189765632153, 'surf_1_OH_PARAM__5': 0.9274886334314942, 'surf_1_OH_PARAM__6': 0.9366570729762316, 'surf_1_OH_PARAM__7': 0.2873556073755026, 'surf_1_conc': 21.898640554372648, 'surf_2_OH_PARAM__0': 0.5704749254509807, 'surf_2_OH_PARAM__1': 0.09733526036143303, 'surf_2_OH_PARAM__2': 0.0786183774471283, 'surf_2_OH_PARAM__3': 0.6736774239689112, 'surf_2_OH_PARAM__4': 0.7005599429830909, 'surf_2_OH_PARAM__5': 0.15307579841464758, 'surf_2_OH_PARAM__6': 0.8743977900594473, 'surf_2_OH_PARAM__7': 0.413175605237484, 'surf_2_conc': 17.377017573797907, 'surf_3_OH_PARAM__0': 0.5576080111786723, 'surf_3_OH_PARAM__1': 0.3870161324739456, 'surf_3_OH_PARAM__2': 0.851041765883565, 'surf_3_OH_PARAM__3': 0.8330219583585858, 'surf_3_OH_PARAM__4': 0.6231314484030008, 'surf_3_OH_PARAM__5': 0.7570016141980886, 'surf_3_OH_PARAM__6': 0.3888455918058753, 'surf_3_OH_PARAM__7': 0.2780658071860671, 'surf_3_conc': 15.755874139313473, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[WARNING 07-17 11:36:08] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.3528), 'Drug_LogP': np.float64(0.281), 'Drug_TPSA': np.float64(0.0711), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(1.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(22.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(1.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(17.0), 'surf_3_OH_PARAM__0': np.float64(0.0), 'surf_3_OH_PARAM__1': np.float64(0.0), 'surf_3_OH_PARAM__2': np.float64(1.0), 'surf_3_OH_PARAM__3': np.float64(0.0), 'surf_3_OH_PARAM__4': np.float64(0.0), 'surf_3_OH_PARAM__5': np.float64(0.0), 'surf_3_OH_PARAM__6': np.float64(0.0), 'surf_3_OH_PARAM__7': np.float64(0.0), 'surf_3_conc': np.float64(16.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[INFO 07-17 11:36:08] ax.service.ax_client: Generated new trial 14 with parameters {'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 22, 'surf_2_conc': 17, 'surf_3_conc': 16, 'drug_conc': 25.0, 'surf_1': 's5', 'surf_2': 's7', 'surf_3': 's3'} using model Sobol.
[WARNING 07-17 11:36:08] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_OH_PARAM__0': 0.4012762410566211, 'surf_1_OH_PARAM__1': 0.02292961161583662, 'surf_1_OH_PARAM__2': 0.18305689841508865, 'surf_1_OH_PARAM__3': 0.5019844742491841, 'surf_1_OH_PARAM__4': 0.8756557935848832, 'surf_1_OH_PARAM__5': 0.30892284866422415, 'surf_1_OH_PARAM__6': 0.4249074421823025, 'surf_1_OH_PARAM__7': 0.10781729780137539, 'surf_1_conc': 31.33181148885846, 'surf_2_OH_PARAM__0': 0.3338134353980422, 'surf_2_OH_PARAM__1': 0.24072706326842308, 'surf_2_OH_PARAM__2': 0.9313753182068467, 'surf_2_OH_PARAM__3': 0.9651937214657664, 'surf_2_OH_PARAM__4': 0.8115158621221781, 'surf_2_OH_PARAM__5': 0.41874539852142334, 'surf_2_OH_PARAM__6': 0.5733588319271803, 'surf_2_OH_PARAM__7': 0.1790928691625595, 'surf_2_conc': 34.8592968184961, 'surf_3_OH_PARAM__0': 0.9585682228207588, 'surf_3_OH_PARAM__1': 0.7972772577777505, 'surf_3_OH_PARAM__2': 0.19084022473543882, 'surf_3_OH_PARAM__3': 0.89883076492697, 'surf_3_OH_PARAM__4': 0.17150150053203106, 'surf_3_OH_PARAM__5': 0.6501191398128867, 'surf_3_OH_PARAM__6': 0.9194891601800919, 'surf_3_OH_PARAM__7': 0.7092969799414277, 'surf_3_conc': 24.17283935884697, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])

**************************************************************************************************** 15  out of  32 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Griseofulvin GLV  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************
**************************************************************************************************** 16  out of  32 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Griseofulvin GLV  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[WARNING 07-17 11:36:08] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.3528), 'Drug_LogP': np.float64(0.281), 'Drug_TPSA': np.float64(0.0711), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(1.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(31.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(1.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(35.0), 'surf_3_OH_PARAM__0': np.float64(1.0), 'surf_3_OH_PARAM__1': np.float64(0.0), 'surf_3_OH_PARAM__2': np.float64(0.0), 'surf_3_OH_PARAM__3': np.float64(0.0), 'surf_3_OH_PARAM__4': np.float64(0.0), 'surf_3_OH_PARAM__5': np.float64(0.0), 'surf_3_OH_PARAM__6': np.float64(0.0), 'surf_3_OH_PARAM__7': np.float64(0.0), 'surf_3_conc': np.float64(24.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[INFO 07-17 11:36:08] ax.service.ax_client: Generated new trial 15 with parameters {'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 31, 'surf_2_conc': 35, 'surf_3_conc': 24, 'drug_conc': 25.0, 'surf_1': 's5', 'surf_2': 's4', 'surf_3': 's1'} using model Sobol.
[WARNING 07-17 11:36:08] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.43060611467808485, 'surf_1_OH_PARAM__1': 0.5295044938102365, 'surf_1_OH_PARAM__2': 0.6534840408712626, 'surf_1_OH_PARAM__3': 0.13626125548034906, 'surf_1_OH_PARAM__4': 0.3937314487993717, 'surf_1_OH_PARAM__5': 0.984841899946332, 'surf_1_OH_PARAM__6': 0.21589539013803005, 'surf_1_OH_PARAM__7': 0.710932832211256, 'surf_1_conc': 49.51156545696037, 'surf_2_OH_PARAM__0': 0.9442754611372948, 'surf_2_OH_PARAM__1': 0.21552518848329782, 'surf_2_OH_PARAM__2': 0.5446923412382603, 'surf_2_OH_PARAM__3': 0.3745659710839391, 'surf_2_OH_PARAM__4': 0.8986916532739997, 'surf_2_OH_PARAM__5': 0.901574227027595, 'surf_2_OH_PARAM__6': 0.45334492716938257, 'surf_2_OH_PARAM__7': 0.054990691132843494, 'surf_2_conc': 0.44367163886766875, 'surf_3_OH_PARAM__0': 0.3998354831710458, 'surf_3_OH_PARAM__1': 0.21619087737053633, 'surf_3_OH_PARAM__2': 0.3416358232498169, 'surf_3_OH_PARAM__3': 0.8586079375818372, 'surf_3_OH_PARAM__4': 0.12997680716216564, 'surf_3_OH_PARAM__5': 0.967319393530488, 'surf_3_OH_PARAM__6': 0.3196230288594961, 'surf_3_OH_PARAM__7': 0.2819222640246153, 'surf_3_conc': 13.485419723028185, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[WARNING 07-17 11:36:08] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2063), 'Drug_LogP': np.float64(0.3073), 'Drug_TPSA': np.float64(0.0373), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(1.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(50.0), 'surf_2_OH_PARAM__0': np.float64(1.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(5.551115123125783e-17), 'surf_3_OH_PARAM__0': np.float64(0.0), 'surf_3_OH_PARAM__1': np.float64(0.0), 'surf_3_OH_PARAM__2': np.float64(0.0), 'surf_3_OH_PARAM__3': np.float64(0.0), 'surf_3_OH_PARAM__4': np.float64(0.0), 'surf_3_OH_PARAM__5': np.float64(1.0), 'surf_3_OH_PARAM__6': np.float64(0.0), 'surf_3_OH_PARAM__7': np.float64(0.0), 'surf_3_conc': np.float64(13.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[INFO 07-17 11:36:08] ax.service.ax_client: Generated new trial 16 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 50, 'surf_2_conc': 0, 'surf_3_conc': 13, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's1', 'surf_3': 's6'} using model Sobol.
[WARNING 07-17 11:36:08] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.8703235862776637, 'surf_1_OH_PARAM__1': 0.30723037011921406, 'surf_1_OH_PARAM__2': 0.8498935662209988, 'surf_1_OH_PARAM__3': 0.5593090746551752, 'surf_1_OH_PARAM__4': 0.4686787882819772, 'surf_1_OH_PARAM__5': 0.36872751638293266, 'surf_1_OH_PARAM__6': 0.704262875020504, 'surf_1_OH_PARAM__7': 0.9061046056449413, 'surf_1_conc': 8.439343380478807, 'surf_2_OH_PARAM__0': 0.21390345320105553, 'surf_2_OH_PARAM__1': 0.07187032047659159, 'surf_2_OH_PARAM__2': 0.4423558982089162, 'surf_2_OH_PARAM__3': 0.017631415277719498, 'surf_2_OH_PARAM__4': 0.6053582672029734, 'surf_2_OH_PARAM__5': 0.667244803160429, 'surf_2_OH_PARAM__6': 0.22291980031877756, 'surf_2_OH_PARAM__7': 0.28929478395730257, 'surf_2_conc': 46.332194317930245, 'surf_3_OH_PARAM__0': 0.11523833312094212, 'surf_3_OH_PARAM__1': 0.5949921924620867, 'surf_3_OH_PARAM__2': 0.7439314210787416, 'surf_3_OH_PARAM__3': 0.9085170263424516, 'surf_3_OH_PARAM__4': 0.5825829301029444, 'surf_3_OH_PARAM__5': 0.5626039979979396, 'surf_3_OH_PARAM__6': 0.8485426092520356, 'surf_3_OH_PARAM__7': 0.7288684844970703, 'surf_3_conc': 20.32416449835617, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])

**************************************************************************************************** 17  out of  32 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Ibuprofen IBP  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************
**************************************************************************************************** 18  out of  32 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Ibuprofen IBP  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[WARNING 07-17 11:36:08] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2063), 'Drug_LogP': np.float64(0.3073), 'Drug_TPSA': np.float64(0.0373), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(1.0), 'surf_1_conc': np.float64(8.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(1.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(46.0), 'surf_3_OH_PARAM__0': np.float64(0.0), 'surf_3_OH_PARAM__1': np.float64(0.0), 'surf_3_OH_PARAM__2': np.float64(0.0), 'surf_3_OH_PARAM__3': np.float64(1.0), 'surf_3_OH_PARAM__4': np.float64(0.0), 'surf_3_OH_PARAM__5': np.float64(0.0), 'surf_3_OH_PARAM__6': np.float64(0.0), 'surf_3_OH_PARAM__7': np.float64(0.0), 'surf_3_conc': np.float64(20.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[INFO 07-17 11:36:08] ax.service.ax_client: Generated new trial 17 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 8, 'surf_2_conc': 46, 'surf_3_conc': 20, 'drug_conc': 25.0, 'surf_1': 's8', 'surf_2': 's6', 'surf_3': 's4'} using model Sobol.
[WARNING 07-17 11:36:08] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_OH_PARAM__0': 0.4612089255824685, 'surf_1_OH_PARAM__1': 0.4801498167216778, 'surf_1_OH_PARAM__2': 0.36985426116734743, 'surf_1_OH_PARAM__3': 0.4508140841498971, 'surf_1_OH_PARAM__4': 0.7287097265943885, 'surf_1_OH_PARAM__5': 0.8708229511976242, 'surf_1_OH_PARAM__6': 0.6011956799775362, 'surf_1_OH_PARAM__7': 0.8261580225080252, 'surf_1_conc': 20.09224965893779, 'surf_2_OH_PARAM__0': 0.4884093226864934, 'surf_2_OH_PARAM__1': 0.1659040590748191, 'surf_2_OH_PARAM__2': 0.724023362621665, 'surf_2_OH_PARAM__3': 0.13233053032308817, 'surf_2_OH_PARAM__4': 0.2103480165824294, 'surf_2_OH_PARAM__5': 0.16132966428995132, 'surf_2_OH_PARAM__6': 0.6084719896316528, 'surf_2_OH_PARAM__7': 0.8646402461454272, 'surf_2_conc': 61.76583137113901, 'surf_3_OH_PARAM__0': 0.20997564401477575, 'surf_3_OH_PARAM__1': 0.7511096326634288, 'surf_3_OH_PARAM__2': 0.8141144383698702, 'surf_3_OH_PARAM__3': 0.021055202931165695, 'surf_3_OH_PARAM__4': 0.6832514414563775, 'surf_3_OH_PARAM__5': 0.3857521777972579, 'surf_3_OH_PARAM__6': 0.2271021706983447, 'surf_3_OH_PARAM__7': 0.5903062066063285, 'surf_3_conc': 1.4792073216261155, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[WARNING 07-17 11:36:09] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.4045), 'Drug_LogP': np.float64(0.4196), 'Drug_TPSA': np.float64(0.0728), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(1.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(20.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(1.0), 'surf_2_conc': np.float64(61.99999999999999), 'surf_3_OH_PARAM__0': np.float64(0.0), 'surf_3_OH_PARAM__1': np.float64(0.0), 'surf_3_OH_PARAM__2': np.float64(1.0), 'surf_3_OH_PARAM__3': np.float64(0.0), 'surf_3_OH_PARAM__4': np.float64(0.0), 'surf_3_OH_PARAM__5': np.float64(0.0), 'surf_3_OH_PARAM__6': np.float64(0.0), 'surf_3_OH_PARAM__7': np.float64(0.0), 'surf_3_conc': np.float64(1.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[INFO 07-17 11:36:09] ax.service.ax_client: Generated new trial 18 with parameters {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 20, 'surf_2_conc': 62, 'surf_3_conc': 1, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's8', 'surf_3': 's3'} using model Sobol.
[WARNING 07-17 11:36:09] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_OH_PARAM__0': 0.12221588660031557, 'surf_1_OH_PARAM__1': 0.791375482454896, 'surf_1_OH_PARAM__2': 0.7847123211249709, 'surf_1_OH_PARAM__3': 0.7317408779636025, 'surf_1_OH_PARAM__4': 0.40916468016803265, 'surf_1_OH_PARAM__5': 0.8554383143782616, 'surf_1_OH_PARAM__6': 0.11080396734178066, 'surf_1_OH_PARAM__7': 0.029423612169921398, 'surf_1_conc': -0.09048842419952158, 'surf_2_OH_PARAM__0': 0.3044317029416561, 'surf_2_OH_PARAM__1': 0.5629395712167025, 'surf_2_OH_PARAM__2': 0.1313801845535636, 'surf_2_OH_PARAM__3': 0.59481171797961, 'surf_2_OH_PARAM__4': 0.3624655343592167, 'surf_2_OH_PARAM__5': 0.07379098050296307, 'surf_2_OH_PARAM__6': 0.7013354143127799, 'surf_2_OH_PARAM__7': 0.6303843697533011, 'surf_2_conc': 29.661812193086313, 'surf_3_OH_PARAM__0': 0.1512819491326809, 'surf_3_OH_PARAM__1': 0.8399146301671863, 'surf_3_OH_PARAM__2': 0.7601930052042007, 'surf_3_OH_PARAM__3': 0.7428089696913958, 'surf_3_OH_PARAM__4': 0.6694836542010307, 'surf_3_OH_PARAM__5': 0.09106407314538956, 'surf_3_OH_PARAM__6': 0.18036865815520287, 'surf_3_OH_PARAM__7': 0.8047311110422015, 'surf_3_conc': 25.177129289967024, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])

**************************************************************************************************** 19  out of  32 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Lovastatin LOV  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************
**************************************************************************************************** 20  out of  32 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Lovastatin LOV  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[WARNING 07-17 11:36:09] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.4045), 'Drug_LogP': np.float64(0.4196), 'Drug_TPSA': np.float64(0.0728), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(1.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(5.551115123125783e-17), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(1.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(30.0), 'surf_3_OH_PARAM__0': np.float64(0.0), 'surf_3_OH_PARAM__1': np.float64(1.0), 'surf_3_OH_PARAM__2': np.float64(0.0), 'surf_3_OH_PARAM__3': np.float64(0.0), 'surf_3_OH_PARAM__4': np.float64(0.0), 'surf_3_OH_PARAM__5': np.float64(0.0), 'surf_3_OH_PARAM__6': np.float64(0.0), 'surf_3_OH_PARAM__7': np.float64(0.0), 'surf_3_conc': np.float64(25.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[INFO 07-17 11:36:09] ax.service.ax_client: Generated new trial 19 with parameters {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 0, 'surf_2_conc': 30, 'surf_3_conc': 25, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's7', 'surf_3': 's2'} using model Sobol.
[WARNING 07-17 11:36:09] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_OH_PARAM__0': 0.8589415773749352, 'surf_1_OH_PARAM__1': 0.582400974817574, 'surf_1_OH_PARAM__2': 0.6030196566134691, 'surf_1_OH_PARAM__3': 0.9386898102238774, 'surf_1_OH_PARAM__4': 0.8154407385736704, 'surf_1_OH_PARAM__5': 0.4039326040074229, 'surf_1_OH_PARAM__6': 0.3239164734259248, 'surf_1_OH_PARAM__7': 0.8406048519536853, 'surf_1_conc': 62.84260564798221, 'surf_2_OH_PARAM__0': 0.5938048642128706, 'surf_2_OH_PARAM__1': 0.46343949902802706, 'surf_2_OH_PARAM__2': 0.7012239256873727, 'surf_2_OH_PARAM__3': 0.9381253132596612, 'surf_2_OH_PARAM__4': 0.01308896392583847, 'surf_2_OH_PARAM__5': 0.8812508545815945, 'surf_2_OH_PARAM__6': 0.7701457878574729, 'surf_2_OH_PARAM__7': 0.3585763880982995, 'surf_2_conc': 14.262917704411352, 'surf_3_OH_PARAM__0': 0.935378578491509, 'surf_3_OH_PARAM__1': 0.723028052598238, 'surf_3_OH_PARAM__2': 0.5727397100999951, 'surf_3_OH_PARAM__3': 0.45400316175073385, 'surf_3_OH_PARAM__4': 0.8988809837028384, 'surf_3_OH_PARAM__5': 0.28760654013603926, 'surf_3_OH_PARAM__6': 0.33253314159810543, 'surf_3_OH_PARAM__7': 0.448197266086936, 'surf_3_conc': 8.64434804593129, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[WARNING 07-17 11:36:09] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2962), 'Drug_LogP': np.float64(0.4364), 'Drug_TPSA': np.float64(0.0493), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(1.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(62.99999999999999), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(1.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(14.0), 'surf_3_OH_PARAM__0': np.float64(1.0), 'surf_3_OH_PARAM__1': np.float64(0.0), 'surf_3_OH_PARAM__2': np.float64(0.0), 'surf_3_OH_PARAM__3': np.float64(0.0), 'surf_3_OH_PARAM__4': np.float64(0.0), 'surf_3_OH_PARAM__5': np.float64(0.0), 'surf_3_OH_PARAM__6': np.float64(0.0), 'surf_3_OH_PARAM__7': np.float64(0.0), 'surf_3_conc': np.float64(9.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[INFO 07-17 11:36:09] ax.service.ax_client: Generated new trial 20 with parameters {'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 63, 'surf_2_conc': 14, 'surf_3_conc': 9, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's4', 'surf_3': 's1'} using model Sobol.
[WARNING 07-17 11:36:09] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_OH_PARAM__0': 0.6864051418378949, 'surf_1_OH_PARAM__1': 0.014597439207136631, 'surf_1_OH_PARAM__2': 0.7118347296491265, 'surf_1_OH_PARAM__3': 0.08837481774389744, 'surf_1_OH_PARAM__4': 0.4826624942943454, 'surf_1_OH_PARAM__5': 0.47077113948762417, 'surf_1_OH_PARAM__6': 0.6223735734820366, 'surf_1_OH_PARAM__7': 0.3340076981112361, 'surf_1_conc': 41.07814504018454, 'surf_2_OH_PARAM__0': 0.5412801131606102, 'surf_2_OH_PARAM__1': 0.7083502728492022, 'surf_2_OH_PARAM__2': 0.8590837027877569, 'surf_2_OH_PARAM__3': 0.7622893173247576, 'surf_2_OH_PARAM__4': 0.1255330452695489, 'surf_2_OH_PARAM__5': 0.37107709143310785, 'surf_2_OH_PARAM__6': 0.9944703495129943, 'surf_2_OH_PARAM__7': 0.8964267438277602, 'surf_2_conc': 21.845550233740955, 'surf_3_OH_PARAM__0': 0.36477219220250845, 'surf_3_OH_PARAM__1': 0.468956271186471, 'surf_3_OH_PARAM__2': 0.17033734265714884, 'surf_3_OH_PARAM__3': 0.5525142084807158, 'surf_3_OH_PARAM__4': 0.12111334130167961, 'surf_3_OH_PARAM__5': 0.4410871872678399, 'surf_3_OH_PARAM__6': 0.6514342902228236, 'surf_3_OH_PARAM__7': 0.23721248377114534, 'surf_3_conc': 33.7004448414287, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])

**************************************************************************************************** 21  out of  32 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Diclofenac DCF  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************
**************************************************************************************************** 22  out of  32 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Diclofenac DCF  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[WARNING 07-17 11:36:09] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2962), 'Drug_LogP': np.float64(0.4364), 'Drug_TPSA': np.float64(0.0493), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(1.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(41.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(1.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(22.0), 'surf_3_OH_PARAM__0': np.float64(0.0), 'surf_3_OH_PARAM__1': np.float64(0.0), 'surf_3_OH_PARAM__2': np.float64(0.0), 'surf_3_OH_PARAM__3': np.float64(0.0), 'surf_3_OH_PARAM__4': np.float64(0.0), 'surf_3_OH_PARAM__5': np.float64(0.0), 'surf_3_OH_PARAM__6': np.float64(1.0), 'surf_3_OH_PARAM__7': np.float64(0.0), 'surf_3_conc': np.float64(34.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[INFO 07-17 11:36:09] ax.service.ax_client: Generated new trial 21 with parameters {'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 41, 'surf_2_conc': 22, 'surf_3_conc': 34, 'drug_conc': 25.0, 'surf_1': 's3', 'surf_2': 's7', 'surf_3': 's7'} using model Sobol.
[WARNING 07-17 11:36:09] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_OH_PARAM__0': 0.6532901944592595, 'surf_1_OH_PARAM__1': 0.5075609786435962, 'surf_1_OH_PARAM__2': 0.24872820358723402, 'surf_1_OH_PARAM__3': 0.707026606425643, 'surf_1_OH_PARAM__4': 0.997782414779067, 'surf_1_OH_PARAM__5': 0.7951582102105021, 'surf_1_OH_PARAM__6': 0.7688226420432329, 'surf_1_OH_PARAM__7': 0.9840066963806748, 'surf_1_conc': 27.535536146204358, 'surf_2_OH_PARAM__0': 0.18105412181466818, 'surf_2_OH_PARAM__1': 0.7494288003072143, 'surf_2_OH_PARAM__2': 0.7458878261968493, 'surf_2_OH_PARAM__3': 0.4211428873240948, 'surf_2_OH_PARAM__4': 0.03731966391205788, 'surf_2_OH_PARAM__5': 0.8242434877902269, 'surf_2_OH_PARAM__6': 0.09515898674726486, 'surf_2_OH_PARAM__7': 0.7762279752641916, 'surf_2_conc': 38.69508374824748, 'surf_3_OH_PARAM__0': 0.8061305116862059, 'surf_3_OH_PARAM__1': 0.5129328593611717, 'surf_3_OH_PARAM__2': 0.2976789344102144, 'surf_3_OH_PARAM__3': 0.6900318283587694, 'surf_3_OH_PARAM__4': 0.08448636159300804, 'surf_3_OH_PARAM__5': 0.1295030303299427, 'surf_3_OH_PARAM__6': 0.11116129625588655, 'surf_3_OH_PARAM__7': 0.7539295572787523, 'surf_3_conc': 29.219945509266665, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[WARNING 07-17 11:36:09] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.3528), 'Drug_LogP': np.float64(0.281), 'Drug_TPSA': np.float64(0.0711), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(1.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(28.000000000000004), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(1.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(39.0), 'surf_3_OH_PARAM__0': np.float64(1.0), 'surf_3_OH_PARAM__1': np.float64(0.0), 'surf_3_OH_PARAM__2': np.float64(0.0), 'surf_3_OH_PARAM__3': np.float64(0.0), 'surf_3_OH_PARAM__4': np.float64(0.0), 'surf_3_OH_PARAM__5': np.float64(0.0), 'surf_3_OH_PARAM__6': np.float64(0.0), 'surf_3_OH_PARAM__7': np.float64(0.0), 'surf_3_conc': np.float64(29.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[INFO 07-17 11:36:09] ax.service.ax_client: Generated new trial 22 with parameters {'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 28, 'surf_2_conc': 39, 'surf_3_conc': 29, 'drug_conc': 25.0, 'surf_1': 's5', 'surf_2': 's6', 'surf_3': 's1'} using model Sobol.
[WARNING 07-17 11:36:09] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_OH_PARAM__0': 0.35829354263842106, 'surf_1_OH_PARAM__1': 0.3856875691562891, 'surf_1_OH_PARAM__2': 0.043745619244873524, 'surf_1_OH_PARAM__3': 0.8313558604568243, 'surf_1_OH_PARAM__4': 0.37988104205578566, 'surf_1_OH_PARAM__5': 0.07036388013511896, 'surf_1_OH_PARAM__6': 0.3722582934424281, 'surf_1_OH_PARAM__7': 0.7452249638736248, 'surf_1_conc': 23.4246295723257, 'surf_2_OH_PARAM__0': 0.04529851023107767, 'surf_2_OH_PARAM__1': 0.8298716144636273, 'surf_2_OH_PARAM__2': 0.035910580307245255, 'surf_2_OH_PARAM__3': 0.8508235001936555, 'surf_2_OH_PARAM__4': 0.2251042015850544, 'surf_2_OH_PARAM__5': 0.03315593861043453, 'surf_2_OH_PARAM__6': 0.25519467890262604, 'surf_2_OH_PARAM__7': 0.011241638101637363, 'surf_2_conc': 20.351295157310012, 'surf_3_OH_PARAM__0': 0.6376881022006273, 'surf_3_OH_PARAM__1': 0.4072225596755743, 'surf_3_OH_PARAM__2': 0.731860863044858, 'surf_3_OH_PARAM__3': 0.005477018654346466, 'surf_3_OH_PARAM__4': 0.9671736350283027, 'surf_3_OH_PARAM__5': 0.3679376319050789, 'surf_3_OH_PARAM__6': 0.35008208360522985, 'surf_3_OH_PARAM__7': 0.69747762568295, 'surf_3_conc': 52.53424908980953, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])

**************************************************************************************************** 23  out of  32 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Griseofulvin GLV  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************
**************************************************************************************************** 24  out of  32 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Griseofulvin GLV  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[WARNING 07-17 11:36:09] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.3528), 'Drug_LogP': np.float64(0.281), 'Drug_TPSA': np.float64(0.0711), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(1.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(23.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(1.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(20.0), 'surf_3_OH_PARAM__0': np.float64(0.0), 'surf_3_OH_PARAM__1': np.float64(0.0), 'surf_3_OH_PARAM__2': np.float64(0.0), 'surf_3_OH_PARAM__3': np.float64(0.0), 'surf_3_OH_PARAM__4': np.float64(1.0), 'surf_3_OH_PARAM__5': np.float64(0.0), 'surf_3_OH_PARAM__6': np.float64(0.0), 'surf_3_OH_PARAM__7': np.float64(0.0), 'surf_3_conc': np.float64(52.99999999999999), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[INFO 07-17 11:36:09] ax.service.ax_client: Generated new trial 23 with parameters {'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 23, 'surf_2_conc': 20, 'surf_3_conc': 53, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's4', 'surf_3': 's5'} using model Sobol.
[WARNING 07-17 11:36:09] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.09301303047686815, 'surf_1_OH_PARAM__1': 0.28425175696611404, 'surf_1_OH_PARAM__2': 0.25568412709981203, 'surf_1_OH_PARAM__3': 0.09843967575579882, 'surf_1_OH_PARAM__4': 0.9233157513663173, 'surf_1_OH_PARAM__5': 0.41389521677047014, 'surf_1_OH_PARAM__6': 0.28076114878058434, 'surf_1_OH_PARAM__7': 0.663789146579802, 'surf_1_conc': 18.197235462230907, 'surf_2_OH_PARAM__0': 0.9107661871239543, 'surf_2_OH_PARAM__1': 0.6037626033648849, 'surf_2_OH_PARAM__2': 0.26849796064198017, 'surf_2_OH_PARAM__3': 0.19020015466958284, 'surf_2_OH_PARAM__4': 0.4585827300325036, 'surf_2_OH_PARAM__5': 0.6215286673977971, 'surf_2_OH_PARAM__6': 0.3330608904361725, 'surf_2_OH_PARAM__7': 0.5104069579392672, 'surf_2_conc': 8.78507597577499, 'surf_3_OH_PARAM__0': 0.7090652929618955, 'surf_3_OH_PARAM__1': 0.17295365873724222, 'surf_3_OH_PARAM__2': 0.6453185034915805, 'surf_3_OH_PARAM__3': 0.5155757497996092, 'surf_3_OH_PARAM__4': 0.6318804398179054, 'surf_3_OH_PARAM__5': 0.2754508825019002, 'surf_3_OH_PARAM__6': 0.580533454194665, 'surf_3_OH_PARAM__7': 0.20206699892878532, 'surf_3_conc': 36.16504099277707, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[WARNING 07-17 11:36:09] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2063), 'Drug_LogP': np.float64(0.3073), 'Drug_TPSA': np.float64(0.0373), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(1.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(18.0), 'surf_2_OH_PARAM__0': np.float64(1.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(9.0), 'surf_3_OH_PARAM__0': np.float64(1.0), 'surf_3_OH_PARAM__1': np.float64(0.0), 'surf_3_OH_PARAM__2': np.float64(0.0), 'surf_3_OH_PARAM__3': np.float64(0.0), 'surf_3_OH_PARAM__4': np.float64(0.0), 'surf_3_OH_PARAM__5': np.float64(0.0), 'surf_3_OH_PARAM__6': np.float64(0.0), 'surf_3_OH_PARAM__7': np.float64(0.0), 'surf_3_conc': np.float64(36.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[INFO 07-17 11:36:09] ax.service.ax_client: Generated new trial 24 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 18, 'surf_2_conc': 9, 'surf_3_conc': 36, 'drug_conc': 25.0, 'surf_1': 's5', 'surf_2': 's1', 'surf_3': 's1'} using model Sobol.
[WARNING 07-17 11:36:09] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_OH_PARAM__0': 0.917358404956758, 'surf_1_OH_PARAM__1': 0.3483367804437876, 'surf_1_OH_PARAM__2': 0.7528123091906309, 'surf_1_OH_PARAM__3': 0.7170329177752137, 'surf_1_OH_PARAM__4': 0.5284695625305176, 'surf_1_OH_PARAM__5': 0.1399817056953907, 'surf_1_OH_PARAM__6': 0.2719117905944586, 'surf_1_OH_PARAM__7': 0.8241688823327422, 'surf_1_conc': 23.853498082911948, 'surf_2_OH_PARAM__0': 0.7498417729511857, 'surf_2_OH_PARAM__1': 0.7927892208099365, 'surf_2_OH_PARAM__2': 0.8441045638173819, 'surf_2_OH_PARAM__3': 0.697355356067419, 'surf_2_OH_PARAM__4': 0.7164443898946047, 'surf_2_OH_PARAM__5': 0.9513957789167762, 'surf_2_OH_PARAM__6': 0.5287791257724166, 'surf_2_OH_PARAM__7': 0.18337277229875326, 'surf_2_conc': 11.64103307478817, 'surf_3_OH_PARAM__0': 0.38034564536064863, 'surf_3_OH_PARAM__1': 0.6594729349017143, 'surf_3_OH_PARAM__2': 0.11445365194231272, 'surf_3_OH_PARAM__3': 0.36313224770128727, 'surf_3_OH_PARAM__4': 0.8601096514612436, 'surf_3_OH_PARAM__5': 0.056698428466916084, 'surf_3_OH_PARAM__6': 0.09901695512235165, 'surf_3_OH_PARAM__7': 0.9168521668761969, 'surf_3_conc': 13.107246674800141, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])

**************************************************************************************************** 25  out of  32 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Ibuprofen IBP  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************
**************************************************************************************************** 26  out of  32 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Ibuprofen IBP  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[WARNING 07-17 11:36:09] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2063), 'Drug_LogP': np.float64(0.3073), 'Drug_TPSA': np.float64(0.0373), 'surf_1_OH_PARAM__0': np.float64(1.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(24.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(1.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(12.0), 'surf_3_OH_PARAM__0': np.float64(0.0), 'surf_3_OH_PARAM__1': np.float64(0.0), 'surf_3_OH_PARAM__2': np.float64(0.0), 'surf_3_OH_PARAM__3': np.float64(0.0), 'surf_3_OH_PARAM__4': np.float64(0.0), 'surf_3_OH_PARAM__5': np.float64(0.0), 'surf_3_OH_PARAM__6': np.float64(0.0), 'surf_3_OH_PARAM__7': np.float64(1.0), 'surf_3_conc': np.float64(13.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[INFO 07-17 11:36:09] ax.service.ax_client: Generated new trial 25 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 24, 'surf_2_conc': 12, 'surf_3_conc': 13, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's6', 'surf_3': 's8'} using model Sobol.
[WARNING 07-17 11:36:09] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_OH_PARAM__0': 0.35219890531152487, 'surf_1_OH_PARAM__1': 0.562616609968245, 'surf_1_OH_PARAM__2': 0.743658758699894, 'surf_1_OH_PARAM__3': 0.10259422846138477, 'surf_1_OH_PARAM__4': 0.5799718396738172, 'surf_1_OH_PARAM__5': 0.5065862629562616, 'surf_1_OH_PARAM__6': 0.775672622025013, 'surf_1_OH_PARAM__7': 0.5037452196702361, 'surf_1_conc': 33.3574710363251, 'surf_2_OH_PARAM__0': 0.47088291961699724, 'surf_2_OH_PARAM__1': 0.9365007430315018, 'surf_2_OH_PARAM__2': 0.13418519403785467, 'surf_2_OH_PARAM__3': 0.9136515455320477, 'surf_2_OH_PARAM__4': 0.7949297344312072, 'surf_2_OH_PARAM__5': 0.7483475059270859, 'surf_2_OH_PARAM__6': 0.790058015845716, 'surf_2_OH_PARAM__7': 0.4176847478374839, 'surf_2_conc': 41.353773756306175, 'surf_3_OH_PARAM__0': 0.10360009223222733, 'surf_3_OH_PARAM__1': 0.030671500600874424, 'surf_3_OH_PARAM__2': 0.9542835652828217, 'surf_3_OH_PARAM__3': 0.43626526556909084, 'surf_3_OH_PARAM__4': 0.4075037371367216, 'surf_3_OH_PARAM__5': 0.41075369250029325, 'surf_3_OH_PARAM__6': 0.5691210562363267, 'surf_3_OH_PARAM__7': 0.09396340698003769, 'surf_3_conc': 20.71810974830715, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[WARNING 07-17 11:36:09] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.4045), 'Drug_LogP': np.float64(0.4196), 'Drug_TPSA': np.float64(0.0728), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(1.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(33.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(1.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(41.0), 'surf_3_OH_PARAM__0': np.float64(0.0), 'surf_3_OH_PARAM__1': np.float64(0.0), 'surf_3_OH_PARAM__2': np.float64(1.0), 'surf_3_OH_PARAM__3': np.float64(0.0), 'surf_3_OH_PARAM__4': np.float64(0.0), 'surf_3_OH_PARAM__5': np.float64(0.0), 'surf_3_OH_PARAM__6': np.float64(0.0), 'surf_3_OH_PARAM__7': np.float64(0.0), 'surf_3_conc': np.float64(21.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[INFO 07-17 11:36:09] ax.service.ax_client: Generated new trial 26 with parameters {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 33, 'surf_2_conc': 41, 'surf_3_conc': 21, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's2', 'surf_3': 's3'} using model Sobol.
[WARNING 07-17 11:36:10] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_OH_PARAM__0': 0.9490658091381192, 'surf_1_OH_PARAM__1': 0.641755766235292, 'surf_1_OH_PARAM__2': 0.22406295035034418, 'surf_1_OH_PARAM__3': 0.8985282117500901, 'surf_1_OH_PARAM__4': 0.34788357745856047, 'surf_1_OH_PARAM__5': 0.004471709951758385, 'surf_1_OH_PARAM__6': 0.9189317543059587, 'surf_1_OH_PARAM__7': 0.7050188453868032, 'surf_1_conc': 46.56161938894168, 'surf_2_OH_PARAM__0': 0.20022277161478996, 'surf_2_OH_PARAM__1': 0.8422873374074697, 'surf_2_OH_PARAM__2': 0.9150134213268757, 'surf_2_OH_PARAM__3': 0.7989200726151466, 'surf_2_OH_PARAM__4': 0.39308355189859867, 'surf_2_OH_PARAM__5': 0.2346169538795948, 'surf_2_OH_PARAM__6': 0.40851845405995846, 'surf_2_OH_PARAM__7': 0.9911390552297235, 'surf_2_conc': 50.57197963482182, 'surf_3_OH_PARAM__0': 0.19832217413932085, 'surf_3_OH_PARAM__1': 0.3740810379385948, 'surf_3_OH_PARAM__2': 0.6027895463630557, 'surf_3_OH_PARAM__3': 0.5091605959460139, 'surf_3_OH_PARAM__4': 0.3266542302444577, 'surf_3_OH_PARAM__5': 0.6089067598804832, 'surf_3_OH_PARAM__6': 0.44788565766066313, 'surf_3_OH_PARAM__7': 0.2090541636571288, 'surf_3_conc': 1.0964221488550305, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])

**************************************************************************************************** 27  out of  32 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Lovastatin LOV  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************
**************************************************************************************************** 28  out of  32 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Lovastatin LOV  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[WARNING 07-17 11:36:10] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.4045), 'Drug_LogP': np.float64(0.4196), 'Drug_TPSA': np.float64(0.0728), 'surf_1_OH_PARAM__0': np.float64(1.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(47.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(1.0), 'surf_2_conc': np.float64(51.0), 'surf_3_OH_PARAM__0': np.float64(0.0), 'surf_3_OH_PARAM__1': np.float64(0.0), 'surf_3_OH_PARAM__2': np.float64(0.0), 'surf_3_OH_PARAM__3': np.float64(0.0), 'surf_3_OH_PARAM__4': np.float64(0.0), 'surf_3_OH_PARAM__5': np.float64(1.0), 'surf_3_OH_PARAM__6': np.float64(0.0), 'surf_3_OH_PARAM__7': np.float64(0.0), 'surf_3_conc': np.float64(1.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[INFO 07-17 11:36:10] ax.service.ax_client: Generated new trial 27 with parameters {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 47, 'surf_2_conc': 51, 'surf_3_conc': 1, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's8', 'surf_3': 's6'} using model Sobol.
[WARNING 07-17 11:36:10] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_OH_PARAM__0': 0.32299119140952826, 'surf_1_OH_PARAM__1': 0.07160235475748777, 'surf_1_OH_PARAM__2': 0.21859743632376194, 'surf_1_OH_PARAM__3': 0.7192929368466139, 'surf_1_OH_PARAM__4': 0.06482548266649246, 'surf_1_OH_PARAM__5': 0.1978251477703452, 'surf_1_OH_PARAM__6': 0.6135279703885317, 'surf_1_OH_PARAM__7': 0.18193304259330034, 'surf_1_conc': 48.3179274579938, 'surf_2_OH_PARAM__0': 0.8603981155902147, 'surf_2_OH_PARAM__1': 0.8953000353649259, 'surf_2_OH_PARAM__2': 0.2784364242106676, 'surf_2_OH_PARAM__3': 0.25415712129324675, 'surf_2_OH_PARAM__4': 0.8835394848138094, 'surf_2_OH_PARAM__5': 0.1969721494242549, 'surf_2_OH_PARAM__6': 0.17396454513072968, 'surf_2_OH_PARAM__7': 0.28576244600117207, 'surf_2_conc': 19.19926006060153, 'surf_3_OH_PARAM__0': 0.5380047122016549, 'surf_3_OH_PARAM__1': 0.986694554798305, 'surf_3_OH_PARAM__2': 0.5777049167081714, 'surf_3_OH_PARAM__3': 0.3221957478672266, 'surf_3_OH_PARAM__4': 0.3865284603089094, 'surf_3_OH_PARAM__5': 0.22233845107257366, 'surf_3_OH_PARAM__6': 0.16797818150371313, 'surf_3_OH_PARAM__7': 0.8973015835508704, 'surf_3_conc': 15.373848059482965, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[WARNING 07-17 11:36:10] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2962), 'Drug_LogP': np.float64(0.4364), 'Drug_TPSA': np.float64(0.0493), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(1.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(48.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(1.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(19.0), 'surf_3_OH_PARAM__0': np.float64(0.0), 'surf_3_OH_PARAM__1': np.float64(1.0), 'surf_3_OH_PARAM__2': np.float64(0.0), 'surf_3_OH_PARAM__3': np.float64(0.0), 'surf_3_OH_PARAM__4': np.float64(0.0), 'surf_3_OH_PARAM__5': np.float64(0.0), 'surf_3_OH_PARAM__6': np.float64(0.0), 'surf_3_OH_PARAM__7': np.float64(0.0), 'surf_3_conc': np.float64(15.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[INFO 07-17 11:36:10] ax.service.ax_client: Generated new trial 28 with parameters {'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 48, 'surf_2_conc': 19, 'surf_3_conc': 15, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's2', 'surf_3': 's2'} using model Sobol.
[WARNING 07-17 11:36:10] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_OH_PARAM__0': 0.29105323273688555, 'surf_1_OH_PARAM__1': 0.9343573059886694, 'surf_1_OH_PARAM__2': 0.8049696879461408, 'surf_1_OH_PARAM__3': 0.912736726924777, 'surf_1_OH_PARAM__4': 0.8080946682021022, 'surf_1_OH_PARAM__5': 0.06378857512027025, 'surf_1_OH_PARAM__6': 0.20195323787629604, 'surf_1_OH_PARAM__7': 0.281548491679132, 'surf_1_conc': 18.952509328150487, 'surf_2_OH_PARAM__0': 0.31627469416707754, 'surf_2_OH_PARAM__1': 0.9703137008473277, 'surf_2_OH_PARAM__2': 0.45872409641742706, 'surf_2_OH_PARAM__3': 0.2463926812633872, 'surf_2_OH_PARAM__4': 0.19492132402956486, 'surf_2_OH_PARAM__5': 0.9919082745909691, 'surf_2_OH_PARAM__6': 0.7627303013578057, 'surf_2_OH_PARAM__7': 0.6032326705753803, 'surf_2_conc': 68.2849544670554, 'surf_3_OH_PARAM__0': 0.8520778259262443, 'surf_3_OH_PARAM__1': 0.045058379881083965, 'surf_3_OH_PARAM__2': 0.08192109409719706, 'surf_3_OH_PARAM__3': 0.5501260040327907, 'surf_3_OH_PARAM__4': 0.927188784815371, 'surf_3_OH_PARAM__5': 0.6778825400397182, 'surf_3_OH_PARAM__6': 0.25367835350334644, 'surf_3_OH_PARAM__7': 0.22863474301993847, 'surf_3_conc': 5.138366398940402, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])

**************************************************************************************************** 29  out of  32 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Diclofenac DCF  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************
**************************************************************************************************** 30  out of  32 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Diclofenac DCF  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[WARNING 07-17 11:36:10] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.2962), 'Drug_LogP': np.float64(0.4364), 'Drug_TPSA': np.float64(0.0493), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(1.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(19.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(1.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(68.0), 'surf_3_OH_PARAM__0': np.float64(0.0), 'surf_3_OH_PARAM__1': np.float64(0.0), 'surf_3_OH_PARAM__2': np.float64(0.0), 'surf_3_OH_PARAM__3': np.float64(0.0), 'surf_3_OH_PARAM__4': np.float64(1.0), 'surf_3_OH_PARAM__5': np.float64(0.0), 'surf_3_OH_PARAM__6': np.float64(0.0), 'surf_3_OH_PARAM__7': np.float64(0.0), 'surf_3_conc': np.float64(5.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[INFO 07-17 11:36:10] ax.service.ax_client: Generated new trial 29 with parameters {'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 19, 'surf_2_conc': 68, 'surf_3_conc': 5, 'drug_conc': 25.0, 'surf_1': 's2', 'surf_2': 's6', 'surf_3': 's5'} using model Sobol.
[WARNING 07-17 11:36:10] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_OH_PARAM__0': 0.8842502823099494, 'surf_1_OH_PARAM__1': 0.8574174121022224, 'surf_1_OH_PARAM__2': 0.2858603857457638, 'surf_1_OH_PARAM__3': 0.08568485546857119, 'surf_1_OH_PARAM__4': 0.014292237348854542, 'surf_1_OH_PARAM__5': 0.5659007588401437, 'surf_1_OH_PARAM__6': 0.11765019223093987, 'surf_1_OH_PARAM__7': 0.48673826176673174, 'surf_1_conc': 7.32883649956066, 'surf_2_OH_PARAM__0': 0.10640550218522549, 'surf_2_OH_PARAM__1': 0.7518442468717694, 'surf_2_OH_PARAM__2': 0.7384236706420779, 'surf_2_OH_PARAM__3': 0.10327916033565998, 'surf_2_OH_PARAM__4': 0.6202355241402984, 'surf_2_OH_PARAM__5': 0.4939248524606228, 'surf_2_OH_PARAM__6': 0.38122347742319107, 'surf_2_OH_PARAM__7': 0.05168711580336094, 'surf_2_conc': 26.818257939026374, 'surf_3_OH_PARAM__0': 0.9467993620783091, 'surf_3_OH_PARAM__1': 0.3264333102852106, 'surf_3_OH_PARAM__2': 0.4800300616770983, 'surf_3_OH_PARAM__3': 0.3794290479272604, 'surf_3_OH_PARAM__4': 0.8381581399589777, 'surf_3_OH_PARAM__5': 0.37231079395860434, 'surf_3_OH_PARAM__6': 0.6402640342712402, 'surf_3_OH_PARAM__7': 0.09006695542484522, 'surf_3_conc': 24.56293270595822, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[WARNING 07-17 11:36:10] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.3528), 'Drug_LogP': np.float64(0.281), 'Drug_TPSA': np.float64(0.0711), 'surf_1_OH_PARAM__0': np.float64(1.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(0.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(7.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(1.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(0.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(26.999999999999996), 'surf_3_OH_PARAM__0': np.float64(1.0), 'surf_3_OH_PARAM__1': np.float64(0.0), 'surf_3_OH_PARAM__2': np.float64(0.0), 'surf_3_OH_PARAM__3': np.float64(0.0), 'surf_3_OH_PARAM__4': np.float64(0.0), 'surf_3_OH_PARAM__5': np.float64(0.0), 'surf_3_OH_PARAM__6': np.float64(0.0), 'surf_3_OH_PARAM__7': np.float64(0.0), 'surf_3_conc': np.float64(25.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[INFO 07-17 11:36:10] ax.service.ax_client: Generated new trial 30 with parameters {'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 7, 'surf_2_conc': 27, 'surf_3_conc': 25, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's2', 'surf_3': 's1'} using model Sobol.
[WARNING 07-17 11:36:10] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_OH_PARAM__0': 0.9040550775825977, 'surf_1_OH_PARAM__1': 0.002947426401078701, 'surf_1_OH_PARAM__2': 0.04253801889717579, 'surf_1_OH_PARAM__3': 0.41620503552258015, 'surf_1_OH_PARAM__4': 0.6428725626319647, 'surf_1_OH_PARAM__5': 0.6633617263287306, 'surf_1_OH_PARAM__6': 0.9715719493106008, 'surf_1_OH_PARAM__7': 0.29830130375921726, 'surf_1_conc': 64.97166588221833, 'surf_2_OH_PARAM__0': 0.7108857668936253, 'surf_2_OH_PARAM__1': 0.6435118997469544, 'surf_2_OH_PARAM__2': 0.4988403534516692, 'surf_2_OH_PARAM__3': 0.933029524050653, 'surf_2_OH_PARAM__4': 0.028912504203617573, 'surf_2_OH_PARAM__5': 0.20790017768740654, 'surf_2_OH_PARAM__6': 0.615949584171176, 'surf_2_OH_PARAM__7': 0.1132782381027937, 'surf_2_conc': 8.52672852309199, 'surf_3_OH_PARAM__0': 0.002285686321556568, 'surf_3_OH_PARAM__1': 0.4486097954213619, 'surf_3_OH_PARAM__2': 0.33615279011428356, 'surf_3_OH_PARAM__3': 0.9904687628149986, 'surf_3_OH_PARAM__4': 0.647106165997684, 'surf_3_OH_PARAM__5': 0.5270008658990264, 'surf_3_OH_PARAM__6': 0.18729656841605902, 'surf_3_OH_PARAM__7': 0.8716515665873885, 'surf_3_conc': 10.700707682316581, 'drug_conc': 100.0}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])

**************************************************************************************************** 31  out of  32 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Griseofulvin GLV  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************
**************************************************************************************************** 32  out of  32 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Griseofulvin GLV  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[WARNING 07-17 11:36:10] ax.modelbridge.transforms.int_to_float: Unable to round {'Drug_MW': np.float64(0.3528), 'Drug_LogP': np.float64(0.281), 'Drug_TPSA': np.float64(0.0711), 'surf_1_OH_PARAM__0': np.float64(0.0), 'surf_1_OH_PARAM__1': np.float64(0.0), 'surf_1_OH_PARAM__2': np.float64(0.0), 'surf_1_OH_PARAM__3': np.float64(0.0), 'surf_1_OH_PARAM__4': np.float64(0.0), 'surf_1_OH_PARAM__5': np.float64(0.0), 'surf_1_OH_PARAM__6': np.float64(1.0), 'surf_1_OH_PARAM__7': np.float64(0.0), 'surf_1_conc': np.float64(65.0), 'surf_2_OH_PARAM__0': np.float64(0.0), 'surf_2_OH_PARAM__1': np.float64(0.0), 'surf_2_OH_PARAM__2': np.float64(0.0), 'surf_2_OH_PARAM__3': np.float64(1.0), 'surf_2_OH_PARAM__4': np.float64(0.0), 'surf_2_OH_PARAM__5': np.float64(0.0), 'surf_2_OH_PARAM__6': np.float64(0.0), 'surf_2_OH_PARAM__7': np.float64(0.0), 'surf_2_conc': np.float64(9.0), 'surf_3_OH_PARAM__0': np.float64(0.0), 'surf_3_OH_PARAM__1': np.float64(0.0), 'surf_3_OH_PARAM__2': np.float64(0.0), 'surf_3_OH_PARAM__3': np.float64(1.0), 'surf_3_OH_PARAM__4': np.float64(0.0), 'surf_3_OH_PARAM__5': np.float64(0.0), 'surf_3_OH_PARAM__6': np.float64(0.0), 'surf_3_OH_PARAM__7': np.float64(0.0), 'surf_3_conc': np.float64(11.0), 'drug_conc': np.float64(100.0)}to meet parameter constraints of SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_1_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_2_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_2_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='surf_3_OH_PARAM__0', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__6', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_OH_PARAM__7', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='surf_3_conc', parameter_type=INT, range=[0, 100]), RangeParameter(name='drug_conc', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*surf_1_conc + 1.0*surf_2_conc + 1.0*surf_3_conc <= 100.0)])
[INFO 07-17 11:36:10] ax.service.ax_client: Generated new trial 31 with parameters {'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 65, 'surf_2_conc': 9, 'surf_3_conc': 11, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's4', 'surf_3': 's4'} using model Sobol.

Time taken for optimization: 0.07 mins
Time taken for optimization: 4.2 seconds

# process results

In [6]:
ax_client = hf.load_design_optimizer(n)
ax_client.experiment.trials

{0: Trial(experiment_name='drug_surfactant', index=0, status=TrialStatus.RUNNING, arm=Arm(name='0_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 12, 'surf_2_conc': 39, 'surf_3_conc': 20, 'drug_conc': 25.0, 'surf_1': 's8', 'surf_2': 's6', 'surf_3': 's7'})),
 1: Trial(experiment_name='drug_surfactant', index=1, status=TrialStatus.RUNNING, arm=Arm(name='1_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 51, 'surf_2_conc': 4, 'surf_3_conc': 40, 'drug_conc': 25.0, 'surf_1': 's3', 'surf_2': 's2', 'surf_3': 's6'})),
 2: Trial(experiment_name='drug_surfactant', index=2, status=TrialStatus.RUNNING, arm=Arm(name='2_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 1, 'surf_2_conc': 56, 'surf_3_conc': 0, 'drug_conc': 25.0, 'surf_1': 's5', 'surf_2': 's7', 'surf_3': 's3'})),
 3: Trial(experiment_name='drug_surfactant', index=3, status=TrialStatus.RUNNING, arm=Arm(name='3_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 28, 'surf_2_conc': 6, 'surf_3_conc': 14, 'drug_conc': 25.0, 'surf_1': 's3', 'surf_2': 's3', 'surf_3': 's8'})),
 4: Trial(experiment_name='drug_surfactant', index=4, status=TrialStatus.RUNNING, arm=Arm(name='4_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 27, 'surf_2_conc': 63, 'surf_3_conc': 3, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's4', 'surf_3': 's5'})),
 5: Trial(experiment_name='drug_surfactant', index=5, status=TrialStatus.RUNNING, arm=Arm(name='5_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 40, 'surf_2_conc': 29, 'surf_3_conc': 22, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's8', 'surf_3': 's7'})),
 6: Trial(experiment_name='drug_surfactant', index=6, status=TrialStatus.RUNNING, arm=Arm(name='6_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 5, 'surf_2_conc': 24, 'surf_3_conc': 18, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's1', 'surf_3': 's6'})),
 7: Trial(experiment_name='drug_surfactant', index=7, status=TrialStatus.RUNNING, arm=Arm(name='7_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 10, 'surf_2_conc': 1, 'surf_3_conc': 36, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'})),
 8: Trial(experiment_name='drug_surfactant', index=8, status=TrialStatus.RUNNING, arm=Arm(name='8_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 4, 'surf_2_conc': 15, 'surf_3_conc': 50, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's4', 'surf_3': 's1'})),
 9: Trial(experiment_name='drug_surfactant', index=9, status=TrialStatus.RUNNING, arm=Arm(name='9_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 37, 'surf_2_conc': 17, 'surf_3_conc': 32, 'drug_conc': 25.0, 'surf_1': 's3', 'surf_2': 's4', 'surf_3': 's5'})),
 10: Trial(experiment_name='drug_surfactant', index=10, status=TrialStatus.RUNNING, arm=Arm(name='10_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 30, 'surf_2_conc': 3, 'surf_3_conc': 54, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's5', 'surf_3': 's5'})),
 11: Trial(experiment_name='drug_surfactant', index=11, status=TrialStatus.RUNNING, arm=Arm(name='11_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 22, 'surf_2_conc': 37, 'surf_3_conc': 27, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's7', 'surf_3': 's3'})),
 12: Trial(experiment_name='drug_surfactant', index=12, status=TrialStatus.RUNNING, arm=Arm(name='12_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 59, 'surf_2_conc': 21, 'surf_3_conc': 6, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's1', 'surf_3': 's8'})),
 13: Trial(experiment_name='drug_surfactant', index=13, status=TrialStatus.RUNNING, arm=Arm(name='13_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 10, 'surf_2_conc': 78, 'surf_3_conc': 9, 'drug_conc': 25.0, 'surf_1': 's2', 'surf_2': 's8', 'surf_3': 's3'})),
 14: Trial(experiment_name='drug_surfactant', index=14, status=TrialStatus.RUNNING, arm=Arm(name='14_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 22, 'surf_2_conc': 17, 'surf_3_conc': 16, 'drug_conc': 25.0, 'surf_1': 's5', 'surf_2': 's7', 'surf_3': 's3'})),
 15: Trial(experiment_name='drug_surfactant', index=15, status=TrialStatus.RUNNING, arm=Arm(name='15_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 31, 'surf_2_conc': 35, 'surf_3_conc': 24, 'drug_conc': 25.0, 'surf_1': 's5', 'surf_2': 's4', 'surf_3': 's1'})),
 16: Trial(experiment_name='drug_surfactant', index=16, status=TrialStatus.RUNNING, arm=Arm(name='16_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 50, 'surf_2_conc': 0, 'surf_3_conc': 13, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's1', 'surf_3': 's6'})),
 17: Trial(experiment_name='drug_surfactant', index=17, status=TrialStatus.RUNNING, arm=Arm(name='17_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 8, 'surf_2_conc': 46, 'surf_3_conc': 20, 'drug_conc': 25.0, 'surf_1': 's8', 'surf_2': 's6', 'surf_3': 's4'})),
 18: Trial(experiment_name='drug_surfactant', index=18, status=TrialStatus.RUNNING, arm=Arm(name='18_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 20, 'surf_2_conc': 62, 'surf_3_conc': 1, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's8', 'surf_3': 's3'})),
 19: Trial(experiment_name='drug_surfactant', index=19, status=TrialStatus.RUNNING, arm=Arm(name='19_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 0, 'surf_2_conc': 30, 'surf_3_conc': 25, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's7', 'surf_3': 's2'})),
 20: Trial(experiment_name='drug_surfactant', index=20, status=TrialStatus.RUNNING, arm=Arm(name='20_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 63, 'surf_2_conc': 14, 'surf_3_conc': 9, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's4', 'surf_3': 's1'})),
 21: Trial(experiment_name='drug_surfactant', index=21, status=TrialStatus.RUNNING, arm=Arm(name='21_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 41, 'surf_2_conc': 22, 'surf_3_conc': 34, 'drug_conc': 25.0, 'surf_1': 's3', 'surf_2': 's7', 'surf_3': 's7'})),
 22: Trial(experiment_name='drug_surfactant', index=22, status=TrialStatus.RUNNING, arm=Arm(name='22_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 28, 'surf_2_conc': 39, 'surf_3_conc': 29, 'drug_conc': 25.0, 'surf_1': 's5', 'surf_2': 's6', 'surf_3': 's1'})),
 23: Trial(experiment_name='drug_surfactant', index=23, status=TrialStatus.RUNNING, arm=Arm(name='23_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 23, 'surf_2_conc': 20, 'surf_3_conc': 53, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's4', 'surf_3': 's5'})),
 24: Trial(experiment_name='drug_surfactant', index=24, status=TrialStatus.RUNNING, arm=Arm(name='24_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 18, 'surf_2_conc': 9, 'surf_3_conc': 36, 'drug_conc': 25.0, 'surf_1': 's5', 'surf_2': 's1', 'surf_3': 's1'})),
 25: Trial(experiment_name='drug_surfactant', index=25, status=TrialStatus.RUNNING, arm=Arm(name='25_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 24, 'surf_2_conc': 12, 'surf_3_conc': 13, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's6', 'surf_3': 's8'})),
 26: Trial(experiment_name='drug_surfactant', index=26, status=TrialStatus.RUNNING, arm=Arm(name='26_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 33, 'surf_2_conc': 41, 'surf_3_conc': 21, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's2', 'surf_3': 's3'})),
 27: Trial(experiment_name='drug_surfactant', index=27, status=TrialStatus.RUNNING, arm=Arm(name='27_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 47, 'surf_2_conc': 51, 'surf_3_conc': 1, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's8', 'surf_3': 's6'})),
 28: Trial(experiment_name='drug_surfactant', index=28, status=TrialStatus.RUNNING, arm=Arm(name='28_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 48, 'surf_2_conc': 19, 'surf_3_conc': 15, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's2', 'surf_3': 's2'})),
 29: Trial(experiment_name='drug_surfactant', index=29, status=TrialStatus.RUNNING, arm=Arm(name='29_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 19, 'surf_2_conc': 68, 'surf_3_conc': 5, 'drug_conc': 25.0, 'surf_1': 's2', 'surf_2': 's6', 'surf_3': 's5'})),
 30: Trial(experiment_name='drug_surfactant', index=30, status=TrialStatus.RUNNING, arm=Arm(name='30_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 7, 'surf_2_conc': 27, 'surf_3_conc': 25, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's2', 'surf_3': 's1'})),
 31: Trial(experiment_name='drug_surfactant', index=31, status=TrialStatus.RUNNING, arm=Arm(name='31_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 65, 'surf_2_conc': 9, 'surf_3_conc': 11, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's4', 'surf_3': 's4'}))}

In [7]:
df_design, df_vol = hf.design_to_vol (n)
df_design

,trial_index,drug_name,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,surf_3_conc,drug_conc,surf_1,surf_2,surf_3,surf_conc,obj_surf_conc
0,0,IBP,0.2063,0.3073,0.0373,12,39,20,25.0,s8,s6,s7,71,NaN
1,1,IBP,0.2063,0.3073,0.0373,51,4,40,25.0,s3,s2,s6,95,NaN
2,2,LOV,0.4045,0.4196,0.0728,1,56,0,25.0,s5,s7,s3,57,NaN
3,3,LOV,0.4045,0.4196,0.0728,28,6,14,25.0,s3,s3,s8,48,NaN
4,4,DCF,0.2962,0.4364,0.0493,27,63,3,25.0,s1,s4,s5,93,NaN
5,5,DCF,0.2962,0.4364,0.0493,40,29,22,25.0,s6,s8,s7,91,NaN
6,6,GLV,0.3528,0.2810,0.0711,5,24,18,25.0,s1,s1,s6,47,NaN
7,7,GLV,0.3528,0.2810,0.0711,10,1,36,25.0,s6,s5,s1,47,NaN
8,8,IBP,0.2063,0.3073,0.0373,4,15,50,25.0,s4,s4,s1,69,NaN
9,9,IBP,0.2063,0.3073,0.0373,37,17,32,25.0,s3,s4,s5,86,NaN
10,10,LOV,0.4045,0.4196,0.0728,30,3,54,25.0,s1,s5,s5,87,NaN
11,11,LOV,0.4045,0.4196,0.0728,22,37,27,25.0,s4,s7,s3,86,NaN
12,12,DCF,0.2962,0.4364,0.0493,59,21,6,25.0,s4,s1,s8,86,NaN
13,13,DCF,0.2962,0.4364,0.0493,10,78,9,25.0,s2,s8,s3,97,NaN
14,14,GLV,0.3528,0.2810,0.0711,22,17,16,25.0,s5,s7,s3,55,NaN
15,15,GLV,0.3528,0.2810,0.0711,31,35,24,25.0,s5,s4,s1,90,NaN
16,16,IBP,0.2063,0.3073,0.0373,50,0,13,25.0,s6,s1,s6,63,NaN
17,17,IBP,0.2063,0.3073,0.0373,8,46,20,25.0,s8,s6,s4,74,NaN
18,18,LOV,0.4045,0.4196,0.0728,20,62,1,25.0,s6,s8,s3,83,NaN
19,19,LOV,0.4045,0.4196,0.0728,0,30,25,25.0,s6,s7,s2,55,NaN
20,20,DCF,0.2962,0.4364,0.0493,63,14,9,25.0,s4,s4,s1,86,NaN
21,21,DCF,0.2962,0.4364,0.0493,41,22,34,25.0,s3,s7,s7,97,NaN
22,22,GLV,0.3528,0.2810,0.0711,28,39,29,25.0,s5,s6,s1,96,NaN
23,23,GLV,0.3528,0.2810,0.0711,23,20,53,25.0,s4,s4,s5,96,NaN
24,24,IBP,0.2063,0.3073,0.0373,18,9,36,25.0,s5,s1,s1,63,NaN
25,25,IBP,0.2063,0.3073,0.0373,24,12,13,25.0,s1,s6,s8,49,NaN
26,26,LOV,0.4045,0.4196,0.0728,33,41,21,25.0,s7,s2,s3,95,NaN
27,27,LOV,0.4045,0.4196,0.0728,47,51,1,25.0,s1,s8,s6,99,NaN
28,28,DCF,0.2962,0.4364,0.0493,48,19,15,25.0,s4,s2,s2,82,NaN
29,29,DCF,0.2962,0.4364,0.0493,19,68,5,25.0,s2,s6,s5,92,NaN
30,30,GLV,0.3528,0.2810,0.0711,7,27,25,25.0,s1,s2,s1,59,NaN
31,31,GLV,0.3528,0.2810,0.0711,65,9,11,25.0,s7,s4,s4,85,NaN

In [8]:
df_vol

,trial_index,drug_name,drug,s1,s2,s3,s4,s5,s6,s7,s8,dmso,water,IBP,LOV,DCF,GLV
0,0,IBP,180.0,0.0,0.0,0.0,0.0,0.0,468.0,240.0,144.0,0.0,348.0,180.0,0.0,0.0,0.0
1,1,IBP,180.0,0.0,48.0,612.0,0.0,0.0,480.0,0.0,0.0,0.0,60.0,180.0,0.0,0.0,0.0
2,2,LOV,180.0,0.0,0.0,0.0,0.0,12.0,0.0,672.0,0.0,0.0,516.0,0.0,180.0,0.0,0.0
3,3,LOV,180.0,0.0,0.0,408.0,0.0,0.0,0.0,0.0,168.0,0.0,624.0,0.0,180.0,0.0,0.0
4,4,DCF,180.0,324.0,0.0,0.0,756.0,36.0,0.0,0.0,0.0,0.0,84.0,0.0,0.0,180.0,0.0
5,5,DCF,180.0,0.0,0.0,0.0,0.0,0.0,480.0,264.0,348.0,0.0,108.0,0.0,0.0,180.0,0.0
6,6,GLV,180.0,348.0,0.0,0.0,0.0,0.0,216.0,0.0,0.0,0.0,636.0,0.0,0.0,0.0,180.0
7,7,GLV,180.0,432.0,0.0,0.0,0.0,12.0,120.0,0.0,0.0,0.0,636.0,0.0,0.0,0.0,180.0
8,8,IBP,180.0,600.0,0.0,0.0,228.0,0.0,0.0,0.0,0.0,0.0,372.0,180.0,0.0,0.0,0.0
9,9,IBP,180.0,0.0,0.0,444.0,204.0,384.0,0.0,0.0,0.0,0.0,168.0,180.0,0.0,0.0,0.0
10,10,LOV,180.0,360.0,0.0,0.0,0.0,684.0,0.0,0.0,0.0,0.0,156.0,0.0,180.0,0.0,0.0
11,11,LOV,180.0,0.0,0.0,324.0,264.0,0.0,0.0,444.0,0.0,0.0,168.0,0.0,180.0,0.0,0.0
12,12,DCF,180.0,252.0,0.0,0.0,708.0,0.0,0.0,0.0,72.0,0.0,168.0,0.0,0.0,180.0,0.0
13,13,DCF,180.0,0.0,120.0,108.0,0.0,0.0,0.0,0.0,936.0,0.0,36.0,0.0,0.0,180.0,0.0
14,14,GLV,180.0,0.0,0.0,192.0,0.0,264.0,0.0,204.0,0.0,0.0,540.0,0.0,0.0,0.0,180.0
15,15,GLV,180.0,288.0,0.0,0.0,420.0,372.0,0.0,0.0,0.0,0.0,120.0,0.0,0.0,0.0,180.0
16,16,IBP,180.0,0.0,0.0,0.0,0.0,0.0,756.0,0.0,0.0,0.0,444.0,180.0,0.0,0.0,0.0
17,17,IBP,180.0,0.0,0.0,0.0,240.0,0.0,552.0,0.0,96.0,0.0,312.0,180.0,0.0,0.0,0.0
18,18,LOV,180.0,0.0,0.0,12.0,0.0,0.0,240.0,0.0,744.0,0.0,204.0,0.0,180.0,0.0,0.0
19,19,LOV,180.0,0.0,300.0,0.0,0.0,0.0,0.0,360.0,0.0,0.0,540.0,0.0,180.0,0.0,0.0
20,20,DCF,180.0,108.0,0.0,0.0,924.0,0.0,0.0,0.0,0.0,0.0,168.0,0.0,0.0,180.0,0.0
21,21,DCF,180.0,0.0,0.0,492.0,0.0,0.0,0.0,672.0,0.0,0.0,36.0,0.0,0.0,180.0,0.0
22,22,GLV,180.0,348.0,0.0,0.0,0.0,336.0,468.0,0.0,0.0,0.0,48.0,0.0,0.0,0.0,180.0
23,23,GLV,180.0,0.0,0.0,0.0,516.0,636.0,0.0,0.0,0.0,0.0,48.0,0.0,0.0,0.0,180.0
24,24,IBP,180.0,540.0,0.0,0.0,0.0,216.0,0.0,0.0,0.0,0.0,444.0,180.0,0.0,0.0,0.0
25,25,IBP,180.0,288.0,0.0,0.0,0.0,0.0,144.0,0.0,156.0,0.0,612.0,180.0,0.0,0.0,0.0
26,26,LOV,180.0,0.0,492.0,252.0,0.0,0.0,0.0,396.0,0.0,0.0,60.0,0.0,180.0,0.0,0.0
27,27,LOV,180.0,564.0,0.0,0.0,0.0,0.0,12.0,0.0,612.0,0.0,12.0,0.0,180.0,0.0,0.0
28,28,DCF,180.0,0.0,408.0,0.0,576.0,0.0,0.0,0.0,0.0,0.0,216.0,0.0,0.0,180.0,0.0
29,29,DCF,180.0,0.0,228.0,0.0,0.0,60.0,816.0,0.0,0.0,0.0,96.0,0.0,0.0,180.0,0.0
30,30,GLV,180.0,384.0,324.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,492.0,0.0,0.0,0.0,180.0
31,31,GLV,180.0,0.0,0.0,0.0,240.0,0.0,0.0,780.0,0.0,0.0,180.0,0.0,0.0,0.0,180.0

In [9]:
plate_well = input("Enter the plate well starting well (e.g., F1): ")
deepplate_well = input("Enter the deep plate well starting well (e.g., F1): ")



print("Please confirm the following information:")
print("Wellplate will start at: " + plate_well)
print("Deep plate will start at: " + deepplate_well)



print()
print("*******************************************************")
print("Continue if correct, or rerun this cell if incorrect.")
print("*******************************************************")

Please confirm the following information:
Wellplate will start at: A1
Deep plate will start at: A1

*******************************************************
Continue if correct, or rerun this cell if incorrect.
*******************************************************

In [10]:
hf.generate_protocol(df_vol=df_vol, iteration=n, plate_well=plate_well, deepplate_well=deepplate_well)

✅ Successfully wrote to: protocol/otflex_0.py

In [ ]:
df_absorbance = hf.process_absorbance(iteration=n, threshold=0.1)
df_absorbance

In [ ]:
results = hf.build_results(n, df_absorbance)
results

# load the results to the optimizer

In [ ]:
ax_client = hf.load_data_to_optimizer(iteration = n, results = results)
ax_client