# import libraries

In [1]:
import pandas as pd
from ax.service.ax_client import AxClient, ObjectiveProperties
import matplotlib.pyplot as plt
from ax.modelbridge.registry import Models
from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy   
import time


import sys
sys.path.append('../')
import helper_functions as hf

/var/folders/9p/f66yhymx35939zzlg51g0rrc0000gn/T/ipykernel_71908/3307975217.py:5: DeprecationWarning: Please import from 'ax.generation_strategy.generation_strategy' instead of 'ax.modelbridge.generation_strategy'. The latter is deprecated and will be removed in a future release.
  from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy

# generate recommendations

In [2]:
n = hf.get_iteration_number()

for i in range(3):
    print("Very Important: Please Confirm the Iteration Number is Iteration " + str(n))

print()

list_of_drugs = ['IBP'] * 2 + ['LOV'] * 2 + ['DCF'] * 2 + ['GLV'] * 2

for i in range(3):
    print("Very Important: Please Confirm the Drugs are: ", list_of_drugs)

Very Important: Please Confirm the Iteration Number is Iteration 9
Very Important: Please Confirm the Iteration Number is Iteration 9
Very Important: Please Confirm the Iteration Number is Iteration 9

Very Important: Please Confirm the Drugs are:  ['IBP', 'IBP', 'LOV', 'LOV', 'DCF', 'DCF', 'GLV', 'GLV']
Very Important: Please Confirm the Drugs are:  ['IBP', 'IBP', 'LOV', 'LOV', 'DCF', 'DCF', 'GLV', 'GLV']
Very Important: Please Confirm the Drugs are:  ['IBP', 'IBP', 'LOV', 'LOV', 'DCF', 'DCF', 'GLV', 'GLV']

In [3]:
results_so_far = hf.results_so_far(n)
results_so_far

,trial_index,arm_name,trial_status,generation_node,success,surfactant_input,complexity,Drug_MW,Drug_LogP,Drug_TPSA,s1,s2,s3,s4,s5,s6,s7,s8,surfactant_conc,drug_conc
0,0,0_0,COMPLETED,GenerationStep_0,0.0,1.0,1.00,0.2063,0.3073,0.0373,48,60,49,31,96,8,9,35,86,100
1,1,1_0,COMPLETED,GenerationStep_0,0.0,1.0,1.00,0.2063,0.3073,0.0373,74,0,88,66,22,52,58,79,35,100
2,2,2_0,COMPLETED,GenerationStep_0,0.0,1.0,1.00,0.4045,0.4196,0.0728,78,88,1,3,32,94,44,58,1,100
3,3,3_0,COMPLETED,GenerationStep_0,0.0,1.0,1.00,0.4045,0.4196,0.0728,0,46,61,94,63,49,98,0,52,100
4,4,4_0,COMPLETED,GenerationStep_0,0.0,1.0,1.00,0.2962,0.4364,0.0493,16,82,85,84,71,23,35,65,21,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,67,67_0,COMPLETED,GenerationStep_1,0.0,1.0,1.00,0.4045,0.4196,0.0728,100,100,0,0,100,0,0,0,100,100
68,68,68_0,COMPLETED,GenerationStep_1,1.0,1.0,0.50,0.2962,0.4364,0.0493,0,100,0,100,0,0,100,100,100,100
69,69,69_0,COMPLETED,GenerationStep_1,1.0,1.0,0.25,0.2962,0.4364,0.0493,0,100,0,0,0,0,0,100,100,100
70,70,70_0,COMPLETED,GenerationStep_1,1.0,1.0,0.25,0.3528,0.2810,0.0711,0,3,0,0,0,0,0,100,100,100
71,71,71_0,COMPLETED,GenerationStep_1,1.0,1.0,0.25,0.3528,0.2810,0.0711,0,0,0,0,0,0,100,100,100,100

In [4]:
time_start = time.time()


df_design, ax_client = hf.run_optimizer(current_iteration=n, drug_list= list_of_drugs,  bopt = 1)

time_end = time.time()
time_duration = round((time_end - time_start)/60,2)

print("Time taken for optimization: " + str(time_duration) + " mins")
print("Time taken for optimization: " + str(time_duration * 60) + " seconds")

[WARNING 07-15 15:49:27] ax.modelbridge.transforms.standardize_y: Outcome surfactant_input is constant, within tolerance.

**************************************************************************************************** 1  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Ibuprofen IBP  | Iteration:  9

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/botorch/models/utils/assorted.py:273: InputDataWarning: Data (outcome observations) is not standardized (std = tensor([1.0000, 1.0000, 0.0000], dtype=torch.float64), mean = tensor([-1.9737e-16,  4.3175e-17,  0.0000e+00], dtype=torch.float64)).Please consider scaling the input to zero mean and unit variance.
  check_standardization(Y=train_Y, raise_on_fail=raise_on_fail)
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:486: RuntimeWarning: divide by zero encountered in scalar divide
  inv_model_std_quality = max_std if max_std > 1 / min_std else min_std
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:489: RuntimeWarning: divide by zero encountered in scalar divide
  return 1 / inv_model_std_quality
[INFO 07-15 15:49:34] ax.service.ax_client: Generated new trial 72 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 0, 's2': 100, 's3': 0, 's4': 100, 's5': 0, 's6': 0, 's7': 0, 's8': 98, 'surfactant_conc': 100, 'drug_conc': 100} using model BO_MIXED.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
[WARNING 07-15 15:49:34] ax.modelbridge.transforms.standardize_y: Outcome surfactant_input is constant, within tolerance.

**************************************************************************************************** 2  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Ibuprofen IBP  | Iteration:  9

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:486: RuntimeWarning: divide by zero encountered in scalar divide
  inv_model_std_quality = max_std if max_std > 1 / min_std else min_std
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:489: RuntimeWarning: divide by zero encountered in scalar divide
  return 1 / inv_model_std_quality
[INFO 07-15 15:49:36] ax.service.ax_client: Generated new trial 73 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 0, 's2': 0, 's3': 0, 's4': 100, 's5': 0, 's6': 0, 's7': 0, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100} using model BO_MIXED.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
[WARNING 07-15 15:49:36] ax.modelbridge.transforms.standardize_y: Outcome surfactant_input is constant, within tolerance.

**************************************************************************************************** 3  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Lovastatin LOV  | Iteration:  9

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:486: RuntimeWarning: divide by zero encountered in scalar divide
  inv_model_std_quality = max_std if max_std > 1 / min_std else min_std
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:489: RuntimeWarning: divide by zero encountered in scalar divide
  return 1 / inv_model_std_quality
[INFO 07-15 15:49:39] ax.service.ax_client: Generated new trial 74 with parameters {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 's1': 0, 's2': 0, 's3': 0, 's4': 100, 's5': 100, 's6': 0, 's7': 0, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100} using model BO_MIXED.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
[WARNING 07-15 15:49:39] ax.modelbridge.transforms.standardize_y: Outcome surfactant_input is constant, within tolerance.

**************************************************************************************************** 4  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Lovastatin LOV  | Iteration:  9

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:486: RuntimeWarning: divide by zero encountered in scalar divide
  inv_model_std_quality = max_std if max_std > 1 / min_std else min_std
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:489: RuntimeWarning: divide by zero encountered in scalar divide
  return 1 / inv_model_std_quality
[INFO 07-15 15:49:41] ax.service.ax_client: Generated new trial 75 with parameters {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 's1': 0, 's2': 0, 's3': 0, 's4': 100, 's5': 100, 's6': 0, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100} using model BO_MIXED.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
[WARNING 07-15 15:49:41] ax.modelbridge.transforms.standardize_y: Outcome surfactant_input is constant, within tolerance.

**************************************************************************************************** 5  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Diclofenac DCF  | Iteration:  9

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:486: RuntimeWarning: divide by zero encountered in scalar divide
  inv_model_std_quality = max_std if max_std > 1 / min_std else min_std
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:489: RuntimeWarning: divide by zero encountered in scalar divide
  return 1 / inv_model_std_quality
[INFO 07-15 15:49:43] ax.service.ax_client: Generated new trial 76 with parameters {'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 's1': 0, 's2': 0, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 0, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100} using model BO_MIXED.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
[WARNING 07-15 15:49:43] ax.modelbridge.transforms.standardize_y: Outcome surfactant_input is constant, within tolerance.

**************************************************************************************************** 6  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Diclofenac DCF  | Iteration:  9

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:486: RuntimeWarning: divide by zero encountered in scalar divide
  inv_model_std_quality = max_std if max_std > 1 / min_std else min_std
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:489: RuntimeWarning: divide by zero encountered in scalar divide
  return 1 / inv_model_std_quality
[INFO 07-15 15:49:46] ax.service.ax_client: Generated new trial 77 with parameters {'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 's1': 0, 's2': 0, 's3': 0, 's4': 100, 's5': 0, 's6': 0, 's7': 0, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100} using model BO_MIXED.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
[WARNING 07-15 15:49:46] ax.modelbridge.transforms.standardize_y: Outcome surfactant_input is constant, within tolerance.

**************************************************************************************************** 7  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Griseofulvin GLV  | Iteration:  9

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:486: RuntimeWarning: divide by zero encountered in scalar divide
  inv_model_std_quality = max_std if max_std > 1 / min_std else min_std
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:489: RuntimeWarning: divide by zero encountered in scalar divide
  return 1 / inv_model_std_quality
[INFO 07-15 15:49:48] ax.service.ax_client: Generated new trial 78 with parameters {'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 's1': 0, 's2': 0, 's3': 0, 's4': 0, 's5': 94, 's6': 0, 's7': 0, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100} using model BO_MIXED.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
[WARNING 07-15 15:49:48] ax.modelbridge.transforms.standardize_y: Outcome surfactant_input is constant, within tolerance.

**************************************************************************************************** 8  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a Bayesian Optimization trial for
Drug name:  Griseofulvin GLV  | Iteration:  9

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:486: RuntimeWarning: divide by zero encountered in scalar divide
  inv_model_std_quality = max_std if max_std > 1 / min_std else min_std
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:489: RuntimeWarning: divide by zero encountered in scalar divide
  return 1 / inv_model_std_quality
[INFO 07-15 15:49:50] ax.service.ax_client: Generated new trial 79 with parameters {'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 's1': 0, 's2': 0, 's3': 0, 's4': 0, 's5': 100, 's6': 0, 's7': 0, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100} using model BO_MIXED.

Time taken for optimization: 0.38 mins
Time taken for optimization: 22.8 seconds

# process results

In [5]:
ax_client = hf.load_design_optimizer(n)
ax_client.experiment.trials

{0: Trial(experiment_name='drug_surfactant', index=0, status=TrialStatus.COMPLETED, arm=Arm(name='0_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 48, 's2': 60, 's3': 49, 's4': 31, 's5': 96, 's6': 8, 's7': 9, 's8': 35, 'surfactant_conc': 86, 'drug_conc': 100})),
 1: Trial(experiment_name='drug_surfactant', index=1, status=TrialStatus.COMPLETED, arm=Arm(name='1_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 74, 's2': 0, 's3': 88, 's4': 66, 's5': 22, 's6': 52, 's7': 58, 's8': 79, 'surfactant_conc': 35, 'drug_conc': 100})),
 2: Trial(experiment_name='drug_surfactant', index=2, status=TrialStatus.COMPLETED, arm=Arm(name='2_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 's1': 78, 's2': 88, 's3': 1, 's4': 3, 's5': 32, 's6': 94, 's7': 44, 's8': 58, 'surfactant_conc': 1, 'drug_conc': 100})),
 3: Trial(experiment_name='drug_surfactant', index=3, status=TrialStatus.COMPLETED, arm=Arm(name='3_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 's1': 0, 's2': 46, 's3': 61, 's4': 94, 's5': 63, 's6': 49, 's7': 98, 's8': 0, 'surfactant_conc': 52, 'drug_conc': 100})),
 4: Trial(experiment_name='drug_surfactant', index=4, status=TrialStatus.COMPLETED, arm=Arm(name='4_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 's1': 16, 's2': 82, 's3': 85, 's4': 84, 's5': 71, 's6': 23, 's7': 35, 's8': 65, 'surfactant_conc': 21, 'drug_conc': 100})),
 5: Trial(experiment_name='drug_surfactant', index=5, status=TrialStatus.COMPLETED, arm=Arm(name='5_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 's1': 93, 's2': 27, 's3': 27, 's4': 17, 's5': 47, 's6': 67, 's7': 83, 's8': 22, 'surfactant_conc': 71, 'drug_conc': 100})),
 6: Trial(experiment_name='drug_surfactant', index=6, status=TrialStatus.COMPLETED, arm=Arm(name='6_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 's1': 59, 's2': 65, 's3': 62, 's4': 55, 's5': 7, 's6': 76, 's7': 19, 's8': 43, 'surfactant_conc': 94, 'drug_conc': 100})),
 7: Trial(experiment_name='drug_surfactant', index=7, status=TrialStatus.COMPLETED, arm=Arm(name='7_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 's1': 31, 's2': 19, 's3': 25, 's4': 46, 's5': 87, 's6': 32, 's7': 74, 's8': 99, 'surfactant_conc': 44, 'drug_conc': 100})),
 8: Trial(experiment_name='drug_surfactant', index=8, status=TrialStatus.COMPLETED, arm=Arm(name='8_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 0, 's2': 100, 's3': 100, 's4': 0, 's5': 100, 's6': 100, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 9: Trial(experiment_name='drug_surfactant', index=9, status=TrialStatus.COMPLETED, arm=Arm(name='9_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 0, 's2': 100, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 10: Trial(experiment_name='drug_surfactant', index=10, status=TrialStatus.COMPLETED, arm=Arm(name='10_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 's1': 100, 's2': 0, 's3': 0, 's4': 100, 's5': 0, 's6': 0, 's7': 0, 's8': 0, 'surfactant_conc': 1, 'drug_conc': 100})),
 11: Trial(experiment_name='drug_surfactant', index=11, status=TrialStatus.COMPLETED, arm=Arm(name='11_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 's1': 0, 's2': 0, 's3': 100, 's4': 0, 's5': 100, 's6': 100, 's7': 0, 's8': 0, 'surfactant_conc': 1, 'drug_conc': 100})),
 12: Trial(experiment_name='drug_surfactant', index=12, status=TrialStatus.COMPLETED, arm=Arm(name='12_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 's1': 100, 's2': 100, 's3': 0, 's4': 100, 's5': 0, 's6': 0, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 13: Trial(experiment_name='drug_surfactant', index=13, status=TrialStatus.COMPLETED, arm=Arm(name='13_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 's1': 0, 's2': 0, 's3': 100, 's4': 0, 's5': 100, 's6': 100, 's7': 0, 's8': 0, 'surfactant_conc': 1, 'drug_conc': 100})),
 14: Trial(experiment_name='drug_surfactant', index=14, status=TrialStatus.COMPLETED, arm=Arm(name='14_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 's1': 100, 's2': 100, 's3': 0, 's4': 100, 's5': 0, 's6': 0, 's7': 100, 's8': 0, 'surfactant_conc': 1, 'drug_conc': 100})),
 15: Trial(experiment_name='drug_surfactant', index=15, status=TrialStatus.COMPLETED, arm=Arm(name='15_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 's1': 0, 's2': 0, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 4, 's8': 0, 'surfactant_conc': 1, 'drug_conc': 100})),
 16: Trial(experiment_name='drug_surfactant', index=16, status=TrialStatus.COMPLETED, arm=Arm(name='16_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 0, 's2': 100, 's3': 100, 's4': 0, 's5': 0, 's6': 0, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 17: Trial(experiment_name='drug_surfactant', index=17, status=TrialStatus.COMPLETED, arm=Arm(name='17_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 0, 's2': 100, 's3': 0, 's4': 0, 's5': 0, 's6': 100, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 18: Trial(experiment_name='drug_surfactant', index=18, status=TrialStatus.COMPLETED, arm=Arm(name='18_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 's1': 0, 's2': 100, 's3': 100, 's4': 0, 's5': 0, 's6': 0, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 19: Trial(experiment_name='drug_surfactant', index=19, status=TrialStatus.COMPLETED, arm=Arm(name='19_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 's1': 0, 's2': 100, 's3': 0, 's4': 3, 's5': 0, 's6': 100, 's7': 100, 's8': 0, 'surfactant_conc': 100, 'drug_conc': 100})),
 20: Trial(experiment_name='drug_surfactant', index=20, status=TrialStatus.COMPLETED, arm=Arm(name='20_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 's1': 0, 's2': 100, 's3': 100, 's4': 0, 's5': 0, 's6': 0, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 21: Trial(experiment_name='drug_surfactant', index=21, status=TrialStatus.COMPLETED, arm=Arm(name='21_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 's1': 0, 's2': 100, 's3': 0, 's4': 3, 's5': 0, 's6': 100, 's7': 100, 's8': 0, 'surfactant_conc': 100, 'drug_conc': 100})),
 22: Trial(experiment_name='drug_surfactant', index=22, status=TrialStatus.COMPLETED, arm=Arm(name='22_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 's1': 0, 's2': 100, 's3': 100, 's4': 0, 's5': 0, 's6': 0, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 23: Trial(experiment_name='drug_surfactant', index=23, status=TrialStatus.COMPLETED, arm=Arm(name='23_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 's1': 0, 's2': 100, 's3': 0, 's4': 13, 's5': 0, 's6': 100, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 24: Trial(experiment_name='drug_surfactant', index=24, status=TrialStatus.COMPLETED, arm=Arm(name='24_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 0, 's2': 100, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 100, 's8': 0, 'surfactant_conc': 100, 'drug_conc': 100})),
 25: Trial(experiment_name='drug_surfactant', index=25, status=TrialStatus.COMPLETED, arm=Arm(name='25_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 0, 's2': 0, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 26: Trial(experiment_name='drug_surfactant', index=26, status=TrialStatus.COMPLETED, arm=Arm(name='26_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 's1': 0, 's2': 100, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 27: Trial(experiment_name='drug_surfactant', index=27, status=TrialStatus.COMPLETED, arm=Arm(name='27_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 's1': 0, 's2': 0, 's3': 100, 's4': 0, 's5': 0, 's6': 100, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 28: Trial(experiment_name='drug_surfactant', index=28, status=TrialStatus.COMPLETED, arm=Arm(name='28_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 's1': 0, 's2': 100, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 29: Trial(experiment_name='drug_surfactant', index=29, status=TrialStatus.COMPLETED, arm=Arm(name='29_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 's1': 0, 's2': 11, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 30: Trial(experiment_name='drug_surfactant', index=30, status=TrialStatus.COMPLETED, arm=Arm(name='30_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 's1': 0, 's2': 100, 's3': 0, 's4': 100, 's5': 100, 's6': 0, 's7': 0, 's8': 0, 'surfactant_conc': 100, 'drug_conc': 100})),
 31: Trial(experiment_name='drug_surfactant', index=31, status=TrialStatus.COMPLETED, arm=Arm(name='31_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 's1': 0, 's2': 0, 's3': 0, 's4': 100, 's5': 100, 's6': 100, 's7': 0, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 32: Trial(experiment_name='drug_surfactant', index=32, status=TrialStatus.COMPLETED, arm=Arm(name='32_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 0, 's2': 0, 's3': 17, 's4': 0, 's5': 0, 's6': 3, 's7': 100, 's8': 0, 'surfactant_conc': 100, 'drug_conc': 100})),
 33: Trial(experiment_name='drug_surfactant', index=33, status=TrialStatus.COMPLETED, arm=Arm(name='33_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 0, 's2': 0, 's3': 18, 's4': 0, 's5': 100, 's6': 2, 's7': 100, 's8': 0, 'surfactant_conc': 100, 'drug_conc': 100})),
 34: Trial(experiment_name='drug_surfactant', index=34, status=TrialStatus.COMPLETED, arm=Arm(name='34_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 's1': 0, 's2': 100, 's3': 0, 's4': 0, 's5': 100, 's6': 0, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 35: Trial(experiment_name='drug_surfactant', index=35, status=TrialStatus.COMPLETED, arm=Arm(name='35_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 's1': 0, 's2': 100, 's3': 0, 's4': 100, 's5': 0, 's6': 0, 's7': 100, 's8': 0, 'surfactant_conc': 100, 'drug_conc': 100})),
 36: Trial(experiment_name='drug_surfactant', index=36, status=TrialStatus.COMPLETED, arm=Arm(name='36_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 's1': 0, 's2': 0, 's3': 25, 's4': 0, 's5': 0, 's6': 0, 's7': 100, 's8': 0, 'surfactant_conc': 100, 'drug_conc': 100})),
 37: Trial(experiment_name='drug_surfactant', index=37, status=TrialStatus.COMPLETED, arm=Arm(name='37_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 's1': 0, 's2': 100, 's3': 22, 's4': 0, 's5': 100, 's6': 0, 's7': 100, 's8': 0, 'surfactant_conc': 100, 'drug_conc': 100})),
 38: Trial(experiment_name='drug_surfactant', index=38, status=TrialStatus.COMPLETED, arm=Arm(name='38_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 's1': 0, 's2': 100, 's3': 0, 's4': 0, 's5': 100, 's6': 0, 's7': 100, 's8': 0, 'surfactant_conc': 100, 'drug_conc': 100})),
 39: Trial(experiment_name='drug_surfactant', index=39, status=TrialStatus.COMPLETED, arm=Arm(name='39_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 's1': 0, 's2': 100, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 100, 's8': 100, 'surfactant_conc': 1, 'drug_conc': 100})),
 40: Trial(experiment_name='drug_surfactant', index=40, status=TrialStatus.COMPLETED, arm=Arm(name='40_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 0, 's2': 35, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 0, 's8': 50, 'surfactant_conc': 100, 'drug_conc': 100})),
 41: Trial(experiment_name='drug_surfactant', index=41, status=TrialStatus.COMPLETED, arm=Arm(name='41_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 0, 's2': 44, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 100, 's8': 42, 'surfactant_conc': 1, 'drug_conc': 100})),
 42: Trial(experiment_name='drug_surfactant', index=42, status=TrialStatus.COMPLETED, arm=Arm(name='42_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 's1': 0, 's2': 99, 's3': 0, 's4': 0, 's5': 6, 's6': 0, 's7': 0, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 43: Trial(experiment_name='drug_surfactant', index=43, status=TrialStatus.COMPLETED, arm=Arm(name='43_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 's1': 0, 's2': 37, 's3': 0, 's4': 0, 's5': 29, 's6': 0, 's7': 0, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 44: Trial(experiment_name='drug_surfactant', index=44, status=TrialStatus.COMPLETED, arm=Arm(name='44_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 's1': 0, 's2': 59, 's3': 0, 's4': 0, 's5': 62, 's6': 0, 's7': 0, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 45: Trial(experiment_name='drug_surfactant', index=45, status=TrialStatus.COMPLETED, arm=Arm(name='45_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 's1': 0, 's2': 83, 's3': 34, 's4': 0, 's5': 0, 's6': 0, 's7': 0, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 46: Trial(experiment_name='drug_surfactant', index=46, status=TrialStatus.COMPLETED, arm=Arm(name='46_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 's1': 100, 's2': 100, 's3': 100, 's4': 100, 's5': 0, 's6': 100, 's7': 0, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 47: Trial(experiment_name='drug_surfactant', index=47, status=TrialStatus.COMPLETED, arm=Arm(name='47_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 's1': 100, 's2': 0, 's3': 100, 's4': 100, 's5': 100, 's6': 100, 's7': 100, 's8': 0, 'surfactant_conc': 1, 'drug_conc': 100})),
 48: Trial(experiment_name='drug_surfactant', index=48, status=TrialStatus.COMPLETED, arm=Arm(name='48_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 0, 's2': 0, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 100, 's8': 56, 'surfactant_conc': 100, 'drug_conc': 100})),
 49: Trial(experiment_name='drug_surfactant', index=49, status=TrialStatus.COMPLETED, arm=Arm(name='49_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 0, 's2': 0, 's3': 0, 's4': 0, 's5': 100, 's6': 0, 's7': 100, 's8': 74, 'surfactant_conc': 100, 'drug_conc': 100})),
 50: Trial(experiment_name='drug_surfactant', index=50, status=TrialStatus.COMPLETED, arm=Arm(name='50_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 's1': 0, 's2': 0, 's3': 0, 's4': 0, 's5': 100, 's6': 0, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 51: Trial(experiment_name='drug_surfactant', index=51, status=TrialStatus.COMPLETED, arm=Arm(name='51_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 's1': 29, 's2': 0, 's3': 0, 's4': 0, 's5': 100, 's6': 0, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 52: Trial(experiment_name='drug_surfactant', index=52, status=TrialStatus.COMPLETED, arm=Arm(name='52_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 's1': 0, 's2': 0, 's3': 0, 's4': 0, 's5': 100, 's6': 0, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 53: Trial(experiment_name='drug_surfactant', index=53, status=TrialStatus.COMPLETED, arm=Arm(name='53_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 's1': 44, 's2': 100, 's3': 0, 's4': 0, 's5': 100, 's6': 100, 's7': 85, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 54: Trial(experiment_name='drug_surfactant', index=54, status=TrialStatus.COMPLETED, arm=Arm(name='54_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 's1': 0, 's2': 0, 's3': 0, 's4': 0, 's5': 100, 's6': 0, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 55: Trial(experiment_name='drug_surfactant', index=55, status=TrialStatus.COMPLETED, arm=Arm(name='55_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 's1': 100, 's2': 100, 's3': 0, 's4': 100, 's5': 0, 's6': 100, 's7': 0, 's8': 100, 'surfactant_conc': 1, 'drug_conc': 100})),
 56: Trial(experiment_name='drug_surfactant', index=56, status=TrialStatus.COMPLETED, arm=Arm(name='56_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 0, 's2': 50, 's3': 15, 's4': 0, 's5': 19, 's6': 0, 's7': 54, 's8': 58, 'surfactant_conc': 100, 'drug_conc': 100})),
 57: Trial(experiment_name='drug_surfactant', index=57, status=TrialStatus.COMPLETED, arm=Arm(name='57_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 0, 's2': 32, 's3': 0, 's4': 0, 's5': 15, 's6': 79, 's7': 56, 's8': 84, 'surfactant_conc': 100, 'drug_conc': 100})),
 58: Trial(experiment_name='drug_surfactant', index=58, status=TrialStatus.COMPLETED, arm=Arm(name='58_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 's1': 0, 's2': 24, 's3': 0, 's4': 0, 's5': 40, 's6': 0, 's7': 99, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 59: Trial(experiment_name='drug_surfactant', index=59, status=TrialStatus.COMPLETED, arm=Arm(name='59_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 's1': 0, 's2': 1, 's3': 0, 's4': 0, 's5': 72, 's6': 0, 's7': 39, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 60: Trial(experiment_name='drug_surfactant', index=60, status=TrialStatus.COMPLETED, arm=Arm(name='60_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 's1': 0, 's2': 39, 's3': 7, 's4': 0, 's5': 0, 's6': 0, 's7': 24, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 61: Trial(experiment_name='drug_surfactant', index=61, status=TrialStatus.COMPLETED, arm=Arm(name='61_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 's1': 0, 's2': 55, 's3': 35, 's4': 0, 's5': 0, 's6': 0, 's7': 60, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 62: Trial(experiment_name='drug_surfactant', index=62, status=TrialStatus.COMPLETED, arm=Arm(name='62_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 's1': 0, 's2': 0, 's3': 0, 's4': 0, 's5': 50, 's6': 0, 's7': 56, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 63: Trial(experiment_name='drug_surfactant', index=63, status=TrialStatus.COMPLETED, arm=Arm(name='63_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 's1': 0, 's2': 0, 's3': 0, 's4': 0, 's5': 25, 's6': 0, 's7': 100, 's8': 100, 'surfactant_conc': 100, 'drug_conc': 100})),
 64: Trial(experiment_name='drug_surfactant', index=64, status=TrialStatus.COMPLETED, arm=Arm(name='64_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 100, 's2': 100, 's3': 0, 's4': 100, 's5': 100, 's6': 100, 's7': 100, 's8': 100, 'surfactant_conc': 1, 'drug_conc': 100})),
 65: Trial(experiment_name='drug_surfactant', index=65, status=TrialStatus.COMPLETED, arm=Arm(name='65_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 's1': 5, 's2': 100, 's3': 0, 's4': 0, 's5': 0, 's6': 0, 's7': 0, 's8': 12, 'surfactant_conc': 100, 'drug_conc': 100})),

In [6]:
df_conc, df_vol = hf.design_to_conc_to_vol (n)

In [7]:
plate_well = input("Enter the plate well starting well (e.g., F1): ")
deepplate_well = input("Enter the deep plate well starting well (e.g., F1): ")


print("Please confirm the following information:")
print("Wellplate will start at: " + plate_well)
print("Deep plate will start at: " + deepplate_well)

print()
print("*******************************************************")
print("Continue if correct, or rerun this cell if incorrect.")
print("*******************************************************")

Please confirm the following information:
Wellplate will start at: G1
Deep plate will start at: F5

*******************************************************
Continue if correct, or rerun this cell if incorrect.
*******************************************************

In [8]:
hf.generate_protocol(df_vol=df_vol, iteration=n, plate_well=plate_well, deepplate_well=deepplate_well)

✅ Successfully wrote to: protocol/otflex_9.py

In [9]:
df_absorbance = hf.process_absorbance(iteration=n, threshold=0.06)
df_absorbance

   trial_index  success
0            0        0
1            1        1
2            2        1
3            3        1
4            4        1
5            5        1
6            6        1
7            7        1

In [10]:
results = hf.build_results(n, df_conc, df_absorbance)
results

,trial_index,drug_name,s1,s2,s3,s4,s5,s6,s7,s8,surfactant_input,drug_conc,success,complexity
0,72,IBP,0,100,0,100,0,0,0,98,50.0,25.0,0,3
1,73,IBP,0,0,0,100,0,0,0,100,50.0,25.0,1,2
2,74,LOV,0,0,0,100,100,0,0,100,50.0,25.0,1,3
3,75,LOV,0,0,0,100,100,0,100,100,50.0,25.0,1,4
4,76,DCF,0,0,0,0,0,0,0,100,50.0,25.0,1,1
5,77,DCF,0,0,0,100,0,0,0,100,50.0,25.0,1,2
6,78,GLV,0,0,0,0,94,0,0,100,50.0,25.0,1,2
7,79,GLV,0,0,0,0,100,0,0,100,50.0,25.0,1,2

In [11]:
norm_results = hf.normalize_data(results, 'normalize')

In [12]:
norm_results

,trial_index,drug_name,s1,s2,s3,s4,s5,s6,s7,s8,surfactant_input,drug_conc,success,complexity
0,72,IBP,0,100,0,100,0,0,0,98,1.0,1.0,0.0,0.375
1,73,IBP,0,0,0,100,0,0,0,100,1.0,1.0,1.0,0.250
2,74,LOV,0,0,0,100,100,0,0,100,1.0,1.0,1.0,0.375
3,75,LOV,0,0,0,100,100,0,100,100,1.0,1.0,1.0,0.500
4,76,DCF,0,0,0,0,0,0,0,100,1.0,1.0,1.0,0.125
5,77,DCF,0,0,0,100,0,0,0,100,1.0,1.0,1.0,0.250
6,78,GLV,0,0,0,0,94,0,0,100,1.0,1.0,1.0,0.250
7,79,GLV,0,0,0,0,100,0,0,100,1.0,1.0,1.0,0.250

# load the results to the optimizer

In [13]:
ax_client = hf.load_data_to_optimizer(iteration = n, norm_results = norm_results)
ax_client

[INFO 07-16 09:35:10] ax.service.ax_client: Completed trial 72 with data: {'success': (0.0, None), 'surfactant_input': (1.0, None), 'complexity': (1.0, None)}.
[INFO 07-16 09:35:10] ax.service.ax_client: Completed trial 73 with data: {'success': (1.0, None), 'surfactant_input': (1.0, None), 'complexity': (0.25, None)}.
[INFO 07-16 09:35:10] ax.service.ax_client: Completed trial 74 with data: {'success': (1.0, None), 'surfactant_input': (1.0, None), 'complexity': (0.375, None)}.
[INFO 07-16 09:35:10] ax.service.ax_client: Completed trial 75 with data: {'success': (1.0, None), 'surfactant_input': (1.0, None), 'complexity': (0.5, None)}.
[INFO 07-16 09:35:10] ax.service.ax_client: Completed trial 76 with data: {'success': (1.0, None), 'surfactant_input': (1.0, None), 'complexity': (0.125, None)}.
[INFO 07-16 09:35:10] ax.service.ax_client: Completed trial 77 with data: {'success': (1.0, None), 'surfactant_input': (1.0, None), 'complexity': (0.25, None)}.
[INFO 07-16 09:35:10] ax.service.ax_client: Completed trial 78 with data: {'success': (1.0, None), 'surfactant_input': (1.0, None), 'complexity': (0.25, None)}.
[INFO 07-16 09:35:10] ax.service.ax_client: Completed trial 79 with data: {'success': (1.0, None), 'surfactant_input': (1.0, None), 'complexity': (0.25, None)}.

Trial 72: success=0 → overriding surfactant_input & complexity to 1
Trial 73: success=1 → using surfactant_input=1.0, complexity=0.25
Trial 74: success=1 → using surfactant_input=1.0, complexity=0.375
Trial 75: success=1 → using surfactant_input=1.0, complexity=0.5
Trial 76: success=1 → using surfactant_input=1.0, complexity=0.125
Trial 77: success=1 → using surfactant_input=1.0, complexity=0.25
Trial 78: success=1 → using surfactant_input=1.0, complexity=0.25
Trial 79: success=1 → using surfactant_input=1.0, complexity=0.25

AxClient(experiment=Experiment(drug_surfactant))