# import libraries

In [1]:
import pandas as pd
from ax.service.ax_client import AxClient, ObjectiveProperties
import matplotlib.pyplot as plt
from ax.modelbridge.registry import Models
from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy   
import time


import sys
sys.path.append('../')
import helper_functions as hf

C:\Users\yunhe\AppData\Local\Temp\ipykernel_27928\3307975217.py:5: DeprecationWarning: Please import from 'ax.generation_strategy.generation_strategy' instead of 'ax.modelbridge.generation_strategy'. The latter is deprecated and will be removed in a future release.
  from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy

# generate recommendations

In [2]:
n = hf.get_iteration_number()

for i in range(3):
    print("Very Important: Please Confirm the Iteration Number is Iteration " + str(n))

print()

list_of_drugs = (['IBP']  + ['LOV']  + ['DCF']  + ['GLV']) * 2

for i in range(3):
    print("Very Important: Please Confirm the Drugs are: ", list_of_drugs)

Very Important: Please Confirm the Iteration Number is Iteration 2
Very Important: Please Confirm the Iteration Number is Iteration 2
Very Important: Please Confirm the Iteration Number is Iteration 2

Very Important: Please Confirm the Drugs are:  ['IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV']
Very Important: Please Confirm the Drugs are:  ['IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV']
Very Important: Please Confirm the Drugs are:  ['IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV']

In [3]:
time_start = time.time()


df_design, ax_client, data_so_far, best_concs = hf.run_optimizer(current_iteration=n, drug_list= list_of_drugs,  bopt = 1)

time_end = time.time()
time_duration = round((time_end - time_start)/60,2)

print("Time taken for optimization: " + str(time_duration) + " mins")
print("Time taken for optimization: " + str(time_duration * 60) + " seconds")

******************************************************************************** 1/8 ********************************************************************************

Update constraints (drug=IBP)：surf_1_conc+surf_2_conc <= 33.0，>=1

c:\Users\yunhe\anaconda3\envs\drug_surfactant\Lib\site-packages\linear_operator\utils\interpolation.py:71: UserWarning: torch.sparse.SparseTensor(indices, values, shape, *, device=) is deprecated.  Please use torch.sparse_coo_tensor(indices, values, shape, dtype=, device=). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\torch\csrc\utils\tensor_new.cpp:656.)
  summing_matrix = cls(summing_matrix_indices, summing_matrix_values, size)
[INFO 08-20 14:47:47] ax.service.ax_client: Generated new trial 40 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'drugs': 0, 'surf_1_conc': 14, 'surf_2_conc': 16, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's4'} using model BoTorch.
c:\Users\yunhe\anaconda3\envs\drug_surfactant\Lib\site-packages\ax\core\data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

******************************************************************************** 2/8 ********************************************************************************

Update constraints (drug=LOV)：surf_1_conc+surf_2_conc <= 28.0，>=1

[INFO 08-20 14:48:05] ax.service.ax_client: Generated new trial 41 with parameters {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'drugs': 2, 'surf_1_conc': 17, 'surf_2_conc': 10, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's8'} using model BoTorch.
c:\Users\yunhe\anaconda3\envs\drug_surfactant\Lib\site-packages\ax\core\data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

******************************************************************************** 3/8 ********************************************************************************

Update constraints (drug=DCF)：surf_1_conc+surf_2_conc <= 60.0，>=1

[INFO 08-20 14:48:32] ax.service.ax_client: Generated new trial 42 with parameters {'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'drugs': 1, 'surf_1_conc': 9, 'surf_2_conc': 42, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's4'} using model BoTorch.
c:\Users\yunhe\anaconda3\envs\drug_surfactant\Lib\site-packages\ax\core\data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

******************************************************************************** 4/8 ********************************************************************************

Update constraints (drug=GLV)：surf_1_conc+surf_2_conc <= 72.0，>=1

[INFO 08-20 14:48:45] ax.service.ax_client: Generated new trial 43 with parameters {'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'drugs': 5, 'surf_1_conc': 8, 'surf_2_conc': 49, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's4'} using model BoTorch.
c:\Users\yunhe\anaconda3\envs\drug_surfactant\Lib\site-packages\ax\core\data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

******************************************************************************** 5/8 ********************************************************************************

Update constraints (drug=IBP)：surf_1_conc+surf_2_conc <= 33.0，>=1

[INFO 08-20 14:49:15] ax.service.ax_client: Generated new trial 44 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'drugs': 0, 'surf_1_conc': 12, 'surf_2_conc': 21, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's4'} using model BoTorch.
c:\Users\yunhe\anaconda3\envs\drug_surfactant\Lib\site-packages\ax\core\data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

******************************************************************************** 6/8 ********************************************************************************

Update constraints (drug=LOV)：surf_1_conc+surf_2_conc <= 28.0，>=1

[INFO 08-20 14:49:37] ax.service.ax_client: Generated new trial 45 with parameters {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'drugs': 2, 'surf_1_conc': 5, 'surf_2_conc': 23, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's4'} using model BoTorch.
c:\Users\yunhe\anaconda3\envs\drug_surfactant\Lib\site-packages\ax\core\data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

******************************************************************************** 7/8 ********************************************************************************

Update constraints (drug=DCF)：surf_1_conc+surf_2_conc <= 60.0，>=1

[INFO 08-20 14:49:50] ax.service.ax_client: Generated new trial 46 with parameters {'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'drugs': 1, 'surf_1_conc': 26, 'surf_2_conc': 4, 'drug_conc': 25.0, 'surf_1': 's2', 'surf_2': 's5'} using model BoTorch.
c:\Users\yunhe\anaconda3\envs\drug_surfactant\Lib\site-packages\ax\core\data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

******************************************************************************** 8/8 ********************************************************************************

Update constraints (drug=GLV)：surf_1_conc+surf_2_conc <= 72.0，>=1

[INFO 08-20 14:50:02] ax.service.ax_client: Generated new trial 47 with parameters {'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'drugs': 5, 'surf_1_conc': 6, 'surf_2_conc': 12, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's1'} using model BoTorch.

Time taken for optimization: 2.57 mins
Time taken for optimization: 154.2 seconds

# process results

In [4]:
ax_client = hf.load_design_optimizer(n)
ax_client.get_trials_data_frame()

c:\Users\yunhe\anaconda3\envs\drug_surfactant\Lib\site-packages\ax\core\data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

,trial_index,arm_name,trial_status,generation_node,obj_surf_conc,Drug_MW,Drug_LogP,Drug_TPSA,drugs,surf_1_conc,surf_2_conc,drug_conc,surf_1,surf_2
0,0,0_0,COMPLETED,GenerationStep_0,35.0,0.2063,0.3073,0.0373,0,29,6,25.0,s7,s6
1,1,1_0,COMPLETED,GenerationStep_0,50.0,0.4045,0.4196,0.0728,2,6,44,25.0,s4,s4
2,2,2_0,COMPLETED,GenerationStep_0,100.0,0.2962,0.4364,0.0493,1,4,27,25.0,s2,s6
3,3,3_0,COMPLETED,GenerationStep_0,92.0,0.3528,0.2810,0.0711,5,91,1,25.0,s1,s2
4,4,4_0,COMPLETED,GenerationStep_0,46.0,0.2063,0.3073,0.0373,0,32,14,25.0,s3,s4
5,5,5_0,COMPLETED,GenerationStep_0,94.0,0.4045,0.4196,0.0728,2,18,76,25.0,s8,s1
6,6,6_0,COMPLETED,GenerationStep_0,62.0,0.2962,0.4364,0.0493,1,59,3,25.0,s8,s2
7,7,7_0,COMPLETED,GenerationStep_0,100.0,0.3528,0.2810,0.0711,5,2,66,25.0,s3,s6
8,8,8_0,COMPLETED,GenerationStep_0,79.0,0.2063,0.3073,0.0373,0,48,31,25.0,s4,s6
9,9,9_0,COMPLETED,GenerationStep_0,30.0,0.4045,0.4196,0.0728,2,12,18,25.0,s4,s8
10,10,10_0,COMPLETED,GenerationStep_0,100.0,0.2962,0.4364,0.0493,1,22,10,25.0,s6,s1
11,11,11_0,COMPLETED,GenerationStep_0,100.0,0.3528,0.2810,0.0711,5,55,24,25.0,s2,s4
12,12,12_0,COMPLETED,GenerationStep_0,73.0,0.2063,0.3073,0.0373,0,12,61,25.0,s1,s8
13,13,13_0,COMPLETED,GenerationStep_0,100.0,0.4045,0.4196,0.0728,2,38,48,25.0,s1,s1
14,14,14_0,COMPLETED,GenerationStep_0,100.0,0.2962,0.4364,0.0493,1,1,75,25.0,s2,s7
15,15,15_0,COMPLETED,GenerationStep_0,100.0,0.3528,0.2810,0.0711,5,57,12,25.0,s1,s3
16,16,16_0,COMPLETED,GenerationStep_0,84.0,0.2063,0.3073,0.0373,0,49,35,25.0,s8,s5
17,17,17_0,COMPLETED,GenerationStep_0,100.0,0.4045,0.4196,0.0728,2,15,22,25.0,s2,s5
18,18,18_0,COMPLETED,GenerationStep_0,100.0,0.2962,0.4364,0.0493,1,24,5,25.0,s2,s2
19,19,19_0,COMPLETED,GenerationStep_0,100.0,0.3528,0.2810,0.0711,5,10,54,25.0,s3,s7
20,20,20_0,COMPLETED,GenerationStep_0,100.0,0.2063,0.3073,0.0373,0,54,17,25.0,s1,s5
21,21,21_0,COMPLETED,GenerationStep_0,100.0,0.4045,0.4196,0.0728,2,40,43,25.0,s6,s4
22,22,22_0,COMPLETED,GenerationStep_0,100.0,0.2962,0.4364,0.0493,1,30,2,25.0,s3,s8
23,23,23_0,COMPLETED,GenerationStep_0,100.0,0.3528,0.2810,0.0711,5,63,25,25.0,s1,s5
24,24,24_0,COMPLETED,GenerationStep_0,49.0,0.2063,0.3073,0.0373,0,9,40,25.0,s7,s4
25,25,25_0,COMPLETED,GenerationStep_0,100.0,0.4045,0.4196,0.0728,2,41,50,25.0,s6,s3
26,26,26_0,COMPLETED,GenerationStep_0,100.0,0.2962,0.4364,0.0493,1,5,32,25.0,s6,s3
27,27,27_0,COMPLETED,GenerationStep_0,97.0,0.3528,0.2810,0.0711,5,89,8,25.0,s8,s1
28,28,28_0,COMPLETED,GenerationStep_0,54.0,0.2063,0.3073,0.0373,0,34,20,25.0,s2,s7
29,29,29_0,COMPLETED,GenerationStep_0,100.0,0.4045,0.4196,0.0728,2,72,15,25.0,s8,s2
30,30,30_0,COMPLETED,GenerationStep_0,67.0,0.2962,0.4364,0.0493,1,14,53,25.0,s6,s1
31,31,31_0,COMPLETED,GenerationStep_0,74.0,0.3528,0.2810,0.0711,5,36,38,25.0,s7,s7
32,32,32_0,COMPLETED,GenerationStep_1,100.0,0.2063,0.3073,0.0373,0,27,1,25.0,s3,s6
33,33,33_0,COMPLETED,GenerationStep_1,100.0,0.4045,0.4196,0.0728,2,10,16,25.0,s4,s8
34,34,34_0,COMPLETED,GenerationStep_1,100.0,0.2962,0.4364,0.0493,1,26,2,25.0,s8,s2
35,35,35_0,COMPLETED,GenerationStep_1,100.0,0.3528,0.2810,0.0711,5,12,17,25.0,s4,s8
36,36,36_0,COMPLETED,GenerationStep_1,100.0,0.2063,0.3073,0.0373,0,30,0,25.0,s7,s6
37,37,37_0,COMPLETED,GenerationStep_1,100.0,0.4045,0.4196,0.0728,2,10,15,25.0,s4,s8
38,38,38_0,COMPLETED,GenerationStep_1,100.0,0.2962,0.4364,0.0493,1,36,0,25.0,s8,s2
39,39,39_0,COMPLETED,GenerationStep_1,100.0,0.3528,0.2810,0.0711,5,10,15,25.0,s4,s8
40,40,40_0,RUNNING,GenerationStep_1,NaN,0.2063,0.3073,0.0373,0,14,16,25.0,s7,s4
41,41,41_0,RUNNING,GenerationStep_1,NaN,0.4045,0.4196,0.0728,2,17,10,25.0,s7,s8
42,42,42_0,RUNNING,GenerationStep_1,NaN,0.2962,0.4364,0.0493,1,9,42,25.0,s4,s4
43,43,43_0,RUNNING,GenerationStep_1,NaN,0.3528,0.2810,0.0711,5,8,49,25.0,s7,s4
44,44,44_0,RUNNING,GenerationStep_1,NaN,0.2063,0.3073,0.0373,0,12,21,25.0,s4,s4
45,45,45_0,RUNNING,GenerationStep_1,NaN,0.4045,0.4196,0.0728,2,5,23,25.0,s4,s4
46,46,46_0,RUNNING,GenerationStep_1,NaN,0.2962,0.4364,0.0493,1,26,4,25.0,s2,s5
47,47,47_0,RUNNING,GenerationStep_1,NaN,0.3528,0.2810,0.0711,5,6,12,25.0,s6,s1

In [5]:
df_design, df_vol = hf.design_to_vol (n)
df_design['constraint'] = df_design['drug_name'].map(best_concs).fillna(0.0)
df_design

,trial_index,drug_name,Drug_MW,Drug_LogP,Drug_TPSA,drugs,surf_1_conc,surf_2_conc,drug_conc,surf_1,surf_2,surf_conc,obj_surf_conc,constraint
0,40,IBP,0.2063,0.3073,0.0373,0,14,16,25.0,s7,s4,30,NaN,35.0
1,41,LOV,0.4045,0.4196,0.0728,2,17,10,25.0,s7,s8,27,NaN,30.0
2,42,DCF,0.2962,0.4364,0.0493,1,9,42,25.0,s4,s4,51,NaN,62.0
3,43,GLV,0.3528,0.2810,0.0711,5,8,49,25.0,s7,s4,57,NaN,74.0
4,44,IBP,0.2063,0.3073,0.0373,0,12,21,25.0,s4,s4,33,NaN,35.0
5,45,LOV,0.4045,0.4196,0.0728,2,5,23,25.0,s4,s4,28,NaN,30.0
6,46,DCF,0.2962,0.4364,0.0493,1,26,4,25.0,s2,s5,30,NaN,62.0
7,47,GLV,0.3528,0.2810,0.0711,5,6,12,25.0,s6,s1,18,NaN,74.0

In [6]:
df_vol

,trial_index,drug_name,drug,s1,s2,s3,s4,s5,s6,s7,s8,dmso,water,IBP,LOV,DCF,GLV
0,40,IBP,180.0,0.0,0.0,0.0,192.0,0.0,0.0,168.0,0.0,0.0,840.0,180.0,0.0,0.0,0.0
1,41,LOV,180.0,0.0,0.0,0.0,0.0,0.0,0.0,204.0,120.0,0.0,876.0,0.0,180.0,0.0,0.0
2,42,DCF,180.0,0.0,0.0,0.0,612.0,0.0,0.0,0.0,0.0,0.0,588.0,0.0,0.0,180.0,0.0
3,43,GLV,180.0,0.0,0.0,0.0,588.0,0.0,0.0,96.0,0.0,0.0,516.0,0.0,0.0,0.0,180.0
4,44,IBP,180.0,0.0,0.0,0.0,396.0,0.0,0.0,0.0,0.0,0.0,804.0,180.0,0.0,0.0,0.0
5,45,LOV,180.0,0.0,0.0,0.0,336.0,0.0,0.0,0.0,0.0,0.0,864.0,0.0,180.0,0.0,0.0
6,46,DCF,180.0,0.0,312.0,0.0,0.0,48.0,0.0,0.0,0.0,0.0,840.0,0.0,0.0,180.0,0.0
7,47,GLV,180.0,144.0,0.0,0.0,0.0,0.0,72.0,0.0,0.0,0.0,984.0,0.0,0.0,0.0,180.0

In [7]:
df_vol[['s1', 's2', 's3', 's4', 's5', 's6', 's7', 's8']].sum()

s1     144.0
s2     312.0
s3       0.0
s4    2124.0
s5      48.0
s6      72.0
s7     468.0
s8     120.0
dtype: float64

In [8]:
plate_well = input("Enter the plate well starting well (e.g., F1): ")
deepplate_well = input("Enter the deep plate well starting well (e.g., F1): ")


print("Please confirm the following information:")
print("Wellplate will start at: " + plate_well)
print("Deep plate will start at: " + deepplate_well)

print()
print("*******************************************************")
print("Continue if correct, or rerun this cell if incorrect.")
print("*******************************************************")

Please confirm the following information:
Wellplate will start at: A1
Deep plate will start at: A!

*******************************************************
Continue if correct, or rerun this cell if incorrect.
*******************************************************

In [9]:
hf.generate_protocol(df_vol=df_vol, iteration=n, plate_well=plate_well, deepplate_well=deepplate_well)

Successfully wrote to: protocol/otflex_2.py

In [10]:
df_absorbance = hf.process_absorbance(iteration=n, threshold=0.06)
df_absorbance

   trial_index  success
0            0        0
1            1        0
2            2        0
3            3        0
4            4        0
5            5        0
6            6        1
7            7        1

In [11]:
results = hf.build_results(n, df_absorbance)
results

,trial_index,drug_name,Drug_MW,Drug_LogP,Drug_TPSA,drugs,surf_1_conc,surf_2_conc,drug_conc,surf_1,surf_2,surf_conc,obj_surf_conc,success
0,40,IBP,0.2063,0.3073,0.0373,0,14,16,25.0,s7,s4,30,100,0
1,41,LOV,0.4045,0.4196,0.0728,2,17,10,25.0,s7,s8,27,100,0
2,42,DCF,0.2962,0.4364,0.0493,1,9,42,25.0,s4,s4,51,100,0
3,43,GLV,0.3528,0.2810,0.0711,5,8,49,25.0,s7,s4,57,100,0
4,44,IBP,0.2063,0.3073,0.0373,0,12,21,25.0,s4,s4,33,100,0
5,45,LOV,0.4045,0.4196,0.0728,2,5,23,25.0,s4,s4,28,100,0
6,46,DCF,0.2962,0.4364,0.0493,1,26,4,25.0,s2,s5,30,30,1
7,47,GLV,0.3528,0.2810,0.0711,5,6,12,25.0,s6,s1,18,18,1

# load the results to the optimizer

In [13]:
ax_client = hf.load_data_to_optimizer(iteration = n, results = results)
ax_client

[INFO 08-20 14:50:41] ax.service.ax_client: Completed trial 40 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 08-20 14:50:41] ax.service.ax_client: Completed trial 41 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 08-20 14:50:41] ax.service.ax_client: Completed trial 42 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 08-20 14:50:41] ax.service.ax_client: Completed trial 43 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 08-20 14:50:41] ax.service.ax_client: Completed trial 44 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 08-20 14:50:41] ax.service.ax_client: Completed trial 45 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 08-20 14:50:41] ax.service.ax_client: Completed trial 46 with data: {'obj_surf_conc': (30.0, None)}.
[INFO 08-20 14:50:41] ax.service.ax_client: Completed trial 47 with data: {'obj_surf_conc': (18.0, None)}.

AxClient(experiment=Experiment(drug_surfactant))