# import libraries

In [1]:
import pandas as pd
from ax.service.ax_client import AxClient, ObjectiveProperties
import matplotlib.pyplot as plt
from ax.modelbridge.registry import Models
from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy   
import time

import sys
sys.path.append('../')
import helper_functions as hf

/var/folders/9p/f66yhymx35939zzlg51g0rrc0000gn/T/ipykernel_80322/1711932296.py:5: DeprecationWarning: Please import from 'ax.generation_strategy.generation_strategy' instead of 'ax.modelbridge.generation_strategy'. The latter is deprecated and will be removed in a future release.
  from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy

# initialize the optimizer

In [2]:
ax_client_init_file_name = 'optimizer/optimizer_00.json'
ax_client = hf.optimizer_init()
ax_client

[INFO 07-16 09:57:18] ax.service.utils.instantiation: Inferred value type of ParameterType.STRING for parameter surf_1. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/service/utils/instantiation.py:258: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "surf_1". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return ChoiceParameter(
[INFO 07-16 09:57:18] ax.service.utils.instantiation: Inferred value type of ParameterType.STRING for parameter surf_2. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/service/utils/instantiation.py:258: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "surf_2". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return ChoiceParameter(
[INFO 07-16 09:57:18] ax.service.utils.instantiation: Inferred value type of ParameterType.STRING for parameter surf_3. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/service/utils/instantiation.py:258: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "surf_3". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return ChoiceParameter(

AxClient(experiment=Experiment(drug_surfactant))

In [3]:
ax_client.save_to_json_file(ax_client_init_file_name)

# generate recommendations

In [4]:
n = hf.get_iteration_number()

for i in range(3):
    print("Very Important: Please Confirm the Iteration Number is Iteration " + str(n))

print()

list_of_drugs = ['IBP'] * 2 + ['LOV'] * 2 + ['DCF'] * 2 + ['GLV'] * 2

for i in range(3):
    print("Very Important: Please Confirm the Drugs are: ", list_of_drugs)

Very Important: Please Confirm the Iteration Number is Iteration 0
Very Important: Please Confirm the Iteration Number is Iteration 0
Very Important: Please Confirm the Iteration Number is Iteration 0

Very Important: Please Confirm the Drugs are:  ['IBP', 'IBP', 'LOV', 'LOV', 'DCF', 'DCF', 'GLV', 'GLV']
Very Important: Please Confirm the Drugs are:  ['IBP', 'IBP', 'LOV', 'LOV', 'DCF', 'DCF', 'GLV', 'GLV']
Very Important: Please Confirm the Drugs are:  ['IBP', 'IBP', 'LOV', 'LOV', 'DCF', 'DCF', 'GLV', 'GLV']

In [5]:
time_start = time.time()



df_design, ax_client = hf.run_optimizer(current_iteration=n, drug_list= list_of_drugs, bopt=0)

time_end = time.time()
time_duration = round((time_end - time_start)/60,2)

print("Time taken for optimization: " + str(time_duration) + " mins")
print("Time taken for optimization: " + str(time_duration * 60) + " seconds")

[INFO 07-16 09:57:40] ax.service.ax_client: Generated new trial 0 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 6.342538, 'surf_2_conc': 19.792553, 'surf_3_conc': 10.062115, 'drug_conc': 25.0, 'surf_1': 's8', 'surf_2': 's6', 'surf_3': 's7'} using model Sobol.
[INFO 07-16 09:57:40] ax.service.ax_client: Generated new trial 1 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 25.388954, 'surf_2_conc': 2.403562, 'surf_3_conc': 19.870581, 'drug_conc': 25.0, 'surf_1': 's3', 'surf_2': 's2', 'surf_3': 's6'} using model Sobol.
[INFO 07-16 09:57:40] ax.service.ax_client: Generated new trial 2 with parameters {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 0.561928, 'surf_2_conc': 27.771701, 'surf_3_conc': 0.445989, 'drug_conc': 25.0, 'surf_1': 's5', 'surf_2': 's7', 'surf_3': 's3'} using model Sobol.
[INFO 07-16 09:57:40] ax.service.ax_client: Generated new trial 3 with parameters {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 14.076332, 'surf_2_conc': 3.422734, 'surf_3_conc': 7.078612, 'drug_conc': 25.0, 'surf_1': 's3', 'surf_2': 's3', 'surf_3': 's8'} using model Sobol.
[INFO 07-16 09:57:40] ax.service.ax_client: Generated new trial 4 with parameters {'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 13.456925, 'surf_2_conc': 31.46619, 'surf_3_conc': 1.570027, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's4', 'surf_3': 's5'} using model Sobol.
[INFO 07-16 09:57:40] ax.service.ax_client: Generated new trial 5 with parameters {'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 20.019197, 'surf_2_conc': 14.54911, 'surf_3_conc': 11.283737, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's8', 'surf_3': 's7'} using model Sobol.
[INFO 07-16 09:57:40] ax.service.ax_client: Generated new trial 6 with parameters {'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 2.750314, 'surf_2_conc': 12.241791, 'surf_3_conc': 9.081532, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's1', 'surf_3': 's6'} using model Sobol.
[INFO 07-16 09:57:40] ax.service.ax_client: Generated new trial 7 with parameters {'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 5.021025, 'surf_2_conc': 0.862688, 'surf_3_conc': 17.897261, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'} using model Sobol.

**************************************************************************************************** 1  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Ibuprofen IBP  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************
**************************************************************************************************** 2  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Ibuprofen IBP  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************
**************************************************************************************************** 3  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Lovastatin LOV  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************
**************************************************************************************************** 4  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Lovastatin LOV  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************
**************************************************************************************************** 5  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Diclofenac DCF  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************
**************************************************************************************************** 6  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Diclofenac DCF  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************
**************************************************************************************************** 7  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Griseofulvin GLV  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************
**************************************************************************************************** 8  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Generating a random trial for
Drug name:  Griseofulvin GLV  | Iteration:  0

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************
Time taken for optimization: 0.0 mins
Time taken for optimization: 0.0 seconds

# process results

In [6]:
ax_client = hf.load_design_optimizer(n)
ax_client.experiment.trials

{0: Trial(experiment_name='drug_surfactant', index=0, status=TrialStatus.RUNNING, arm=Arm(name='0_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 6.342537747696042, 'surf_2_conc': 19.79255275800824, 'surf_3_conc': 10.062114521861076, 'drug_conc': 25.0, 'surf_1': 's8', 'surf_2': 's6', 'surf_3': 's7'})),
 1: Trial(experiment_name='drug_surfactant', index=1, status=TrialStatus.RUNNING, arm=Arm(name='1_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 25.38895425386727, 'surf_2_conc': 2.403562143445015, 'surf_3_conc': 19.870580919086933, 'drug_conc': 25.0, 'surf_1': 's3', 'surf_2': 's2', 'surf_3': 's6'})),
 2: Trial(experiment_name='drug_surfactant', index=2, status=TrialStatus.RUNNING, arm=Arm(name='2_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 0.5619284231215715, 'surf_2_conc': 27.77170091867447, 'surf_3_conc': 0.44598919339478016, 'drug_conc': 25.0, 'surf_1': 's5', 'surf_2': 's7', 'surf_3': 's3'})),
 3: Trial(experiment_name='drug_surfactant', index=3, status=TrialStatus.RUNNING, arm=Arm(name='3_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 14.076332002878189, 'surf_2_conc': 3.4227336291223764, 'surf_3_conc': 7.078612456098199, 'drug_conc': 25.0, 'surf_1': 's3', 'surf_2': 's3', 'surf_3': 's8'})),
 4: Trial(experiment_name='drug_surfactant', index=4, status=TrialStatus.RUNNING, arm=Arm(name='4_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 13.45692495815456, 'surf_2_conc': 31.46618972532451, 'surf_3_conc': 1.5700268559157848, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's4', 'surf_3': 's5'})),
 5: Trial(experiment_name='drug_surfactant', index=5, status=TrialStatus.RUNNING, arm=Arm(name='5_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 20.0191970448941, 'surf_2_conc': 14.549109572544694, 'surf_3_conc': 11.283737001940608, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's8', 'surf_3': 's7'})),
 6: Trial(experiment_name='drug_surfactant', index=6, status=TrialStatus.RUNNING, arm=Arm(name='6_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 2.750313561409712, 'surf_2_conc': 12.241790909320116, 'surf_3_conc': 9.081532154232264, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's1', 'surf_3': 's6'})),
 7: Trial(experiment_name='drug_surfactant', index=7, status=TrialStatus.RUNNING, arm=Arm(name='7_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 5.021025240421295, 'surf_2_conc': 0.8626881986856461, 'surf_3_conc': 17.897260980680585, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's5', 'surf_3': 's1'}))}

In [7]:
df_design, df_vol = hf.design_to_vol (n)
df_design

,trial_index,drug_name,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,surf_3_conc,drug_conc,surf_1,surf_2,surf_3,surf_conc,obj_surf_conc
0,0,IBP,0.2063,0.3073,0.0373,6.342538,19.792553,10.062115,25.0,s8,s6,s7,36.197205,NaN
1,1,IBP,0.2063,0.3073,0.0373,25.388954,2.403562,19.870581,25.0,s3,s2,s6,47.663097,NaN
2,2,LOV,0.4045,0.4196,0.0728,0.561928,27.771701,0.445989,25.0,s5,s7,s3,28.779619,NaN
3,3,LOV,0.4045,0.4196,0.0728,14.076332,3.422734,7.078612,25.0,s3,s3,s8,24.577678,NaN
4,4,DCF,0.2962,0.4364,0.0493,13.456925,31.466190,1.570027,25.0,s1,s4,s5,46.493142,NaN
5,5,DCF,0.2962,0.4364,0.0493,20.019197,14.549110,11.283737,25.0,s6,s8,s7,45.852044,NaN
6,6,GLV,0.3528,0.2810,0.0711,2.750314,12.241791,9.081532,25.0,s1,s1,s6,24.073637,NaN
7,7,GLV,0.3528,0.2810,0.0711,5.021025,0.862688,17.897261,25.0,s6,s5,s1,23.780974,NaN

In [8]:
df_vol

,trial_index,drug_name,drug,s1,s2,s3,s4,s5,s6,s7,s8,dmso,water,IBP,LOV,DCF,GLV
0,0,IBP,180.0,0.000000,0.000000,0.000000,0.000000,0.000000,475.021266,241.490749,152.220906,0.0,331.267079,180.0,0.0,0.0,0.0
1,1,IBP,180.0,0.000000,57.685491,609.334902,0.000000,0.000000,476.893942,0.000000,0.000000,0.0,56.085664,180.0,0.0,0.0,0.0
2,2,LOV,180.0,0.000000,0.000000,10.703741,0.000000,13.486282,0.000000,666.520822,0.000000,0.0,509.289155,0.0,180.0,0.0,0.0
3,3,LOV,180.0,0.000000,0.000000,419.977575,0.000000,0.000000,0.000000,0.000000,169.886699,0.0,610.135726,0.0,180.0,0.0,0.0
4,4,DCF,180.0,322.966199,0.000000,0.000000,755.188553,37.680645,0.000000,0.000000,0.000000,0.0,84.164603,0.0,0.0,180.0,0.0
5,5,DCF,180.0,0.000000,0.000000,0.000000,0.000000,0.000000,480.460729,270.809688,349.178630,0.0,99.550953,0.0,0.0,180.0,0.0
6,6,GLV,180.0,359.810507,0.000000,0.000000,0.000000,0.000000,217.956772,0.000000,0.000000,0.0,622.232721,0.0,0.0,0.0,180.0
7,7,GLV,180.0,429.534264,0.000000,0.000000,0.000000,20.704517,120.504606,0.000000,0.000000,0.0,629.256614,0.0,0.0,0.0,180.0

In [9]:
plate_well = input("Enter the plate well starting well (e.g., F1): ")
deepplate_well = input("Enter the deep plate well starting well (e.g., F1): ")



print("Please confirm the following information:")
print("Wellplate will start at: " + plate_well)
print("Deep plate will start at: " + deepplate_well)



print()
print("*******************************************************")
print("Continue if correct, or rerun this cell if incorrect.")
print("*******************************************************")

Please confirm the following information:
Wellplate will start at: A1
Deep plate will start at: G9

*******************************************************
Continue if correct, or rerun this cell if incorrect.
*******************************************************

In [10]:
hf.generate_protocol(df_vol=df_vol, iteration=n, plate_well=plate_well, deepplate_well=deepplate_well)

✅ Successfully wrote to: protocol/otflex_0.py

In [11]:
df_absorbance = hf.process_absorbance(iteration=n, threshold=0.1)
df_absorbance

   trial_index  success
0            0        0
1            1        1
2            2        1
3            3        1
4            4        0
5            5        0
6            6        1
7            7        1

In [12]:
results = hf.build_results(n, df_absorbance)
results

,trial_index,drug_name,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,surf_3_conc,drug_conc,surf_1,surf_2,surf_3,surf_conc,obj_surf_conc,success
0,0,IBP,0.2063,0.3073,0.0373,6.342538,19.792553,10.062115,25.0,s8,s6,s7,36.197205,50.000000,0
1,1,IBP,0.2063,0.3073,0.0373,25.388954,2.403562,19.870581,25.0,s3,s2,s6,47.663097,47.663097,1
2,2,LOV,0.4045,0.4196,0.0728,0.561928,27.771701,0.445989,25.0,s5,s7,s3,28.779619,28.779619,1
3,3,LOV,0.4045,0.4196,0.0728,14.076332,3.422734,7.078612,25.0,s3,s3,s8,24.577678,24.577678,1
4,4,DCF,0.2962,0.4364,0.0493,13.456925,31.466190,1.570027,25.0,s1,s4,s5,46.493142,50.000000,0
5,5,DCF,0.2962,0.4364,0.0493,20.019197,14.549110,11.283737,25.0,s6,s8,s7,45.852044,50.000000,0
6,6,GLV,0.3528,0.2810,0.0711,2.750314,12.241791,9.081532,25.0,s1,s1,s6,24.073637,24.073637,1
7,7,GLV,0.3528,0.2810,0.0711,5.021025,0.862688,17.897261,25.0,s6,s5,s1,23.780974,23.780974,1

# load the results to the optimizer

In [13]:
ax_client = hf.load_data_to_optimizer(iteration = n, results = results)
ax_client

[INFO 07-16 11:51:37] ax.service.ax_client: Completed trial 0 with data: {'obj_surf_conc': (50.0, None)}.
[INFO 07-16 11:51:37] ax.service.ax_client: Completed trial 1 with data: {'obj_surf_conc': (47.663097, None)}.
[INFO 07-16 11:51:37] ax.service.ax_client: Completed trial 2 with data: {'obj_surf_conc': (28.779619, None)}.
[INFO 07-16 11:51:37] ax.service.ax_client: Completed trial 3 with data: {'obj_surf_conc': (24.577678, None)}.
[INFO 07-16 11:51:37] ax.service.ax_client: Completed trial 4 with data: {'obj_surf_conc': (50.0, None)}.
[INFO 07-16 11:51:37] ax.service.ax_client: Completed trial 5 with data: {'obj_surf_conc': (50.0, None)}.
[INFO 07-16 11:51:37] ax.service.ax_client: Completed trial 6 with data: {'obj_surf_conc': (24.073637, None)}.
[INFO 07-16 11:51:37] ax.service.ax_client: Completed trial 7 with data: {'obj_surf_conc': (23.780974, None)}.

AxClient(experiment=Experiment(drug_surfactant))