# import libraries

In [1]:
import pandas as pd
from ax.service.ax_client import AxClient, ObjectiveProperties
import matplotlib.pyplot as plt
from ax.modelbridge.registry import Models
from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy   
import time

import sys
sys.path.append('../')
import helper_functions as hf

/var/folders/hk/7jjnrbrj53n1t8_bmkhf0_k00000gn/T/ipykernel_4317/1711932296.py:5: DeprecationWarning: Please import from 'ax.generation_strategy.generation_strategy' instead of 'ax.modelbridge.generation_strategy'. The latter is deprecated and will be removed in a future release.
  from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy

# initialize the optimizer

In [2]:
ax_client_init_file_name = 'optimizer/optimizer_00.json'
ax_client = hf.optimizer_init()
ax_client

AxClient(experiment=Experiment(drug_surfactant))

In [3]:
ax_client.save_to_json_file(ax_client_init_file_name)

# generate recommendations

In [4]:
n = hf.get_iteration_number()

for i in range(3):
    print("Very Important: Please Confirm the Iteration Number is Iteration " + str(n))

Very Important: Please Confirm the Iteration Number is Iteration 0
Very Important: Please Confirm the Iteration Number is Iteration 0
Very Important: Please Confirm the Iteration Number is Iteration 0

In [5]:
time_start = time.time()

df_design, ax_client = hf.run_optimizer(current_iteration=n, n_trials=3, drug="IBP", bopt=0)

time_end = time.time()
time_duration = round((time_end - time_start)/60,2)

print("Time taken for optimization: " + str(time_duration) + " mins")
print("Time taken for optimization: " + str(time_duration * 60) + " seconds")

[INFO 06-27 10:50:11] ax.service.ax_client: Generated new trial 0 with parameters {'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 47, 's2': 59, 's3': 50, 's4': 31, 's5': 96, 's6': 8, 's7': 10, 's8': 35, 'surfactant_conc': 85, 'drug_conc': 100} using model Sobol.
[INFO 06-27 10:50:11] ax.service.ax_client: Generated new trial 1 with parameters {'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 74, 's2': 0, 's3': 89, 's4': 66, 's5': 22, 's6': 52, 's7': 57, 's8': 79, 'surfactant_conc': 35, 'drug_conc': 100} using model Sobol.
[INFO 06-27 10:50:11] ax.service.ax_client: Generated new trial 2 with parameters {'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 78, 's2': 88, 's3': 1, 's4': 3, 's5': 32, 's6': 94, 's7': 44, 's8': 58, 'surfactant_conc': 1, 'drug_conc': 100} using model Sobol.

**************************************************************************************************************

Generating random trials for
Drug name:  Ibuprofen IBP  | Iteration:  0

**************************************************************************************************************
Time taken for optimization: 0.0 mins
Time taken for optimization: 0.0 seconds

# process results

In [6]:
ax_client = hf.load_design_optimizer(n)
ax_client.experiment.trials

{0: Trial(experiment_name='drug_surfactant', index=0, status=TrialStatus.RUNNING, arm=Arm(name='0_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 47, 's2': 59, 's3': 50, 's4': 31, 's5': 96, 's6': 8, 's7': 10, 's8': 35, 'surfactant_conc': 85, 'drug_conc': 100})),
 1: Trial(experiment_name='drug_surfactant', index=1, status=TrialStatus.RUNNING, arm=Arm(name='1_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 74, 's2': 0, 's3': 89, 's4': 66, 's5': 22, 's6': 52, 's7': 57, 's8': 79, 'surfactant_conc': 35, 'drug_conc': 100})),
 2: Trial(experiment_name='drug_surfactant', index=2, status=TrialStatus.RUNNING, arm=Arm(name='2_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 78, 's2': 88, 's3': 1, 's4': 3, 's5': 32, 's6': 94, 's7': 44, 's8': 58, 'surfactant_conc': 1, 'drug_conc': 100}))}

In [7]:
df_conc, df_vol = hf.design_to_conc_to_vol (n)

In [9]:
plate_well = input("Enter the plate well starting well (e.g., F1): ")
deepplate_well = input("Enter the deep plate well starting well (e.g., F1): ")


print("Please confirm the following information:")
print("Wellplate will start at: " + plate_well)
print("Deep plate will start at: " + deepplate_well)

print()
print("*******************************************************")
print("Continue if correct, or rerun this cell if incorrect.")
print("*******************************************************")

Please confirm the following information:
Wellplate will start at:
Deep plate will start at:

*******************************************************
Continue if correct, or rerun this cell if incorrect.
*******************************************************

In [10]:

hf.generate_protocol(df_vol=df_vol, iteration=n, plate_well=plate_well, deepplate_well=deepplate_well)

✅ Successfully wrote to: protocol/otflex_0.py

In [8]:
df_absorbance = hf.process_absorbance(iteration=n)
df_absorbance

   trial_index  success
0            0        0
1            1        0
2            2        0

In [9]:
df_conc

,trial_index,surfactant_conc,drug_conc,s1,s2,s3,s4,s5,s6,s7,s8
0,0,4.25,25.0,0.594494,0.746280,0.632440,0.392113,1.214286,0.101190,0.126488,0.442708
1,1,1.75,25.0,0.294989,0.000000,0.354784,0.263098,0.087699,0.207289,0.227221,0.314920
2,2,0.05,25.0,0.009799,0.011055,0.000126,0.000377,0.004020,0.011809,0.005528,0.007286

In [10]:
results = hf.build_results(n, df_conc, df_absorbance)

In [11]:
results

,trial_index,s1,s2,s3,s4,s5,s6,s7,s8,surfactant_input,drug_conc,success,complexity
0,0,47,59,50,31,96,8,10,35,4.25,25.0,0,8
1,1,74,0,89,66,22,52,57,79,1.75,25.0,0,7
2,2,78,88,1,3,32,94,44,58,0.05,25.0,0,8

In [12]:
norm_results = hf.normalize_data(results, 'normalize')

In [13]:
norm_results

,trial_index,s1,s2,s3,s4,s5,s6,s7,s8,surfactant_input,drug_conc,success,complexity
0,0,47,59,50,31,96,8,10,35,0.85,1.0,0.0,1.000
1,1,74,0,89,66,22,52,57,79,0.35,1.0,0.0,0.875
2,2,78,88,1,3,32,94,44,58,0.01,1.0,0.0,1.000

# load the results to the optimizer

In [14]:
ax_client = hf.load_data_to_optimizer(iteration = n, norm_results = norm_results)
ax_client

[INFO 06-27 10:50:27] ax.service.ax_client: Completed trial 0 with data: {'success': (0.0, None), 'surfactant_input': (1.0, None), 'complexity': (1.0, None)}.
[INFO 06-27 10:50:27] ax.service.ax_client: Completed trial 1 with data: {'success': (0.0, None), 'surfactant_input': (1.0, None), 'complexity': (1.0, None)}.
[INFO 06-27 10:50:27] ax.service.ax_client: Completed trial 2 with data: {'success': (0.0, None), 'surfactant_input': (1.0, None), 'complexity': (1.0, None)}.

Trial 0: success=0 → overriding surfactant_input & complexity to 1
Trial 1: success=0 → overriding surfactant_input & complexity to 1
Trial 2: success=0 → overriding surfactant_input & complexity to 1

AxClient(experiment=Experiment(drug_surfactant))