# import libraries

In [5]:
import pandas as pd
from ax.service.ax_client import AxClient, ObjectiveProperties
import matplotlib.pyplot as plt
from ax.modelbridge.factory import Models
from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy   
import time
import torch

import sys
sys.path.append('../')
import helper_functions as hf

# initialize the optimizer

In [6]:
ax_client_init_file_name = 'optimizer/optimizer_00.json'
ax_client = hf.optimizer_init()
ax_client

[INFO 06-23 16:40:41] ax.service.ax_client: Starting optimization with verbose logging. To disable logging, set the `verbose_logging` argument to `False`. Note that float values in the logs are rounded to 6 decimal points.
[INFO 06-23 16:40:41] ax.service.utils.instantiation: Created search space: SearchSpace(parameters=[RangeParameter(name='Drug_MW', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_LogP', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='Drug_TPSA', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='s1', parameter_type=INT, range=[0, 100]), RangeParameter(name='s2', parameter_type=INT, range=[0, 100]), RangeParameter(name='s3', parameter_type=INT, range=[0, 100]), RangeParameter(name='s4', parameter_type=INT, range=[0, 100]), RangeParameter(name='s5', parameter_type=INT, range=[0, 100]), RangeParameter(name='s6', parameter_type=INT, range=[0, 100]), RangeParameter(name='s7', parameter_type=INT, range=[0, 100]), RangeParameter(name='s8', parameter_type=INT, range=[0, 100]), RangeParameter(name='surfactant_conc', parameter_type=INT, range=[1, 100]), RangeParameter(name='drug_conc', parameter_type=INT, range=[1, 100])], parameter_constraints=[ParameterConstraint(-1.0*s1 + -1.0*s2 + -1.0*s3 + -1.0*s4 + -1.0*s5 + -1.0*s6 + -1.0*s7 + -1.0*s8 <= -1.0)]).

AxClient(experiment=Experiment(drug_surfactant))

In [7]:
ax_client.save_to_json_file(ax_client_init_file_name)

[INFO 06-23 16:40:44] ax.service.ax_client: Saved JSON-serialized state of optimization to `optimizer/optimizer_00.json`.

# generate recommendations

In [8]:
n = hf.get_iteration_number()

for i in range(3):
    print("Very Important: Please Confirm the Iteration Number is Iteration " + str(n))

Very Important: Please Confirm the Iteration Number is Iteration 0
Very Important: Please Confirm the Iteration Number is Iteration 0
Very Important: Please Confirm the Iteration Number is Iteration 0

In [9]:
time_start = time.time()

df_design, ax_client = hf.run_optimizer(current_iteration=n, n_trials=6, drug="IBP", bopt=0)

time_end = time.time()
time_duration = round((time_end - time_start)/60,2)

print("Time taken for optimization: " + str(time_duration) + " mins")
print("Time taken for optimization: " + str(time_duration * 60) + " seconds")

[INFO 06-23 16:40:48] ax.service.ax_client: Starting optimization with verbose logging. To disable logging, set the `verbose_logging` argument to `False`. Note that float values in the logs are rounded to 6 decimal points.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 06-23 16:40:48] ax.service.ax_client: Generated new trial 0 with parameters {'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 47, 's2': 59, 's3': 49, 's4': 31, 's5': 96, 's6': 8, 's7': 10, 's8': 35, 'surfactant_conc': 86, 'drug_conc': 77} using model Sobol.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 06-23 16:40:48] ax.service.ax_client: Generated new trial 1 with parameters {'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 94, 's2': 22, 's3': 76, 's4': 63, 's5': 42, 's6': 72, 's7': 55, 's8': 99, 'surfactant_conc': 35, 'drug_conc': 3} using model Sobol.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 06-23 16:40:48] ax.service.ax_client: Generated new trial 2 with parameters {'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 53, 's2': 99, 's3': 4, 's4': 13, 's5': 22, 's6': 89, 's7': 28, 's8': 56, 'surfactant_conc': 18, 'drug_conc': 33} using model Sobol.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 06-23 16:40:48] ax.service.ax_client: Generated new trial 3 with parameters {'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 6, 's2': 34, 's3': 70, 's4': 82, 's5': 63, 's6': 25, 's7': 87, 's8': 16, 'surfactant_conc': 68, 'drug_conc': 59} using model Sobol.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 06-23 16:40:48] ax.service.ax_client: Generated new trial 4 with parameters {'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 24, 's2': 87, 's3': 96, 's4': 99, 's5': 59, 's6': 17, 's7': 48, 's8': 64, 'surfactant_conc': 1, 'drug_conc': 24} using model Sobol.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 06-23 16:40:48] ax.service.ax_client: Generated new trial 5 with parameters {'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 72, 's2': 46, 's3': 29, 's4': 4, 's5': 5, 's6': 54, 's7': 93, 's8': 3, 'surfactant_conc': 51, 'drug_conc': 99} using model Sobol.
[INFO 06-23 16:40:48] ax.service.ax_client: Saved JSON-serialized state of optimization to `optimizer/optimizer_0.json`.

**************************************************************************************************************

Generating random trials for
Drug name:  Ibuprofen IBP  | Iteration:  0

**************************************************************************************************************
Time taken for optimization: 0.0 mins
Time taken for optimization: 0.0 seconds

# process results

In [10]:
ax_client = hf.load_design_optimizer(n)
ax_client.experiment.trials

[INFO 06-23 16:40:53] ax.service.ax_client: Starting optimization with verbose logging. To disable logging, set the `verbose_logging` argument to `False`. Note that float values in the logs are rounded to 6 decimal points.

{0: Trial(experiment_name='drug_surfactant', index=0, status=TrialStatus.RUNNING, arm=Arm(name='0_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 47, 's2': 59, 's3': 49, 's4': 31, 's5': 96, 's6': 8, 's7': 10, 's8': 35, 'surfactant_conc': 86, 'drug_conc': 77})),
 1: Trial(experiment_name='drug_surfactant', index=1, status=TrialStatus.RUNNING, arm=Arm(name='1_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 94, 's2': 22, 's3': 76, 's4': 63, 's5': 42, 's6': 72, 's7': 55, 's8': 99, 'surfactant_conc': 35, 'drug_conc': 3})),
 2: Trial(experiment_name='drug_surfactant', index=2, status=TrialStatus.RUNNING, arm=Arm(name='2_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 53, 's2': 99, 's3': 4, 's4': 13, 's5': 22, 's6': 89, 's7': 28, 's8': 56, 'surfactant_conc': 18, 'drug_conc': 33})),
 3: Trial(experiment_name='drug_surfactant', index=3, status=TrialStatus.RUNNING, arm=Arm(name='3_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 6, 's2': 34, 's3': 70, 's4': 82, 's5': 63, 's6': 25, 's7': 87, 's8': 16, 'surfactant_conc': 68, 'drug_conc': 59})),
 4: Trial(experiment_name='drug_surfactant', index=4, status=TrialStatus.RUNNING, arm=Arm(name='4_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 24, 's2': 87, 's3': 96, 's4': 99, 's5': 59, 's6': 17, 's7': 48, 's8': 64, 'surfactant_conc': 1, 'drug_conc': 24})),
 5: Trial(experiment_name='drug_surfactant', index=5, status=TrialStatus.RUNNING, arm=Arm(name='5_0', parameters={'Drug_MW': 0.206, 'Drug_LogP': 0.307, 'Drug_TPSA': 0.037, 's1': 72, 's2': 46, 's3': 29, 's4': 4, 's5': 5, 's6': 54, 's7': 93, 's8': 3, 'surfactant_conc': 51, 'drug_conc': 99}))}

In [11]:
df_conc, df_vol = hf.design_to_conc_to_vol (n)

In [12]:
plate_well = input("Enter the plate well starting well (e.g., F1): ")
deepplate_well = input("Enter the deep plate well starting well (e.g., F1): ")


print("Please confirm the following information:")
print("Wellplate will start at: " + plate_well)
print("Deep plate will start at: " + deepplate_well)

print()
print("*******************************************************")
print("Continue if correct, or rerun this cell if incorrect.")
print("*******************************************************")

Please confirm the following information:
Wellplate will start at: B1
Deep plate will start at: D1

*******************************************************
Continue if correct, or rerun this cell if incorrect.
*******************************************************

In [13]:

hf.generate_protocol(df_vol=df_vol, iteration=n, plate_well=plate_well, deepplate_well=deepplate_well)

✅ Successfully wrote to: protocol/otflex_0.py

In [14]:
df_absorbance = hf.process_absorbance(iteration=n)
df_absorbance

   trial_index  success
0            0        0
1            1        0
2            2        0
3            3        1
4            4        0
5            5        1

In [15]:
results = hf.build_results(n, df_conc, df_absorbance)

In [16]:
results

,trial_index,s1,s2,s3,s4,s5,s6,s7,s8,surfactant_conc,drug_conc,initial_drug_conc_surfactant_conc_ratio,success,micelle_drug_conc,complexity
0,0,47,59,49,31,96,8,10,35,43.0,19.25,0.447674,0,0.000,8
1,1,94,22,76,63,42,72,55,99,17.5,0.75,0.042857,0,0.000,8
2,2,53,99,4,13,22,89,28,56,9.0,8.25,0.916667,0,0.000,8
3,3,6,34,70,82,63,25,87,16,34.0,14.75,0.433824,1,1.475,8
4,4,24,87,96,99,59,17,48,64,0.5,6.00,12.000000,0,0.000,8
5,5,72,46,29,4,5,54,93,3,25.5,24.75,0.970588,1,2.475,8

In [17]:
norm_results = hf.normalize_data(results, 'normalize')

In [18]:
norm_results

,trial_index,s1,s2,s3,s4,s5,s6,s7,s8,surfactant_conc,drug_conc,initial_drug_conc_surfactant_conc_ratio,success,micelle_drug_conc,complexity
0,0,47,59,49,31,96,8,10,35,43.0,19.25,0.004477,0.0,0.00,1.0
1,1,94,22,76,63,42,72,55,99,17.5,0.75,0.000429,0.0,0.00,1.0
2,2,53,99,4,13,22,89,28,56,9.0,8.25,0.009167,0.0,0.00,1.0
3,3,6,34,70,82,63,25,87,16,34.0,14.75,0.004338,1.0,0.59,1.0
4,4,24,87,96,99,59,17,48,64,0.5,6.00,0.120000,0.0,0.00,1.0
5,5,72,46,29,4,5,54,93,3,25.5,24.75,0.009706,1.0,0.99,1.0

# load the results to the optimizer

In [19]:
ax_client = hf.load_data_to_optimizer(iteration = n, norm_results = norm_results)
ax_client

[INFO 06-23 16:42:33] ax.service.ax_client: Starting optimization with verbose logging. To disable logging, set the `verbose_logging` argument to `False`. Note that float values in the logs are rounded to 6 decimal points.
[INFO 06-23 16:42:33] ax.service.ax_client: Completed trial 0 with data: {'micelle_drug_conc': (0.0, None), 'success': (0.0, None), 'initial_drug_conc_surfactant_conc_ratio': (0.004477, None), 'complexity': (1.0, None)}.
[INFO 06-23 16:42:33] ax.service.ax_client: Completed trial 1 with data: {'micelle_drug_conc': (0.0, None), 'success': (0.0, None), 'initial_drug_conc_surfactant_conc_ratio': (0.000429, None), 'complexity': (1.0, None)}.
[INFO 06-23 16:42:33] ax.service.ax_client: Completed trial 2 with data: {'micelle_drug_conc': (0.0, None), 'success': (0.0, None), 'initial_drug_conc_surfactant_conc_ratio': (0.009167, None), 'complexity': (1.0, None)}.
[INFO 06-23 16:42:33] ax.service.ax_client: Completed trial 3 with data: {'micelle_drug_conc': (0.59, None), 'success': (1.0, None), 'initial_drug_conc_surfactant_conc_ratio': (0.004338, None), 'complexity': (1.0, None)}.
[INFO 06-23 16:42:33] ax.service.ax_client: Completed trial 4 with data: {'micelle_drug_conc': (0.0, None), 'success': (0.0, None), 'initial_drug_conc_surfactant_conc_ratio': (0.12, None), 'complexity': (1.0, None)}.
[INFO 06-23 16:42:33] ax.service.ax_client: Completed trial 5 with data: {'micelle_drug_conc': (0.99, None), 'success': (1.0, None), 'initial_drug_conc_surfactant_conc_ratio': (0.009706, None), 'complexity': (1.0, None)}.
[INFO 06-23 16:42:33] ax.service.ax_client: Saved JSON-serialized state of optimization to `optimizer/optimizer_0_loaded.json`.

AxClient(experiment=Experiment(drug_surfactant))